const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1366,height:900}});await p.route(/fonts\./,r=>r.abort());const e=[];p.on('pageerror',x=>e.push(x.message));
await p.goto('file:///home/claude/che/out/CHE_lab_wizualizacje_v0_57_GFX16.html#Na/reaction');await p.waitForTimeout(2500);
await p.evaluate(()=>{const c=document.querySelectorAll('[data-panel="atlas"]');c[c.length-1].click()});await p.waitForTimeout(1500);
await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Rozumiem');b&&b.click()});
await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].filter(x=>x.offsetParent&&x.textContent.trim()==='Reakcja');b[0].click()});await p.waitForTimeout(800);
await p.evaluate(()=>{document.querySelector('#rx-cat button[data-f="all"]').click()});await p.waitForTimeout(400);
await p.type('#rxl-q','NaOH');await p.waitForTimeout(400);
console.log(await p.evaluate(()=>document.querySelector('.rxl-n').textContent+' | '+document.activeElement.id));
await p.evaluate(()=>{document.querySelector('#rx-cat button[data-r]').click()});await p.waitForTimeout(400);
await p.screenshot({path:'v5/atl_rx2.png'});console.log('ERR',e.join('|'));await b.close()})();
