const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1300,height:1000}});await p.route(/fonts\./,r=>r.abort());const e=[];p.on('pageerror',x=>e.push(x.message));
await p.goto('file:///home/claude/che/out/CHE_lab_wizualizacje_v0_57_GFX16.html');await p.waitForTimeout(2500);
const dismiss=async()=>{await p.evaluate(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='Rozumiem'&&x.offsetParent);b&&b.click()})};
await p.screenshot({path:'v4/hub_0.png'});
await p.evaluate(()=>{const c=document.querySelectorAll('[data-panel="lessons"]');(c[c.length-1]).click()});await p.waitForTimeout(1200);await dismiss();await p.waitForTimeout(300);await p.screenshot({path:'v4/hub_1.png'});
await p.evaluate(()=>{const b=[...document.querySelectorAll('.h2card')].find(c=>/FIZ-01/.test(c.textContent)).querySelector('.h2act button:last-child');b.click()});await p.waitForTimeout(1500);await dismiss();await p.screenshot({path:'v4/hub_2.png'});
await p.evaluate(()=>{const b=[...document.querySelectorAll('#h2vs button')][0];b.click()});await p.waitForTimeout(500);await p.screenshot({path:'v4/hub_3.png'});
console.log(await p.evaluate(()=>document.getElementById('h2n').textContent));
await p.evaluate(()=>{document.querySelector('#h2g .h2v .h2act button').click()});await p.waitForTimeout(1500);console.log(await p.evaluate(()=>(document.getElementById('che-viz-ov-title')||{}).textContent));
console.log('ERR',e.join('|'));await b.close()})();
