sceneReg('dilution',{label:'Rozcieńczanie kwasu: „kwas do wody!"',lesson:'kwasy',desc:'Poprawnie: smugi i umiarkowane ogrzanie. Błędnie (woda do kwasu): wrzenie i pryskanie.',height:380,aspect:1.55,
 init:()=>({mode:'ok',tap:.9,Vadd:0,T:20,schl:0,splash:0,boil:0}),
 parts:[{id:'stand',x:.02,y:.02,w:.5,h:.96,s:{clamps:[{x:.42,y:.13,w:20}]}},
  {id:'dropFunnel',name:'fun',x:.36,y:.02,w:.12,h:.42,get:S=>({liquid:S.mode==='ok'?ACIDC:WATER,level:Math.max(0,1-S.Vadd),tap:S.Vadd<1?S.tap:0,landY:.88-.38*(.42+S.Vadd*.3),onDrop:()=>{S.Vadd=Math.min(1,S.Vadd+.006);if(S.mode==='ok'){S.schl=1;S.T=Math.min(62,S.T+.32)}else{S.T=Math.min(115,S.T+3);S.splash=Math.max(S.splash,.35);S.boil=1}}})},
  {id:'stand',x:.02,y:.02,w:.5,h:.96,s:{layer:'front',clamps:[{x:.42,y:.13,w:20}]}},
  {id:'beaker',name:'bk',x:.26,y:.5,w:.32,h:.38,get:S=>({liquid:colors.mix(S.mode==='ok'?WATER:ACIDC,S.mode==='ok'?ACIDC:WATER,S.Vadd*.5),level:.42+S.Vadd*.3,schl:S.schl,splash:S.splash,T:S.T,gas:S.boil,bubSize:1.4,label:S.mode==='ok'?'H₂O':'H₂SO₄ stęż.'})},
  {id:'thermometer',x:.72,y:.18,w:.14,h:.72,get:S=>({T:S.T})}],
 tick(S,dt){S.schl=Math.max(S.tap&&S.mode==='ok'&&S.Vadd<1?.3:0,S.schl-dt*.5);S.boil=Math.max(0,S.boil-dt*.8);S.T+=(20-S.T)*dt*.006},
 overlay(c,W,H,S,t,T){head(c,T,W,'Rozcieńczanie stężonego H₂SO₄',S.mode==='ok'?'kwas wlewany powoli do wody':'BŁĄD: woda wlewana do kwasu',1);if(S.mode!=='ok'&&S.T>60){c.fillStyle='rgba(220,38,38,.92)';rr(c,W*.56,H*.08+30,W*.42,40,8);c.fill();txt(c,'Wrzenie i pryskanie kwasu!',W*.77,H*.08+47,'#fff','center',12,800);txt(c,'Zawsze: KWAS DO WODY',W*.77,H*.08+63,'#fff','center',11,700)}},
 ui(h,S,m,api){const r=UI.row(h);UI.sel(r,[['ok','kwas → do wody (poprawnie)'],['bad','woda → do kwasu (błąd)']],S.mode,v=>{api.reset();S.mode=v;S.tap=.9;b.textContent='Zamknij kranik'},'Sposób');const b=UI.btn(r,S.tap?'Zamknij kranik':'Otwórz kranik',()=>{S.tap=S.tap?0:.9;b.textContent=S.tap?'Zamknij kranik':'Otwórz kranik'},1);UI.btn(r,'Powtórz',()=>{const md=S.mode;api.reset();S.mode=md;S.tap=.9;b.textContent='Zamknij kranik'});
  const n=UI.note(h);return S=>{n.innerHTML=S.mode==='ok'?'Kwas jest gęstszy od wody — opada smugami i miesza się. Wydziela się ciepło (T = '+fmt(S.T,1)+' °C), ale duża ilość wody je pochłania.':'Pierwsze krople wody pływają po kwasie i <b>gwałtownie wrą</b> — kwas pryska. T lokalnie = '+fmt(S.T,0)+' °C. Nigdy nie wlewaj wody do stężonego kwasu!'}}});