try {

(function(g){'use strict';
const C=g.CHE=g.CHE||{}, clone=o=>JSON.parse(JSON.stringify(o));
const ok=v=>C.OK?C.OK(v):{ok:true,value:v};
const fail=(c,m,x)=>C.FAIL?C.FAIL(c,m,x):{ok:false,error:{code:c,message:m,context:x}};
const canonical=m=>C.STRUCTURE.canonicalize(m||{});
function create(input){const x=input||{};return {id:String(x.id||'reaction-set-'+Date.now()),type:x.type||'multicomponent',components:Array.isArray(x.components)?clone(x.components):[],reactants:(x.reactants||[]).map(canonical),products:(x.products||[]).map(canonical),conditions:C.TRANSFORM.conditions(x.conditions||{}),changes:clone(x.changes||{}),status:x.status||'STRUCTURAL',validation:null,meta:{createdAt:new Date().toISOString(),source:x.source||'CHE.REACTIONSET'}};}
function roles(r){const out={substrate:[],reagent:[],catalyst:[],solvent:[],product:[],byproduct:[]};for(const c of r.components||[]){const role=c.role||'reagent';(out[role]||(out[role]=[])).push(clone(c));}return out;}
function atomInventory(graphs){const out={};for(const m of graphs||[])for(const a of m.atoms||[])out[a.element]=(out[a.element]||0)+1;return out;}
function balance(r){const x=create(r),left=atomInventory(x.reactants),right=atomInventory(x.products),els=[...new Set([...Object.keys(left),...Object.keys(right)])].sort(),delta={};els.forEach(e=>delta[e]=(right[e]||0)-(left[e]||0));const charge=(gs)=>gs.reduce((n,m)=>n+Number(m.charge||0),0);const ql=charge(x.reactants),qr=charge(x.products);return {ok:els.every(e=>delta[e]===0)&&ql===qr,atomsLeft:left,atomsRight:right,delta,chargeLeft:ql,chargeRight:qr,elements:els};}
function mapGraphs(before,after){const b=before||[],a=after||[], used=new Set(),maps=[];for(const bm of b){const map=[];for(const ba of bm.atoms||[]){let hit=null;for(const am of a){if(used.has(am.id)||am.element!==ba.element)continue;const sameCharge=Number(am.charge||0)===Number(ba.charge||0);if(sameCharge){hit=am;break;}}if(hit){used.add(hit.id);map.push({from:ba.id,to:hit.id,element:ba.element});}}maps.push(map);}return maps;}
function diff(r){const x=create(r), pairs=[];const n=Math.max(x.reactants.length,x.products.length);for(let i=0;i<n;i++)if(x.reactants[i]&&x.products[i])pairs.push({index:i,diff:C.RECONSTRUCT?.mappedDiff?C.RECONSTRUCT.mappedDiff(x.reactants[i],x.products[i]):C.TRANSFORM.diff(x.reactants[i],x.products[i])});return {pairs,mapping:mapGraphs(x.reactants,x.products),globalBalance:balance(x)};}
function transferAtom(r,fromIndex,atomId,toIndex){const x=create(r),src=x.reactants[fromIndex],dst=x.reactants[toIndex];if(!src||!dst)return fail('CHE.E.DATA_NOT_FOUND','Brak grafu źródłowego lub docelowego',{fromIndex,toIndex});const a=src.atoms.find(q=>String(q.id)===String(atomId));if(!a)return fail('CHE.E.DATA_NOT_FOUND','Nie znaleziono atomu',{atomId});if(src.bonds.some(b=>b.atomA===a.id||b.atomB===a.id))return fail('CHE.E.TRANSFER_REQUIRES_BOND_EDIT','Atom ma wiązania',{atomId});const ns=clone(src),nd=clone(dst);ns.atoms=ns.atoms.filter(q=>q.id!==a.id);nd.atoms.push(clone(a));x.reactants[fromIndex]=canonical(ns);x.reactants[toIndex]=canonical(nd);return ok({reaction:x,transferred:clone(a)});}
function transferProton(r,fromIndex,toIndex,hydrogenId,targetAtomId){const x=create(r),src=x.reactants[fromIndex],dst=x.reactants[toIndex];if(!src||!dst)return fail('CHE.E.DATA_NOT_FOUND','Brak grafu',{fromIndex,toIndex});const h=src.atoms.find(a=>a.id===hydrogenId&&a.element==='H');if(!h)return fail('CHE.E.DATA_NOT_FOUND','Nie znaleziono protonu',{hydrogenId});const donorBond=src.bonds.find(b=>b.atomA===h.id||b.atomB===h.id);if(!donorBond)return fail('CHE.E.INVALID_INPUT','Proton nie ma wiązania donorowego',{hydrogenId});if(!dst.atoms.some(a=>a.id===targetAtomId))return fail('CHE.E.DATA_NOT_FOUND','Nie znaleziono akceptora',{targetAtomId});const ns=clone(src),nd=clone(dst);ns.atoms=ns.atoms.filter(a=>a.id!==h.id);ns.bonds=ns.bonds.filter(b=>b.id!==donorBond.id);nd.atoms.push(clone(h));nd.bonds.push({id:'transfer-H-'+Date.now(),atomA:targetAtomId,atomB:h.id,order:1,type:'single',labels:['transferred-proton']});x.reactants[fromIndex]=canonical(ns);x.reactants[toIndex]=canonical(nd);return ok({reaction:x,proton:{atomId:h.id,from:donorBond.atomA===h.id?donorBond.atomB:donorBond.atomA,to:targetAtomId}});}
function validate(r){const x=create(r),errors=[],warnings=[];x.reactants.forEach((m,i)=>{const v=C.STRUCTURE.validate(m);if(!v.ok)errors.push({code:'INVALID_REACTANT',index:i,detail:v});});x.products.forEach((m,i)=>{const v=C.STRUCTURE.validate(m);if(!v.ok)errors.push({code:'INVALID_PRODUCT',index:i,detail:v});});const b=balance(x);if(!b.ok)errors.push({code:'UNBALANCED_REACTION_SET',detail:b});if(!x.products.length)warnings.push({code:'NO_PRODUCTS'});if(!x.reactants.length)warnings.push({code:'NO_REACTANTS'});return ok({ok:errors.length===0,status:errors.length?'INVALID':warnings.length?'VALID_WITH_WARNING':'VALID',errors,warnings,balance:b,diff:diff(x)});}
function apply(r,ops){let x=create(r);for(const op of ops||[]){if(op.type==='transferAtom'){const q=transferAtom(x,op.fromIndex,op.atomId,op.toIndex);if(!q.ok)return q;x=q.value.reaction;}else if(op.type==='transferProton'){const q=transferProton(x,op.fromIndex,op.toIndex,op.hydrogenId,op.targetAtomId);if(!q.ok)return q;x=q.value.reaction;}else return fail('CHE.E.INVALID_OPERATION','Nieznana operacja',{operation:op.type});}x.validation=validate(x).value;return ok(x);}
C.REACTIONSET={version:'2.20',create,roles,balance,mapGraphs,diff,transferAtom,transferProton,validate,apply};
})(window);

} catch (err) {
  try { console.warn('[CHE module 42]', err && err.message ? err.message : err); } catch(_){}
}

