try {

(function(g){'use strict';
const C=g.CHE=g.CHE||{},D=C.DATA=C.DATA||{},E=C.ENGINE=C.ENGINE||{};
const CAT=C.LESSON_REACTION_CATALOG||{}, records=Array.isArray(CAT.records)?CAT.records:[];
function normFormula(x){return String(x||'').replace(/[₀₁₂₃₄₅₆₇₈₉]/g,m=>'0123456789'['₀₁₂₃₄₅₆₇₈₉'.indexOf(m)]).replace(/[⁺⁻]/g,m=>m==='⁺'?'+':'-').replace(/\s+/g,'').replace(/\((aq|s|l|g)\)/gi,'').replace(/[↓↑]/g,'').replace(/[‐‑‒–—]/g,'-');}
function side(r,key){return Array.isArray(r?.[key])?r[key].map(x=>({formula:normFormula(x?.formula),coef:Number(x?.coef??1)})).filter(x=>x.formula):[];}
function renderSide(a){return a.map(x=>(x.coef===1?'':String(x.coef))+x.formula).join('+');}
function canonicalRows(){return Object.entries(D.REACTIONS||{}).map(([id,r])=>{const a=side(r,'reactants'),b=side(r,'products');return {id,raw:r,equation:renderSide(a)+'->'+renderSide(b),reactants:a,products:b};});}
function equationText(x){let t=String(x||'');t=t.replace(/[“”„”]/g,'"').replace(/\b(?:Równanie|Wynik|Popraw|Równanie \(przykład\)|Przykład(?: \d+)?|Suma|Redukcja|Utlenianie)\s*:?\s*/gi,'');t=t.replace(/^[\s>*#\-•|\d.)]+/,'');const m=t.match(/([^:]*?[A-Z][A-Za-z0-9₀-₉()\[\]^⁺⁻.=+\-–—]*(?:\s*\+\s*[A-Z][A-Za-z0-9₀-₉()\[\]^⁺⁻.=+\-–—]*)+\s*(?:→|->|⟶)\s*[^|]+?)(?:\s*\(|\s*$)/);return (m?m[1]:t).trim();}
function normalizeEquation(x){return normFormula(String(x||'').replace(/→|⟶/g,'->').replace(/\s+/g,'').replace(/—\([^)]*\)/g,'').replace(/\([^)]*(?:kat|MnO₂|hν|Δ|°C|światł|temp)[^)]*\)/gi,'').replace(/\([^)]*\)/g,'').replace(/[↓↑]/g,''));}
function parsedSides(x){const n=normalizeEquation(x),parts=n.split('->');if(parts.length!==2)return null;function parse(z){return z.split('+').map(q=>{const m=q.match(/^(\d+)?(.+)$/);return {coef:Number(m?.[1]||1),formula:normFormula(m?.[2]||q)}}).filter(q=>q.formula);};return {left:parse(parts[0]),right:parse(parts[1])};}
function signature(eq){const p=parsedSides(eq);if(!p)return '';const f=a=>a.map(x=>`${x.coef}*${x.formula}`).sort().join('+');return f(p.left)+'->'+f(p.right);}
function classify(text){const t=String(text||'');const eq=equationText(t);const hasArrow=/→|⟶|->/.test(eq), formulas=/[A-Z][a-z]?(?:\d|₀|₁|₂|₃|₄|₅|₆|₇|₈|₉|\(|\)|\^|⁺|⁻)/.test(eq);if(!hasArrow||!formulas)return 'NON_REACTION';if(/^(?:reguła|błąd|popraw|pytanie|zadanie|dlaczego|krok|ustaw|wynik|szkic|wniosek|obserwacja|typ|przykład|wzór|klucze)\b/i.test(t))return 'INSTRUCTION_OR_EXAMPLE';return 'REACTION_EQUATION';}
function conditionContext(text){const t=String(text||'');const flags=[];if(/MnO₂|kat\.?|katal|Ni\b|Pt\b/i.test(t))flags.push('CATALYST');if(/Δ|temperatur|°C|K\b/i.test(t))flags.push('TEMPERATURE');if(/hν|światł/i.test(t))flags.push('LIGHT');if(/aq|wodn|roztwor/i.test(t))flags.push('AQUEOUS');if(/BHP|okular|żrąc|toksy|niebezp|gwałtown/i.test(t))flags.push('SAFETY');return flags;}
function match(rec,rows,index){const eq=equationText(rec.equation),sig=signature(eq);if(!sig)return {status:'UNPARSEABLE'};const ex=index.get(sig)||[];if(ex.length===1)return {status:'EXACT_CANONICAL',reactionIds:ex};if(ex.length>1)return {status:'MULTIPLE_CANONICAL',reactionIds:ex};return {status:'NO_CANONICAL_MATCH'};}
function audit(){const rows=canonicalRows(),idx=new Map();rows.forEach(x=>{const s=signature(x.equation);if(s){if(!idx.has(s))idx.set(s,[]);idx.get(s).push(x.id);}});const mapped=records.map(r=>{const classification=classify(r.equation);const reconciliation=classification==='REACTION_EQUATION'?match(r,rows,idx):{status:'NOT_APPLICABLE'};return {...r,classification,normalizedEquation:equationText(r.equation),reconciliation,conditionFlags:conditionContext(r.equation)};});const counts={};mapped.forEach(x=>{const k=x.reconciliation.status;counts[k]=(counts[k]||0)+1;});const classes={};mapped.forEach(x=>{classes[x.classification]=(classes[x.classification]||0)+1;});return {version:'2.77',source:CAT.source||null,candidateRecords:mapped.length,canonicalRecords:rows.length,counts,classes,exact:mapped.filter(x=>x.reconciliation.status==='EXACT_CANONICAL').length,needsReview:mapped.filter(x=>x.reconciliation.status==='NEEDS_REVIEW').length,unmatched:mapped.filter(x=>x.reconciliation.status==='NO_CANONICAL_MATCH').length,unparseable:mapped.filter(x=>x.reconciliation.status==='UNPARSEABLE').length,realReactionCandidates:mapped.filter(x=>x.classification==='REACTION_EQUATION').length,records:mapped,policy:'audit-only; canonical reactions remain the single reaction database'};}
function regression(){const a=audit();return [{id:'RX77-001',name:'canonical equations derived from common graph data',ok:a.canonicalRecords>0&&a.exact>=0},{id:'RX77-002',name:'candidate classification present',ok:a.realReactionCandidates>0},{id:'RX77-003',name:'non-reactions excluded from matching',ok:(a.classes.NON_REACTION||0)+(a.classes.INSTRUCTION_OR_EXAMPLE||0)>0},{id:'RX77-004',name:'single canonical reaction store',ok:a.policy.includes('single reaction database')}];}
C.REACTION_LESSON_RECONCILIATION={version:'2.77',audit,regression};E.modules=E.modules||{};E.modules.REACTION_LESSON_RECONCILIATION='2.77';E.registry=E.registry||{};E.registry.REACTION_LESSON_RECONCILIATION={layer:'AUDIT/RECONCILIATION',owner:'CHE.REACTION_LESSON_RECONCILIATION',depends:['LESSON_REACTION_CATALOG','DATA.REACTIONS','STRUCTURE']};
})(window);

} catch (err) {
  try { console.warn('[CHE module 138]', err && err.message ? err.message : err); } catch(_){}
}

