try {

(function(){
  window.CHE=window.CHE||{}; const CHE=window.CHE;
  CHE.DATA=CHE.DATA||{};
  CHE.LO_FINAL=CHE.LO_FINAL||{};
  CHE.LO_FINAL.regression=function(){const keys=['LO_CHEM_MAX03_GASES_SOLUTIONS','LO_CHEM_MAX04_THERMOKINETICS','LO_CHEM_MAX05_EQUILIBRIUM','LO_CHEM_MAX366_ACID_BASE','LO_CHEM_MAX367_BUFFERS_TITRATION','LO_CHEM_MAX368_SOLUBILITY_KSP','LO_CHEM_MAX369_REDOX','LO_CHEM_MAX370_ELECTROCHEMISTRY','LO_CHEM_MAX371_INORGANIC_CORE','LO_CHEM_MAX372_METALS_NONMETALS','LO_CHEM_MAX373_ORGANIC_HYDROCARBONS','LO_CHEM_MAX374_ORGANIC_FUNCTIONAL','LO_CHEM_MAX375_BIOCHEMISTRY_AS_CHEMISTRY','LO_CHEM_MAX376_DNA_RNA_CHEMISTRY','LO_CHEM_MAX377_LAB_METHOD','LO_CHEM_MAX378_DATA_QUALITY'];const reg=CHE.PROJECT_REQUIREMENTS_LOCK_V331||{};const missing=keys.filter(k=>!reg[k]);return{status:missing.length?'PARTIAL':'READY',missing,browserRuntime:'NOT_VERIFIED',scientificGate:'BLOCKED'};};
  CHE.LO_FINAL.status=CHE.LO_FINAL.regression();
  CHE.PROJECT_REQUIREMENTS_LOCK_V331['LO_CHEM_FINAL_REGRESSION']={status:'DONE',version:'3.80',fingerprint:'LO-CHEM-FINAL-REGRESSION-V380',scope:['LO chemistry closure','common data','common engine','curriculum mapping','browser runtime remains unverified']};
  CHE.PROJECT_REQUIREMENTS_LOCK_V331=CHE.PROJECT_REQUIREMENTS_LOCK_V331||{};
  CHE.PROJECT_REQUIREMENTS_LOCK_V331['LO_CHEM_MAX380_LO_FULL_REGRESSION_CONTRACT']={status:'DONE',version:'3.80',fingerprint:'LO-CHEM-MAX-380-LO_FULL_REGRESSION_CONTRACT',scope:['LO_FULL_REGRESSION_CONTRACT']};
})();

} catch (err) {
  try { console.warn('[CHE module 269]', err && err.message ? err.message : err); } catch(_){}
}

