

try {

(function(g){
'use strict';
const C = g.CHE = g.CHE || {};
const D = C.DATA = C.DATA || {};
const S = {
  HCl:{formula:'HCl',name:'kwas chlorowodorowy',state:'aq',molarMass:36.46,role:'kwas',safety:['żrący'],uses:['żołądek','odkamienianie','PVC']},
  NaOH:{formula:'NaOH',name:'wodorotlenek sodu',state:'aq',molarMass:40.0,role:'zasada',safety:['żrący'],uses:['chemia przemysłowa','mydło']},
  Zn:{formula:'Zn',name:'cynk',state:'s',molarMass:65.38,role:'metal',safety:[],uses:['galwanizacja']},
  Mg:{formula:'Mg',name:'magnez',state:'s',molarMass:24.305,role:'metal',safety:['palny'],uses:['stopy','pirotechnika']},
  Fe:{formula:'Fe',name:'żelazo',state:'s',molarMass:55.845,role:'metal',safety:[],uses:['stal']},
  MgCl2:{formula:'MgCl2',name:'chlorek magnezu',state:'aq',molarMass:95.211,role:'sól',safety:[],uses:['sól drogowa']},
  FeCl2:{formula:'FeCl2',name:'chlorek żelaza(II)',state:'aq',molarMass:126.751,role:'sól',safety:[],uses:[]},
  ZnCl2:{formula:'ZnCl2',name:'chlorek cynku',state:'aq',molarMass:136.315,role:'sól',safety:['żrący'],uses:['lutowanie']},
  CaCO3:{formula:'CaCO3',name:'węglan wapnia',state:'s',molarMass:100.086,role:'sól',safety:[],uses:['wapno','budownictwo']},
  CO2:{formula:'CO2',name:'dwutlenek węgla',state:'g',molarMass:44.009,role:'tlenek kwasowy',safety:[],uses:['napoje']},
  H2O:{formula:'H2O',name:'woda',state:'l',molarMass:18.015,role:'rozpuszczalnik',safety:[],uses:[]},
  H2:{formula:'H2',name:'wodór',state:'g',molarMass:2.016,role:'pierwiastek',safety:['palny'],uses:['paliwo']},
  NaCl:{formula:'NaCl',name:'chlorek sodu',state:'aq',molarMass:58.44,role:'sól',safety:[],uses:['spożywczy']},
  H2SO4:{formula:'H2SO4',name:'kwas siarkowy(VI)',state:'aq',molarMass:98.079,role:'kwas',safety:['żrący'],uses:['akumulatory','nawozy']},
  Na2SO4:{formula:'Na2SO4',name:'siarczan(VI) sodu',state:'aq',molarMass:142.04,role:'sól',safety:[],uses:['detergenty']},
  NaHSO4:{formula:'NaHSO4',name:'wodorosiarczan(VI) sodu',state:'aq',molarMass:120.06,role:'sól kwaśna',safety:['żrący'],uses:['czyszczenie']},
  CuO:{formula:'CuO',name:'tlenek miedzi(II)',state:'s',molarMass:79.545,role:'tlenek zasadowy',safety:[],uses:['pigment']},
  CuSO4:{formula:'CuSO4',name:'siarczan(VI) miedzi(II)',state:'aq',molarMass:159.609,role:'sól',safety:['szkodliwy'],uses:['fungicyd']},
  CuCl2:{formula:'CuCl2',name:'chlorek miedzi(II)',state:'aq',molarMass:134.452,role:'sól',safety:['szkodliwy'],uses:['katalizator']},
  CaCl2:{formula:'CaCl2',name:'chlorek wapnia',state:'aq',molarMass:110.978,role:'sól',safety:[],uses:['osuszacz']},
  AgNO3:{formula:'AgNO3',name:'azotan(V) srebra',state:'aq',molarMass:169.871,role:'sól',safety:['żrący','plami'],uses:['fotografia']},
  AgCl:{formula:'AgCl',name:'chlorek srebra',state:'s',molarMass:143.321,role:'osad',safety:[],uses:[]},
  HNO3:{formula:'HNO3',name:'kwas azotowy(V)',state:'aq',molarMass:63.012,role:'kwas',safety:['żrący','utleniacz'],uses:['nawozy']},
  NO2:{formula:'NO2',name:'dwutlenek azotu',state:'g',molarMass:46.005,role:'tlenek',safety:['toksyczny'],uses:[]},
  CuNO32:{formula:'Cu(NO3)2',name:'azotan(V) miedzi(II)',state:'aq',molarMass:187.554,role:'sól',safety:['szkodliwy'],uses:[]},
  SO3:{formula:'SO3',name:'tlenek siarki(VI)',state:'l',molarMass:80.06,role:'tlenek kwasowy',safety:['żrący'],uses:['H₂SO₄']},
  HF:{formula:'HF',name:'kwas fluorowodorowy',state:'aq',molarMass:20.006,role:'kwas',safety:['silnie toksyczny'],uses:['trawienie szkła']},
  CH3COOH:{formula:'CH3COOH',name:'kwas octowy',state:'aq',molarMass:60.052,role:'kwas',safety:['żrący'],uses:['ocet','synteza']},
  H3PO4:{formula:'H3PO4',name:'kwas fosforowy(V)',state:'aq',molarMass:97.994,role:'kwas',safety:['żrący'],uses:['nawozy']},
  H2CO3:{formula:'H2CO3',name:'kwas węglowy',state:'aq',molarMass:62.024,role:'kwas',safety:[],uses:[]},
  HCOOH:{formula:'HCOOH',name:'kwas mrówkowy',state:'aq',molarMass:46.025,role:'kwas',safety:['żrący'],uses:['synteza']},
  NH3:{formula:'NH3',name:'amoniak',state:'g',molarMass:17.031,role:'zasada',safety:['toksyczny'],uses:['nawozy']},
  CH4:{formula:'CH4',name:'metan',state:'g',molarMass:16.043,role:'alkan',safety:['palny'],uses:['paliwo']},
  H2S:{formula:'H2S',name:'siarkowodór',state:'g',molarMass:34.081,role:'kwas słaby',safety:['silnie toksyczny'],uses:[],cas:'7783-06-4'},
  SO2:{formula:'SO2',name:'dwutlenek siarki',state:'g',molarMass:64.064,role:'tlenek kwasowy',safety:['toksyczny'],uses:[],cas:'7446-09-5'},
  HCN:{formula:'HCN',name:'cyjanowodór',state:'g',molarMass:27.025,role:'kwas słaby',safety:['silnie toksyczny'],uses:[],cas:'74-90-8'},
  H2O2:{formula:'H2O2',name:'nadtlenek wodoru',state:'l',molarMass:34.015,role:'nadtlenek',safety:['utleniacz','żrący'],uses:[],cas:'7722-84-1'},
  CO:{formula:'CO',name:'tlenek węgla(II)',state:'g',molarMass:28.010,role:'tlenek obojętny',safety:['silnie toksyczny'],uses:[],cas:'630-08-0'},
  H3O:{formula:'H3O+',name:'jon hydroniowy',state:'aq',molarMass:19.023,role:'jon',safety:[],uses:[]}
};
 
(function(){
const fix={
 CO2:{name:'tlenek węgla(IV)',alias:['dwutlenek węgla'],uses:['napoje gazowane','gaśnice','fotosynteza']},
 NO2:{name:'tlenek azotu(IV)',alias:['dwutlenek azotu'],uses:['produkcja HNO₃'],props:{appearance:'brunatny gaz',smell:'duszący',special:['cięższy od powietrza','składnik kwaśnych deszczy i smogu']}},
 SO2:{name:'tlenek siarki(IV)',alias:['dwutlenek siarki'],uses:['konserwant (E220)','produkcja H₂SO₄'],props:{appearance:'bezbarwny gaz',smell:'ostry, duszący (palona siarka)',special:['odbarwia KMnO₄','składnik kwaśnych deszczy']}},
 CaCO3:{uses:['kreda, marmur, wapień','budownictwo','produkcja wapna palonego CaO'],alias:['węglan wapnia (nie „wapno” — wapno palone to CaO)']},
 AgCl:{name:'chlorek srebra(I)',alias:['chlorek srebra'],props:{appearance:'biały, serowaty osad; ciemnieje na świetle'}},
 HCl:{aqName:'kwas solny (chlorowodorowy)',gasName:'chlorowodór',uses:['sok żołądkowy','odkamienianie, środki do WC','produkcja PVC','trawienie metali'],
  props:{appearance:'bezbarwna ciecz (techniczny — żółtawy od Fe³⁺)',smell:'ostry, duszący',conc:'36–38%',density:1.18,cm:11.7,special:['„dymi” na powietrzu (mgiełka kropelek kwasu)','lotny']},volatile:true,strength:'mocny'},
 H2SO4:{uses:['elektrolit w akumulatorach (ok. 37%)','nawozy fosforowe','osuszacz','produkcja barwników i detergentów'],
  props:{appearance:'bezbarwna, oleista, bezwonna ciecz',conc:'96–98%',density:1.84,cm:18.0,bp:337,special:['higroskopijny (osuszacz)','odwadnia i zwęgla cukier, papier, drewno','rozcieńczanie silnie egzotermiczne — kwas do wody','gorący stężony — utleniacz; na zimno pasywuje Fe, Al']},dehydrating:true,strength:'mocny (I stopień)'},
 HNO3:{uses:['nawozy (saletry)','materiały wybuchowe','wytrawianie metali','barwniki'],
  props:{appearance:'bezbarwna ciecz (na świetle żółknie)',smell:'ostry',conc:'65–68%',density:1.40,special:['rozkład na świetle: 4 HNO₃ → 4 NO₂ + O₂ + 2 H₂O','z białkiem żółte zabarwienie (reakcja ksantoproteinowa)','silny utleniacz — z metalami nie daje H₂','na zimno pasywuje Fe, Al, Cr']},oxidizing:true,strength:'mocny'},
 HF:{safety:['silnie toksyczny','żrący — penetruje skórę, wiąże Ca²⁺'],uses:['trawienie szkła (SiO₂ + 4 HF → SiF₄ + 2 H₂O)','produkcja fluorków'],props:{special:['słaby kwas mimo dużej elektroujemności F (mocne wiązanie H–F)','przechowywany w naczyniach z tworzywa, nie ze szkła']},strength:'słaby'},
 CH3COOH:{aqName:'kwas octowy (etanowy)',uses:['ocet 5–10% (E260)','konserwowanie','synteza octanów'],props:{appearance:'bezbarwna ciecz; 100% — „lodowaty” (krzepnie w 16,6 °C)',smell:'octu, ostry',special:['jednoprotonowy — kwasowy tylko H z –COOH']},strength:'słaby'},
 H3PO4:{uses:['nawozy fosforowe','zakwaszacz E338 (napoje typu cola)','odrdzewiacze'],props:{appearance:'bezbarwna, syropowata ciecz (czysty — kryształy, t.t. ok. 42 °C)',conc:'ok. 85%',density:1.69,special:['nie utlenia, mało lotny','kwas średniej mocy (pKa₁ ≈ 2,16)']},strength:'słaby (średniej mocy)'},
 H2CO3:{uses:['napoje gazowane','bufor krwi (H₂CO₃/HCO₃⁻)'],props:{appearance:'istnieje tylko w roztworze',special:['nietrwały: H₂CO₃ ⇌ H₂O + CO₂']},strength:'słaby'},
 HCOOH:{aqName:'kwas mrówkowy (metanowy)',uses:['jad mrówek i pokrzyw','konserwant (E236)','garbarstwo'],strength:'słaby'},
 H2S:{aqName:'kwas siarkowodorowy',gasName:'siarkowodór',uses:['wody siarczkowe','analiza jakościowa (strącanie siarczków)'],props:{appearance:'bezbarwny gaz',smell:'zgniłych jaj',special:['silnie trujący','czernieje papierek z octanem ołowiu(II)']},strength:'słaby'},
 HCN:{aqName:'kwas cyjanowodorowy',gasName:'cyjanowodór',strength:'słaby'}
};
Object.keys(fix).forEach(k=>{if(S[k])Object.assign(S[k],fix[k])});
Object.assign(S,{
 HBr:{formula:'HBr',name:'kwas bromowodorowy',state:'aq',molarMass:80.912,role:'kwas',safety:['żrący'],uses:['synteza bromków'],strength:'mocny'},
 HI:{formula:'HI',name:'kwas jodowodorowy',state:'aq',molarMass:127.912,role:'kwas',safety:['żrący'],uses:['synteza jodków','reduktor'],strength:'mocny'},
 HClO4:{formula:'HClO4',name:'kwas chlorowy(VII)',state:'aq',molarMass:100.46,role:'kwas',safety:['żrący','silny utleniacz (stężony)'],uses:['analityka','paliwa rakietowe (chlorany(VII))'],strength:'mocny'},
 H2SO3:{formula:'H2SO3',name:'kwas siarkowy(IV)',state:'aq',molarMass:82.07,role:'kwas',safety:['drażniący'],uses:['konserwowanie (SO₂)','bielenie'],props:{special:['nietrwały: H₂SO₃ ⇌ H₂O + SO₂']},strength:'słaby (średniej mocy)'},
 HNO2:{formula:'HNO2',name:'kwas azotowy(III)',state:'aq',molarMass:47.013,role:'kwas',safety:['toksyczny'],uses:['synteza barwników azowych'],props:{special:['nietrwały — istnieje tylko w rozcieńczonym roztworze']},strength:'słaby'},
 H3PO3:{formula:'H3PO3',name:'kwas fosforowy(III)',state:'s',molarMass:81.996,role:'kwas',safety:['żrący'],uses:['środki ochrony roślin (fosforyny)'],props:{special:['w praktyce dwuprotonowy: HP(O)(OH)₂ — jeden H związany z P']},protonsReal:2,strength:'słaby'},
 H2SiO3:{formula:'H2SiO3',name:'kwas krzemowy',state:'s',molarMass:78.10,role:'kwas',safety:[],uses:['silikażel (osuszacz)'],props:{appearance:'galaretowaty, nierozpuszczalny osad',special:['otrzymywany z soli: Na₂SiO₃ + 2 HCl → H₂SiO₃↓ + 2 NaCl','SiO₂ nie reaguje z wodą']},strength:'bardzo słaby'},
 C3H6O3:{formula:'C3H6O3',name:'kwas mlekowy',state:'aq',molarMass:90.08,role:'kwas',safety:[],uses:['fermentacja mlekowa (jogurt, kiszonki)','mięśnie (glikoliza beztlenowa)','E270'],strength:'słaby'},
 C6H8O7:{formula:'C6H8O7',name:'kwas cytrynowy',state:'s',molarMass:192.12,role:'kwas',safety:['drażniący'],uses:['odkamienianie','E330','cykl Krebsa'],strength:'słaby'},
 NH4Cl:{formula:'NH4Cl',name:'chlorek amonu',state:'s',molarMass:53.49,role:'sól',safety:[],uses:['biały dym HCl + NH₃','lutowanie'],props:{appearance:'biały kryształ / „dym”'}},
 CaO:{formula:'CaO',name:'tlenek wapnia (wapno palone)',state:'s',molarMass:56.077,role:'tlenek zasadowy',safety:['żrący'],uses:['budownictwo','wapnowanie gleb']},
 FeCl3:{formula:'FeCl3',name:'chlorek żelaza(III)',state:'aq',molarMass:162.20,role:'sól',safety:['żrący'],uses:['trawienie płytek drukowanych','koagulant'],props:{appearance:'żółtobrunatny roztwór'}},
 BaSO4:{formula:'BaSO4',name:'siarczan(VI) baru',state:'s',molarMass:233.39,role:'osad',safety:[],uses:['kontrast RTG (nierozpuszczalny, nietoksyczny)'],props:{appearance:'biały, drobnokrystaliczny osad'}},
 NaHCO3:{formula:'NaHCO3',name:'wodorowęglan sodu (soda oczyszczona)',state:'s',molarMass:84.007,role:'sól kwaśna',safety:[],uses:['proszek do pieczenia','lek zobojętniający','neutralizacja rozlanych kwasów']}
});
 
Object.assign(S,{
  'Na':{formula:'Na',name:'sód',state:'s',molarMass:22.99,role:'metal',safety:['reaguje gwałtownie z wodą'],uses:[]},
  'Cu':{formula:'Cu',name:'miedź',state:'s',molarMass:63.546,role:'metal',safety:[],uses:[]},
  'Cl2':{formula:'Cl2',name:'chlor',state:'g',molarMass:70.9,role:'pierwiastek',safety:[],uses:[]},
  'Al':{formula:'Al',name:'glin',state:'s',molarMass:26.982,role:'metal',safety:[],uses:[]},
  'AlCl3':{formula:'AlCl3',name:'chlorek glinu',state:'aq',molarMass:133.332,role:'sól',safety:[],uses:[]},
  'ZnSO4':{formula:'ZnSO4',name:'siarczan(VI) cynku',state:'aq',molarMass:161.436,role:'sól',safety:[],uses:[]},
  'MgSO4':{formula:'MgSO4',name:'siarczan(VI) magnezu',state:'aq',molarMass:120.361,role:'sól',safety:[],uses:[]},
  'MgO':{formula:'MgO',name:'tlenek magnezu',state:'s',molarMass:40.304,role:'tlenek zasadowy',safety:[],uses:[]},
  'Fe2O3':{formula:'Fe2O3',name:'tlenek żelaza(III)',state:'s',molarMass:159.687,role:'tlenek zasadowy (słabo amfoteryczny)',safety:[],uses:[]},
  'Na2O':{formula:'Na2O',name:'tlenek sodu',state:'s',molarMass:61.979,role:'tlenek zasadowy',safety:[],uses:[]},
  'NaNO3':{formula:'NaNO3',name:'azotan(V) sodu (saletra chilijska)',state:'aq',molarMass:84.994,role:'sól',safety:[],uses:[]},
  'ZnO':{formula:'ZnO',name:'tlenek cynku',state:'s',molarMass:81.379,role:'tlenek amfoteryczny',safety:[],uses:[]},
  'KOH':{formula:'KOH',name:'wodorotlenek potasu',state:'aq',molarMass:56.105,role:'zasada',safety:[],uses:[]},
  'K2SO4':{formula:'K2SO4',name:'siarczan(VI) potasu',state:'aq',molarMass:174.252,role:'sól',safety:[],uses:[]},
  'Ca(OH)2':{formula:'Ca(OH)2',name:'wodorotlenek wapnia',state:'aq',molarMass:74.092,role:'zasada',safety:[],uses:[]},
  'Ca(NO3)2':{formula:'Ca(NO3)2',name:'azotan(V) wapnia',state:'aq',molarMass:164.086,role:'sól',safety:[],uses:[]},
  'Al(OH)3':{formula:'Al(OH)3',name:'wodorotlenek glinu',state:'s',molarMass:78.003,role:'wodorotlenek amfoteryczny',safety:[],uses:[]},
  'Ca3(PO4)2':{formula:'Ca3(PO4)2',name:'fosforan(V) wapnia',state:'s',molarMass:310.174,role:'osad',safety:[],uses:[]},
  'Mg(OH)2':{formula:'Mg(OH)2',name:'wodorotlenek magnezu',state:'s',molarMass:58.319,role:'zasada (słabo rozpuszczalna)',safety:[],uses:[]},
  'Na2CO3':{formula:'Na2CO3',name:'węglan sodu (soda)',state:'aq',molarMass:105.988,role:'sól',safety:[],uses:[]},
  'BaCl2':{formula:'BaCl2',name:'chlorek baru',state:'aq',molarMass:208.227,role:'sól',safety:[],uses:[]},
  'Na2S':{formula:'Na2S',name:'siarczek sodu',state:'aq',molarMass:78.04,role:'sól',safety:[],uses:[]},
  'Na2SO3':{formula:'Na2SO3',name:'siarczan(IV) sodu',state:'aq',molarMass:126.037,role:'sól',safety:[],uses:[]},
  'Na2SiO3':{formula:'Na2SiO3',name:'krzemian sodu (szkło wodne — roztwór)',state:'aq',molarMass:122.062,role:'sól',safety:[],uses:[]},
  'NO':{formula:'NO',name:'tlenek azotu(II)',state:'g',molarMass:30.006,role:'tlenek obojętny',safety:[],uses:[]},
  'Au':{formula:'Au',name:'złoto',state:'s',molarMass:196.967,role:'metal',safety:[],uses:[]},
  'HAuCl4':{formula:'HAuCl4',name:'kwas tetrachlorozłotowy(III)',state:'aq',molarMass:339.775,role:'kwas (kompleks)',safety:[],uses:[]},
  'P4O10':{formula:'P4O10',name:'tlenek fosforu(V)',state:'s',molarMass:283.886,role:'tlenek kwasowy',safety:[],uses:[]},
  'N2O5':{formula:'N2O5',name:'tlenek azotu(V)',state:'s',molarMass:108.009,role:'tlenek kwasowy',safety:[],uses:[]},
  'N2O3':{formula:'N2O3',name:'tlenek azotu(III)',state:'g',molarMass:76.011,role:'tlenek kwasowy',safety:[],uses:[]},
  'Br2':{formula:'Br2',name:'brom',state:'l',molarMass:159.808,role:'pierwiastek',safety:[],uses:[]},
  'I2':{formula:'I2',name:'jod',state:'s',molarMass:253.808,role:'pierwiastek',safety:[],uses:[]},
  'S':{formula:'S',name:'siarka',state:'s',molarMass:32.06,role:'pierwiastek',safety:[],uses:[]},
  'O2':{formula:'O2',name:'tlen',state:'g',molarMass:31.998,role:'pierwiastek',safety:[],uses:[]},
  'N2':{formula:'N2',name:'azot',state:'g',molarMass:28.014,role:'pierwiastek',safety:[],uses:[]},
  'CaSO4':{formula:'CaSO4',name:'siarczan(VI) wapnia (gips — dihydrat)',state:'s',molarMass:136.134,role:'sól',safety:[],uses:[]},
  'C12H22O11':{formula:'C12H22O11',name:'sacharoza',state:'s',molarMass:342.297,role:'cukier',safety:[],uses:[]},
  'C':{formula:'C',name:'węgiel',state:'s',molarMass:12.011,role:'pierwiastek',safety:[],uses:[]},
  'SiO2':{formula:'SiO2',name:'tlenek krzemu(IV) (krzemionka)',state:'s',molarMass:60.083,role:'tlenek kwasowy',safety:[],uses:[]},
  'SiF4':{formula:'SiF4',name:'fluorek krzemu(IV)',state:'g',molarMass:104.077,role:'fluorek',safety:[],uses:[]},
  'CH3COONa':{formula:'CH3COONa',name:'octan sodu',state:'aq',molarMass:82.034,role:'sól',safety:[],uses:[]},
  'FeS':{formula:'FeS',name:'siarczek żelaza(II)',state:'s',molarMass:87.91,role:'sól',safety:[],uses:[]},
  'Cu(OH)2':{formula:'Cu(OH)2',name:'wodorotlenek miedzi(II)',state:'s',molarMass:97.56,role:'osad',safety:[],uses:[],props:{appearance:'niebieski, galaretowaty osad'}},
  'Fe(OH)3':{formula:'Fe(OH)3',name:'wodorotlenek żelaza(III)',state:'s',molarMass:106.87,role:'osad',safety:[],uses:[],props:{appearance:'rdzawobrunatny osad'}},
  'NaNO3':{formula:'NaNO3',name:'azotan(V) sodu (saletra chilijska)',state:'aq',molarMass:84.99,role:'sól',safety:['utleniacz'],uses:['nawóz','konserwant E251']},
  'KNO3':{formula:'KNO3',name:'azotan(V) potasu (saletra indyjska)',state:'aq',molarMass:101.10,role:'sól',safety:['utleniacz'],uses:['nawóz','proch czarny']},
  'KI':{formula:'KI',name:'jodek potasu',state:'aq',molarMass:166.00,role:'sól',safety:[],uses:['sól jodowana','tabletki jodowe']},
  'Pb(NO3)2':{formula:'Pb(NO3)2',name:'azotan(V) ołowiu(II)',state:'aq',molarMass:331.2,role:'sól',safety:['toksyczny'],uses:[]},
  'PbI2':{formula:'PbI2',name:'jodek ołowiu(II)',state:'s',molarMass:461.0,role:'osad',safety:['toksyczny'],uses:[],props:{appearance:'jaskrawożółty osad'}},
  'FeSO4':{formula:'FeSO4',name:'siarczan(VI) żelaza(II)',state:'aq',molarMass:151.91,role:'sól',safety:[],uses:['nawozy, suplementy żelaza']},
  'Ag':{formula:'Ag',name:'srebro',state:'s',molarMass:107.87,role:'metal',safety:[],uses:[]},
  'Ca(HCO3)2':{formula:'Ca(HCO3)2',name:'wodorowęglan wapnia',state:'aq',molarMass:162.11,role:'sól wodorowa',safety:[],uses:[],props:{special:['twardość przemijająca wody','istnieje tylko w roztworze']}},
  'CuSO4·5H2O':{formula:'CuSO4·5H2O',name:'siarczan(VI) miedzi(II)—woda (1/5) (sól uwodniona, „siny kamień”)',state:'s',molarMass:249.69,role:'hydrat',safety:['szkodliwy'],uses:['fungicyd','wykrywanie wody (forma bezwodna)']}
});
})();

(function(){const add={
 "K2O":{"formula": "K2O", "name": "tlenek potasu", "state": "s", "molarMass": 94.195, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": []},
 "Li2O":{"formula": "Li2O", "name": "tlenek litu", "state": "s", "molarMass": 29.879, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": ["ceramika, szkło"]},
 "BeO":{"formula": "BeO", "name": "tlenek berylu", "state": "s", "molarMass": 25.011, "role": "tlenek amfoteryczny", "safety": ["toksyczny (pył)"], "uses": ["ceramika techniczna"]},
 "B2O3":{"formula": "B2O3", "name": "tlenek boru", "state": "s", "molarMass": 69.617, "role": "tlenek kwasowy", "safety": [], "uses": ["szkło borokrzemianowe"]},
 "Al2O3":{"formula": "Al2O3", "name": "tlenek glinu", "state": "s", "molarMass": 101.961, "role": "tlenek amfoteryczny", "safety": [], "uses": ["korund, szlifierki", "warstwa pasywna glinu", "ceramika techniczna", "rubin/szafir (z domieszkami)"]},
 "FeO":{"formula": "FeO", "name": "tlenek żelaza(II)", "state": "s", "molarMass": 71.844, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Fe3O4":{"formula": "Fe3O4", "name": "tlenek żelaza(II,III) (magnetyt)", "state": "s", "molarMass": 231.531, "role": "tlenek mieszany", "safety": [], "uses": ["ruda żelaza", "magnetyczne nośniki"]},
 "Cu2O":{"formula": "Cu2O", "name": "tlenek miedzi(I)", "state": "s", "molarMass": 143.091, "role": "tlenek zasadowy", "safety": [], "uses": ["pigment, kupryt"]},
 "P2O5":{"formula": "P2O5", "name": "tlenek fosforu(V) (zapis empiryczny P₂O₅)", "state": "s", "molarMass": 141.943, "role": "tlenek kwasowy", "safety": ["żrący", "silnie higroskopijny"], "uses": ["osuszacz"]},
 "N2O":{"formula": "N2O", "name": "tlenek azotu(I) (podtlenek azotu, gaz rozweselający)", "state": "g", "molarMass": 44.013, "role": "tlenek obojętny", "safety": ["gaz cieplarniany"], "uses": ["anestezja", "bita śmietana (gaz nośny)"]},
 "Mn2O7":{"formula": "Mn2O7", "name": "tlenek manganu(VII)", "state": "l", "molarMass": 221.869, "role": "tlenek kwasowy", "safety": ["silny utleniacz, wybuchowy"], "uses": []},
 "CrO3":{"formula": "CrO3", "name": "tlenek chromu(VI)", "state": "s", "molarMass": 99.993, "role": "tlenek kwasowy", "safety": ["toksyczny, rakotwórczy", "silny utleniacz"], "uses": ["chromowanie"]},
 "Cr2O3":{"formula": "Cr2O3", "name": "tlenek chromu(III)", "state": "s", "molarMass": 151.989, "role": "tlenek amfoteryczny", "safety": [], "uses": ["zielony pigment"]},
 "MnO2":{"formula": "MnO2", "name": "tlenek manganu(IV)", "state": "s", "molarMass": 86.936, "role": "tlenek amfoteryczny", "safety": [], "uses": ["baterie", "katalizator rozkładu H₂O₂"]},
 "MnO":{"formula": "MnO", "name": "tlenek manganu(II)", "state": "s", "molarMass": 70.937, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "CrO":{"formula": "CrO", "name": "tlenek chromu(II)", "state": "s", "molarMass": 67.995, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "TiO2":{"formula": "TiO2", "name": "tlenek tytanu(IV) (biel tytanowa, rutyl)", "state": "s", "molarMass": 79.865, "role": "tlenek amfoteryczny (słabo)", "safety": [], "uses": ["biały pigment", "filtry UV", "fotokataliza"]},
 "HgO":{"formula": "HgO", "name": "tlenek rtęci(II)", "state": "s", "molarMass": 216.589, "role": "tlenek zasadowy", "safety": ["toksyczny"], "uses": ["historyczne otrzymywanie tlenu"]},
 "Ag2O":{"formula": "Ag2O", "name": "tlenek srebra(I)", "state": "s", "molarMass": 231.739, "role": "tlenek zasadowy", "safety": [], "uses": ["ogniwa srebrowe"]},
 "PbO":{"formula": "PbO", "name": "tlenek ołowiu(II)", "state": "s", "molarMass": 223.199, "role": "tlenek amfoteryczny", "safety": ["toksyczny"], "uses": ["szkło ołowiowe"]},
 "PbO2":{"formula": "PbO2", "name": "tlenek ołowiu(IV)", "state": "s", "molarMass": 239.198, "role": "tlenek (utleniacz)", "safety": ["toksyczny"], "uses": ["akumulator ołowiowy"]},
 "Cl2O7":{"formula": "Cl2O7", "name": "tlenek chloru(VII)", "state": "l", "molarMass": 182.893, "role": "tlenek kwasowy", "safety": ["wybuchowy"], "uses": []},
 "Na2O2":{"formula": "Na2O2", "name": "nadtlenek sodu", "state": "s", "molarMass": 77.978, "role": "nadtlenek (nie tlenek!)", "safety": ["żrący", "silny utleniacz"], "uses": ["regeneracja powietrza (okręty, statki kosmiczne)"]},
 "H2O2":{"formula": "H2O2", "name": "nadtlenek wodoru (woda utleniona 3%)", "state": "aq", "molarMass": 34.014, "role": "nadtlenek (nie tlenek!)", "safety": ["stężony — żrący, utleniacz"], "uses": ["dezynfekcja", "wybielanie"]},
 "OF2":{"formula": "OF2", "name": "difluorek tlenu (fluorek tlenu — nie tlenek!)", "state": "g", "molarMass": 53.995, "role": "fluorek tlenu", "safety": ["silnie toksyczny"], "uses": []},
 "LiOH":{"formula": "LiOH", "name": "wodorotlenek litu", "state": "aq", "molarMass": 23.947, "role": "zasada", "safety": ["żrący"], "uses": ["pochłaniacze CO₂"]},
 "KOH":{"formula": "KOH", "name": "wodorotlenek potasu", "state": "aq", "molarMass": 56.105, "role": "zasada", "safety": ["żrący"], "uses": ["mydła miękkie", "elektrolit"]},
 "Mg(OH)2":{"formula": "Mg(OH)2", "name": "wodorotlenek magnezu", "state": "s", "molarMass": 58.319, "role": "wodorotlenek", "safety": [], "uses": ["lek zobojętniający (mleko magnezowe)"]},
 "HMnO4":{"formula": "HMnO4", "name": "kwas manganowy(VII)", "state": "aq", "molarMass": 119.942, "role": "kwas", "safety": ["silny utleniacz"], "uses": []},
 "H2CrO4":{"formula": "H2CrO4", "name": "kwas chromowy(VI)", "state": "aq", "molarMass": 118.008, "role": "kwas", "safety": ["toksyczny"], "uses": []},
 "Fe2(SO4)3":{"formula": "Fe2(SO4)3", "name": "siarczan(VI) żelaza(III)", "state": "aq", "molarMass": 399.858, "role": "sól", "safety": [], "uses": ["koagulant (uzdatnianie wody)"]},
 "NaAlO2":{"formula": "NaAlO2", "name": "glinian sodu (zapis uproszczony / po stopieniu)", "state": "s", "molarMass": 81.97, "role": "sól", "safety": ["żrący"], "uses": []},
 "NaAl(OH)4":{"formula": "NaAl(OH)4", "name": "tetrahydroksoglinian sodu", "state": "aq", "molarMass": 118.0, "role": "sól kompleksowa", "safety": ["żrący"], "uses": []},
 "Na2ZnO2":{"formula": "Na2ZnO2", "name": "cynkan sodu (zapis uproszczony)", "state": "s", "molarMass": 143.358, "role": "sól", "safety": [], "uses": []},
 "Na2Zn(OH)4":{"formula": "Na2Zn(OH)4", "name": "tetrahydroksocynkan sodu", "state": "aq", "molarMass": 179.388, "role": "sól kompleksowa", "safety": [], "uses": []},
 "K2CO3":{"formula": "K2CO3", "name": "węglan potasu (potaż)", "state": "aq", "molarMass": 138.204, "role": "sól", "safety": [], "uses": ["szkło", "mydła"]},
 "K2SiO3":{"formula": "K2SiO3", "name": "krzemian potasu", "state": "aq", "molarMass": 154.278, "role": "sól", "safety": [], "uses": []},
 "CaSiO3":{"formula": "CaSiO3", "name": "krzemian wapnia (żużel wielkopiecowy)", "state": "s", "molarMass": 116.16, "role": "sól", "safety": [], "uses": ["cement, materiały budowlane"]},
 "Hg":{"formula": "Hg", "name": "rtęć", "state": "l", "molarMass": 200.59, "role": "metal", "safety": ["toksyczna (pary)"], "uses": []},
 "Pb":{"formula": "Pb", "name": "ołów", "state": "s", "molarMass": 207.2, "role": "metal", "safety": ["toksyczny"], "uses": []},
 "Fe":{"formula": "Fe", "name": "żelazo", "state": "s", "molarMass": 55.845, "role": "metal", "safety": [], "uses": []},
 "Cu":{"formula": "Cu", "name": "miedź", "state": "s", "molarMass": 63.546, "role": "metal", "safety": [], "uses": []},
 "Al":{"formula": "Al", "name": "glin", "state": "s", "molarMass": 26.982, "role": "metal", "safety": [], "uses": []},
 "Zn":{"formula": "Zn", "name": "cynk", "state": "s", "molarMass": 65.38, "role": "metal", "safety": [], "uses": []},
 "Mg":{"formula": "Mg", "name": "magnez", "state": "s", "molarMass": 24.305, "role": "metal", "safety": ["pali się oślepiającym płomieniem"], "uses": []},
 "Ca":{"formula": "Ca", "name": "wapń", "state": "s", "molarMass": 40.078, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "Na":{"formula": "Na", "name": "sód", "state": "s", "molarMass": 22.99, "role": "metal", "safety": ["reaguje gwałtownie z wodą"], "uses": []},
 "C":{"formula": "C", "name": "węgiel", "state": "s", "molarMass": 12.011, "role": "niemetal", "safety": [], "uses": []},
 "P":{"formula": "P", "name": "fosfor (zapis szkolny)", "state": "s", "molarMass": 30.974, "role": "niemetal", "safety": ["biały — samozapalny, trujący"], "uses": []},
 "P4":{"formula": "P4", "name": "fosfor biały (cząsteczka P₄)", "state": "s", "molarMass": 123.896, "role": "niemetal", "safety": ["samozapalny, trujący"], "uses": []},
 "H2":{"formula": "H2", "name": "wodór", "state": "g", "molarMass": 2.016, "role": "pierwiastek", "safety": ["palny, mieszanina z O₂ wybuchowa"], "uses": []},
 "O2":{"formula": "O2", "name": "tlen", "state": "g", "molarMass": 31.998, "role": "pierwiastek", "safety": ["podtrzymuje palenie"], "uses": []},
 "CH4":{"formula": "CH4", "name": "metan", "state": "g", "molarMass": 16.043, "role": "węglowodór", "safety": ["palny"], "uses": ["gaz ziemny"]},
 "C3H8":{"formula": "C3H8", "name": "propan", "state": "g", "molarMass": 44.097, "role": "węglowodór", "safety": ["palny"], "uses": ["butle turystyczne, LPG"]},
 "C8H18":{"formula": "C8H18", "name": "oktan", "state": "l", "molarMass": 114.232, "role": "węglowodór", "safety": ["palny"], "uses": ["benzyna (składnik)"]},
 "KClO3":{"formula": "KClO3", "name": "chloran(V) potasu", "state": "s", "molarMass": 122.545, "role": "sól", "safety": ["silny utleniacz"], "uses": ["otrzymywanie tlenu (z MnO₂)"]},
 "KCl":{"formula": "KCl", "name": "chlorek potasu", "state": "s", "molarMass": 74.548, "role": "sól", "safety": [], "uses": ["nawóz"]},
 "NaOH":{"formula": "NaOH", "name": "wodorotlenek sodu", "state": "aq", "molarMass": 39.997, "role": "zasada", "safety": ["żrący"], "uses": []},
 "NaHCO3":{"formula": "NaHCO3", "name": "wodorowęglan sodu", "state": "s", "molarMass": 84.006, "role": "sól", "safety": [], "uses": []},
 "Na2CO3":{"formula": "Na2CO3", "name": "węglan sodu", "state": "aq", "molarMass": 105.988, "role": "sól", "safety": [], "uses": []}
};Object.keys(add).forEach(k=>{if(!S[k])S[k]=add[k]});})();

(function(){const add={
 "LiOH":{"formula": "LiOH", "name": "wodorotlenek litu", "state": "s", "molarMass": 23.947, "role": "zasada (rozpuszczalny wodorotlenek)", "safety": ["żrący"], "uses": ["pochłaniacze CO₂ (łodzie podwodne, stacje kosmiczne)"]},
 "Ba(OH)2":{"formula": "Ba(OH)2", "name": "wodorotlenek baru", "state": "s", "molarMass": 171.344, "role": "zasada (rozpuszczalny wodorotlenek)", "safety": ["żrący", "związki baru trujące"], "uses": ["analiza chemiczna"]},
 "Zn(OH)2":{"formula": "Zn(OH)2", "name": "wodorotlenek cynku", "state": "s", "molarMass": 99.394, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "Fe(OH)2":{"formula": "Fe(OH)2", "name": "wodorotlenek żelaza(II)", "state": "s", "molarMass": 89.859, "role": "osad (utlenia się na powietrzu)", "safety": [], "uses": []},
 "Ni(OH)2":{"formula": "Ni(OH)2", "name": "wodorotlenek niklu(II)", "state": "s", "molarMass": 92.707, "role": "osad", "safety": ["związki niklu uczulają"], "uses": ["akumulatory Ni-MH"]},
 "Mn(OH)2":{"formula": "Mn(OH)2", "name": "wodorotlenek manganu(II)", "state": "s", "molarMass": 88.952, "role": "osad (brunatnieje na powietrzu)", "safety": [], "uses": []},
 "Pb(OH)2":{"formula": "Pb(OH)2", "name": "wodorotlenek ołowiu(II)", "state": "s", "molarMass": 241.214, "role": "wodorotlenek amfoteryczny", "safety": ["związki ołowiu trujące"], "uses": []},
 "Sn(OH)2":{"formula": "Sn(OH)2", "name": "wodorotlenek cyny(II)", "state": "s", "molarMass": 152.724, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "Cr(OH)3":{"formula": "Cr(OH)3", "name": "wodorotlenek chromu(III)", "state": "s", "molarMass": 103.017, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "AgOH":{"formula": "AgOH", "name": "wodorotlenek srebra(I)", "state": "s", "molarMass": 124.877, "role": "nietrwały (→ Ag₂O)", "safety": [], "uses": []},
 "CuOH":{"formula": "CuOH", "name": "wodorotlenek miedzi(I)", "state": "s", "molarMass": 80.553, "role": "nietrwały (→ Cu₂O)", "safety": [], "uses": []},
 "Ag2O":{"formula": "Ag2O", "name": "tlenek srebra(I)", "state": "s", "molarMass": 231.739, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Cu2O":{"formula": "Cu2O", "name": "tlenek miedzi(I)", "state": "s", "molarMass": 143.091, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Fe2O3":{"formula": "Fe2O3", "name": "tlenek żelaza(III)", "state": "s", "molarMass": 159.687, "role": "tlenek zasadowy (słabo amfoteryczny)", "safety": [], "uses": ["pigment, ruda"]},
 "Al2O3":{"formula": "Al2O3", "name": "tlenek glinu", "state": "s", "molarMass": 101.961, "role": "tlenek amfoteryczny", "safety": [], "uses": []},
 "ZnO":{"formula": "ZnO", "name": "tlenek cynku", "state": "s", "molarMass": 81.379, "role": "tlenek amfoteryczny", "safety": [], "uses": []},
 "CuO":{"formula": "CuO", "name": "tlenek miedzi(II)", "state": "s", "molarMass": 79.545, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "MgO":{"formula": "MgO", "name": "tlenek magnezu", "state": "s", "molarMass": 40.304, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "CaO":{"formula": "CaO", "name": "tlenek wapnia", "state": "s", "molarMass": 56.077, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": []},
 "BaO":{"formula": "BaO", "name": "tlenek baru", "state": "s", "molarMass": 153.329, "role": "tlenek zasadowy", "safety": ["żrący", "trujący"], "uses": []},
 "Li":{"formula": "Li", "name": "lit", "state": "s", "molarMass": 6.94, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "K":{"formula": "K", "name": "potas", "state": "s", "molarMass": 39.098, "role": "metal", "safety": ["gwałtownie reaguje z wodą"], "uses": []},
 "Ca":{"formula": "Ca", "name": "wapń", "state": "s", "molarMass": 40.078, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "Ba":{"formula": "Ba", "name": "bar", "state": "s", "molarMass": 137.33, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "MgCl2":{"formula": "MgCl2", "name": "chlorek magnezu", "state": "aq", "molarMass": 95.205, "role": "sól", "safety": [], "uses": []},
 "AlCl3":{"formula": "AlCl3", "name": "chlorek glinu", "state": "aq", "molarMass": 133.332, "role": "sól", "safety": [], "uses": []},
 "ZnSO4":{"formula": "ZnSO4", "name": "siarczan(VI) cynku", "state": "aq", "molarMass": 161.436, "role": "sól", "safety": [], "uses": []},
 "FeSO4":{"formula": "FeSO4", "name": "siarczan(VI) żelaza(II)", "state": "aq", "molarMass": 151.901, "role": "sól", "safety": [], "uses": []},
 "CuCl2":{"formula": "CuCl2", "name": "chlorek miedzi(II)", "state": "aq", "molarMass": 134.446, "role": "sól", "safety": [], "uses": []},
 "NiSO4":{"formula": "NiSO4", "name": "siarczan(VI) niklu(II)", "state": "aq", "molarMass": 154.749, "role": "sól", "safety": ["uczula"], "uses": []},
 "MnSO4":{"formula": "MnSO4", "name": "siarczan(VI) manganu(II)", "state": "aq", "molarMass": 150.994, "role": "sól", "safety": [], "uses": []},
 "Pb(NO3)2":{"formula": "Pb(NO3)2", "name": "azotan(V) ołowiu(II)", "state": "aq", "molarMass": 331.208, "role": "sól", "safety": ["trujący"], "uses": []},
 "CaCl2":{"formula": "CaCl2", "name": "chlorek wapnia", "state": "aq", "molarMass": 110.978, "role": "sól", "safety": [], "uses": []},
 "AgNO3":{"formula": "AgNO3", "name": "azotan(V) srebra", "state": "aq", "molarMass": 169.874, "role": "sól", "safety": ["plami skórę"], "uses": []},
 "NaNO3":{"formula": "NaNO3", "name": "azotan(V) sodu", "state": "aq", "molarMass": 84.994, "role": "sól", "safety": [], "uses": []},
 "KNO3":{"formula": "KNO3", "name": "azotan(V) potasu", "state": "aq", "molarMass": 101.102, "role": "sól", "safety": [], "uses": []},
 "KCl":{"formula": "KCl", "name": "chlorek potasu", "state": "aq", "molarMass": 74.548, "role": "sól", "safety": [], "uses": []},
 "CaSO4":{"formula": "CaSO4", "name": "siarczan(VI) wapnia", "state": "s", "molarMass": 136.134, "role": "sól (trudno rozpuszczalna)", "safety": [], "uses": ["gips"]},
 "BaSO4":{"formula": "BaSO4", "name": "siarczan(VI) baru", "state": "s", "molarMass": 233.386, "role": "sól (nierozpuszczalna)", "safety": [], "uses": ["kontrast RTG"]},
 "BaCl2":{"formula": "BaCl2", "name": "chlorek baru", "state": "aq", "molarMass": 208.23, "role": "sól", "safety": ["trujący"], "uses": []},
 "BaCO3":{"formula": "BaCO3", "name": "węglan baru", "state": "s", "molarMass": 197.338, "role": "sól (nierozpuszczalna)", "safety": ["trujący"], "uses": []},
 "Ca(HCO3)2":{"formula": "Ca(HCO3)2", "name": "wodorowęglan wapnia", "state": "aq", "molarMass": 162.11, "role": "sól (wodorosól)", "safety": [], "uses": ["twardość wody"]},
 "Al2(SO4)3":{"formula": "Al2(SO4)3", "name": "siarczan(VI) glinu", "state": "aq", "molarMass": 342.132, "role": "sól", "safety": [], "uses": ["uzdatnianie wody"]},
 "Na2Pb(OH)4":{"formula": "Na2Pb(OH)4", "name": "tetrahydroksoołowian(II) sodu", "state": "aq", "molarMass": 321.208, "role": "sól kompleksowa", "safety": [], "uses": []},
 "NH4Cl":{"formula": "NH4Cl", "name": "chlorek amonu", "state": "aq", "molarMass": 53.489, "role": "sól", "safety": [], "uses": []},
 "NH3":{"formula": "NH3", "name": "amoniak", "state": "g", "molarMass": 17.031, "role": "zasada Brønsteda", "safety": ["drażniący"], "uses": []},
 "Na2CO3":{"formula": "Na2CO3", "name": "węglan sodu", "state": "aq", "molarMass": 105.988, "role": "sól", "safety": [], "uses": []},
 "CaCO3":{"formula": "CaCO3", "name": "węglan wapnia", "state": "s", "molarMass": 100.086, "role": "sól (nierozpuszczalna)", "safety": [], "uses": []},
 "Na2SO4":{"formula": "Na2SO4", "name": "siarczan(VI) sodu", "state": "aq", "molarMass": 142.036, "role": "sól", "safety": [], "uses": []},
 "NaCl":{"formula": "NaCl", "name": "chlorek sodu", "state": "aq", "molarMass": 58.44, "role": "sól", "safety": [], "uses": []},
 "CuSO4":{"formula": "CuSO4", "name": "siarczan(VI) miedzi(II)", "state": "aq", "molarMass": 159.602, "role": "sól", "safety": [], "uses": []},
 "FeCl3":{"formula": "FeCl3", "name": "chlorek żelaza(III)", "state": "aq", "molarMass": 162.195, "role": "sól", "safety": [], "uses": []},
 "ZnCl2":{"formula": "ZnCl2", "name": "chlorek cynku", "state": "aq", "molarMass": 136.28, "role": "sól", "safety": [], "uses": []},
 "H2":{"formula": "H2", "name": "wodór", "state": "g", "molarMass": 2.016, "role": "pierwiastek", "safety": ["palny"], "uses": []},
 "O2":{"formula": "O2", "name": "tlen", "state": "g", "molarMass": 31.998, "role": "pierwiastek", "safety": [], "uses": []}
};Object.keys(add).forEach(k=>{if(!S[k])S[k]=add[k]});})();

D.SUBSTANCES = S;
D.ACID_SYSTEMS = {
  HCl:{id:'HCl',formula:'HCl',species:['HCl','Cl⁻'],pKa:[-7],Ka:[null],strong:true,anion:'Cl⁻'},
  HNO3:{id:'HNO3',formula:'HNO₃',species:['HNO₃','NO₃⁻'],pKa:[-1.4],Ka:[null],strong:true,anion:'NO₃⁻'},
  H2SO4:{id:'H2SO4',formula:'H₂SO₄',species:['H₂SO₄','HSO₄⁻','SO₄²⁻'],pKa:[-3,1.99],Ka:[null,1.02e-2],strong:false,strongFirst:true,anion:'HSO₄⁻'},
  H3PO4:{id:'H3PO4',formula:'H₃PO₄',species:['H₃PO₄','H₂PO₄⁻','HPO₄²⁻','PO₄³⁻'],pKa:[2.17,7.20,12.35],Ka:[7.1e-3,6.3e-8,4.5e-13],strong:false,anion:'H₂PO₄⁻'},
  HF:{id:'HF',formula:'HF',species:['HF','F⁻'],pKa:[3.17],Ka:[6.8e-4],strong:false,anion:'F⁻'},
  HCOOH:{id:'HCOOH',formula:'HCOOH',species:['HCOOH','HCOO⁻'],pKa:[3.75],Ka:[1.78e-4],strong:false,anion:'HCOO⁻'},
  CH3COOH:{id:'CH3COOH',formula:'CH₃COOH',species:['CH₃COOH','CH₃COO⁻'],pKa:[4.76],Ka:[1.8e-5],strong:false,anion:'CH₃COO⁻'},
  H2CO3:{id:'H2CO3',formula:'H₂CO₃',species:['H₂CO₃','HCO₃⁻','CO₃²⁻'],pKa:[6.37,10.32],Ka:[4.27e-7,4.8e-11],strong:false,anion:'HCO₃⁻'},
  HCN:{id:'HCN',formula:'HCN',species:['HCN','CN⁻'],pKa:[9.21],Ka:[6.2e-10],strong:false,anion:'CN⁻'}
};
 
(function(){
const A=D.ACID_SYSTEMS,set=(k,o)=>{if(A[k])Object.assign(A[k],o)};
set('HF',{pKa:[3.20],Ka:[6.3e-4],note:'słaby mimo dużej elektroujemności F'});
set('CH3COOH',{pKa:[4.756],Ka:[1.75e-5],ref:'PUBCHEM-ACETIC-PKA-25C'});
set('H3PO4',{pKa:[2.16,7.21,12.32],Ka:[6.9e-3,6.2e-8,4.8e-13],note:'średniej mocy (α₁ ≈ 0,23 dla 0,1 mol/dm³)'});
set('H2CO3',{pKa:[6.35,10.33],Ka:[4.47e-7,4.68e-11],note:'stała „pozorna” — dotyczy CO₂(aq) + H₂CO₃'});
set('H2SO4',{note:'mocny tylko w I stopniu; HSO₄⁻ pKa 1,99'});
Object.assign(A,{
 HBr:{id:'HBr',formula:'HBr',species:['HBr','Br⁻'],pKa:[-9],Ka:[null],strong:true,anion:'Br⁻'},
 HI:{id:'HI',formula:'HI',species:['HI','I⁻'],pKa:[-10],Ka:[null],strong:true,anion:'I⁻'},
 HClO4:{id:'HClO4',formula:'HClO₄',species:['HClO₄','ClO₄⁻'],pKa:[-10],Ka:[null],strong:true,anion:'ClO₄⁻'},
 H2SO3:{id:'H2SO3',formula:'H₂SO₃',species:['H₂SO₃','HSO₃⁻','SO₃²⁻'],pKa:[1.85,7.2],Ka:[1.4e-2,6.3e-8],strong:false,anion:'HSO₃⁻',note:'średniej mocy; nietrwały (SO₂ + H₂O)'},
 HNO2:{id:'HNO2',formula:'HNO₂',species:['HNO₂','NO₂⁻'],pKa:[3.35],Ka:[4.5e-4],strong:false,anion:'NO₂⁻'},
 H2S:{id:'H2S',formula:'H₂S',species:['H₂S','HS⁻'],pKa:[7.0],Ka:[1.0e-7],strong:false,anion:'HS⁻',protonsFormal:2,note:'formalnie dwuprotonowy; II stopień praktycznie nie zachodzi (pKa₂ w literaturze 12–19)'},
 H3PO3:{id:'H3PO3',formula:'H₃PO₃',species:['H₃PO₃','H₂PO₃⁻','HPO₃²⁻'],pKa:[1.3,6.7],Ka:[5.0e-2,2.0e-7],strong:false,anion:'H₂PO₃⁻',note:'dwuprotonowy (jeden H związany z P)'},
 C3H6O3:{id:'C3H6O3',formula:'CH₃CH(OH)COOH',species:['kwas mlekowy','mleczan'],pKa:[3.86],Ka:[1.38e-4],strong:false,anion:'CH₃CH(OH)COO⁻'},
 C6H8O7:{id:'C6H8O7',formula:'C₆H₈O₇',species:['H₃Cit','H₂Cit⁻','HCit²⁻','Cit³⁻'],pKa:[3.13,4.76,6.40],Ka:[7.4e-4,1.7e-5,4.0e-7],strong:false,anion:'H₂Cit⁻'}
});
})();

D.ACIDS = {};
Object.values(D.ACID_SYSTEMS).forEach(a=>{
  D.ACIDS[a.id] = { formula:a.formula, name:S[a.id]?.name||a.id,
    type:a.strong?'strong':(a.pKa.length>1?'polyprotic':'weak'),
    Ka:a.Ka.filter(x=>x!==null), pKa:a.pKa.filter(x=>x!==null), protons:a.protonsFormal||a.species.length-1, note:a.note||null };
});
C.deepFreeze(D.SUBSTANCES); C.deepFreeze(D.ACID_SYSTEMS); C.deepFreeze(D.ACIDS);
})(window);

} catch (err) {
  try { console.warn('[CHE module 5]', err && err.message ? err.message : err); } catch(_){}
}