# -*- coding: utf-8 -*-
"""Kanon CHE v0.3 — jedno źródło danych o lekcjach (kod, tytuł, poziom, zależności, cel, zakres).
Z tego pliku `spis_tresci.py` generuje chemia/plany/CHE_SPIS_TRESCI.md. Edytuj tutaj, nie w wygenerowanym md.
Pola: kod, tytul, poziom (E8 / E8+LO / LO), wymaga, poglebia, cel, zakres (co ma być w lekcji), bylo (kod v0.1), dlaczego.
"""

GRUPY = [
    ("01", "F", "Fundamenty", "język, atom, wiązanie, równanie — potrzebne wszędzie"),
    ("02", "N", "Chemia nieorganiczna", "pierwsze klasy związków; oparta tylko na F"),
    ("03", "R", "Roztwory i stechiometria", "ilościowy opis; potrzebny J, X, E, K"),
    ("04", "J", "Chemia jonowa", "wymaga N (substancje) i R (stężenia)"),
    ("05", "O", "Chemia organiczna", "wymaga F (wiązania, wzory) i częściowo J (kwasowość)"),
    ("06", "X", "Redoks", "wymaga F09, N, J"),
    ("07", "E", "Elektrochemia", "wymaga X + J + R"),
    ("08", "K", "Energetyka, kinetyka i równowaga", "wymaga R; J07–J10 korzystają z K09 (stała równowagi)"),
    ("09", "A", "Chemia jądrowa", "rozwija F04–F05; niezależna od reszty"),
    ("10", "P", "Układ okresowy — pogłębienie", "spina wszystko: przewidywanie właściwości z położenia"),
]

FAZY_F = {
    "F01": "Faza A — Co badamy?", "F04": "Faza B — Z czego to wynika?",
    "F10": "Faza C — Jak powstaje struktura?", "F16": "Faza D — Jak opisujemy przemianę?",
    "F18": "Faza E — Integracja i samodzielność",
}

L = [
# ---------------- F ----------------
dict(kod="F01", tytul="Jak myśli chemik", poziom="E8", wymaga="—", poglebia="F02–F03; F16–F17",
     cel="Uczeń odróżnia obserwację od wniosku, model od rzeczywistości, zna cztery poziomy opisu i pięć pytań chemika.",
     zakres="obserwacja, wniosek, hipoteza, model; poziomy makro / cząsteczkowy / symboliczny / ilościowy; pięć pytań chemika; zmiana fizyczna vs reakcja (wstęp); metoda badawcza problem → hipoteza → plan → obserwacja → wniosek; minimum BHP i piktogramy; pracownia GFX (6 zlewek)"),
dict(kod="F02", tytul="Materia i substancje", poziom="E8", wymaga="F01", poglebia="F03; F04; F12",
     cel="Uczeń klasyfikuje próbkę: substancja czysta (pierwiastek, związek) czy mieszanina (jednorodna, niejednorodna) i uzasadnia.",
     zakres="materia, substancja, pierwiastek, związek, mieszanina; jednorodność i fazy; drzewo klasyfikacji; metale i niemetale (wstęp)"),
dict(kod="F03", tytul="Właściwości i rozdzielanie mieszanin", poziom="E8", wymaga="F01; F02", poglebia="F16–F17; R01–R02",
     cel="Uczeń rozróżnia właściwości fizyczne i chemiczne, zjawisko i reakcję oraz dobiera metodę rozdzielania do różnicy właściwości.",
     zakres="właściwości fizyczne i chemiczne; stany skupienia i przemiany fazowe; zjawisko vs reakcja; sączenie, dekantacja, odparowanie, krystalizacja, destylacja, chromatografia, magnes; dobór metody"),
dict(kod="F04", tytul="Atom", poziom="E8", wymaga="F01; F02", poglebia="F05; F06–F09",
     cel="Uczeń oblicza liczbę protonów, neutronów i elektronów w atomie i jonie oraz rozróżnia Z i A.",
     zakres="budowa atomu; Z, A, N; zapis nuklidu; atom obojętny vs jon; modele atomu (historia skrócona)"),
dict(kod="F05", tytul="Izotopy, jony i masa atomowa", poziom="E8+LO", wymaga="F04", poglebia="F06–F09; A01–A06",
     cel="Uczeń rozróżnia izotop, jon i inny pierwiastek oraz liczy masę atomową jako średnią ważoną.",
     zakres="izotopy i nuklidy; kationy i aniony; masa atomowa i jednostka u; procedura średniej izotopowej; izotop i jon jednocześnie (np. ³⁵Cl⁻)"),
dict(kod="F06", tytul="Układ okresowy", poziom="E8+LO", wymaga="F04; F05", poglebia="F08–F11; P01–P06",
     cel="Uczeń czyta położenie pierwiastka, określa elektrony walencyjne i przewiduje trendy.",
     zakres="okres, grupa, blok; rodziny (litowce, berylowce, fluorowce, helowce); elektrony walencyjne; trendy: promień, elektroujemność, charakter metaliczny — każdy z „dlaczego”; OWNER trendów"),
dict(kod="F07", tytul="Konfiguracja elektronowa", poziom="E8+LO", wymaga="F04; F06", poglebia="F08–F10; F13",
     cel="E8: rozmieszczenie elektronów na powłokach. LO: konfiguracja podpowłokowa z regułami.",
     zakres="E8: powłoki K, L, M, N; LO: podpowłoki, orbitale, reguła rozbudowy, Hund, Pauli, wyjątki Cr i Cu, konfiguracje jonów"),
dict(kod="F08", tytul="Konfiguracja ↔ układ okresowy", poziom="E8+LO", wymaga="F06; F07", poglebia="F09–F15",
     cel="Uczeń przechodzi w obie strony między konfiguracją a położeniem w układzie.",
     zakres="okres z liczby powłok, grupa z elektronów walencyjnych, blok z podpowłoki; ograniczenia uproszczeń; w ścieżce E8 łączona z F07"),
dict(kod="F09", tytul="Wartościowość, ładunek i stopień utlenienia", poziom="E8+LO", wymaga="F04; F05; F06; F08", poglebia="F12; F17; X01–X09",
     cel="Uczeń rozróżnia trzy liczby, wie której używać do czego i oblicza stopień utlenienia.",
     zakres="wartościowość (E8), ładunek jonu, stopień utlenienia i jego reguły (OWNER); tabela typowych wartości; pułapki mylenia trzech pojęć"),
dict(kod="F10", tytul="Dlaczego atomy się łączą", poziom="E8+LO", wymaga="F06–F09", poglebia="F11; F13–F15",
     cel="Uczeń rozumie wiązanie jako przejście do stanu o niższej energii oraz sens i granice reguły oktetu.",
     zakres="trwałe konfiguracje (oktet, dublet); energia a wiązanie; wyjątki od oktetu (LO); do rozbudowy — treść cienka"),
dict(kod="F11", tytul="Wiązania jonowe, kowalencyjne i metaliczne", poziom="E8+LO", wymaga="F06; F08; F09; F10", poglebia="F12–F15; P03–P06",
     cel="Uczeń rozpoznaje typ wiązania (także kowalencyjne spolaryzowane) i przewiduje właściwości substancji.",
     zakres="wiązanie jonowe (sieć jonowa), kowalencyjne niespolaryzowane i spolaryzowane, metaliczne; elektroujemność jako wskazówka, nie ostra granica; typ wiązania → właściwości; wiązanie koordynacyjne (LO)"),
dict(kod="F12", tytul="Wzory chemiczne", poziom="E8", wymaga="F09; F11", poglebia="F13; F17; N02–N08",
     cel="Uczeń poprawnie zapisuje i odczytuje wzory, liczy masę cząsteczkową i skład procentowy.",
     zakres="W–K–S–K; indeks, współczynnik, nawias; grupy wieloatomowe; wzór sumaryczny i strukturalny; masa cząsteczkowa; stosunek masowy; skład procentowy; prawo stałości składu (OWNER)"),
dict(kod="F13", tytul="Wzory elektronowe (Lewis)", poziom="E8+LO", wymaga="F11; F12", poglebia="F14; F15; F18",
     cel="Uczeń rysuje wzory kropkowe i kreskowe cząsteczek (E8) oraz jonów (LO).",
     zakres="elektrony walencyjne w zapisie; pary wiążące i wolne; wiązania wielokrotne; ładunek formalny i jony (LO)"),
dict(kod="F14", tytul="Geometria cząsteczek (VSEPR)", poziom="LO", wymaga="F11; F12; F13", poglebia="F15; F18",
     cel="Uczeń liczy domeny i przewiduje geometrię oraz kąty.",
     zakres="domeny elektronowe; geometria elektronowa vs cząsteczkowa; kąty; wpływ wolnych par; hybrydyzacja (wstęp, LO-R)"),
dict(kod="F15", tytul="Polarność i oddziaływania", poziom="E8+LO", wymaga="F11; F13; F14", poglebia="F18; R01–R03; J01–J02",
     cel="E8: polarność wiązania i „podobne rozpuszcza podobne”. LO: polarność cząsteczki z geometrii i oddziaływania.",
     zakres="E8: polarność wiązania z elektroujemności, woda jako rozpuszczalnik (mostek do R01); LO: moment dipolowy, wiązania wodorowe, siły van der Waalsa, wpływ na temperatury wrzenia; do rozbudowy"),
dict(kod="F16", tytul="Od obserwacji do modelu reakcji", poziom="E8", wymaga="F01; F02; F03", poglebia="F17; F19",
     cel="Uczeń zbiera objawy reakcji, oddziela je od wniosku i buduje słowny model reakcji.",
     zakres="objawy reakcji (gaz, osad, barwa, ciepło, światło); substraty i produkty; zapis słowny; reakcje egzo- i endoenergetyczne (wstęp)"),
dict(kod="F17", tytul="Równania reakcji", poziom="E8+LO", wymaga="F12; F16", poglebia="F19; R07; X01–X09",
     cel="Uczeń dobiera współczynniki, rozpoznaje typ reakcji i zapisuje warunki.",
     zakres="prawo zachowania masy (OWNER); współczynniki; synteza, analiza, wymiana; zapis warunków; bilans ładunku (LO)"),
dict(kod="F18", tytul="Dossier substancji", poziom="E8+LO", wymaga="F02; F03; F06; F09; F11; F12", poglebia="F13–F15; N02–N08; R01–R03",
     cel="Uczeń tworzy pełny profil jednej substancji ze wszystkich warstw wiedzy.",
     zakres="wzór, typ wiązania, wzór elektronowy, geometria, polarność, właściwości, zastosowania, BHP; karta rekordu substancji"),
dict(kod="F19", tytul="Dossier reakcji", poziom="E8+LO", wymaga="F16; F17", poglebia="N02–N08; R07–R09; X01–X09; K01–K11",
     cel="Uczeń tworzy rekord reakcji od substratów i warunków po obserwacje, energię, BHP i równanie.",
     zakres="substraty, warunki, obserwacje, typ, energia, BHP, równanie; karta rekordu reakcji"),
dict(kod="F20", tytul="Klinika błędów fundamentów", poziom="E8+LO", wymaga="zależnie od diagnozy F01–F19", poglebia="F21 i właściciele pojęć",
     cel="Uczeń diagnozuje błędy przekrojowe (łączące kilka lekcji) i stosuje procedurę naprawczą.",
     zakres="katalog błędów przekrojowych; procedura: wykryj → nazwij → napraw model; kliniki pojedynczych pojęć zostają w swoich lekcjach"),
dict(kod="F21", tytul="Zadania transferowe i diagnostyka", poziom="E8+LO", wymaga="F01–F20 zależnie od problemu", poglebia="dalsze grupy kursu",
     cel="Uczeń łączy cały blok F w nowym problemie bez wskazania metody.",
     zakres="zadania transferowe; test mistrzostwa bloku F; zestawy interleavingu (przekrój, „dlaczego”); system powtórek po F03, F05, F07, F09"),
# ---------------- N ----------------
dict(kod="N01", tytul="Powietrze i gazy", poziom="E8", wymaga="F02; F03; F16", poglebia="N02; N06; K07", bylo="nowa",
     cel="Uczeń zna skład powietrza oraz otrzymywanie, właściwości i wykrywanie tlenu, wodoru i CO₂.",
     zakres="skład powietrza; tlen, azot, wodór, CO₂, gazy szlachetne — otrzymywanie, właściwości, wykrywanie, zastosowania; zanieczyszczenia powietrza, efekt cieplarniany, dziura ozonowa",
     dlaczego="cały dział IV podstawy E8 nie miał lekcji; tlen i wodór są potrzebne do tlenków i wodorków"),
dict(kod="N02", tytul="Tlenki", poziom="E8+LO", wymaga="F09; F12; N01", poglebia="N03; N04; J05", bylo="N01",
     cel="Uczeń zapisuje, nazywa i otrzymuje tlenki oraz klasyfikuje je wg charakteru chemicznego.",
     zakres="budowa i nazewnictwo; otrzymywanie (spalanie, rozkład); tlenki kwasowe, zasadowe, obojętne, amfoteryczne (LO); reakcje z wodą"),
dict(kod="N03", tytul="Wodorotlenki i zasady", poziom="E8+LO", wymaga="F09; F12; N02", poglebia="J01; J02; J05", bylo="N02",
     cel="Uczeń zapisuje i otrzymuje wodorotlenki, odróżnia wodorotlenek od zasady i bada odczyn.",
     zakres="budowa i nazwy; otrzymywanie (metal + woda, tlenek + woda); właściwości i zastosowania; dysocjacja (E8); wskaźniki"),
dict(kod="N04", tytul="Kwasy", poziom="E8+LO", wymaga="F09; F12; N02", poglebia="J01–J03; X04", bylo="N03",
     cel="Uczeń zapisuje i otrzymuje kwasy tlenowe i beztlenowe, opisuje ich właściwości i odczyn.",
     zakres="kwasy beztlenowe i tlenowe; otrzymywanie; właściwości, zastosowania, BHP; dysocjacja i pH (E8); metal + kwas (OWNER E8); kwaśne deszcze"),
dict(kod="N05", tytul="Sole", poziom="E8+LO", wymaga="N03; N04", poglebia="J03; J04; J08", bylo="N04",
     cel="Uczeń zapisuje i nazywa sole, zna metody ich otrzymywania i przewiduje strącanie.",
     zakres="budowa i nazwy; metody otrzymywania (zobojętnianie, metal + kwas, tlenek + kwas itd.); dysocjacja soli; tabela rozpuszczalności i strącanie (E8); zastosowania"),
dict(kod="N06", tytul="Wodorki", poziom="E8+LO", wymaga="N01; F12", poglebia="N07; P01–P02", bylo="N05",
     cel="E8: wodór i jego proste związki. LO: systematyka wodorków.",
     zakres="wodorki metali i niemetali; charakter chemiczny w układzie okresowym; amoniak, chlorowodór, siarkowodór"),
dict(kod="N07", tytul="Systematyka nieorganiczna", poziom="E8+LO", wymaga="N02–N06", poglebia="N08", bylo="N06",
     cel="Uczeń klasyfikuje dowolny związek nieorganiczny: wzór → nazwa → klasa.",
     zakres="klasyfikacja wszystkich klas; nazewnictwo systematyczne; procedura rozpoznawania klasy"),
dict(kod="N08", tytul="Mapa przemian „co powstanie?”", poziom="E8+LO", wymaga="N02–N07", poglebia="J03; X01", bylo="N07",
     cel="Uczeń przewiduje produkty przemian między klasami związków.",
     zakres="pierwiastek → tlenek → wodorotlenek / kwas → sól; reakcje między klasami; moduł interaktywny dostępny z każdej lekcji N",
     dlaczego="mapa spina N i ma być dostępna z każdej lekcji N, nie tylko na końcu"),
# ---------------- R ----------------
dict(kod="R01", tytul="Woda i roztwory", poziom="E8", wymaga="F03; F15", poglebia="R02; J01", bylo="R01",
     cel="Uczeń opisuje wodę jako rozpuszczalnik i rozróżnia roztwór, zawiesinę i koloid.",
     zakres="budowa i polarność wody; rozpuszczanie; roztwór, zawiesina, koloid; czynniki szybkości rozpuszczania"),
dict(kod="R02", tytul="Rozpuszczalność", poziom="E8", wymaga="R01", poglebia="R03; J10", bylo="R02",
     cel="Uczeń odczytuje krzywe rozpuszczalności i rozróżnia roztwór nasycony i nienasycony.",
     zakres="rozpuszczalność i jej zależność od temperatury; krzywe; roztwór nasycony / nienasycony; krystalizacja; zadania z krzywych"),
dict(kod="R03", tytul="Stężenie procentowe", poziom="E8+LO", wymaga="R02", poglebia="R05", bylo="R03",
     cel="Uczeń oblicza stężenie procentowe, rozcieńcza, zatęża i miesza roztwory.",
     zakres="Cp; rozcieńczanie i zatężanie; mieszanie roztworów; gęstość (LO)"),
dict(kod="R04", tytul="Mol i masa molowa", poziom="LO", wymaga="F12", poglebia="R05–R09", bylo="R05",
     cel="Uczeń przelicza masę, liczbę moli i liczbę cząstek.",
     zakres="mol, liczba Avogadra, masa molowa; przeliczenia masa ↔ mol ↔ liczba cząstek",
     dlaczego="stężenie molowe wymaga mola — w v0.1 było odwrotnie"),
dict(kod="R05", tytul="Stężenie molowe", poziom="LO", wymaga="R03; R04", poglebia="J02; J07; E01", bylo="R04",
     cel="Uczeń oblicza stężenie molowe i przelicza Cp ↔ Cm.",
     zakres="Cm; przygotowanie roztworu; przeliczanie Cp ↔ Cm z gęstością"),
dict(kod="R06", tytul="Gazy: objętość molowa", poziom="LO", wymaga="R04", poglebia="R07", bylo="nowa",
     cel="Uczeń stosuje objętość molową i równanie Clapeyrona.",
     zakres="objętość molowa w warunkach normalnych; równanie Clapeyrona; gęstość gazu",
     dlaczego="stechiometria z objętością gazu nie miała właściciela"),
dict(kod="R07", tytul="Stechiometria", poziom="LO", wymaga="F17; R04; R06", poglebia="R08; R09", bylo="R06",
     cel="Uczeń wykonuje obliczenia na podstawie równań reakcji.",
     zakres="obliczenia masa / mole / objętość z równania; proporcje; skład mieszanin"),
dict(kod="R08", tytul="Reagent ograniczający", poziom="LO", wymaga="R07", poglebia="R09", bylo="R07",
     cel="Uczeń wskazuje reagent ograniczający i oblicza skład mieszaniny poreakcyjnej.",
     zakres="nadmiar i niedomiar; reagent ograniczający; skład po reakcji"),
dict(kod="R09", tytul="Wydajność reakcji", poziom="LO", wymaga="R07; R08", poglebia="K11", bylo="R08",
     cel="Uczeń oblicza wydajność i uwzględnia zanieczyszczenia substratów.",
     zakres="wydajność; straty; czystość substratów; zadania wieloetapowe"),
# ---------------- J ----------------
dict(kod="J01", tytul="Dysocjacja elektrolityczna", poziom="E8+LO", wymaga="F15; N03–N05; R01", poglebia="J02–J04; J06", bylo="J01",
     cel="Uczeń zapisuje równania dysocjacji i rozróżnia elektrolity mocne i słabe.",
     zakres="elektrolity i nieelektrolity; dysocjacja kwasów, zasad, soli (OWNER pełny); dysocjacja stopniowa; stopień dysocjacji (LO)"),
dict(kod="J02", tytul="pH i odczyn", poziom="E8+LO", wymaga="J01", poglebia="J07; J09; J12", bylo="J02",
     cel="Uczeń określa odczyn, posługuje się skalą pH i wskaźnikami; LO: oblicza pH.",
     zakres="odczyn kwasowy, obojętny, zasadowy; skala pH; wskaźniki; obliczenia pH roztworów mocnych elektrolitów (LO)"),
dict(kod="J03", tytul="Reakcje jonowe", poziom="E8+LO", wymaga="J01", poglebia="J04; J11", bylo="J03",
     cel="Uczeń zapisuje reakcje w formie cząsteczkowej, jonowej pełnej i skróconej.",
     zakres="zapis jonowy pełny i skrócony; zobojętnianie; kiedy reakcja jonowa zachodzi"),
dict(kod="J04", tytul="Strącanie osadów", poziom="E8+LO", wymaga="J03; N05", poglebia="J10; J11", bylo="J04",
     cel="Uczeń przewiduje powstanie osadu z tabeli rozpuszczalności.",
     zakres="tabela rozpuszczalności; reakcje strąceniowe; dobór odczynników"),
dict(kod="J05", tytul="Amfoteryczność", poziom="LO", wymaga="N02; N03; J03", poglebia="P03", bylo="J05",
     cel="Uczeń rozpoznaje substancje amfoteryczne i zapisuje ich reakcje.",
     zakres="tlenki i wodorotlenki amfoteryczne (Al, Zn); reakcje z kwasem i zasadą; kompleksy hydroksylowe"),
dict(kod="J06", tytul="Równowagi kwasowo-zasadowe", poziom="LO", wymaga="J01; J02", poglebia="J07", bylo="J06",
     cel="Uczeń stosuje teorię Brønsteda jakościowo.",
     zakres="teoria Arrheniusa i Brønsteda; pary sprzężone; moc kwasów i zasad — opis jakościowy"),
dict(kod="J07", tytul="Ka, Kb i Kw", poziom="LO", wymaga="J06; K09", poglebia="J08; J09", bylo="J09",
     cel="Uczeń oblicza stałe dysocjacji i korzysta z iloczynu jonowego wody.",
     zakres="Ka, Kb, Kw; pKa; prawo rozcieńczeń Ostwalda; pH słabych elektrolitów",
     dlaczego="stałe są potrzebne do hydrolizy i buforów, więc idą przed nimi"),
dict(kod="J08", tytul="Hydroliza soli", poziom="LO", wymaga="J07; N05", poglebia="J09", bylo="J07",
     cel="Uczeń przewiduje odczyn roztworów soli i zapisuje równania hydrolizy.",
     zakres="hydroliza kationowa, anionowa, kationowo-anionowa; przewidywanie odczynu; obliczenia (LO-R)"),
dict(kod="J09", tytul="Bufory", poziom="LO", wymaga="J07; J08", poglebia="J12", bylo="J08",
     cel="Uczeń wyjaśnia działanie buforu i oblicza jego pH.",
     zakres="skład i działanie buforu; bufory w organizmie; pH buforu"),
dict(kod="J10", tytul="Iloczyn rozpuszczalności Ksp", poziom="LO", wymaga="J04; K09", poglebia="J11", bylo="J10",
     cel="Uczeń oblicza rozpuszczalność z Ksp i warunek strącania.",
     zakres="Ksp; rozpuszczalność molowa; warunek strącania; efekt wspólnego jonu"),
dict(kod="J11", tytul="Identyfikacja jonów", poziom="E8+LO", wymaga="J03; J04", poglebia="J12", bylo="J11",
     cel="Uczeń planuje wykrycie jonów reakcjami charakterystycznymi.",
     zakres="analiza jakościowa; reakcje charakterystyczne kationów i anionów; projekt doświadczenia"),
dict(kod="J12", tytul="Miareczkowanie", poziom="LO", wymaga="J02; R05", poglebia="—", bylo="J12",
     cel="Uczeń przeprowadza i interpretuje miareczkowanie alkacymetryczne.",
     zakres="procedura i sprzęt; krzywe miareczkowania; punkt równoważnikowy i wskaźnik; obliczenia"),
# ---------------- O ----------------
dict(kod="O01", tytul="Język chemii organicznej", poziom="E8+LO", wymaga="F11; F12; F13", poglebia="O02–O25", bylo="O01 + część O20",
     cel="Uczeń zapisuje wzory związków węgla i stosuje podstawy nazewnictwa.",
     zakres="węgiel w związkach; wzory strukturalne, półstrukturalne, szkieletowe; szereg homologiczny; podstawy nazewnictwa (OWNER podstaw)",
     dlaczego="nazewnictwo to warstwa — podstawy na początku, zbiorcza procedura (O24) na końcu"),
dict(kod="O02", tytul="Alkany", poziom="E8+LO", wymaga="O01", poglebia="O03; O06", bylo="O02",
     cel="Uczeń opisuje budowę, nazwy i właściwości alkanów.",
     zakres="szereg alkanów; nazwy; właściwości fizyczne; reakcja podstawienia (halogenowanie); źródła (ropa, gaz)"),
dict(kod="O03", tytul="Izomeria", poziom="E8+LO", wymaga="O02", poglebia="O04; O15; O18", bylo="O06",
     cel="Uczeń rozpoznaje i rysuje izomery.",
     zakres="izomeria łańcuchowa (od alkanów), położenia, funkcyjna; geometryczna cis-trans i optyczna (LO)",
     dlaczego="izomeria łańcuchowa pojawia się już przy alkanach"),
dict(kod="O04", tytul="Alkeny", poziom="E8+LO", wymaga="O02; O03", poglebia="O05; O21", bylo="O03",
     cel="Uczeń opisuje wiązanie podwójne i reakcje addycji.",
     zakres="budowa i nazwy; addycja (H₂, Br₂, HX, H₂O); reguła Markownikowa (LO); polimeryzacja (wstęp); odbarwianie wody bromowej"),
dict(kod="O05", tytul="Alkiny", poziom="E8+LO", wymaga="O04", poglebia="O06", bylo="O04",
     cel="Uczeń opisuje wiązanie potrójne i właściwości etynu.",
     zakres="budowa i nazwy; etyn — otrzymywanie z karbidu, właściwości; addycja"),
dict(kod="O06", tytul="Spalanie węglowodorów", poziom="E8", wymaga="O02; O04; O05; F17", poglebia="K01", bylo="O07",
     cel="Uczeń zapisuje spalanie całkowite i niecałkowite i wykrywa produkty.",
     zakres="spalanie całkowite, półspalanie, niecałkowite; wykrywanie CO₂ i H₂O; paliwa; BHP (CO)"),
dict(kod="O07", tytul="Areny", poziom="LO", wymaga="O04", poglebia="O09; O25", bylo="O05",
     cel="Uczeń opisuje aromatyczność benzenu i substytucję.",
     zakres="benzen, aromatyczność; substytucja elektrofilowa; homologi benzenu"),
dict(kod="O08", tytul="Alkohole", poziom="E8+LO", wymaga="O02", poglebia="O10–O12", bylo="O08",
     cel="Uczeń opisuje budowę, właściwości i reakcje alkoholi.",
     zakres="metanol, etanol, glicerol; alkohole jedno- i wielowodorotlenowe; właściwości; fermentacja; utlenianie (LO); rzędowość (LO)"),
dict(kod="O09", tytul="Fenole", poziom="LO", wymaga="O07; O08", poglebia="—", bylo="nowa",
     cel="Uczeń porównuje fenole z alkoholami.",
     zakres="budowa fenolu; kwasowość; reakcje; porównanie z alkoholami"),
dict(kod="O10", tytul="Aldehydy i ketony", poziom="LO", wymaga="O08", poglebia="O11; O15", bylo="nowa",
     cel="Uczeń rozpoznaje grupę karbonylową i wykonuje próby Tollensa i Trommera.",
     zakres="aldehydy i ketony — budowa, nazwy; otrzymywanie z alkoholi; próba Tollensa, Trommera"),
dict(kod="O11", tytul="Kwasy karboksylowe", poziom="E8+LO", wymaga="O08; J01", poglebia="O12; O13", bylo="O09",
     cel="Uczeń opisuje budowę i reakcje kwasów karboksylowych.",
     zakres="kwas mrówkowy, octowy; kwasy tłuszczowe; dysocjacja; reakcje z metalami, zasadami, tlenkami; hydroksykwasy i aminokwasy (wstęp, LO)"),
dict(kod="O12", tytul="Estry", poziom="E8+LO", wymaga="O08; O11", poglebia="O13", bylo="O10",
     cel="Uczeń zapisuje estryfikację i hydrolizę estrów.",
     zakres="estryfikacja; nazwy estrów; hydroliza kwasowa i zasadowa; zastosowania"),
dict(kod="O13", tytul="Tłuszcze, mydła i detergenty", poziom="E8+LO", wymaga="O11; O12", poglebia="O22; O23", bylo="O11 + nowe",
     cel="Uczeń opisuje budowę tłuszczów, zmydlanie i działanie mydła.",
     zakres="tłuszcze nasycone i nienasycone; utwardzanie; zmydlanie; budowa i działanie mydła i detergentów; twarda woda",
     dlaczego="mydła nie miały właściciela; do weryfikacji, czy są w E8 po 2024"),
dict(kod="O14", tytul="Aminy i amidy", poziom="LO", wymaga="O01; J06", poglebia="O18", bylo="nowa",
     cel="Uczeń opisuje zasadowość amin i budowę amidów.",
     zakres="aminy — budowa, zasadowość; amidy; mocznik"),
dict(kod="O15", tytul="Cukry — monosacharydy", poziom="E8+LO", wymaga="O08; O10", poglebia="O16; O17", bylo="O12",
     cel="Uczeń opisuje glukozę i fruktozę i je wykrywa.",
     zakres="glukoza, fruktoza; budowa łańcuchowa i pierścieniowa (LO); wykrywanie; fotosynteza (wstęp)"),
dict(kod="O16", tytul="Cukry — disacharydy", poziom="E8+LO", wymaga="O15", poglebia="O17", bylo="O13",
     cel="Uczeń opisuje sacharozę i jej hydrolizę.",
     zakres="sacharoza, laktoza, maltoza; hydroliza; cukry redukujące i nieredukujące (LO)"),
dict(kod="O17", tytul="Cukry — polisacharydy", poziom="E8+LO", wymaga="O16", poglebia="O23", bylo="O14",
     cel="Uczeń porównuje skrobię i celulozę i wykrywa skrobię.",
     zakres="skrobia, celuloza, glikogen; wykrywanie skrobi jodem; znaczenie"),
dict(kod="O18", tytul="Aminokwasy", poziom="E8+LO", wymaga="O11; O14", poglebia="O19", bylo="O15",
     cel="Uczeń opisuje budowę aminokwasów i wiązanie peptydowe.",
     zakres="glicyna; amfoteryczność; jon obojnaczy (LO); wiązanie peptydowe; peptydy"),
dict(kod="O19", tytul="Białka — struktura", poziom="E8+LO", wymaga="O18", poglebia="O20", bylo="O16",
     cel="Uczeń opisuje struktury białek, denaturację i koagulację.",
     zakres="struktury I–IV rzędowe; denaturacja i koagulacja; czynniki denaturujące"),
dict(kod="O20", tytul="Białka — reakcje charakterystyczne", poziom="E8+LO", wymaga="O19", poglebia="O23", bylo="O17",
     cel="Uczeń wykrywa białka reakcjami charakterystycznymi.",
     zakres="reakcja ksantoproteinowa i biuretowa; projekt doświadczenia"),
dict(kod="O21", tytul="Polimery i tworzywa", poziom="E8+LO", wymaga="O04; O12", poglebia="—", bylo="nowa",
     cel="Uczeń opisuje polimeryzację, polikondensację i problem tworzyw sztucznych.",
     zakres="polimeryzacja i polikondensacja; PE, PVC, PET; tworzywa i środowisko; recykling"),
dict(kod="O22", tytul="Witaminy i sole mineralne", poziom="E8", wymaga="O13", poglebia="—", bylo="O18",
     cel="Aspekt chemiczny — właściciel tematu w biologii (REF).",
     zakres="witaminy rozpuszczalne w wodzie i tłuszczach; makro- i mikroelementy — tylko chemiczne odniesienie do biologii"),
dict(kod="O23", tytul="Metabolizm", poziom="LO", wymaga="O15–O20", poglebia="—", bylo="O19",
     cel="Aspekt chemiczny — właściciel tematu w biologii (REF).",
     zakres="reakcje i energia w metabolizmie; oddychanie komórkowe chemicznie — odniesienie do biologii"),
dict(kod="O24", tytul="Nazewnictwo — procedura zbiorcza", poziom="LO", wymaga="O01–O21", poglebia="O25", bylo="O20",
     cel="Uczeń nazywa związki wszystkich klas wg zasad IUPAC.",
     zakres="priorytety grup funkcyjnych; łańcuch główny; lokanty; związki wielofunkcyjne"),
dict(kod="O25", tytul="Mechanizmy reakcji organicznych", poziom="LO", wymaga="O24", poglebia="—", bylo="O21",
     cel="Uczeń opisuje przepływ elektronów w typowych mechanizmach.",
     zakres="substytucja rodnikowa, elektrofilowa, nukleofilowa; addycja; eliminacja; zapis strzałkowy"),
# ---------------- X ----------------
dict(kod="X01", tytul="Reakcje redoks", poziom="LO", wymaga="F09; F17", poglebia="X02–X09", bylo="X01 + X02",
     cel="Uczeń rozpoznaje redoks po zmianie stopni utlenienia i wskazuje utleniacz i reduktor.",
     zakres="ściąga stopnia utlenienia (definicja w F09); utlenianie, redukcja; utleniacz, reduktor; rozpoznawanie reakcji redoks",
     dlaczego="stary X01 dublował F09 — definicja zostaje tylko w F09"),
dict(kod="X02", tytul="Typowe utleniacze i reduktory", poziom="LO", wymaga="X01", poglebia="X05–X07", bylo="X05",
     cel="Uczeń zna katalog typowych utleniaczy i reduktorów i przewiduje produkty.",
     zakres="KMnO₄, K₂Cr₂O₇, H₂O₂, HNO₃, H₂SO₄ stęż.; metale, węgiel, wodór; zależność od środowiska"),
dict(kod="X03", tytul="Bilans elektronowy", poziom="LO", wymaga="X01", poglebia="X05–X08", bylo="X03",
     cel="Uczeń dobiera współczynniki metodą bilansu elektronowego.",
     zakres="równania połówkowe; bilans elektronów; procedura krok po kroku"),
dict(kod="X04", tytul="Szereg aktywności metali", poziom="E8+LO", wymaga="N04; X01", poglebia="E02", bylo="X04",
     cel="Uczeń przewiduje wypieranie metali i wodoru.",
     zakres="szereg aktywności; metal + kwas, metal + sól; metale szlachetne"),
dict(kod="X05", tytul="Redoks jonowy", poziom="LO", wymaga="X03; J03", poglebia="X06; X07", bylo="X06",
     cel="Uczeń bilansuje redoks w formie jonowej.",
     zakres="zapis jonowy redoks; bilans ładunku i elektronów"),
dict(kod="X06", tytul="Redoks w środowisku kwasowym", poziom="LO", wymaga="X05", poglebia="E04", bylo="X07",
     cel="Uczeń bilansuje metodą połówkową w środowisku kwasowym.",
     zakres="metoda połówkowa z H⁺ i H₂O; KMnO₄ w kwasie"),
dict(kod="X07", tytul="Redoks w środowisku zasadowym", poziom="LO", wymaga="X05", poglebia="—", bylo="X08",
     cel="Uczeń bilansuje metodą połówkową w środowisku zasadowym.",
     zakres="metoda połówkowa z OH⁻ i H₂O; KMnO₄ w środowisku obojętnym i zasadowym"),
dict(kod="X08", tytul="Dysproporcjonowanie i synproporcjonowanie", poziom="LO", wymaga="X03", poglebia="—", bylo="X09",
     cel="Uczeń rozpoznaje i bilansuje dys- i synproporcjonowanie.",
     zakres="definicje; przykłady (Cl₂ w zasadzie, H₂O₂); bilans"),
dict(kod="X09", tytul="Redoks przekrojowy", poziom="LO", wymaga="X01–X08", poglebia="E01–E06", bylo="X10",
     cel="Uczeń łączy całą grupę X w zadaniach przekrojowych.",
     zakres="zadania łączące; diagnostyka błędów redoks"),
# ---------------- E ----------------
dict(kod="E01", tytul="Ogniwo galwaniczne", poziom="LO", wymaga="X03; J01; R05", poglebia="E02; E03", bylo="E01",
     cel="Uczeń opisuje budowę i działanie ogniwa i zapisuje jego schemat.",
     zakres="ogniwo Daniella; anoda, katoda; klucz elektrolityczny; schemat ogniwa"),
dict(kod="E02", tytul="Potencjały elektrodowe", poziom="LO", wymaga="E01; X04", poglebia="E03", bylo="E02",
     cel="Uczeń korzysta z szeregu elektrochemicznego.",
     zakres="potencjał standardowy; elektroda wodorowa; szereg elektrochemiczny"),
dict(kod="E03", tytul="SEM", poziom="LO", wymaga="E02", poglebia="E06", bylo="E03",
     cel="Uczeń oblicza SEM i przewiduje samorzutność reakcji.",
     zakres="obliczanie SEM; kierunek reakcji; równanie Nernsta (LO-R, wstęp)"),
dict(kod="E04", tytul="Elektroliza", poziom="LO", wymaga="E02; X06", poglebia="—", bylo="E04",
     cel="Uczeń zapisuje procesy elektrodowe i stosuje prawa Faradaya.",
     zakres="elektroliza stopionych soli i roztworów; kolejność wydzielania; prawa Faradaya"),
dict(kod="E05", tytul="Korozja", poziom="E8+LO", wymaga="X04", poglebia="—", bylo="E05",
     cel="Uczeń wyjaśnia korozję i dobiera ochronę.",
     zakres="korozja chemiczna i elektrochemiczna; czynniki; ochrona (powłoki, protektor)"),
dict(kod="E06", tytul="Źródła energii i akumulatory", poziom="LO", wymaga="E03", poglebia="—", bylo="E06",
     cel="Uczeń porównuje baterie, akumulatory i ogniwa paliwowe.",
     zakres="ogniwo Leclanchégo; akumulator ołowiowy i litowo-jonowy; ogniwo paliwowe"),
# ---------------- K ----------------
dict(kod="K01", tytul="Energia reakcji", poziom="E8+LO", wymaga="F16; F17", poglebia="K02; K06", bylo="K05",
     cel="Uczeń rozróżnia reakcje egzo- i endoenergetyczne i czyta wykres energetyczny.",
     zakres="egzo- i endoenergetyczne; wykres energetyczny — jakościowo",
     dlaczego="energia przed szybkością — energia aktywacji wymaga wykresu energetycznego"),
dict(kod="K02", tytul="Entalpia", poziom="LO", wymaga="K01", poglebia="K03", bylo="K06",
     cel="Uczeń oblicza ΔH, także z prawa Hessa.",
     zakres="ΔH; entalpie tworzenia i spalania; prawo Hessa; energia wiązań"),
dict(kod="K03", tytul="Kalorymetria i przemiany fazowe", poziom="LO", wymaga="K02", poglebia="—", bylo="K10",
     cel="Uczeń mierzy i oblicza ciepło reakcji i przemian fazowych.",
     zakres="ciepło właściwe; kalorymetr; ciepło przemian fazowych; wykres ogrzewania"),
dict(kod="K04", tytul="Szybkość reakcji", poziom="LO", wymaga="R05", poglebia="K05", bylo="K01",
     cel="Uczeń definiuje i mierzy szybkość reakcji.",
     zakres="szybkość średnia i chwilowa; pomiar; wykresy stężenie–czas; równanie kinetyczne (LO-R)"),
dict(kod="K05", tytul="Czynniki wpływające na szybkość", poziom="E8+LO", wymaga="K04", poglebia="K06; K07", bylo="K02",
     cel="Uczeń przewiduje wpływ stężenia, temperatury i rozdrobnienia.",
     zakres="stężenie, temperatura, rozdrobnienie, katalizator — doświadczenia"),
dict(kod="K06", tytul="Zderzenia i energia aktywacji", poziom="LO", wymaga="K01; K05", poglebia="K07", bylo="K03",
     cel="Uczeń wyjaśnia szybkość teorią zderzeń.",
     zakres="teoria zderzeń; energia aktywacji na wykresie; rozkład energii cząsteczek"),
dict(kod="K07", tytul="Kataliza", poziom="E8+LO", wymaga="K06", poglebia="O19", bylo="K04",
     cel="Uczeń opisuje działanie katalizatora, enzymu i inhibitora.",
     zakres="kataliza homo- i heterogeniczna; enzymy; inhibitory; katalizatory w przemyśle i samochodach"),
dict(kod="K08", tytul="Równowaga dynamiczna", poziom="LO", wymaga="K04", poglebia="K09", bylo="K07",
     cel="Uczeń opisuje stan równowagi w reakcjach odwracalnych.",
     zakres="reakcje odwracalne; stan równowagi dynamicznej; modele"),
dict(kod="K09", tytul="Stała równowagi", poziom="LO", wymaga="K08; R05", poglebia="K10; J07; J10", bylo="K08",
     cel="Uczeń zapisuje wyrażenie na K i wykonuje obliczenia.",
     zakres="wyrażenie K; obliczenia stężeń równowagowych; Kp (LO-R)"),
dict(kod="K10", tytul="Reguła Le Chateliera", poziom="LO", wymaga="K09", poglebia="K11", bylo="K09",
     cel="Uczeń przewiduje przesunięcie równowagi.",
     zakres="wpływ stężenia, ciśnienia, temperatury; zastosowania przemysłowe (synteza amoniaku)"),
dict(kod="K11", tytul="Równowaga ilościowa", poziom="LO", wymaga="K09; K10", poglebia="—", bylo="K11",
     cel="Uczeń rozwiązuje zadania z równowagi.",
     zakres="stopień przereagowania; zadania złożone z K"),
# ---------------- A ----------------
dict(kod="A01", tytul="Jądro atomowe", poziom="LO", wymaga="F04; F05", poglebia="A02", bylo="A01",
     cel="Uczeń opisuje siły jądrowe i stabilność jąder.",
     zakres="skład jądra (REF do F04–F05); siły jądrowe; ścieżka stabilności"),
dict(kod="A02", tytul="Radioaktywność", poziom="E8+LO", wymaga="A01", poglebia="A03", bylo="A02",
     cel="Uczeń rozróżnia rodzaje promieniowania i ich właściwości.",
     zakres="promieniowanie α, β, γ; przenikliwość; detekcja"),
dict(kod="A03", tytul="Przemiany jądrowe", poziom="LO", wymaga="A02", poglebia="A04", bylo="A03",
     cel="Uczeń zapisuje równania przemian jądrowych.",
     zakres="przemiany α, β⁻, β⁺; szeregi promieniotwórcze; reakcje jądrowe"),
dict(kod="A04", tytul="Okres półtrwania i aktywność", poziom="LO", wymaga="A03", poglebia="A06", bylo="A04",
     cel="Uczeń oblicza ubytek substancji promieniotwórczej.",
     zakres="okres półtrwania; aktywność; datowanie izotopowe"),
dict(kod="A05", tytul="Energia wiązania jądra", poziom="LO", wymaga="A01", poglebia="A06", bylo="A06",
     cel="Uczeń oblicza deficyt masy i energię wiązania.",
     zakres="deficyt masy; E = mc²; rozszczepienie i synteza jądrowa"),
dict(kod="A06", tytul="Zastosowania i BHP", poziom="E8+LO", wymaga="A04; A05", poglebia="—", bylo="A05",
     cel="Uczeń ocenia zastosowania i zagrożenia promieniotwórczości.",
     zakres="medycyna, energetyka, datowanie; ochrona radiologiczna",
     dlaczego="energetyka jądrowa wymaga energii wiązania, więc zastosowania na koniec"),
# ---------------- P ----------------
dict(kod="P01", tytul="Blok s", poziom="E8+LO", wymaga="F06; F11; N03", poglebia="P04", bylo="P01",
     cel="Uczeń opisuje litowce i berylowce oraz ich związki.",
     zakres="właściwości; reakcje z wodą i tlenem; najważniejsze związki"),
dict(kod="P02", tytul="Blok p", poziom="LO", wymaga="F06; N02; N04", poglebia="P04", bylo="P02",
     cel="Uczeń opisuje pierwiastki bloku p i ich związki.",
     zakres="borowce do helowców; metale i niemetale bloku p; najważniejsze związki"),
dict(kod="P03", tytul="Blok d i metale przejściowe", poziom="LO", wymaga="F07; F08; X01", poglebia="P05", bylo="P03 + P04",
     cel="Uczeń opisuje konfiguracje, stopnie utlenienia i związki metali przejściowych.",
     zakres="konfiguracje bloku d; zmienne stopnie utlenienia (Cr, Mn, Fe, Cu); związki barwne; kompleksy (wstęp)",
     dlaczego="„blok d” i „metale przejściowe” to prawie ten sam temat"),
dict(kod="P04", tytul="Charakterystyka grup", poziom="LO", wymaga="P01–P03", poglebia="P05", bylo="P05",
     cel="Uczeń porównuje grupy i ich typowe właściwości.",
     zakres="porównanie grup; podobieństwa i wyjątki"),
dict(kod="P05", tytul="Związki charakterystyczne pierwiastków", poziom="LO", wymaga="P04", poglebia="P06", bylo="P06",
     cel="Uczeń zna najważniejsze związki każdej grupy i ich zastosowania.",
     zakres="katalog związków charakterystycznych; zastosowania"),
dict(kod="P06", tytul="Trend → właściwość → reaktywność", poziom="LO", wymaga="F06; P01–P05", poglebia="—", bylo="P07 + P08",
     cel="Uczeń przewiduje właściwości z położenia w układzie.",
     zakres="łańcuch: położenie → budowa → właściwości → reakcje (trendy jako OWNER w F06 — tu przewidywanie)",
     dlaczego="stare P07 i P08 opisywały to samo"),
]

UZUPELNIENIA = [
    ("FIZ-01", "Elektrostatyka (fizyka, pomost do F04 i F11)"),
    ("LAB", "Zbiór doświadczeń LAB01–24 — przypisane do lekcji przez `wymaga`"),
    ("REV01", "Powtórka fundamentów z klasy 7 (start klasy 8)"),
    ("REV02", "Powtórka klasy 8"),
    ("REV03–05", "LO podstawowe, LO rozszerzone, zadania przekrojowe"),
    ("REV06", "Pomost akademicki / zaawansowana"),
    ("REV07", "Mapa kompetencji i diagnostyka zależności"),
    # powtórki tematyczne z audytu W1 Perplexity (tam REV00–REV10); nowe kody, by nie kolidować z REV01/REV02/REV06
    ("RT00", "Powtórka tematyczna: Powtórki i diagnostyka — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT01", "Powtórka tematyczna: Materia i substancje — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT02", "Powtórka tematyczna: Atom, układ okresowy i konfiguracja — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT03", "Powtórka tematyczna: Wiązania, Lewis i geometria — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT04", "Powtórka tematyczna: Wzory i równania reakcji — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT05", "Powtórka tematyczna: Kwasy, zasady i chemia jonowa — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT06", "Powtórka tematyczna: Stechiometria i roztwory — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT07", "Powtórka tematyczna: Redoks i elektrochemia — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT08", "Powtórka tematyczna: Kinetyka, energia i równowaga — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT09", "Powtórka tematyczna: Jądro, promieniotwórczość i laboratorium — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
    ("RT10", "Powtórka tematyczna: Test mistrzostwa — szkic w plany/audyty/W1_perplexity_REV00-REV10_2026-10-09.md"),
]
