/* N02 Wodorotlenki — substancje (generowane; dodawane tylko, gdy brak) */
(function(){const add={
 "LiOH":{"formula": "LiOH", "name": "wodorotlenek litu", "state": "s", "molarMass": 23.947, "role": "zasada (rozpuszczalny wodorotlenek)", "safety": ["żrący"], "uses": ["pochłaniacze CO₂ (łodzie podwodne, stacje kosmiczne)"]},
 "Ba(OH)2":{"formula": "Ba(OH)2", "name": "wodorotlenek baru", "state": "s", "molarMass": 171.344, "role": "zasada (rozpuszczalny wodorotlenek)", "safety": ["żrący", "związki baru trujące"], "uses": ["analiza chemiczna"]},
 "Zn(OH)2":{"formula": "Zn(OH)2", "name": "wodorotlenek cynku", "state": "s", "molarMass": 99.394, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "Fe(OH)2":{"formula": "Fe(OH)2", "name": "wodorotlenek żelaza(II)", "state": "s", "molarMass": 89.859, "role": "osad (utlenia się na powietrzu)", "safety": [], "uses": []},
 "Ni(OH)2":{"formula": "Ni(OH)2", "name": "wodorotlenek niklu(II)", "state": "s", "molarMass": 92.707, "role": "osad", "safety": ["związki niklu uczulają"], "uses": ["akumulatory Ni-MH"]},
 "Mn(OH)2":{"formula": "Mn(OH)2", "name": "wodorotlenek manganu(II)", "state": "s", "molarMass": 88.952, "role": "osad (brunatnieje na powietrzu)", "safety": [], "uses": []},
 "Pb(OH)2":{"formula": "Pb(OH)2", "name": "wodorotlenek ołowiu(II)", "state": "s", "molarMass": 241.214, "role": "wodorotlenek amfoteryczny", "safety": ["związki ołowiu trujące"], "uses": []},
 "Sn(OH)2":{"formula": "Sn(OH)2", "name": "wodorotlenek cyny(II)", "state": "s", "molarMass": 152.724, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "Cr(OH)3":{"formula": "Cr(OH)3", "name": "wodorotlenek chromu(III)", "state": "s", "molarMass": 103.017, "role": "wodorotlenek amfoteryczny", "safety": [], "uses": []},
 "AgOH":{"formula": "AgOH", "name": "wodorotlenek srebra(I)", "state": "s", "molarMass": 124.877, "role": "nietrwały (→ Ag₂O)", "safety": [], "uses": []},
 "CuOH":{"formula": "CuOH", "name": "wodorotlenek miedzi(I)", "state": "s", "molarMass": 80.553, "role": "nietrwały (→ Cu₂O)", "safety": [], "uses": []},
 "Ag2O":{"formula": "Ag2O", "name": "tlenek srebra(I)", "state": "s", "molarMass": 231.739, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Cu2O":{"formula": "Cu2O", "name": "tlenek miedzi(I)", "state": "s", "molarMass": 143.091, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Fe2O3":{"formula": "Fe2O3", "name": "tlenek żelaza(III)", "state": "s", "molarMass": 159.687, "role": "tlenek zasadowy (słabo amfoteryczny)", "safety": [], "uses": ["pigment, ruda"]},
 "Al2O3":{"formula": "Al2O3", "name": "tlenek glinu", "state": "s", "molarMass": 101.961, "role": "tlenek amfoteryczny", "safety": [], "uses": []},
 "ZnO":{"formula": "ZnO", "name": "tlenek cynku", "state": "s", "molarMass": 81.379, "role": "tlenek amfoteryczny", "safety": [], "uses": []},
 "CuO":{"formula": "CuO", "name": "tlenek miedzi(II)", "state": "s", "molarMass": 79.545, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "MgO":{"formula": "MgO", "name": "tlenek magnezu", "state": "s", "molarMass": 40.304, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "CaO":{"formula": "CaO", "name": "tlenek wapnia", "state": "s", "molarMass": 56.077, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": []},
 "BaO":{"formula": "BaO", "name": "tlenek baru", "state": "s", "molarMass": 153.329, "role": "tlenek zasadowy", "safety": ["żrący", "trujący"], "uses": []},
 "Li":{"formula": "Li", "name": "lit", "state": "s", "molarMass": 6.94, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "K":{"formula": "K", "name": "potas", "state": "s", "molarMass": 39.098, "role": "metal", "safety": ["gwałtownie reaguje z wodą"], "uses": []},
 "Ca":{"formula": "Ca", "name": "wapń", "state": "s", "molarMass": 40.078, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "Ba":{"formula": "Ba", "name": "bar", "state": "s", "molarMass": 137.33, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "MgCl2":{"formula": "MgCl2", "name": "chlorek magnezu", "state": "aq", "molarMass": 95.205, "role": "sól", "safety": [], "uses": []},
 "AlCl3":{"formula": "AlCl3", "name": "chlorek glinu", "state": "aq", "molarMass": 133.332, "role": "sól", "safety": [], "uses": []},
 "ZnSO4":{"formula": "ZnSO4", "name": "siarczan(VI) cynku", "state": "aq", "molarMass": 161.436, "role": "sól", "safety": [], "uses": []},
 "FeSO4":{"formula": "FeSO4", "name": "siarczan(VI) żelaza(II)", "state": "aq", "molarMass": 151.901, "role": "sól", "safety": [], "uses": []},
 "CuCl2":{"formula": "CuCl2", "name": "chlorek miedzi(II)", "state": "aq", "molarMass": 134.446, "role": "sól", "safety": [], "uses": []},
 "NiSO4":{"formula": "NiSO4", "name": "siarczan(VI) niklu(II)", "state": "aq", "molarMass": 154.749, "role": "sól", "safety": ["uczula"], "uses": []},
 "MnSO4":{"formula": "MnSO4", "name": "siarczan(VI) manganu(II)", "state": "aq", "molarMass": 150.994, "role": "sól", "safety": [], "uses": []},
 "Pb(NO3)2":{"formula": "Pb(NO3)2", "name": "azotan(V) ołowiu(II)", "state": "aq", "molarMass": 331.208, "role": "sól", "safety": ["trujący"], "uses": []},
 "CaCl2":{"formula": "CaCl2", "name": "chlorek wapnia", "state": "aq", "molarMass": 110.978, "role": "sól", "safety": [], "uses": []},
 "AgNO3":{"formula": "AgNO3", "name": "azotan(V) srebra", "state": "aq", "molarMass": 169.874, "role": "sól", "safety": ["plami skórę"], "uses": []},
 "NaNO3":{"formula": "NaNO3", "name": "azotan(V) sodu", "state": "aq", "molarMass": 84.994, "role": "sól", "safety": [], "uses": []},
 "KNO3":{"formula": "KNO3", "name": "azotan(V) potasu", "state": "aq", "molarMass": 101.102, "role": "sól", "safety": [], "uses": []},
 "KCl":{"formula": "KCl", "name": "chlorek potasu", "state": "aq", "molarMass": 74.548, "role": "sól", "safety": [], "uses": []},
 "CaSO4":{"formula": "CaSO4", "name": "siarczan(VI) wapnia", "state": "s", "molarMass": 136.134, "role": "sól (trudno rozpuszczalna)", "safety": [], "uses": ["gips"]},
 "BaSO4":{"formula": "BaSO4", "name": "siarczan(VI) baru", "state": "s", "molarMass": 233.386, "role": "sól (nierozpuszczalna)", "safety": [], "uses": ["kontrast RTG"]},
 "BaCl2":{"formula": "BaCl2", "name": "chlorek baru", "state": "aq", "molarMass": 208.23, "role": "sól", "safety": ["trujący"], "uses": []},
 "BaCO3":{"formula": "BaCO3", "name": "węglan baru", "state": "s", "molarMass": 197.338, "role": "sól (nierozpuszczalna)", "safety": ["trujący"], "uses": []},
 "Ca(HCO3)2":{"formula": "Ca(HCO3)2", "name": "wodorowęglan wapnia", "state": "aq", "molarMass": 162.11, "role": "sól (wodorosól)", "safety": [], "uses": ["twardość wody"]},
 "Al2(SO4)3":{"formula": "Al2(SO4)3", "name": "siarczan(VI) glinu", "state": "aq", "molarMass": 342.132, "role": "sól", "safety": [], "uses": ["uzdatnianie wody"]},
 "Na2Pb(OH)4":{"formula": "Na2Pb(OH)4", "name": "tetrahydroksoołowian(II) sodu", "state": "aq", "molarMass": 321.208, "role": "sól kompleksowa", "safety": [], "uses": []},
 "NH4Cl":{"formula": "NH4Cl", "name": "chlorek amonu", "state": "aq", "molarMass": 53.489, "role": "sól", "safety": [], "uses": []},
 "NH3":{"formula": "NH3", "name": "amoniak", "state": "g", "molarMass": 17.031, "role": "zasada Brønsteda", "safety": ["drażniący"], "uses": []},
 "Na2CO3":{"formula": "Na2CO3", "name": "węglan sodu", "state": "aq", "molarMass": 105.988, "role": "sól", "safety": [], "uses": []},
 "CaCO3":{"formula": "CaCO3", "name": "węglan wapnia", "state": "s", "molarMass": 100.086, "role": "sól (nierozpuszczalna)", "safety": [], "uses": []},
 "Na2SO4":{"formula": "Na2SO4", "name": "siarczan(VI) sodu", "state": "aq", "molarMass": 142.036, "role": "sól", "safety": [], "uses": []},
 "NaCl":{"formula": "NaCl", "name": "chlorek sodu", "state": "aq", "molarMass": 58.44, "role": "sól", "safety": [], "uses": []},
 "CuSO4":{"formula": "CuSO4", "name": "siarczan(VI) miedzi(II)", "state": "aq", "molarMass": 159.602, "role": "sól", "safety": [], "uses": []},
 "FeCl3":{"formula": "FeCl3", "name": "chlorek żelaza(III)", "state": "aq", "molarMass": 162.195, "role": "sól", "safety": [], "uses": []},
 "ZnCl2":{"formula": "ZnCl2", "name": "chlorek cynku", "state": "aq", "molarMass": 136.28, "role": "sól", "safety": [], "uses": []},
 "H2":{"formula": "H2", "name": "wodór", "state": "g", "molarMass": 2.016, "role": "pierwiastek", "safety": ["palny"], "uses": []},
 "O2":{"formula": "O2", "name": "tlen", "state": "g", "molarMass": 31.998, "role": "pierwiastek", "safety": [], "uses": []}
};Object.keys(add).forEach(k=>{if(!S[k])S[k]=add[k]});})();
