/* v0.44: N01 Tlenki — substancje (generowane; dodawane tylko, gdy brak) */
(function(){const add={
 "K2O":{"formula": "K2O", "name": "tlenek potasu", "state": "s", "molarMass": 94.195, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": []},
 "Li2O":{"formula": "Li2O", "name": "tlenek litu", "state": "s", "molarMass": 29.879, "role": "tlenek zasadowy", "safety": ["żrący"], "uses": ["ceramika, szkło"]},
 "BeO":{"formula": "BeO", "name": "tlenek berylu", "state": "s", "molarMass": 25.011, "role": "tlenek amfoteryczny", "safety": ["toksyczny (pył)"], "uses": ["ceramika techniczna"]},
 "B2O3":{"formula": "B2O3", "name": "tlenek boru", "state": "s", "molarMass": 69.617, "role": "tlenek kwasowy", "safety": [], "uses": ["szkło borokrzemianowe"]},
 "Al2O3":{"formula": "Al2O3", "name": "tlenek glinu", "state": "s", "molarMass": 101.961, "role": "tlenek amfoteryczny", "safety": [], "uses": ["korund, szlifierki", "warstwa pasywna glinu", "ceramika techniczna", "rubin/szafir (z domieszkami)"]},
 "FeO":{"formula": "FeO", "name": "tlenek żelaza(II)", "state": "s", "molarMass": 71.844, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "Fe3O4":{"formula": "Fe3O4", "name": "tlenek żelaza(II,III) (magnetyt)", "state": "s", "molarMass": 231.531, "role": "tlenek mieszany", "safety": [], "uses": ["ruda żelaza", "magnetyczne nośniki"]},
 "Cu2O":{"formula": "Cu2O", "name": "tlenek miedzi(I)", "state": "s", "molarMass": 143.091, "role": "tlenek zasadowy", "safety": [], "uses": ["pigment, kupryt"]},
 "P2O5":{"formula": "P2O5", "name": "tlenek fosforu(V) (zapis empiryczny P₂O₅)", "state": "s", "molarMass": 141.943, "role": "tlenek kwasowy", "safety": ["żrący", "silnie higroskopijny"], "uses": ["osuszacz"]},
 "N2O":{"formula": "N2O", "name": "tlenek azotu(I) (podtlenek azotu, gaz rozweselający)", "state": "g", "molarMass": 44.013, "role": "tlenek obojętny", "safety": ["gaz cieplarniany"], "uses": ["anestezja", "bita śmietana (gaz nośny)"]},
 "Mn2O7":{"formula": "Mn2O7", "name": "tlenek manganu(VII)", "state": "l", "molarMass": 221.869, "role": "tlenek kwasowy", "safety": ["silny utleniacz, wybuchowy"], "uses": []},
 "CrO3":{"formula": "CrO3", "name": "tlenek chromu(VI)", "state": "s", "molarMass": 99.993, "role": "tlenek kwasowy", "safety": ["toksyczny, rakotwórczy", "silny utleniacz"], "uses": ["chromowanie"]},
 "Cr2O3":{"formula": "Cr2O3", "name": "tlenek chromu(III)", "state": "s", "molarMass": 151.989, "role": "tlenek amfoteryczny", "safety": [], "uses": ["zielony pigment"]},
 "MnO2":{"formula": "MnO2", "name": "tlenek manganu(IV)", "state": "s", "molarMass": 86.936, "role": "tlenek amfoteryczny", "safety": [], "uses": ["baterie", "katalizator rozkładu H₂O₂"]},
 "MnO":{"formula": "MnO", "name": "tlenek manganu(II)", "state": "s", "molarMass": 70.937, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "CrO":{"formula": "CrO", "name": "tlenek chromu(II)", "state": "s", "molarMass": 67.995, "role": "tlenek zasadowy", "safety": [], "uses": []},
 "TiO2":{"formula": "TiO2", "name": "tlenek tytanu(IV) (biel tytanowa, rutyl)", "state": "s", "molarMass": 79.865, "role": "tlenek amfoteryczny (słabo)", "safety": [], "uses": ["biały pigment", "filtry UV", "fotokataliza"]},
 "HgO":{"formula": "HgO", "name": "tlenek rtęci(II)", "state": "s", "molarMass": 216.589, "role": "tlenek zasadowy", "safety": ["toksyczny"], "uses": ["historyczne otrzymywanie tlenu"]},
 "Ag2O":{"formula": "Ag2O", "name": "tlenek srebra(I)", "state": "s", "molarMass": 231.739, "role": "tlenek zasadowy", "safety": [], "uses": ["ogniwa srebrowe"]},
 "PbO":{"formula": "PbO", "name": "tlenek ołowiu(II)", "state": "s", "molarMass": 223.199, "role": "tlenek amfoteryczny", "safety": ["toksyczny"], "uses": ["szkło ołowiowe"]},
 "PbO2":{"formula": "PbO2", "name": "tlenek ołowiu(IV)", "state": "s", "molarMass": 239.198, "role": "tlenek (utleniacz)", "safety": ["toksyczny"], "uses": ["akumulator ołowiowy"]},
 "Cl2O7":{"formula": "Cl2O7", "name": "tlenek chloru(VII)", "state": "l", "molarMass": 182.893, "role": "tlenek kwasowy", "safety": ["wybuchowy"], "uses": []},
 "Na2O2":{"formula": "Na2O2", "name": "nadtlenek sodu", "state": "s", "molarMass": 77.978, "role": "nadtlenek (nie tlenek!)", "safety": ["żrący", "silny utleniacz"], "uses": ["regeneracja powietrza (okręty, statki kosmiczne)"]},
 "H2O2":{"formula": "H2O2", "name": "nadtlenek wodoru (woda utleniona 3%)", "state": "aq", "molarMass": 34.014, "role": "nadtlenek (nie tlenek!)", "safety": ["stężony — żrący, utleniacz"], "uses": ["dezynfekcja", "wybielanie"]},
 "OF2":{"formula": "OF2", "name": "difluorek tlenu (fluorek tlenu — nie tlenek!)", "state": "g", "molarMass": 53.995, "role": "fluorek tlenu", "safety": ["silnie toksyczny"], "uses": []},
 "LiOH":{"formula": "LiOH", "name": "wodorotlenek litu", "state": "aq", "molarMass": 23.947, "role": "zasada", "safety": ["żrący"], "uses": ["pochłaniacze CO₂"]},
 "KOH":{"formula": "KOH", "name": "wodorotlenek potasu", "state": "aq", "molarMass": 56.105, "role": "zasada", "safety": ["żrący"], "uses": ["mydła miękkie", "elektrolit"]},
 "Mg(OH)2":{"formula": "Mg(OH)2", "name": "wodorotlenek magnezu", "state": "s", "molarMass": 58.319, "role": "wodorotlenek", "safety": [], "uses": ["lek zobojętniający (mleko magnezowe)"]},
 "HMnO4":{"formula": "HMnO4", "name": "kwas manganowy(VII)", "state": "aq", "molarMass": 119.942, "role": "kwas", "safety": ["silny utleniacz"], "uses": []},
 "H2CrO4":{"formula": "H2CrO4", "name": "kwas chromowy(VI)", "state": "aq", "molarMass": 118.008, "role": "kwas", "safety": ["toksyczny"], "uses": []},
 "Fe2(SO4)3":{"formula": "Fe2(SO4)3", "name": "siarczan(VI) żelaza(III)", "state": "aq", "molarMass": 399.858, "role": "sól", "safety": [], "uses": ["koagulant (uzdatnianie wody)"]},
 "NaAlO2":{"formula": "NaAlO2", "name": "glinian sodu (zapis uproszczony / po stopieniu)", "state": "s", "molarMass": 81.97, "role": "sól", "safety": ["żrący"], "uses": []},
 "NaAl(OH)4":{"formula": "NaAl(OH)4", "name": "tetrahydroksoglinian sodu", "state": "aq", "molarMass": 118.0, "role": "sól kompleksowa", "safety": ["żrący"], "uses": []},
 "Na2ZnO2":{"formula": "Na2ZnO2", "name": "cynkan sodu (zapis uproszczony)", "state": "s", "molarMass": 143.358, "role": "sól", "safety": [], "uses": []},
 "Na2Zn(OH)4":{"formula": "Na2Zn(OH)4", "name": "tetrahydroksocynkan sodu", "state": "aq", "molarMass": 179.388, "role": "sól kompleksowa", "safety": [], "uses": []},
 "K2CO3":{"formula": "K2CO3", "name": "węglan potasu (potaż)", "state": "aq", "molarMass": 138.204, "role": "sól", "safety": [], "uses": ["szkło", "mydła"]},
 "K2SiO3":{"formula": "K2SiO3", "name": "krzemian potasu", "state": "aq", "molarMass": 154.278, "role": "sól", "safety": [], "uses": []},
 "CaSiO3":{"formula": "CaSiO3", "name": "krzemian wapnia (żużel wielkopiecowy)", "state": "s", "molarMass": 116.16, "role": "sól", "safety": [], "uses": ["cement, materiały budowlane"]},
 "Hg":{"formula": "Hg", "name": "rtęć", "state": "l", "molarMass": 200.59, "role": "metal", "safety": ["toksyczna (pary)"], "uses": []},
 "Pb":{"formula": "Pb", "name": "ołów", "state": "s", "molarMass": 207.2, "role": "metal", "safety": ["toksyczny"], "uses": []},
 "Fe":{"formula": "Fe", "name": "żelazo", "state": "s", "molarMass": 55.845, "role": "metal", "safety": [], "uses": []},
 "Cu":{"formula": "Cu", "name": "miedź", "state": "s", "molarMass": 63.546, "role": "metal", "safety": [], "uses": []},
 "Al":{"formula": "Al", "name": "glin", "state": "s", "molarMass": 26.982, "role": "metal", "safety": [], "uses": []},
 "Zn":{"formula": "Zn", "name": "cynk", "state": "s", "molarMass": 65.38, "role": "metal", "safety": [], "uses": []},
 "Mg":{"formula": "Mg", "name": "magnez", "state": "s", "molarMass": 24.305, "role": "metal", "safety": ["pali się oślepiającym płomieniem"], "uses": []},
 "Ca":{"formula": "Ca", "name": "wapń", "state": "s", "molarMass": 40.078, "role": "metal", "safety": ["reaguje z wodą"], "uses": []},
 "Na":{"formula": "Na", "name": "sód", "state": "s", "molarMass": 22.99, "role": "metal", "safety": ["reaguje gwałtownie z wodą"], "uses": []},
 "C":{"formula": "C", "name": "węgiel", "state": "s", "molarMass": 12.011, "role": "niemetal", "safety": [], "uses": []},
 "P":{"formula": "P", "name": "fosfor (zapis szkolny)", "state": "s", "molarMass": 30.974, "role": "niemetal", "safety": ["biały — samozapalny, trujący"], "uses": []},
 "P4":{"formula": "P4", "name": "fosfor biały (cząsteczka P₄)", "state": "s", "molarMass": 123.896, "role": "niemetal", "safety": ["samozapalny, trujący"], "uses": []},
 "H2":{"formula": "H2", "name": "wodór", "state": "g", "molarMass": 2.016, "role": "pierwiastek", "safety": ["palny, mieszanina z O₂ wybuchowa"], "uses": []},
 "O2":{"formula": "O2", "name": "tlen", "state": "g", "molarMass": 31.998, "role": "pierwiastek", "safety": ["podtrzymuje palenie"], "uses": []},
 "CH4":{"formula": "CH4", "name": "metan", "state": "g", "molarMass": 16.043, "role": "węglowodór", "safety": ["palny"], "uses": ["gaz ziemny"]},
 "C3H8":{"formula": "C3H8", "name": "propan", "state": "g", "molarMass": 44.097, "role": "węglowodór", "safety": ["palny"], "uses": ["butle turystyczne, LPG"]},
 "C8H18":{"formula": "C8H18", "name": "oktan", "state": "l", "molarMass": 114.232, "role": "węglowodór", "safety": ["palny"], "uses": ["benzyna (składnik)"]},
 "KClO3":{"formula": "KClO3", "name": "chloran(V) potasu", "state": "s", "molarMass": 122.545, "role": "sól", "safety": ["silny utleniacz"], "uses": ["otrzymywanie tlenu (z MnO₂)"]},
 "KCl":{"formula": "KCl", "name": "chlorek potasu", "state": "s", "molarMass": 74.548, "role": "sól", "safety": [], "uses": ["nawóz"]},
 "NaOH":{"formula": "NaOH", "name": "wodorotlenek sodu", "state": "aq", "molarMass": 39.997, "role": "zasada", "safety": ["żrący"], "uses": []},
 "NaHCO3":{"formula": "NaHCO3", "name": "wodorowęglan sodu", "state": "s", "molarMass": 84.006, "role": "sól", "safety": [], "uses": []},
 "Na2CO3":{"formula": "Na2CO3", "name": "węglan sodu", "state": "aq", "molarMass": 105.988, "role": "sól", "safety": [], "uses": []}
};Object.keys(add).forEach(k=>{if(!S[k])S[k]=add[k]});})();
