/* v0.35: CHE.DATA.REACTIONS + REACTION_DATA — reakcje z lekcji N03 Kwasy (bilans sprawdza CHE.REACTION.check) */
(function(){
const R=(r,p)=>({reactants:r.map(x=>({formula:x[1],coef:x[0]})),products:p.map(x=>({formula:x[1],coef:x[0]}))});
const add={
 alHcl:[R([[2,'Al'],[6,'HCl']],[[2,'AlCl3'],[3,'H2']]),{type:'metal+acid',conditions:'roztwór wodny; początkowo wolno (warstwa Al₂O₃)',observation:'po chwili intensywne wydzielanie H₂; glin się roztwarza',safety:['H₂ palny']}],
 znH2so4:[R([[1,'Zn'],[1,'H2SO4']],[[1,'ZnSO4'],[1,'H2']]),{type:'metal+acid',conditions:'rozcieńczony H₂SO₄',observation:'pęcherzyki H₂ na powierzchni cynku',safety:['H₂ palny']}],
 mgH2so4:[R([[1,'Mg'],[1,'H2SO4']],[[1,'MgSO4'],[1,'H2']]),{type:'metal+acid',conditions:'rozcieńczony H₂SO₄',observation:'gwałtowne wydzielanie H₂, roztwór się ogrzewa',safety:['H₂ palny']}],
 caoHcl:[R([[1,'CaO'],[2,'HCl']],[[1,'CaCl2'],[1,'H2O']]),{type:'acid+basic-oxide',conditions:'roztwór wodny',observation:'biały proszek roztwarza się, roztwór się ogrzewa',safety:['CaO i HCl żrące']}],
 mgoHcl:[R([[1,'MgO'],[2,'HCl']],[[1,'MgCl2'],[1,'H2O']]),{type:'acid+basic-oxide',conditions:'roztwór wodny',observation:'biały proszek znika, roztwór bezbarwny',safety:['kwas żrący']}],
 fe2o3Hcl:[R([[1,'Fe2O3'],[6,'HCl']],[[2,'FeCl3'],[3,'H2O']]),{type:'acid+basic-oxide',conditions:'roztwór wodny, ogrzewanie przyspiesza',observation:'rdzawy tlenek znika, roztwór żółtobrunatny (Fe³⁺)',safety:['kwas żrący']}],
 na2oHno3:[R([[1,'Na2O'],[2,'HNO3']],[[2,'NaNO3'],[1,'H2O']]),{type:'acid+basic-oxide',conditions:'roztwór wodny',observation:'tlenek roztwarza się, roztwór bezbarwny',safety:['Na₂O i HNO₃ żrące']}],
 znoHcl:[R([[1,'ZnO'],[2,'HCl']],[[1,'ZnCl2'],[1,'H2O']]),{type:'acid+amphoteric-oxide',conditions:'roztwór wodny',observation:'biały tlenek roztwarza się (ZnO amfoteryczny — reaguje też z NaOH)',safety:['kwas żrący']}],
 h2so4Koh:[R([[1,'H2SO4'],[2,'KOH']],[[1,'K2SO4'],[2,'H2O']]),{type:'neutralization',conditions:'roztwór wodny',observation:'zobojętnianie, roztwór się ogrzewa',safety:['kwas i zasada żrące']}],
 caoh2Hno3:[R([[1,'Ca(OH)2'],[2,'HNO3']],[[1,'Ca(NO3)2'],[2,'H2O']]),{type:'neutralization',conditions:'roztwór wodny',observation:'mętne mleko wapienne staje się klarowne',safety:['kwas i zasada żrące']}],
 aloh3Hcl:[R([[1,'Al(OH)3'],[3,'HCl']],[[1,'AlCl3'],[3,'H2O']]),{type:'neutralization',conditions:'roztwór wodny',observation:'galaretowaty osad Al(OH)₃ roztwarza się',safety:['kwas żrący']}],
 h3po4Caoh2:[R([[2,'H3PO4'],[3,'Ca(OH)2']],[[1,'Ca3(PO4)2'],[6,'H2O']]),{type:'neutralization',conditions:'roztwór wodny',observation:'wytrąca się biały osad Ca₃(PO₄)₂',safety:['kwas i zasada żrące']}],
 mgoh2Hcl:[R([[1,'Mg(OH)2'],[2,'HCl']],[[1,'MgCl2'],[2,'H2O']]),{type:'neutralization',conditions:'sok żołądkowy — lek zobojętniający',observation:'zawiesina roztwarza się',safety:[]}],
 nahco3Hcl:[R([[1,'NaHCO3'],[1,'HCl']],[[1,'NaCl'],[1,'H2O'],[1,'CO2']]),{type:'carbonate+acid',conditions:'roztwór wodny',observation:'musowanie — wydziela się CO₂',safety:[]}],
 na2co3Hcl:[R([[1,'Na2CO3'],[2,'HCl']],[[2,'NaCl'],[1,'H2O'],[1,'CO2']]),{type:'carbonate+acid',conditions:'roztwór wodny',observation:'burzenie — wydziela się CO₂ (mętni wodę wapienną)',safety:['kwas żrący']}],
 bacl2H2so4:[R([[1,'BaCl2'],[1,'H2SO4']],[[1,'BaSO4'],[2,'HCl']]),{type:'precipitation',conditions:'roztwór wodny',observation:'biały, drobnokrystaliczny osad BaSO₄ (nie roztwarza się w kwasach)',safety:['rozpuszczalne sole baru trujące']}],
 na2sHcl:[R([[1,'Na2S'],[2,'HCl']],[[2,'NaCl'],[1,'H2S']]),{type:'salt+acid',conditions:'roztwór wodny; dygestorium',observation:'zapach zgniłych jaj — wydziela się H₂S',safety:['H₂S silnie trujący']}],
 na2so3Hcl:[R([[1,'Na2SO3'],[2,'HCl']],[[2,'NaCl'],[1,'H2O'],[1,'SO2']]),{type:'salt+acid',conditions:'roztwór wodny; dygestorium',observation:'ostry zapach SO₂ (H₂SO₃ rozkłada się)',safety:['SO₂ toksyczny']}],
 na2sio3Hcl:[R([[1,'Na2SiO3'],[2,'HCl']],[[1,'H2SiO3'],[2,'NaCl']]),{type:'salt+acid',conditions:'roztwór wodny',observation:'galaretowaty, biały osad kwasu krzemowego',safety:['kwas żrący']}],
 hclNh3:[R([[1,'HCl'],[1,'NH3']],[[1,'NH4Cl']]),{type:'acid+base (Brønsted)',conditions:'gazy nad stężonymi roztworami',observation:'biały „dym” NH₄Cl',safety:['HCl i NH₃ drażniące']}],
 cuHno3Dil:[R([[3,'Cu'],[8,'HNO3']],[[3,'Cu(NO3)2'],[2,'NO'],[4,'H2O']]),{type:'redox',conditions:'rozcieńczony HNO₃; wyciąg',observation:'roztwór niebieski; bezbarwny NO brunatnieje u wylotu (2 NO + O₂ → 2 NO₂)',safety:['NO i NO₂ toksyczne — pokaz nauczyciela']}],
 cuH2so4Conc:[R([[1,'Cu'],[2,'H2SO4']],[[1,'CuSO4'],[1,'SO2'],[2,'H2O']]),{type:'redox',conditions:'stężony, gorący H₂SO₄; dygestorium',observation:'wydziela się SO₂; po rozcieńczeniu roztwór niebieski',safety:['stężony H₂SO₄ i SO₂ — pokaz nauczyciela']}],
 auAquaRegia:[R([[1,'Au'],[1,'HNO3'],[4,'HCl']],[[1,'HAuCl4'],[1,'NO'],[2,'H2O']]),{type:'redox (kompleksowanie)',conditions:'woda królewska: stęż. HNO₃ + stęż. HCl (1:3)',observation:'złoto roztwarza się, roztwór żółty',safety:['bardzo żrące, toksyczne gazy']}],
 so2H2o:[R([[1,'SO2'],[1,'H2O']],[[1,'H2SO3']]),{type:'synteza kwasu',conditions:'roztwór wodny (równowaga)',observation:'roztwór kwaśny; wskaźnik czerwienieje',safety:['SO₂ toksyczny']}],
 co2H2o:[R([[1,'CO2'],[1,'H2O']],[[1,'H2CO3']]),{type:'synteza kwasu',conditions:'roztwór wodny (równowaga, mało H₂CO₃)',observation:'woda gazowana ma pH ≈ 4–5',safety:[]}],
 p4o10H2o:[R([[1,'P4O10'],[6,'H2O']],[[4,'H3PO4']]),{type:'synteza kwasu',conditions:'gwałtowna reakcja z wodą',observation:'biały proszek rozpuszcza się z sykiem',safety:['P₄O₁₀ silnie higroskopijny, żrący']}],
 n2o5H2o:[R([[1,'N2O5'],[1,'H2O']],[[2,'HNO3']]),{type:'synteza kwasu',conditions:'roztwór wodny',observation:'powstaje HNO₃',safety:['żrący']}],
 n2o3H2o:[R([[1,'N2O3'],[1,'H2O']],[[2,'HNO2']]),{type:'synteza kwasu',conditions:'zimna woda',observation:'niebieski roztwór HNO₂ (nietrwały)',safety:['toksyczny']}],
 h2Br2:[R([[1,'H2'],[1,'Br2']],[[2,'HBr']]),{type:'synteza',conditions:'ogrzewanie (lub kat. Pt)',observation:'brunatna barwa Br₂ zanika',safety:['Br₂ żrący, toksyczny']}],
 h2I2:[R([[1,'H2'],[1,'I2']],[[2,'HI']]),{type:'synteza (równowagowa)',conditions:'ogrzewanie; reakcja odwracalna',observation:'fioletowe pary I₂ częściowo zanikają',safety:['I₂ drażniący']}],
 h2S:[R([[1,'H2'],[1,'S']],[[1,'H2S']]),{type:'synteza',conditions:'ogrzewanie (wodór nad stopioną siarką)',observation:'zapach zgniłych jaj',safety:['H₂S silnie trujący']}],
 sO2:[R([[1,'S'],[1,'O2']],[[1,'SO2']]),{type:'spalanie',conditions:'zapalenie siarki',observation:'niebieski płomień, ostry zapach SO₂',safety:['SO₂ toksyczny']}],
 so2O2:[R([[2,'SO2'],[1,'O2']],[[2,'SO3']]),{type:'utlenianie',conditions:'kat. V₂O₅ (przemysł) / atmosfera',observation:'—',safety:['SO₃ żrący']}],
 n2O2:[R([[1,'N2'],[1,'O2']],[[2,'NO']]),{type:'synteza',conditions:'bardzo wysoka temperatura (silniki, wyładowania)',observation:'—',safety:[]}],
 noO2:[R([[2,'NO'],[1,'O2']],[[2,'NO2']]),{type:'utlenianie',conditions:'powietrze, temperatura pokojowa',observation:'bezbarwny gaz brunatnieje',safety:['NO₂ toksyczny']}],
 no2H2o:[R([[3,'NO2'],[1,'H2O']],[[2,'HNO3'],[1,'NO']]),{type:'dysproporcjonowanie',conditions:'woda (kwaśne deszcze)',observation:'brunatny gaz zanika, roztwór kwaśny',safety:['NO₂ toksyczny']}],
 no2O2H2o:[R([[4,'NO2'],[1,'O2'],[2,'H2O']],[[4,'HNO3']]),{type:'synteza kwasu',conditions:'woda + tlen (przemysł, atmosfera)',observation:'—',safety:['NO₂ toksyczny']}],
 caco3H2so4:[R([[1,'CaCO3'],[1,'H2SO4']],[[1,'CaSO4'],[1,'H2O'],[1,'CO2']]),{type:'carbonate+acid',conditions:'kwaśne deszcze — niszczenie marmuru i wapienia',observation:'musowanie, powierzchnia się kruszy (CaSO₄ słabo rozpuszczalny)',safety:[]}],
 hno3Decomp:[R([[4,'HNO3']],[[4,'NO2'],[1,'O2'],[2,'H2O']]),{type:'rozkład',conditions:'światło lub ogrzewanie',observation:'kwas żółknie (rozpuszczony NO₂)',safety:['przechowywać w ciemnych butelkach']}],
 sugarH2so4:[R([[1,'C12H22O11']],[[12,'C'],[11,'H2O']]),{type:'odwodnienie',conditions:'stężony H₂SO₄ (czynnik odwadniający); dygestorium',observation:'cukier czernieje, porowata masa węgla rośnie, wydziela się para i SO₂',safety:['tylko pokaz nauczyciela']}],
 sio2Hf:[R([[1,'SiO2'],[4,'HF']],[[1,'SiF4'],[2,'H2O']]),{type:'acid+oxide',conditions:'HF(aq); naczynia z tworzywa',observation:'szkło matowieje (trawienie)',safety:['HF silnie toksyczny']}],
 naH2o:[R([[2,'Na'],[2,'H2O']],[[2,'NaOH'],[1,'H2']]),{type:'metal+water',conditions:'mały kawałek Na w krystalizatorze z wodą; tylko pokaz nauczyciela',observation:'Na topi się w kulkę i biega po powierzchni; wydziela się H₂; z fenoloftaleiną roztwór malinowy',safety:['reakcja gwałtowna — osłona, okulary, mały kawałek']}],
 caoh2Co2:[R([[1,'Ca(OH)2'],[1,'CO2']],[[1,'CaCO3'],[1,'H2O']]),{type:'precipitation (wykrywanie CO₂)',conditions:'CO₂ wprowadzany do wody wapiennej',observation:'klarowna woda wapienna mętnieje — biały osad CaCO₃',safety:['nie wciągać wody wapiennej do ust']}],
 na2Cl2:[R([[2,'Na'],[1,'Cl2']],[[2,'NaCl']]),{type:'synteza',conditions:'ogrzany sód w chlorze (pokaz)',observation:'jasny żółty płomień, biały dym NaCl',safety:['Cl₂ trujący, Na żrący — tylko pokaz']}],
 feS:[R([[1,'Fe'],[1,'S']],[[1,'FeS']]),{type:'synteza',conditions:'ogrzewanie mieszaniny opiłków Fe i siarki',observation:'mieszanina żarzy się; powstaje czarna, niemagnetyczna masa FeS',safety:['możliwy SO₂ — wentylacja']}],
 caoCo2:[R([[1,'CaO'],[1,'CO2']],[[1,'CaCO3']]),{type:'synteza',conditions:'tlenek zasadowy + tlenek kwasowy (twardnienie wapna)',observation:'—',safety:[]}],
 naohCo2:[R([[2,'NaOH'],[1,'CO2']],[[1,'Na2CO3'],[1,'H2O']]),{type:'zasada + tlenek kwasowy',conditions:'roztwór wodny',observation:'brak widocznych zmian (pochłanianie CO₂)',safety:['NaOH żrący']}],
 cuso4Naoh:[R([[1,'CuSO4'],[2,'NaOH']],[[1,'Cu(OH)2'],[1,'Na2SO4']]),{type:'precipitation',conditions:'roztwór wodny',observation:'niebieski, galaretowaty osad Cu(OH)₂',safety:['NaOH żrący']}],
 fecl3Naoh:[R([[1,'FeCl3'],[3,'NaOH']],[[1,'Fe(OH)3'],[3,'NaCl']]),{type:'precipitation',conditions:'roztwór wodny',observation:'rdzawobrunatny, kłaczkowaty osad Fe(OH)₃',safety:['NaOH żrący']}],
 agno3Nacl:[R([[1,'AgNO3'],[1,'NaCl']],[[1,'AgCl'],[1,'NaNO3']]),{type:'precipitation',conditions:'roztwór wodny',observation:'biały, serowaty osad AgCl (ciemnieje na świetle)',safety:['AgNO₃ żrący, plami skórę']}],
 bacl2Na2so4:[R([[1,'BaCl2'],[1,'Na2SO4']],[[1,'BaSO4'],[2,'NaCl']]),{type:'precipitation',conditions:'roztwór wodny',observation:'biały, drobnokrystaliczny osad BaSO₄',safety:['rozpuszczalne sole baru trujące']}],
 cacl2Na2co3:[R([[1,'CaCl2'],[1,'Na2CO3']],[[1,'CaCO3'],[2,'NaCl']]),{type:'precipitation',conditions:'roztwór wodny',observation:'biały osad CaCO₃ (musuje po dodaniu kwasu)',safety:[]}],
 pbno32Ki:[R([[1,'Pb(NO3)2'],[2,'KI']],[[1,'PbI2'],[2,'KNO3']]),{type:'precipitation',conditions:'roztwór wodny',observation:'jaskrawożółty osad PbI₂ („złoty deszcz” po przekrystalizowaniu)',safety:['związki ołowiu toksyczne']}],
 znCuso4:[R([[1,'Zn'],[1,'CuSO4']],[[1,'ZnSO4'],[1,'Cu']]),{type:'displacement',conditions:'roztwór wodny',observation:'niebieski roztwór odbarwia się, na cynku osadza się czerwonobrunatna miedź',safety:[]}],
 feCuso4:[R([[1,'Fe'],[1,'CuSO4']],[[1,'FeSO4'],[1,'Cu']]),{type:'displacement',conditions:'roztwór wodny (gwóźdź w CuSO₄)',observation:'gwóźdź pokrywa się miedzią, roztwór blednie i zielenieje',safety:[]}],
 cuAgno3:[R([[1,'Cu'],[2,'AgNO3']],[[1,'Cu(NO3)2'],[2,'Ag']]),{type:'displacement',conditions:'roztwór wodny (drut Cu w AgNO₃)',observation:'na drucie wyrastają srebrzyste kryształy Ag, roztwór niebieszczeje',safety:['AgNO₃ plami skórę']}],
 caco3Decomp:[R([[1,'CaCO3']],[[1,'CaO'],[1,'CO2']]),{type:'rozkład termiczny',conditions:'prażenie ok. 900 °C (wapno palone)',observation:'wapień traci masę; gaz mętni wodę wapienną',safety:['wysoka temperatura']}],
 caoH2o:[R([[1,'CaO'],[1,'H2O']],[[1,'Ca(OH)2']]),{type:'synteza',conditions:'gaszenie wapna',observation:'silne ogrzanie, syczenie; powstaje wapno gaszone',safety:['CaO i Ca(OH)₂ żrące — okulary']}],
 caoh2Co2Mortar:[R([[1,'Ca(OH)2'],[1,'CO2']],[[1,'CaCO3'],[1,'H2O']]),{type:'twardnienie zaprawy',conditions:'zaprawa wapienna na powietrzu (tygodnie)',observation:'zaprawa twardnieje',safety:[]}],
 caco3Co2H2o:[R([[1,'CaCO3'],[1,'CO2'],[1,'H2O']],[[1,'Ca(HCO3)2']]),{type:'synteza (kras)',conditions:'woda z CO₂ przesiąka przez wapień',observation:'wapień się rozpuszcza — jaskinie krasowe',safety:[]}],
 cahco32Decomp:[R([[1,'Ca(HCO3)2']],[[1,'CaCO3'],[1,'H2O'],[1,'CO2']]),{type:'rozkład termiczny',conditions:'gotowanie wody twardej',observation:'kamień kotłowy (biały osad CaCO₃); w jaskiniach — stalaktyty',safety:[]}],
 cuso4Hydrate:[R([[1,'CuSO4'],[5,'H2O']],[[1,'CuSO4·5H2O']]),{type:'hydratacja',conditions:'bezwodny CuSO₄ + woda',observation:'biały proszek niebieszczeje (wykrywanie wody)',safety:[]}],
 elHcl:[R([[2,'HCl']],[[1,'H2'],[1,'Cl2']]),{type:'elektroliza',conditions:'prąd stały, elektrody grafitowe; HCl(aq)',observation:'katoda (−): pęcherzyki H₂; anoda (+): Cl₂ (zapach chloru, częściowo rozpuszcza się)',safety:['Cl₂ toksyczny — krótko, wentylacja']}],
 elH2o:[R([[2,'H2O']],[[2,'H2'],[1,'O2']]),{type:'elektroliza',conditions:'prąd stały; roztwór H₂SO₄, NaOH lub innego elektrolitu (sam elektrolit się nie zużywa)',observation:'katoda (−): H₂, anoda (+): O₂ — objętości 2 : 1',safety:['mieszanina H₂ + O₂ wybuchowa']}],
 elNacl:[R([[2,'NaCl'],[2,'H2O']],[[2,'NaOH'],[1,'H2'],[1,'Cl2']]),{type:'elektroliza',conditions:'prąd stały; stężony roztwór NaCl',observation:'katoda (−): H₂ (roztwór zasadowy — fenoloftaleina malinowa), anoda (+): Cl₂',safety:['Cl₂ toksyczny']}],
 ch3coohNaoh:[R([[1,'CH3COOH'],[1,'NaOH']],[[1,'CH3COONa'],[1,'H2O']]),{type:'neutralization',conditions:'roztwór wodny',observation:'zobojętnianie; w PR pH > 7 (hydroliza octanu)',safety:['NaOH żrący']}]
};
Object.keys(add).forEach(k=>{if(D.REACTIONS[k])return;D.REACTIONS[k]=add[k][0];D.REACTION_DATA[k]=Object.assign({products:add[k][0].products.map(x=>x.formula)},add[k][1])});

/* alias bez danych (naclH2SO4 → naclH2so4) — zamyka indeks danych reakcji (test SIMPLE-006) */
Object.keys(D.REACTIONS).forEach(k=>{const a=D.REACTIONS[k].aliasOf;if(a&&!D.REACTION_DATA[k]&&D.REACTION_DATA[a])D.REACTION_DATA[k]=Object.assign({aliasOf:a},D.REACTION_DATA[a])});
/* nazwy typów reakcji po polsku — jedno miejsce dla lekcji, Atlasu, GFX */
D.REACTION_TYPE_NAMES={'metal+acid':'metal + kwas (redoks)','metal+water':'metal + woda (redoks)','neutralization':'zobojętnianie','precipitation':'strącanie osadu','precipitation (wykrywanie CO₂)':'strącanie (wykrywanie CO₂)','carbonate+acid':'węglan + kwas','acid+basic-oxide':'tlenek zasadowy + kwas','acid+amphoteric-oxide':'tlenek amfoteryczny + kwas','acid+oxide':'tlenek + kwas','salt+acid':'sól + kwas','redox':'redoks','redox (kompleksowanie)':'redoks z kompleksowaniem','acid+base (Brønsted)':'kwas + zasada (Brønsted)','synteza':'synteza','synteza kwasu':'synteza kwasu','synteza (równowagowa)':'synteza (równowagowa)','spalanie':'spalanie','utlenianie':'utlenianie','dysproporcjonowanie':'dysproporcjonowanie','rozkład':'rozkład','odwodnienie':'odwodnienie','otrzymywanie kwasu':'otrzymywanie kwasu','displacement':'wypieranie metalu (redoks)','rozkład termiczny':'rozkład termiczny','zasada + tlenek kwasowy':'zasada + tlenek kwasowy','twardnienie zaprawy':'twardnienie zaprawy wapiennej','synteza (kras)':'synteza (zjawiska krasowe)','hydratacja':'hydratacja (powstawanie hydratu)'};
})();
