/* v0.35: korekta i uzupełnienie CHE.DATA.SUBSTANCES (spójność z lekcją N03 Kwasy i z Atlasem) */
(function(){
const fix={
 CO2:{name:'tlenek węgla(IV)',alias:['dwutlenek węgla'],uses:['napoje gazowane','gaśnice','fotosynteza']},
 NO2:{name:'tlenek azotu(IV)',alias:['dwutlenek azotu'],uses:['produkcja HNO₃'],props:{appearance:'brunatny gaz',smell:'duszący',special:['cięższy od powietrza','składnik kwaśnych deszczy i smogu']}},
 SO2:{name:'tlenek siarki(IV)',alias:['dwutlenek siarki'],uses:['konserwant (E220)','produkcja H₂SO₄'],props:{appearance:'bezbarwny gaz',smell:'ostry, duszący (palona siarka)',special:['odbarwia KMnO₄','składnik kwaśnych deszczy']}},
 CaCO3:{uses:['kreda, marmur, wapień','budownictwo','produkcja wapna palonego CaO'],alias:['węglan wapnia (nie „wapno” — wapno palone to CaO)']},
 AgCl:{name:'chlorek srebra(I)',alias:['chlorek srebra'],props:{appearance:'biały, serowaty osad; ciemnieje na świetle'}},
 HCl:{aqName:'kwas solny (chlorowodorowy)',gasName:'chlorowodór',uses:['sok żołądkowy','odkamienianie, środki do WC','produkcja PVC','trawienie metali'],
  props:{appearance:'bezbarwna ciecz (techniczny — żółtawy od Fe³⁺)',smell:'ostry, duszący',conc:'36–38%',density:1.18,cm:11.7,special:['„dymi” na powietrzu (mgiełka kropelek kwasu)','lotny']},volatile:true,strength:'mocny'},
 H2SO4:{uses:['elektrolit w akumulatorach (ok. 37%)','nawozy fosforowe','osuszacz','produkcja barwników i detergentów'],
  props:{appearance:'bezbarwna, oleista, bezwonna ciecz',conc:'96–98%',density:1.84,cm:18.0,bp:337,special:['higroskopijny (osuszacz)','odwadnia i zwęgla cukier, papier, drewno','rozcieńczanie silnie egzotermiczne — kwas do wody','gorący stężony — utleniacz; na zimno pasywuje Fe, Al']},dehydrating:true,strength:'mocny (I stopień)'},
 HNO3:{uses:['nawozy (saletry)','materiały wybuchowe','wytrawianie metali','barwniki'],
  props:{appearance:'bezbarwna ciecz (na świetle żółknie)',smell:'ostry',conc:'65–68%',density:1.40,special:['rozkład na świetle: 4 HNO₃ → 4 NO₂ + O₂ + 2 H₂O','z białkiem żółte zabarwienie (reakcja ksantoproteinowa)','silny utleniacz — z metalami nie daje H₂','na zimno pasywuje Fe, Al, Cr']},oxidizing:true,strength:'mocny'},
 HF:{safety:['silnie toksyczny','żrący — penetruje skórę, wiąże Ca²⁺'],uses:['trawienie szkła (SiO₂ + 4 HF → SiF₄ + 2 H₂O)','produkcja fluorków'],props:{special:['słaby kwas mimo dużej elektroujemności F (mocne wiązanie H–F)','przechowywany w naczyniach z tworzywa, nie ze szkła']},strength:'słaby'},
 CH3COOH:{aqName:'kwas octowy (etanowy)',uses:['ocet 5–10% (E260)','konserwowanie','synteza octanów'],props:{appearance:'bezbarwna ciecz; 100% — „lodowaty” (krzepnie w 16,6 °C)',smell:'octu, ostry',special:['jednoprotonowy — kwasowy tylko H z –COOH']},strength:'słaby'},
 H3PO4:{uses:['nawozy fosforowe','zakwaszacz E338 (napoje typu cola)','odrdzewiacze'],props:{appearance:'bezbarwna, syropowata ciecz (czysty — kryształy, t.t. ok. 42 °C)',conc:'ok. 85%',density:1.69,special:['nie utlenia, mało lotny','kwas średniej mocy (pKa₁ ≈ 2,16)']},strength:'słaby (średniej mocy)'},
 H2CO3:{uses:['napoje gazowane','bufor krwi (H₂CO₃/HCO₃⁻)'],props:{appearance:'istnieje tylko w roztworze',special:['nietrwały: H₂CO₃ ⇌ H₂O + CO₂']},strength:'słaby'},
 HCOOH:{aqName:'kwas mrówkowy (metanowy)',uses:['jad mrówek i pokrzyw','konserwant (E236)','garbarstwo'],strength:'słaby'},
 H2S:{aqName:'kwas siarkowodorowy',gasName:'siarkowodór',uses:['wody siarczkowe','analiza jakościowa (strącanie siarczków)'],props:{appearance:'bezbarwny gaz',smell:'zgniłych jaj',special:['silnie trujący','czernieje papierek z octanem ołowiu(II)']},strength:'słaby'},
 HCN:{aqName:'kwas cyjanowodorowy',gasName:'cyjanowodór',strength:'słaby'}
};
Object.keys(fix).forEach(k=>{if(S[k])Object.assign(S[k],fix[k])});
Object.assign(S,{
 HBr:{formula:'HBr',name:'kwas bromowodorowy',state:'aq',molarMass:80.912,role:'kwas',safety:['żrący'],uses:['synteza bromków'],strength:'mocny'},
 HI:{formula:'HI',name:'kwas jodowodorowy',state:'aq',molarMass:127.912,role:'kwas',safety:['żrący'],uses:['synteza jodków','reduktor'],strength:'mocny'},
 HClO4:{formula:'HClO4',name:'kwas chlorowy(VII)',state:'aq',molarMass:100.46,role:'kwas',safety:['żrący','silny utleniacz (stężony)'],uses:['analityka','paliwa rakietowe (chlorany(VII))'],strength:'mocny'},
 H2SO3:{formula:'H2SO3',name:'kwas siarkowy(IV)',state:'aq',molarMass:82.07,role:'kwas',safety:['drażniący'],uses:['konserwowanie (SO₂)','bielenie'],props:{special:['nietrwały: H₂SO₃ ⇌ H₂O + SO₂']},strength:'słaby (średniej mocy)'},
 HNO2:{formula:'HNO2',name:'kwas azotowy(III)',state:'aq',molarMass:47.013,role:'kwas',safety:['toksyczny'],uses:['synteza barwników azowych'],props:{special:['nietrwały — istnieje tylko w rozcieńczonym roztworze']},strength:'słaby'},
 H3PO3:{formula:'H3PO3',name:'kwas fosforowy(III)',state:'s',molarMass:81.996,role:'kwas',safety:['żrący'],uses:['środki ochrony roślin (fosforyny)'],props:{special:['w praktyce dwuprotonowy: HP(O)(OH)₂ — jeden H związany z P']},protonsReal:2,strength:'słaby'},
 H2SiO3:{formula:'H2SiO3',name:'kwas krzemowy',state:'s',molarMass:78.10,role:'kwas',safety:[],uses:['silikażel (osuszacz)'],props:{appearance:'galaretowaty, nierozpuszczalny osad',special:['otrzymywany z soli: Na₂SiO₃ + 2 HCl → H₂SiO₃↓ + 2 NaCl','SiO₂ nie reaguje z wodą']},strength:'bardzo słaby'},
 C3H6O3:{formula:'C3H6O3',name:'kwas mlekowy',state:'aq',molarMass:90.08,role:'kwas',safety:[],uses:['fermentacja mlekowa (jogurt, kiszonki)','mięśnie (glikoliza beztlenowa)','E270'],strength:'słaby'},
 C6H8O7:{formula:'C6H8O7',name:'kwas cytrynowy',state:'s',molarMass:192.12,role:'kwas',safety:['drażniący'],uses:['odkamienianie','E330','cykl Krebsa'],strength:'słaby'},
 NH4Cl:{formula:'NH4Cl',name:'chlorek amonu',state:'s',molarMass:53.49,role:'sól',safety:[],uses:['biały dym HCl + NH₃','lutowanie'],props:{appearance:'biały kryształ / „dym”'}},
 CaO:{formula:'CaO',name:'tlenek wapnia (wapno palone)',state:'s',molarMass:56.077,role:'tlenek zasadowy',safety:['żrący'],uses:['budownictwo','wapnowanie gleb']},
 FeCl3:{formula:'FeCl3',name:'chlorek żelaza(III)',state:'aq',molarMass:162.20,role:'sól',safety:['żrący'],uses:['trawienie płytek drukowanych','koagulant'],props:{appearance:'żółtobrunatny roztwór'}},
 BaSO4:{formula:'BaSO4',name:'siarczan(VI) baru',state:'s',molarMass:233.39,role:'osad',safety:[],uses:['kontrast RTG (nierozpuszczalny, nietoksyczny)'],props:{appearance:'biały, drobnokrystaliczny osad'}},
 NaHCO3:{formula:'NaHCO3',name:'wodorowęglan sodu (soda oczyszczona)',state:'s',molarMass:84.007,role:'sól kwaśna',safety:[],uses:['proszek do pieczenia','lek zobojętniający','neutralizacja rozlanych kwasów']}
});
/* v0.35b: substancje używane w reakcjach CHE.REACTION (audyt missingData) */
Object.assign(S,{
  'Na':{formula:'Na',name:'sód',state:'s',molarMass:22.99,role:'metal',safety:['reaguje gwałtownie z wodą'],uses:[]},
  'Cu':{formula:'Cu',name:'miedź',state:'s',molarMass:63.546,role:'metal',safety:[],uses:[]},
  'Cl2':{formula:'Cl2',name:'chlor',state:'g',molarMass:70.9,role:'pierwiastek',safety:[],uses:[]},
  'Al':{formula:'Al',name:'glin',state:'s',molarMass:26.982,role:'metal',safety:[],uses:[]},
  'AlCl3':{formula:'AlCl3',name:'chlorek glinu',state:'aq',molarMass:133.332,role:'sól',safety:[],uses:[]},
  'ZnSO4':{formula:'ZnSO4',name:'siarczan(VI) cynku',state:'aq',molarMass:161.436,role:'sól',safety:[],uses:[]},
  'MgSO4':{formula:'MgSO4',name:'siarczan(VI) magnezu',state:'aq',molarMass:120.361,role:'sól',safety:[],uses:[]},
  'MgO':{formula:'MgO',name:'tlenek magnezu',state:'s',molarMass:40.304,role:'tlenek zasadowy',safety:[],uses:[]},
  'Fe2O3':{formula:'Fe2O3',name:'tlenek żelaza(III)',state:'s',molarMass:159.687,role:'tlenek zasadowy (słabo amfoteryczny)',safety:[],uses:[]},
  'Na2O':{formula:'Na2O',name:'tlenek sodu',state:'s',molarMass:61.979,role:'tlenek zasadowy',safety:[],uses:[]},
  'NaNO3':{formula:'NaNO3',name:'azotan(V) sodu (saletra chilijska)',state:'aq',molarMass:84.994,role:'sól',safety:[],uses:[]},
  'ZnO':{formula:'ZnO',name:'tlenek cynku',state:'s',molarMass:81.379,role:'tlenek amfoteryczny',safety:[],uses:[]},
  'KOH':{formula:'KOH',name:'wodorotlenek potasu',state:'aq',molarMass:56.105,role:'zasada',safety:[],uses:[]},
  'K2SO4':{formula:'K2SO4',name:'siarczan(VI) potasu',state:'aq',molarMass:174.252,role:'sól',safety:[],uses:[]},
  'Ca(OH)2':{formula:'Ca(OH)2',name:'wodorotlenek wapnia',state:'aq',molarMass:74.092,role:'zasada',safety:[],uses:[]},
  'Ca(NO3)2':{formula:'Ca(NO3)2',name:'azotan(V) wapnia',state:'aq',molarMass:164.086,role:'sól',safety:[],uses:[]},
  'Al(OH)3':{formula:'Al(OH)3',name:'wodorotlenek glinu',state:'s',molarMass:78.003,role:'wodorotlenek amfoteryczny',safety:[],uses:[]},
  'Ca3(PO4)2':{formula:'Ca3(PO4)2',name:'fosforan(V) wapnia',state:'s',molarMass:310.174,role:'osad',safety:[],uses:[]},
  'Mg(OH)2':{formula:'Mg(OH)2',name:'wodorotlenek magnezu',state:'s',molarMass:58.319,role:'zasada (słabo rozpuszczalna)',safety:[],uses:[]},
  'Na2CO3':{formula:'Na2CO3',name:'węglan sodu (soda)',state:'aq',molarMass:105.988,role:'sól',safety:[],uses:[]},
  'BaCl2':{formula:'BaCl2',name:'chlorek baru',state:'aq',molarMass:208.227,role:'sól',safety:[],uses:[]},
  'Na2S':{formula:'Na2S',name:'siarczek sodu',state:'aq',molarMass:78.04,role:'sól',safety:[],uses:[]},
  'Na2SO3':{formula:'Na2SO3',name:'siarczan(IV) sodu',state:'aq',molarMass:126.037,role:'sól',safety:[],uses:[]},
  'Na2SiO3':{formula:'Na2SiO3',name:'krzemian sodu (szkło wodne — roztwór)',state:'aq',molarMass:122.062,role:'sól',safety:[],uses:[]},
  'NO':{formula:'NO',name:'tlenek azotu(II)',state:'g',molarMass:30.006,role:'tlenek obojętny',safety:[],uses:[]},
  'Au':{formula:'Au',name:'złoto',state:'s',molarMass:196.967,role:'metal',safety:[],uses:[]},
  'HAuCl4':{formula:'HAuCl4',name:'kwas tetrachlorozłotowy(III)',state:'aq',molarMass:339.775,role:'kwas (kompleks)',safety:[],uses:[]},
  'P4O10':{formula:'P4O10',name:'tlenek fosforu(V)',state:'s',molarMass:283.886,role:'tlenek kwasowy',safety:[],uses:[]},
  'N2O5':{formula:'N2O5',name:'tlenek azotu(V)',state:'s',molarMass:108.009,role:'tlenek kwasowy',safety:[],uses:[]},
  'N2O3':{formula:'N2O3',name:'tlenek azotu(III)',state:'g',molarMass:76.011,role:'tlenek kwasowy',safety:[],uses:[]},
  'Br2':{formula:'Br2',name:'brom',state:'l',molarMass:159.808,role:'pierwiastek',safety:[],uses:[]},
  'I2':{formula:'I2',name:'jod',state:'s',molarMass:253.808,role:'pierwiastek',safety:[],uses:[]},
  'S':{formula:'S',name:'siarka',state:'s',molarMass:32.06,role:'pierwiastek',safety:[],uses:[]},
  'O2':{formula:'O2',name:'tlen',state:'g',molarMass:31.998,role:'pierwiastek',safety:[],uses:[]},
  'N2':{formula:'N2',name:'azot',state:'g',molarMass:28.014,role:'pierwiastek',safety:[],uses:[]},
  'CaSO4':{formula:'CaSO4',name:'siarczan(VI) wapnia (gips — dihydrat)',state:'s',molarMass:136.134,role:'sól',safety:[],uses:[]},
  'C12H22O11':{formula:'C12H22O11',name:'sacharoza',state:'s',molarMass:342.297,role:'cukier',safety:[],uses:[]},
  'C':{formula:'C',name:'węgiel',state:'s',molarMass:12.011,role:'pierwiastek',safety:[],uses:[]},
  'SiO2':{formula:'SiO2',name:'tlenek krzemu(IV) (krzemionka)',state:'s',molarMass:60.083,role:'tlenek kwasowy',safety:[],uses:[]},
  'SiF4':{formula:'SiF4',name:'fluorek krzemu(IV)',state:'g',molarMass:104.077,role:'fluorek',safety:[],uses:[]},
  'CH3COONa':{formula:'CH3COONa',name:'octan sodu',state:'aq',molarMass:82.034,role:'sól',safety:[],uses:[]},
  'FeS':{formula:'FeS',name:'siarczek żelaza(II)',state:'s',molarMass:87.91,role:'sól',safety:[],uses:[]},
  'Cu(OH)2':{formula:'Cu(OH)2',name:'wodorotlenek miedzi(II)',state:'s',molarMass:97.56,role:'osad',safety:[],uses:[],props:{appearance:'niebieski, galaretowaty osad'}},
  'Fe(OH)3':{formula:'Fe(OH)3',name:'wodorotlenek żelaza(III)',state:'s',molarMass:106.87,role:'osad',safety:[],uses:[],props:{appearance:'rdzawobrunatny osad'}},
  'NaNO3':{formula:'NaNO3',name:'azotan(V) sodu (saletra chilijska)',state:'aq',molarMass:84.99,role:'sól',safety:['utleniacz'],uses:['nawóz','konserwant E251']},
  'KNO3':{formula:'KNO3',name:'azotan(V) potasu (saletra indyjska)',state:'aq',molarMass:101.10,role:'sól',safety:['utleniacz'],uses:['nawóz','proch czarny']},
  'KI':{formula:'KI',name:'jodek potasu',state:'aq',molarMass:166.00,role:'sól',safety:[],uses:['sól jodowana','tabletki jodowe']},
  'Pb(NO3)2':{formula:'Pb(NO3)2',name:'azotan(V) ołowiu(II)',state:'aq',molarMass:331.2,role:'sól',safety:['toksyczny'],uses:[]},
  'PbI2':{formula:'PbI2',name:'jodek ołowiu(II)',state:'s',molarMass:461.0,role:'osad',safety:['toksyczny'],uses:[],props:{appearance:'jaskrawożółty osad'}},
  'FeSO4':{formula:'FeSO4',name:'siarczan(VI) żelaza(II)',state:'aq',molarMass:151.91,role:'sól',safety:[],uses:['nawozy, suplementy żelaza']},
  'Ag':{formula:'Ag',name:'srebro',state:'s',molarMass:107.87,role:'metal',safety:[],uses:[]},
  'Ca(HCO3)2':{formula:'Ca(HCO3)2',name:'wodorowęglan wapnia',state:'aq',molarMass:162.11,role:'sól wodorowa',safety:[],uses:[],props:{special:['twardość przemijająca wody','istnieje tylko w roztworze']}},
  'CuSO4·5H2O':{formula:'CuSO4·5H2O',name:'siarczan(VI) miedzi(II)—woda (1/5) (sól uwodniona, „siny kamień”)',state:'s',molarMass:249.69,role:'hydrat',safety:['szkodliwy'],uses:['fungicyd','wykrywanie wody (forma bezwodna)']}
});
})();
