/* ===== CHE.LAB.GFX v1.0 — wspólny zestaw wizualizacji: naczynia + efekty + palnik + chłodnica + scena =====
   Każdy element działa osobno (GFX.mount / GFX.draw) lub razem (GFX.mount z parts).
   Rozszerzanie: GFX.effects.register(id,{layer:'back|in|front',vessels?,draw(e)}) · GFX.vessels.register(id,{path|custom,hmax,pad}) */
const GFX=(function(){
const E={},V={};
const rnd=i=>{const x=Math.sin(i*127.1)*43758.5453;return x-Math.floor(x)};
const rgba=(c,a)=>'rgba('+(c[0]|0)+','+(c[1]|0)+','+(c[2]|0)+','+(a==null?1:a)+')';
const th=()=>{const d=document.documentElement.getAttribute('data-theme')==='dark';return{dark:d,glass:d?'#94a3b8':'#64748b',text:d?'#e2e8f0':'#1e293b',mut:d?'#94a3b8':'#64748b',hi:'rgba(255,255,255,.5)'}};
const tc=T=>{const k=Math.max(0,Math.min(1,(T-10)/80));return[60+k*195,150-k*40,235-k*195]};
function effect(id,def){E[id]=Object.assign({id,layer:'in',portable:true,independent:true},def);if(C.LAB.VISUALS&&C.LAB.VISUALS.effectRegistry)C.LAB.VISUALS.effectRegistry[id]={id,portable:true,independent:true,enabledByDefault:true};return E[id]}
function vessel(id,def){V[id]=Object.assign({id,hmax:1,pad:0,lw:4},def);return V[id]}
/* --- naczynia --- */
const rc=(c,x,y,w,h,r)=>{c.beginPath();c.moveTo(x,y);c.lineTo(x,y+h-r);c.quadraticCurveTo(x,y+h,x+r,y+h);c.lineTo(x+w-r,y+h);c.quadraticCurveTo(x+w,y+h,x+w,y+h-r);c.lineTo(x+w,y)};
vessel('beaker',{path:(c,r)=>rc(c,r.x,r.y,r.w,r.h,16),hmax:1});
vessel('testTube',{path:(c,r)=>{const w=Math.min(r.w,70),x=r.x+(r.w-w)/2;c.beginPath();c.moveTo(x,r.y);c.lineTo(x,r.y+r.h-w/2);c.arc(x+w/2,r.y+r.h-w/2,w/2,Math.PI,0,true);c.lineTo(x+w,r.y)},hmax:.8,pad:2});
vessel('cylinder',{path:(c,r)=>{const w=Math.min(r.w,90),x=r.x+(r.w-w)/2;rc(c,x,r.y,w,r.h,6)},hmax:.88,pad:2});
vessel('flask',{path:(c,r)=>{const cx=r.x+r.w/2,n=Math.min(r.w*.16,30),sh=r.y+r.h*.34;c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,sh);c.lineTo(r.x+r.w*.06,r.y+r.h-14);c.quadraticCurveTo(r.x+r.w*.06,r.y+r.h,r.x+r.w*.06+14,r.y+r.h);c.lineTo(r.x+r.w*.94-14,r.y+r.h);c.quadraticCurveTo(r.x+r.w*.94,r.y+r.h,r.x+r.w*.94,r.y+r.h-14);c.lineTo(cx+n,sh);c.lineTo(cx+n,r.y)},hmax:.6,pad:2});
/* --- efekty (kolejność rejestracji = kolejność rysowania w warstwie) --- */
effect('heatGlow',{layer:'back',label:'Poświata cieplna',defaults:{color:null},schema:{color:{t:'color',l:'Barwa poświaty'}},draw:e=>{const s=e.st;const gc=e.o.color||[255,140,40];if(!(s.heat>0))return;const c=e.c;c.save();c.shadowColor=rgba(gc,Math.min(1,s.heat/2));c.shadowBlur=26;e.path();c.strokeStyle=rgba(gc,.8);c.lineWidth=6;c.stroke();c.restore()}});
effect('liquid',{draw:e=>{const c=e.c,r=e.r,col=e.st.liquid||[205,228,238],g=c.createLinearGradient(0,e.top,0,e.bot);g.addColorStop(0,rgba(col,.66));g.addColorStop(1,rgba(col.map(v=>v*.86),.82));c.fillStyle=g;c.beginPath();c.moveTo(r.x,e.bot);c.lineTo(r.x,e.top);for(let x=0;x<=r.w;x+=8)c.lineTo(r.x+x,e.top+Math.sin(e.t/400+x/22)*1.3);c.lineTo(r.x+r.w,e.bot);c.closePath();c.fill()}});
effect('meniscus',{draw:e=>{e.c.fillStyle='rgba(255,255,255,.25)';e.c.fillRect(e.r.x,e.top,e.r.w,3)}});
effect('precipitate',{draw:e=>{const c=e.c,r=e.r,pop=e.st.pop||0;let p=0;(e.st.ppts||[]).forEach(q=>{if(!q.metal&&pop>0){c.fillStyle=rgba(q.col,.35*Math.min(1,pop));c.fillRect(r.x,e.top,r.w,e.bot-e.top)}if(q.eq<=.02)return;const hh=Math.max(4,Math.min(34,q.eq*7));c.fillStyle=rgba(q.col,q.metal?.95:.9);c.fillRect(r.x,e.bot-p-hh,r.w,hh);p+=hh});e.ph=p}});
effect('plume',{draw:e=>{const p=e.st.plume;if(!p||p.k<=.02)return;const c=e.c,r=e.r,cx=r.x+r.w/2,cy=e.bot-(e.ph||0)-22,rad=Math.max(24,r.w*.22)*(1+p.k*.8),g=c.createRadialGradient(cx,cy-rad*.2,2,cx,cy-rad*.2,rad);g.addColorStop(0,rgba(p.col,.55*p.k));g.addColorStop(1,rgba(p.col,0));c.fillStyle=g;c.fillRect(cx-rad,cy-rad*1.3,rad*2,rad*2.1)}});
effect('solids',{draw:e=>{const c=e.c,r=e.r;let sx=r.x+r.w*.18;(e.st.solids||[]).forEach(s=>{if(s.eq<=.02)return;const k=Math.max(.15,Math.min(1,s.eq/4)),w=r.w*.2*(s.t==='metal'?.7:1)*(.5+k*.5),h=s.t==='metal'?(26+14*k):(14+8*k),y=e.bot-(e.ph||0)-h-2;c.fillStyle=rgba(s.col);c.beginPath();if(c.roundRect)c.roundRect(sx,y,w,h,4);else c.rect(sx,y,w,h);c.fill();c.strokeStyle='rgba(0,0,0,.25)';c.lineWidth=1;c.stroke();sx+=w+8;if(sx>r.x+r.w-w)sx=r.x+r.w*.18})}});
effect('bubbles',{label:'Bąbelki',defaults:{size:1,rate:1},schema:{size:{t:'range',min:.4,max:3,step:.1,l:'Wielkość'},rate:{t:'range',min:.2,max:4,step:.1,l:'Natężenie'}},draw:e=>{const c=e.c,r=e.r,b=e.pool.bub=e.pool.bub||[],pp=e.pool.pops=e.pool.pops||[],g=e.st.gas||0,sz=(e.st.bubSize||1)*e.o.size,nn=(e.st.bubN||1)*e.o.rate;if(g>0){const n=Math.floor(g*nn*e.dt*22+Math.random());for(let i=0;i<n&&b.length<160;i++)b.push({x:r.x+18+Math.random()*(r.w-36),y:e.bot-18-(e.ph||0),r:(1.5+Math.random()*3)*sz,v:22+Math.random()*36,p:Math.random()*6})}
for(let i=b.length-1;i>=0;i--){const q=b[i];q.y-=q.v*e.dt;q.x+=Math.sin(e.t/200+q.p)*.4;if(q.y<e.top){pp.push({x:q.x,r:q.r,a:1});b.splice(i,1);continue}const k=1+.35*(e.bot-q.y)/Math.max(1,e.bot-e.top),rb=q.r*k;c.beginPath();c.arc(q.x,q.y,rb,0,7);c.fillStyle='rgba(255,255,255,.5)';c.fill();c.strokeStyle='rgba(80,100,120,.45)';c.lineWidth=1;c.stroke();c.beginPath();c.arc(q.x-rb*.3,q.y-rb*.3,Math.max(.6,rb*.25),0,7);c.fillStyle='rgba(255,255,255,.85)';c.fill()}
for(let i=pp.length-1;i>=0;i--){const q=pp[i];q.a-=e.dt*4;if(q.a<=0){pp.splice(i,1);continue}c.strokeStyle='rgba(255,255,255,'+q.a*.7+')';c.lineWidth=1;c.beginPath();c.ellipse(q.x,e.top+1,q.r*(2.2-q.a),q.r*.6*(2.2-q.a),0,0,7);c.stroke()}}});
effect('foam',{draw:e=>{const f=e.st.foam||0;if(f<=.02)return;const c=e.c,r=e.r;for(let i=0;i<26;i++){const x=r.x+6+rnd(i+31)*(r.w-12),y=e.top+1-rnd(i+8)*10*f+Math.sin(e.t/500+i)*1.2,rad=2+rnd(i+2)*4*f;c.beginPath();c.arc(x,y,rad,0,7);c.fillStyle='rgba(255,255,255,'+(.55*f)+')';c.fill();c.strokeStyle='rgba(120,140,160,'+(.35*f)+')';c.lineWidth=.8;c.stroke()}}});
effect('ripples',{draw:e=>{const p=e.st.pop||0;if(p<=0)return;const c=e.c,f=1-p;for(let i=0;i<3;i++){const k=Math.min(1,f+i*.12);c.strokeStyle='rgba(255,255,255,'+(.5*(1-k)*p)+')';c.lineWidth=1.5;c.beginPath();c.ellipse(e.r.x+e.r.w/2,e.top+2,10+k*e.r.w*.35,2+k*7,0,0,7);c.stroke()}}});
effect('condensation',{vessels:['beaker','flask','testTube','cylinder'],draw:e=>{if((e.st.T||25)<55)return;const c=e.c,a=Math.min(.55,((e.st.T||25)-55)/60);c.fillStyle='rgba(235,245,255,'+a+')';for(let i=0;i<14;i++){const side=i%2?e.r.x+e.r.w-5-rnd(i)*7:e.r.x+5+rnd(i)*7,y=e.r.y+8+rnd(i+9)*Math.max(10,e.top-e.r.y-6)+((e.t/1800+rnd(i))%1)*6;c.beginPath();c.arc(side,y,1.4+rnd(i+4)*1.8,0,7);c.fill()}}});
effect('fumes',{layer:'front',label:'Opary',defaults:{color:null,density:1},schema:{color:{t:'color',l:'Barwa oparów'},density:{t:'range',min:0,max:3,step:.1,l:'Gęstość'}},draw:e=>{const s=(e.st.fumes||0)*e.o.density;if(s<=0)return;const c=e.c,r=e.r;for(let i=0;i<12;i++){const f=((e.t/2600)+rnd(i))%1;c.beginPath();c.arc(r.x+r.w*.25+rnd(i+3)*r.w*.5+Math.sin(e.t/700+i)*12,r.y-f*40,10+f*16,0,7);c.fillStyle=rgba(e.o.color||e.st.fumeColor||[170,90,30],.3*(1-f)*Math.min(1,s));c.fill()}}});
effect('steam',{layer:'front',label:'Para wodna',defaults:{color:null},schema:{color:{t:'color',l:'Barwa pary'}},draw:e=>{const T=e.st.T||25;if(T<70)return;const c=e.c,r=e.r,k=Math.min(1,(T-70)/30);for(let i=0;i<9;i++){const f=((e.t/2200)+rnd(i+40))%1;c.beginPath();c.ellipse(r.x+r.w*.3+rnd(i+7)*r.w*.4+Math.sin(e.t/600+i)*9,r.y-4-f*55,7+f*13,5+f*9,0,0,7);c.fillStyle=rgba(e.o.color||[240,246,252],.38*k*(1-f));c.fill()}}});
effect('heatConvection',{layer:'front',draw:e=>{if(!(e.st.heat>2.2))return;const c=e.c,r=e.r;for(let i=0;i<5;i++){const f=((e.t/1500)+rnd(i+20))%1;c.beginPath();c.arc(r.x+r.w*(.2+.15*i)+Math.sin(e.t/500+i)*8,r.y-f*50,8+f*14,0,7);c.fillStyle='rgba(235,240,245,'+.45*(1-f)+')';c.fill()}}});
effect('splash',{layer:'front',draw:e=>{const c=e.c,d=e.pool.drops=e.pool.drops||[],s=e.st;if(s.splash>0){const n=Math.ceil(s.splash*e.dt*40);for(let i=0;i<n;i++)d.push({x:e.r.x+e.r.w/2+(Math.random()-.5)*e.r.w*.8,y:e.r.y+e.r.h*.5,vx:(Math.random()-.5)*260,vy:-180-Math.random()*220,r:2+Math.random()*3});s.splash=Math.max(0,s.splash-e.dt)}for(let i=d.length-1;i>=0;i--){const q=d[i];q.vy+=620*e.dt;q.x+=q.vx*e.dt;q.y+=q.vy*e.dt;if(q.y>e.r.y+e.r.h+60){d.splice(i,1);continue}c.beginPath();c.arc(q.x,q.y,q.r,0,7);c.fillStyle=rgba(s.liquid||[205,228,238],.9);c.fill();c.strokeStyle='rgba(180,40,40,.7)';c.lineWidth=1;c.stroke()}}});

/* ===== SILNIK EFEKTÓW SWOBODNYCH (free): płomień, iskry, spalanie metalu, wybuch, błysk =====
   Opcje: defaults + schema (UI generowane automatycznie: GFX.optionsPanel). Włączanie: st.fx={id:opcje|true}; jednorazowe: GFX.trigger(pool,id,opcje). */
const lg=(c,k)=>c.map(v=>Math.round(v+(255-v)*k));
const FLAME_COLORS={Li:[225,45,70],Na:[255,196,40],K:[190,125,235],Ca:[255,115,45],Sr:[245,40,45],Ba:[150,225,95],Cu:[50,225,165]};
const FLAME_NAMES={Li:'lit — karminowy',Na:'sód — żółty',K:'potas — fioletowy',Ca:'wapń — ceglastoczerwony',Sr:'stront — czerwony',Ba:'bar — zielony',Cu:'miedź — niebieskozielony'};
const METALS={Mg:{flame:[255,255,255],glow:[255,252,240],ash:[240,240,235],smoke:[240,240,240],sparks:[255,250,225],dur:7,bright:1.5,sparkRate:45,ribbon:'#aab3bb'},Fe:{flame:[255,185,70],glow:[255,170,60],ash:[55,45,42],smoke:[100,95,92],sparks:[255,205,95],dur:10,bright:.65,sparkRate:75,ribbon:'#6b7280'},Na:{flame:[255,200,40],glow:[255,225,120],ash:[235,235,230],smoke:[235,235,230],sparks:[255,215,70],dur:6,bright:1,sparkRate:20,ribbon:'#cbd5e1'},Zn:{flame:[170,235,255],glow:[220,250,255],ash:[240,240,240],smoke:[235,240,245],sparks:[200,240,255],dur:8,bright:.9,sparkRate:25,ribbon:'#94a3b8'},Cu:{flame:[50,225,165],glow:[160,255,220],ash:[30,30,32],smoke:[60,90,80],sparks:[90,240,190],dur:9,bright:.7,sparkRate:15,ribbon:'#c2703a'}};
function emit(pool,n,o,x,y){const sp=pool.sp=pool.sp||[];for(let i=0;i<n&&sp.length<700;i++){const an=(o.angle||0)*Math.PI/180+(Math.random()-.5)*(o.spread==null?1:o.spread),v=o.speed*(.35+Math.random()*.85);sp.push({x,y,vx:Math.cos(an)*v,vy:Math.sin(an)*v,life:o.life*(.5+Math.random()*.7),age:0,col:o.color,g:o.gravity,s:o.size*(.6+Math.random()*.8)})}}
function trigger(pool,id,opts){const f=E[id];if(!f)return null;const o=Object.assign({},f.defaults,opts||{}),ev={id,o,age:0,dur:o.dur||f.dur||.5,fired:0};(pool.events=pool.events||[]).push(ev);return ev}
effect('flame',{free:true,layer:'front',label:'Płomień',defaults:{power:1,phi:1,soot:0,temp:1200,color:null,size:1,flicker:1,glow:1},schema:{power:{t:'range',min:0,max:1,step:.05,l:'Moc'},phi:{t:'range',min:.4,max:1.6,step:.05,l:'φ mieszanki'},soot:{t:'range',min:0,max:1,step:.05,l:'Kopcenie'},size:{t:'range',min:.4,max:2,step:.05,l:'Rozmiar'},flicker:{t:'range',min:0,max:3,step:.1,l:'Migotanie'},glow:{t:'range',min:0,max:3,step:.1,l:'Poświata'},color:{t:'color',l:'Barwa (próba płomieniowa)'}},
draw:e=>{const c=e.c,o=e.o,t=e.t,cx=e.anchor.x,top=e.anchor.y,P=Math.max(0,Math.min(1,o.power));if(P<.03)return;const phi=o.phi,H=(60+125*P*(.55+.45*Math.min(1,o.temp/1800)))*o.size,W=(10+28*P*(phi>1.15?1.25:1))*o.size,rich=phi>1.15||o.soot>.25,lean=phi<.75,fl=(Math.sin(t/90)*W*.08+Math.sin(t/37)*W*.04)*o.flicker,col=o.color;
const outer=col?[col.map(Math.round).join(','),col.map(v=>v*.75|0).join(',')]:rich?['255,200,70','255,150,35']:lean?['150,205,255','90,160,255']:['190,225,255','95,160,255'],core=col?[lg(col,.7).join(','),lg(col,.35).join(',')]:rich?['255,235,150','255,190,60']:['40,90,230','110,170,255'];
const gl=c.createRadialGradient(cx,top-H*.4,2,cx,top-H*.4,H*1.1);gl.addColorStop(0,'rgba('+outer[1]+','+Math.min(1,.22*P*o.glow)+')');gl.addColorStop(1,'rgba('+outer[1]+',0)');c.fillStyle=gl;c.fillRect(cx-H*1.2,top-H*1.6,H*2.4,H*2.2);
const body=(k,cl,al)=>{const w=W*k,h=H*k;c.beginPath();c.moveTo(cx-w,top);c.bezierCurveTo(cx-w*1.15,top-h*.4,cx-w*.45+fl,top-h*.8,cx+fl*1.6,top-h);c.bezierCurveTo(cx+w*.45+fl,top-h*.8,cx+w*1.15,top-h*.4,cx+w,top);c.closePath();const g=c.createLinearGradient(0,top,0,top-h);g.addColorStop(0,'rgba('+cl[0]+','+al+')');g.addColorStop(1,'rgba('+cl[1]+','+(al*.35)+')');c.fillStyle=g;c.fill()};
c.save();c.shadowColor='rgba('+outer[1]+',.85)';c.shadowBlur=18;body(1,outer,.78);c.restore();body(.52,core,.9);
if(o.soot>.15){c.fillStyle='rgba(40,40,40,.22)';for(let i=0;i<7;i++){const u=((t/1600)+i*.14)%1;c.beginPath();c.arc(cx+(i-3)*9+Math.sin(t/300+i)*5,top-H*.9-u*60,3+i%2+u*3,0,7);c.fill()}}}});
effect('sparks',{free:true,layer:'front',label:'Iskry',defaults:{rate:40,color:[255,215,120],speed:260,gravity:700,spread:1.3,life:.9,size:2,angle:-90,count:60},schema:{rate:{t:'range',min:0,max:200,step:5,l:'Natężenie'},color:{t:'color',l:'Barwa'},speed:{t:'range',min:60,max:700,step:10,l:'Prędkość'},gravity:{t:'range',min:0,max:1600,step:50,l:'Grawitacja'},spread:{t:'range',min:.1,max:6.28,step:.1,l:'Rozrzut'},life:{t:'range',min:.2,max:2.5,step:.1,l:'Czas życia'},size:{t:'range',min:.5,max:5,step:.1,l:'Grubość'}},alive:p=>p.sp&&p.sp.length>0,
draw:e=>{const c=e.c,o=e.o,p=e.pool,a=e.anchor,sp=p.sp=p.sp||[],dt=e.dt;if(e.active)emit(p,Math.floor(o.rate*dt+Math.random()),o,a.x,a.y);e.evs.forEach(v=>{if(!v.fired){v.fired=1;emit(p,v.o.count||60,v.o,v.o.x==null?a.x:v.o.x,v.o.y==null?a.y:v.o.y)}});
c.globalCompositeOperation='lighter';c.lineCap='round';for(let i=sp.length-1;i>=0;i--){const q=sp[i];q.age+=dt;if(q.age>q.life){sp.splice(i,1);continue}q.vy+=q.g*dt;const px=q.x,py=q.y;q.x+=q.vx*dt;q.y+=q.vy*dt;const k=1-q.age/q.life;c.strokeStyle=rgba(q.col,k);c.lineWidth=q.s*k+.3;c.beginPath();c.moveTo(px-q.vx*.012,py-q.vy*.012);c.lineTo(q.x,q.y);c.stroke()}c.globalCompositeOperation='source-over'}});
effect('metalBurn',{free:true,layer:'front',label:'Spalanie metalu',defaults:{metal:'Mg',power:1,progress:null,sparks:1,smoke:1,glow:1},schema:{metal:{t:'select',opts:['Mg','Fe','Na','Zn','Cu'],l:'Metal'},power:{t:'range',min:.2,max:2,step:.1,l:'Intensywność'},glow:{t:'range',min:0,max:2,step:.1,l:'Blask'},sparks:{t:'range',min:0,max:3,step:.1,l:'Iskry'},smoke:{t:'range',min:0,max:3,step:.1,l:'Dym tlenku'}},alive:p=>p.mb&&p.mb.k>0,
draw:e=>{const c=e.c,o=e.o,a=e.anchor,t=e.t,dt=e.dt,pb=e.pool.mb=e.pool.mb||{k:0,sm:[]};if(e.active)pb.metal=o.metal;const M=METALS[pb.metal||o.metal]||METALS.Mg;if(o.progress!=null)pb.k=o.progress;else if(e.active)pb.k=Math.min(1,pb.k+dt*o.power/M.dur);
const burning=e.active&&pb.k<1,xs=a.x-70,len=64*(1-pb.k*.94),ex=xs+len;c.strokeStyle=e.T.glass;c.lineWidth=3;c.lineCap='round';c.beginPath();c.moveTo(xs-34,a.y-52);c.lineTo(xs,a.y);c.stroke();c.strokeStyle=M.ribbon;c.lineWidth=3.5;c.beginPath();c.moveTo(xs,a.y);c.lineTo(ex,a.y);c.stroke();
const fy=e.r.y+e.r.h-12;c.fillStyle=rgba(M.ash,.95);c.beginPath();c.ellipse(a.x,fy,10+42*pb.k,2+9*pb.k,0,0,7);c.fill();
if(burning){const fl=.75+.25*Math.sin(t/35)+.15*Math.sin(t/13),R=(40+90*o.power)*fl*o.glow*M.bright;c.globalCompositeOperation='lighter';const g=c.createRadialGradient(ex,a.y,1,ex,a.y,R);g.addColorStop(0,rgba(M.glow,1));g.addColorStop(.25,rgba(M.flame,.55));g.addColorStop(1,rgba(M.flame,0));c.fillStyle=g;c.beginPath();c.arc(ex,a.y,R,0,7);c.fill();c.globalCompositeOperation='source-over';c.fillStyle='#fff';c.beginPath();c.arc(ex,a.y,3+3*fl,0,7);c.fill();
if(o.sparks)emit(e.pool,Math.floor(M.sparkRate*o.sparks*dt+Math.random()),{angle:-90,spread:6.28,speed:200,gravity:500,life:.7,color:M.sparks,size:1.8},ex,a.y);if(o.smoke&&Math.random()<dt*14*o.smoke)pb.sm.push({x:ex,y:a.y,r:6,a:.5,vx:(Math.random()-.5)*14})}
for(let i=pb.sm.length-1;i>=0;i--){const q=pb.sm[i];q.y-=26*dt;q.x+=q.vx*dt;q.r+=10*dt;q.a-=.18*dt;if(q.a<=0){pb.sm.splice(i,1);continue}c.fillStyle=rgba(M.smoke,q.a);c.beginPath();c.arc(q.x,q.y,q.r,0,7);c.fill()}}});
effect('explosion',{free:true,oneShot:true,layer:'front',label:'Wybuch',defaults:{size:1,color:[255,170,60],dur:1.3,smoke:1,smokeColor:[70,70,75],shock:1,flash:1,debris:70,shake:1},schema:{size:{t:'range',min:.4,max:2.5,step:.1,l:'Rozmiar'},color:{t:'color',l:'Barwa ognia'},dur:{t:'range',min:.5,max:3,step:.1,l:'Czas [s]'},smoke:{t:'range',min:0,max:2,step:.1,l:'Dym'},smokeColor:{t:'color',l:'Barwa dymu'},shock:{t:'range',min:0,max:2,step:.1,l:'Fala uderzeniowa'},flash:{t:'range',min:0,max:1,step:.05,l:'Błysk'},debris:{t:'range',min:0,max:200,step:5,l:'Odłamki / iskry'},shake:{t:'range',min:0,max:3,step:.1,l:'Drżenie'}},
draw:e=>{const c=e.c,a=e.anchor;e.evs.forEach(v=>{const o=v.o,k=Math.min(1,v.age/o.dur),R=(30+150*Math.sqrt(k))*o.size,x=o.x==null?a.x:o.x,y=o.y==null?a.y:o.y;if(!v.fired){v.fired=1;emit(e.pool,o.debris,{angle:-90,spread:6.28,speed:380*o.size,gravity:900,life:1.1,color:lg(o.color,.35),size:2.6},x,y)}
if(o.flash&&v.age<.18){c.fillStyle='rgba(255,255,255,'+(.85*o.flash*(1-v.age/.18))+')';c.fillRect(x-2000,y-2000,4000,4000)}
const al=Math.pow(1-k,.8),g=c.createRadialGradient(x,y,0,x,y,R);g.addColorStop(0,'rgba(255,255,240,'+al+')');g.addColorStop(.35,rgba(o.color,.85*al));g.addColorStop(1,rgba(o.color.map(q=>q*.5),0));c.fillStyle=g;c.beginPath();c.arc(x,y,R,0,7);c.fill();
if(o.shock){c.strokeStyle='rgba(255,255,255,'+(.6*(1-k)*Math.min(1,o.shock))+')';c.lineWidth=3*(1-k)+1;c.beginPath();c.arc(x,y,R*1.7,0,7);c.stroke()}
if(o.smoke&&k>.2){const u=(k-.2)/.8;for(let i=0;i<10;i++){const an=rnd(i+3)*6.28,d=R*(.5+rnd(i)*.6);c.beginPath();c.arc(x+Math.cos(an)*d*.7,y-u*90*o.size+Math.sin(an)*d*.4,(14+rnd(i+9)*22)*o.size*(.6+u),0,7);c.fillStyle=rgba(o.smokeColor,.4*Math.min(1,o.smoke)*(1-u));c.fill()}}})}});
effect('flash',{free:true,oneShot:true,layer:'front',label:'Błysk',defaults:{color:[255,255,255],dur:.35,alpha:.8},schema:{color:{t:'color',l:'Barwa'},dur:{t:'range',min:.1,max:1.5,step:.05,l:'Czas [s]'},alpha:{t:'range',min:.1,max:1,step:.05,l:'Jasność'}},draw:e=>{const c=e.c,a=e.anchor;e.evs.forEach(v=>{c.fillStyle=rgba(v.o.color,v.o.alpha*(1-v.age/v.dur));c.fillRect(a.x-2000,a.y-2000,4000,4000)})}});
function hexOf(c){return '#'+c.map(v=>('0'+Math.round(v).toString(16)).slice(-2)).join('')}
function rgbOf(h){return[1,3,5].map(i=>parseInt(h.substr(i,2),16))}
function optionsPanel(host,id,o,cb){host.innerHTML='';const f=E[id];if(!f||!f.schema)return;const d=f.defaults||{};Object.keys(f.schema).forEach(k=>{const s=f.schema[k],row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:120px 1fr auto;gap:6px;align-items:center;font-size:12px';row.innerHTML='<span>'+s.l+'</span>';let inp;
if(s.t==='range'){inp=document.createElement('input');inp.type='range';inp.min=s.min;inp.max=s.max;inp.step=s.step||.05;inp.value=o[k]!=null?o[k]:d[k];const out=document.createElement('output');out.textContent=inp.value;inp.oninput=()=>{o[k]=+inp.value;out.textContent=inp.value;cb&&cb(k)};row.append(inp,out)}
else if(s.t==='color'){inp=document.createElement('input');inp.type='color';inp.value=hexOf(o[k]||d[k]||[255,200,60]);inp.oninput=()=>{o[k]=rgbOf(inp.value);cb&&cb(k)};const b=document.createElement('button');b.type='button';b.textContent='auto';b.onclick=()=>{delete o[k];if(d[k])inp.value=hexOf(d[k]);cb&&cb(k)};row.append(inp,b)}
else{inp=document.createElement('select');(s.opts||[]).forEach(x=>{const q=document.createElement('option');q.value=q.textContent=x;inp.appendChild(q)});inp.value=o[k]||d[k];inp.onchange=()=>{o[k]=inp.value;cb&&cb(k)};row.append(inp,document.createElement('span'))}
host.appendChild(row)})}
const PRESETS=[{label:'Spalanie magnezu',id:'metalBurn',o:{metal:'Mg'}},{label:'Wełna stalowa (iskry)',id:'metalBurn',o:{metal:'Fe'}},{label:'Spalanie sodu (żółty)',id:'metalBurn',o:{metal:'Na'}},{label:'Spalanie miedzi (zielone)',id:'metalBurn',o:{metal:'Cu'}},{label:'Płomień — metan',id:'flame',o:{phi:1,power:.8}},{label:'Płomień — kopcący',id:'flame',o:{phi:1.4,soot:.6,power:.9}},{label:'Płomień — lit (czerwony)',id:'flame',o:{color:FLAME_COLORS.Li,power:.8}},{label:'Płomień — sód (żółty)',id:'flame',o:{color:FLAME_COLORS.Na,power:.8}},{label:'Płomień — potas (fioletowy)',id:'flame',o:{color:FLAME_COLORS.K,power:.8}},{label:'Płomień — bar (zielony)',id:'flame',o:{color:FLAME_COLORS.Ba,power:.8}},{label:'Płomień — miedź (niebieskozielony)',id:'flame',o:{color:FLAME_COLORS.Cu,power:.8}},{label:'Wybuch H₂ + O₂ (niebieski)',id:'explosion',o:{color:[140,185,255],size:1.1,smoke:.5,smokeColor:[190,200,215]}},{label:'Wybuch — ognisty',id:'explosion',o:{}},{label:'Iskry',id:'sparks',o:{rate:90}},{label:'Błysk',id:'flash',o:{}}];
vessel('stage',{custom:(c,r,st,env)=>{const T=env.th,ax=r.x+r.w/2,ay=r.y+r.h*.72,fy=r.y+r.h-8;c.strokeStyle=T.glass;c.lineWidth=4;c.lineCap='round';c.beginPath();c.moveTo(r.x+r.w*.12,fy);c.lineTo(r.x+r.w*.88,fy);c.stroke();c.fillStyle=T.dark?'#475569':'#94a3b8';c.fillRect(ax-3,ay+4,6,fy-ay-4);return{x:ax,y:ay}}});

/* --- palnik Bunsena + płomień (λ/φ → barwa, kopcenie, moc) --- */
function burner(c,r,st,env){const T=env.th,f=st.flame||{},cx=r.x+r.w/2,base=r.y+r.h-6,tw=Math.min(r.w*.14,16),top=base-64;
c.strokeStyle=T.glass;c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(cx-58,base);c.lineTo(cx+58,base);c.stroke();
c.fillStyle=T.dark?'#475569':'#94a3b8';c.fillRect(cx-34,base-10,68,10);c.fillRect(cx-tw,base-64,tw*2,54);
c.fillStyle=T.dark?'#334155':'#64748b';c.fillRect(cx-tw-3,base-40,tw*2+6,9);
const air=Math.max(0,Math.min(1.6,(f.air==null?100:f.air)/100));c.fillStyle='rgba(15,23,42,'+(.35+.25*(1-Math.min(1,air)))+')';c.fillRect(cx-tw-2,base-37,tw*2+4,3);
if(!f.on||!(f.power>.05)){c.fillStyle='rgba(120,140,160,.25)';c.beginPath();c.arc(cx,base-68,4,0,7);c.fill()}
else env.fx=Object.assign({},env.fx,{flame:{power:Math.min(1,f.power),phi:f.phi==null?1:f.phi,soot:f.soot||0,temp:f.temp||900,color:f.color||null}});
return{x:cx,y:top}}
vessel('burner',{custom:burner});
/* --- chłodnica Liebiga: płaszcz, przeciwprąd chłodziwa, skraplanie --- */
function cooler(c,r,st,env){const T=env.th,k=st.coolant||{Tin:15,Tout:15,flow:.0004,q:0},t=env.t,x0=r.x+r.w*.16,x1=r.x+r.w*.84,cy=r.y+r.h/2,jh=Math.min(r.h*.5,70),ih=jh*.28;
const g=c.createLinearGradient(x0,0,x1,0);g.addColorStop(0,rgba(tc(k.Tout),.55));g.addColorStop(1,rgba(tc(k.Tin),.55));c.fillStyle=g;c.fillRect(x0,cy-jh/2,x1-x0,jh);
const sp=Math.min(1,(k.flow||0)/.0008),dir=-1;c.strokeStyle='rgba(255,255,255,.55)';c.lineWidth=1.5;c.setLineDash([8,12]);c.lineDashOffset=dir*t/1000*(10+90*sp);[-.28,.28].forEach(o=>{c.beginPath();c.moveTo(x1,cy+jh*o);c.lineTo(x0,cy+jh*o);c.stroke()});c.setLineDash([]);
c.fillStyle=T.dark?'rgba(15,23,42,.8)':'rgba(255,255,255,.8)';c.fillRect(x0-14,cy-ih/2,x1-x0+28,ih);
const vap=Math.max(0,Math.min(1,((st.T==null?25:st.T)-30)/70));for(let i=0;i<10;i++){const u=((t/2000)+rnd(i))%1,x=x0-14+u*(x1-x0+28),a=vap*(1-u)*.5;c.fillStyle='rgba(235,240,248,'+a+')';c.beginPath();c.arc(x,cy-ih*.1+Math.sin(t/300+i)*2,3+3*(1-u),0,7);c.fill()}
const cd=Math.min(1,(k.q||0)/80)*vap;c.fillStyle='rgba(120,180,230,.85)';for(let i=0;i<6;i++){const u=((t/1500)+rnd(i+12))%1,x=x0+(x1-x0)*(.45+.55*u);if(rnd(i+5)>cd+.3)continue;c.beginPath();c.arc(x,cy+ih*.3+u*ih*.2,2.2,0,7);c.fill()}
c.strokeStyle=T.glass;c.lineWidth=4;c.lineJoin='round';c.strokeRect(x0,cy-jh/2,x1-x0,jh);c.lineWidth=3;c.beginPath();c.moveTo(x0-14,cy-ih/2);c.lineTo(x1+14,cy-ih/2);c.moveTo(x0-14,cy+ih/2);c.lineTo(x1+14,cy+ih/2);c.stroke();
c.lineWidth=5;c.beginPath();c.moveTo(x0+16,cy-jh/2);c.lineTo(x0+16,cy-jh/2-18);c.moveTo(x1-16,cy+jh/2);c.lineTo(x1-16,cy+jh/2+18);c.stroke();
c.fillStyle=T.text;c.font='700 11px Inter,system-ui';c.textAlign='left';c.fillText('woda wyj. '+(+k.Tout||0).toFixed(1)+' °C',x0+22,cy-jh/2-8);c.textAlign='right';c.fillText('woda wej. '+(+k.Tin||0).toFixed(1)+' °C',x1-22,cy+jh/2+30);c.textAlign='left';c.fillStyle=T.mut;c.fillText('para →  ← skropliny',x0,r.y+10)}
vessel('cooler',{custom:cooler});
/* --- rysowanie jednego naczynia/modułu --- */
function free(c,r,st,env,an){const pool=env.pool,evs=pool.events,cfgAll=Object.assign({},st.fx,env.fx),offs=(env.opt&&env.opt.effects)||{},e0={c,r,st,env,T:env.th,t:env.t||0,dt:env.dt||.016,pool,anchor:an||st.anchor||{x:r.x+r.w/2,y:r.y+r.h*.72}};
Object.keys(E).forEach(k=>{const f=E[k];if(!f.free||offs[k]===0||offs[k]===false)return;if(env.only&&env.only.indexOf(k)<0)return;const cfg=cfgAll[k],mine=evs.filter(x=>x.id===k),alive=f.alive&&f.alive(pool);if(!cfg&&!mine.length&&!alive)return;
const e=Object.assign({},e0,{o:Object.assign({},f.defaults,(env.opt&&env.opt.fx&&env.opt.fx[k])||{},cfg&&cfg!==true?cfg:{}),active:!!cfg,evs:mine});c.save();f.draw(e);c.restore()});
for(let i=evs.length-1;i>=0;i--){const v=evs[i];v.age+=e0.dt;if(v.age>v.dur)evs.splice(i,1)}}
function body(id,v,c,r,st,env){const on=(env.opt&&env.opt.effects)||{},only=env.only,use=k=>only?only.indexOf(k)>=0:(on[k]!==0&&on[k]!==false),T=env.th;
const lv=Math.max(0,Math.min(1,st.level==null?.5:st.level)),bot=r.y+r.h-v.pad,top=bot-v.hmax*r.h*lv,id_=v.id;
const e={c,r,st,env,top,bot,T,t:env.t||0,dt:env.dt||.016,pool:env.pool,use,path:()=>v.path(c,r)};
const run=l=>Object.keys(E).forEach(k=>{const f=E[k];if(!f.free&&f.layer===l&&use(k)&&(!f.vessels||f.vessels.indexOf(id_)>=0)){e.o=Object.assign({},f.defaults,(env.opt&&env.opt.fx&&env.opt.fx[k])||{},(st.fx&&st.fx[k]&&st.fx[k]!==true)?st.fx[k]:{});f.draw(e)}});
run('back');c.save();v.path(c,r);c.closePath();c.clip();run('in');c.restore();
if(!only&&use('glass')){v.path(c,r);c.strokeStyle=T.glass;c.lineWidth=v.lw;c.lineJoin=c.lineCap='round';c.stroke();c.beginPath();c.moveTo(r.x+8,r.y+14);c.lineTo(r.x+8,bot-24);c.strokeStyle=T.hi;c.lineWidth=3;c.stroke()}
run('front')}
function draw(id,c,r,st,env){const v=V[id];if(!v)return;env=env||{};env.th=th();const pool=env.pool=env.pool||{};pool.events=pool.events||[];st=st||{};env.fx=null;
const sh=pool.events.find(x=>x.id==='explosion'&&x.o.shake);let sx=0,sy=0;if(sh){const k=Math.pow(Math.max(0,1-sh.age/.6),2)*6*sh.o.shake*sh.o.size;sx=(Math.random()-.5)*k;sy=(Math.random()-.5)*k}
c.save();c.translate(sx,sy);let an=null;if(v.custom)an=v.custom(c,r,st,env);else body(id,v,c,r,st,env);free(c,r,st,env,an);c.restore()}
/* --- stan wspólny: jedna sesja LAB → każdy moduł --- */
function fromLab(lab){const S=lab.S||{};let ph=7;try{ph=pH(S)}catch(_){}const t=lab.thermalState,b=lab.combustionState,k=lab.coolerState;return{pH:ph,titrant:lab.titrationState||null,liquid:liquidColor(S),level:clamp(.28+.18*Math.min(S.V||1,4),.28,.82),ppts:S.ppts||[],solids:S.solids||[],gas:Math.min(1,S.gasT||0),heat:S.heat||0,fumes:S.fumes||0,pop:0,T:t?t.T:(S.T!=null?S.T:25),flame:b&&b.on?{on:1,power:b.power,phi:b.phi,soot:b.soot,temp:b.temp,air:b.air,color:b.flameRGB||null}:null,coolant:k?{Tin:k.Tin,Tout:k.Tout,flow:k.flow,q:k.q}:null}}
/* --- scena: parts=[{id,x,y,w,h (ułamki 0-1),get?}] albo vessel:'id' --- */
function mount(host,spec){spec=spec||{};const cv=document.createElement('canvas');cv.style.cssText='width:100%;height:'+(spec.height||260)+'px;border-radius:12px;background:var(--surface-soft,#f1f5f9);display:block';host.appendChild(cv);const c=cv.getContext('2d'),parts=(spec.parts||[{id:spec.vessel||'beaker',x:.1,y:.06,w:.8,h:.88}]).map(p=>Object.assign({pool:{}},p));let raf=0,last=0,W=0,H=0,dead=0;
const sz=()=>{const d=Math.min(g.devicePixelRatio||1,2);W=cv.clientWidth||320;H=cv.clientHeight||260;cv.width=W*d;cv.height=H*d;c.setTransform(d,0,0,d,0,0)};if(g.ResizeObserver)new ResizeObserver(sz).observe(cv);sz();
const lab=spec.lab,popTimer={v:0};if(lab&&lab.on)lab.on('add',()=>{popTimer.v=1});
function frame(t){if(dead||!cv.isConnected)return;const dt=Math.min(.05,(t-last)/1000||0);last=t;if(!W)sz();c.clearRect(0,0,W,H);popTimer.v=Math.max(0,popTimer.v-dt*2);
parts.forEach(p=>{const st=(p.get||spec.get||(lab?()=>fromLab(lab):()=>({})))();st.pop=popTimer.v;if(spec.fx)st.fx=Object.assign({},spec.fx,st.fx);draw(p.id,c,{x:p.x*W,y:p.y*H,w:p.w*W,h:p.h*H},st,{t,dt,pool:p.pool,only:spec.only,opt:{effects:spec.effects,fx:spec.fxOpt}})});raf=requestAnimationFrame(frame)}
raf=requestAnimationFrame(frame);return{canvas:cv,trigger:(id,o,i)=>trigger(parts[i||0].pool,id,o),reset:()=>parts.forEach(p=>{p.pool={}}),destroy(){dead=1;cancelAnimationFrame(raf);if(cv.parentNode)cv.parentNode.removeChild(cv)}}}
/* --- pojedynczy efekt jako samodzielny widżet (zastępuje stary mountEffect) --- */
function mountEffect(id,host,opt){opt=opt||{};const wrap=document.createElement('div');wrap.dataset.effect=id;wrap.style.cssText='position:relative;border:1px solid var(--border,#e2e8f0);border-radius:12px;overflow:hidden';host.appendChild(wrap);const demo={liquid:[205,228,238],level:.55,gas:1,heat:3,fumes:1,splash:1,T:95,pop:0,ppts:[],solids:[]};let n=0;const m=mount(wrap,{height:opt.height||170,vessel:(E[id]&&E[id].free)?'stage':'beaker',only:[id].concat(id==='bubbles'||id==='ripples'||id==='condensation'?['liquid']:[]),get:()=>{n++;demo.fx=E[id]&&E[id].free&&!E[id].oneShot?{[id]:{}}:null;if(E[id]&&E[id].oneShot&&n%150===1&&m)m.trigger(id);demo.pop=id==='ripples'?1-((n%90)/90):0;demo.splash=id==='splash'?1:0;return demo}});return{host:wrap,destroy:()=>{m.destroy();if(wrap.parentNode)wrap.parentNode.removeChild(wrap)}}}

/* --- PRZYRZĄDY: pH-metr cyfrowy, termometr, biureta (ten sam stan sesji, własne wygładzanie odczytu) --- */
const pHcol=p=>'hsl('+Math.round(Math.max(0,Math.min(14,p))/14*250)+',70%,48%)';
const fmt=(x,n)=>(+x).toFixed(n).replace('.',',');
const rr=(c,x,y,w,h,r)=>{c.beginPath();if(c.roundRect)c.roundRect(x,y,w,h,r);else c.rect(x,y,w,h)};
function smooth(env,k,target,rate){const p=env.pool;if(p[k]==null||!isFinite(p[k]))p[k]=target;p[k]+=(target-p[k])*Math.min(1,(env.dt||.016)*rate);return p[k]}
function pHmeter(c,r,st,env){const T=env.th,w=Math.min(r.w,150),x=r.x+(r.w-w)/2,bh=Math.min(r.h*.5,95),tgt=st.pH==null?7:st.pH,v=smooth(env,'ph',tgt,2.2),stable=Math.abs(v-tgt)<.02;
c.fillStyle=T.dark?'#1e293b':'#e2e8f0';c.strokeStyle=T.glass;c.lineWidth=3;rr(c,x,r.y,w,bh,12);c.fill();c.stroke();
c.fillStyle=T.dark?'#06130c':'#cfe8d4';rr(c,x+8,r.y+8,w-16,bh*.52,6);c.fill();
c.fillStyle=T.dark?'#7cffb2':'#10361f';c.font='800 '+Math.round(bh*.34)+'px ui-monospace,monospace';c.textAlign='center';c.fillText(fmt(v,2),x+w/2,r.y+8+bh*.38);c.font='700 10px ui-monospace,monospace';c.fillText('pH · '+fmt(st.T==null?25:st.T,1)+' °C',x+w/2,r.y+8+bh*.5);
const g=c.createLinearGradient(x+10,0,x+w-10,0);for(let i=0;i<=14;i+=2)g.addColorStop(i/14,pHcol(i));c.fillStyle=g;rr(c,x+10,r.y+bh*.68,w-20,7,3);c.fill();const px=x+10+(w-20)*Math.max(0,Math.min(1,v/14));c.fillStyle=T.text;c.beginPath();c.moveTo(px,r.y+bh*.68-2);c.lineTo(px-4,r.y+bh*.68-8);c.lineTo(px+4,r.y+bh*.68-8);c.fill();
c.fillStyle=stable?'#22c55e':'#f59e0b';c.beginPath();c.arc(x+w-14,r.y+bh-9,4,0,7);c.fill();c.fillStyle=T.mut;c.font='600 9px Inter,system-ui';c.textAlign='left';c.fillText(stable?'stabilny':'ustala się…',x+12,r.y+bh-6);
const ex=x+w/2,ey=r.y+bh,eb=r.y+r.h-14;c.strokeStyle=T.glass;c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(ex,ey);c.lineTo(ex,eb);c.stroke();c.fillStyle=pHcol(v);c.beginPath();c.arc(ex,eb+2,7,0,7);c.fill();c.strokeStyle=T.glass;c.lineWidth=2;c.stroke()}
vessel('pHmeter',{custom:pHmeter});
function thermometer(c,r,st,env){const T=env.th,t=smooth(env,'T',st.T==null?25:st.T,2.5),cx=r.x+r.w/2,top=r.y+14,bot=r.y+r.h-26,lo=-20,hi=120,y=bot-(bot-top)*Math.max(0,Math.min(1,(t-lo)/(hi-lo)));
c.strokeStyle=T.glass;c.lineWidth=3;c.lineCap='round';c.beginPath();c.moveTo(cx-6,top);c.lineTo(cx-6,bot);c.arc(cx,bot+8,12,Math.PI*1.17,Math.PI*1.83,true);c.lineTo(cx+6,top);c.arc(cx,top,6,0,Math.PI,true);c.stroke();
const col=t>70?'#ef4444':t<5?'#3b82f6':'#f97316';c.fillStyle=col;c.fillRect(cx-3,y,6,bot+4-y);c.beginPath();c.arc(cx,bot+8,9,0,7);c.fill();c.fillStyle=T.mut;c.font='600 9px Inter,system-ui';c.textAlign='left';c.strokeStyle=T.mut;c.lineWidth=1;for(let v=lo;v<=hi;v+=20){const yy=bot-(bot-top)*(v-lo)/(hi-lo);c.beginPath();c.moveTo(cx+9,yy);c.lineTo(cx+(v%40?15:20),yy);c.stroke();if(!(v%40))c.fillText(v,cx+23,yy+3)}
c.fillStyle=T.dark?'#06130c':'#cfe8d4';rr(c,r.x+4,r.y+r.h-20,Math.min(r.w-8,76),18,4);c.fill();c.fillStyle=T.dark?'#7cffb2':'#10361f';c.font='800 12px ui-monospace,monospace';c.textAlign='center';c.fillText(fmt(t,1)+' °C',r.x+4+Math.min(r.w-8,76)/2,r.y+r.h-7)}
vessel('thermometer',{custom:thermometer});
function burette(c,r,st,env){const T=env.th,b=st.titrant||{V:0,Vmax:50,drip:0,color:[205,228,238]},cx=r.x+r.w/2,w=26,top=r.y+8,bot=r.y+r.h-34,fl=bot-top,lv=1-Math.max(0,Math.min(1,b.V/b.Vmax));
c.fillStyle=rgba(b.color||[205,228,238],.7);c.fillRect(cx-w/2+2,top+fl*(1-lv),w-4,fl*lv);c.strokeStyle=T.glass;c.lineWidth=3;c.lineJoin='round';c.strokeRect(cx-w/2,top,w,fl);
c.strokeStyle=T.mut;c.fillStyle=T.mut;c.lineWidth=1;c.font='600 9px Inter,system-ui';c.textAlign='left';for(let v=0;v<=b.Vmax;v+=5){const y=top+fl*v/b.Vmax;c.beginPath();c.moveTo(cx+w/2,y);c.lineTo(cx+w/2+(v%10?5:9),y);c.stroke();if(!(v%10))c.fillText(v,cx+w/2+12,y+3)}
c.fillStyle=T.glass;c.fillRect(cx-3,bot,6,16);c.fillRect(cx-10,bot+6,20,4);c.fillRect(cx-1.5,bot+16,3,8);
if(b.drip>0){const d=env.pool.d=env.pool.d||[];if(Math.random()<Math.min(1,b.drip)*env.dt*6)d.push({y:bot+24,v:0});for(let i=d.length-1;i>=0;i--){const q=d[i];q.v+=500*env.dt;q.y+=q.v*env.dt;if(q.y>r.y+r.h){d.splice(i,1);continue}c.fillStyle=rgba(b.color||[205,228,238],.9);c.beginPath();c.arc(cx,q.y,2.6,0,7);c.fill()}}
c.fillStyle=T.text;c.font='800 11px Inter,system-ui';c.textAlign='center';c.fillText(fmt(b.V,2)+' cm³',cx,r.y+r.h-6)}
vessel('burette',{custom:burette});
/* --- v1.4: nowe naczynia (path → działają wszystkie efekty cieczy), przyrządy, papierki, zbiornik cząsteczek --- */
vessel('roundFlask',{path:(c,r)=>{const cx=r.x+r.w/2,n=Math.min(r.w*.12,22),R=Math.max(n*2,Math.min(r.w*.46,r.h*.36)),cy=r.y+r.h-R-2,h=Math.sqrt(R*R-n*n),d=Math.atan2(h,n);c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,cy-h);c.arc(cx,cy,R,Math.PI+d,-d,true);c.lineTo(cx+n,r.y)},hmax:.62,pad:2});
vessel('volFlask',{path:(c,r)=>{const cx=r.x+r.w/2,n=r.w*.07,sh=r.y+r.h*.42,L=r.x+r.w*.04,R=r.x+r.w*.96,b=r.y+r.h;c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,sh);c.bezierCurveTo(cx-n,sh+r.h*.12,L,sh+r.h*.08,L,b-26);c.quadraticCurveTo(L,b,L+22,b);c.lineTo(R-22,b);c.quadraticCurveTo(R,b,R,b-26);c.bezierCurveTo(R,sh+r.h*.08,cx+n,sh+r.h*.12,cx+n,sh);c.lineTo(cx+n,r.y)},hmax:.84,pad:2});
vessel('funnel',{path:(c,r)=>{const cx=r.x+r.w/2;c.beginPath();c.moveTo(r.x+r.w*.08,r.y);c.lineTo(cx-4,r.y+r.h*.55);c.lineTo(cx-4,r.y+r.h);c.lineTo(cx+4,r.y+r.h);c.lineTo(cx+4,r.y+r.h*.55);c.lineTo(r.x+r.w*.92,r.y)},hmax:.9,pad:2});
vessel('petri',{path:(c,r)=>{const y0=r.y+r.h*.7;rc(c,r.x+r.w*.04,y0,r.w*.92,r.y+r.h-y0-2,8)},hmax:.26,pad:2});
vessel('evapDish',{path:(c,r)=>{const x0=r.x+r.w*.08,x1=r.x+r.w*.92,y0=r.y+r.h*.5,yb=r.y+r.h;c.beginPath();c.moveTo(x0,y0);c.bezierCurveTo(x0,yb,x1,yb,x1,y0)},hmax:.45,pad:2});
effect('ringMark',{layer:'front',vessels:['volFlask'],label:'Kreska miarowa',defaults:{text:'100 mL'},schema:{},draw:e=>{const c=e.c,r=e.r,cx=r.x+r.w/2,n=r.w*.07,y=r.y+r.h*.16;c.strokeStyle=e.T.text;c.lineWidth=2;c.beginPath();c.moveTo(cx-n-5,y);c.lineTo(cx+n+5,y);c.stroke();c.fillStyle=e.T.mut;c.font='600 9px Inter,system-ui';c.textAlign='left';c.fillText(e.o.text,cx+n+8,y+3)}});
/* pipeta */
function pipette(c,r,st,env){const T=env.th,p=st.pip||{lv:.6,drip:0,color:[205,228,238]},cx=r.x+r.w/2,bR=Math.min(r.w*.2,16),top=r.y+bR*2+8,bot=r.y+r.h-30,w=10,tipY=bot+16,fl=bot-top,lv=Math.max(0,Math.min(1,p.lv==null?.6:p.lv));
c.fillStyle=T.dark?'#7f1d1d':'#dc2626';c.beginPath();c.ellipse(cx,r.y+bR+2,bR*.8,bR,0,0,7);c.fill();c.fillRect(cx-w/2-1,r.y+bR*2,w+2,8);
if(lv>.45){c.fillStyle=rgba(p.color||[205,228,238],.6);c.beginPath();c.ellipse(cx,top+fl*.45,w*1.1,fl*.17,0,0,7);c.fill()}
c.fillStyle=rgba(p.color||[205,228,238],.75);c.fillRect(cx-w/2+1.5,bot-fl*lv,w-3,fl*lv+4);
c.strokeStyle=T.glass;c.lineWidth=3;c.lineJoin='round';c.beginPath();c.ellipse(cx,top+fl*.45,w*1.1,fl*.17,0,0,7);c.stroke();c.beginPath();c.moveTo(cx-w/2,top);c.lineTo(cx-w/2,bot);c.lineTo(cx-1.5,tipY);c.lineTo(cx+1.5,tipY);c.lineTo(cx+w/2,bot);c.lineTo(cx+w/2,top);c.stroke();
c.strokeStyle=T.mut;c.lineWidth=1.5;c.beginPath();c.moveTo(cx-w/2-6,top+fl*.1);c.lineTo(cx+w/2+6,top+fl*.1);c.stroke();
if(p.drip>0){const d=env.pool.d=env.pool.d||[];if(Math.random()<Math.min(1,p.drip)*env.dt*6)d.push({y:tipY,v:0});for(let i=d.length-1;i>=0;i--){const q=d[i];q.v+=500*env.dt;q.y+=q.v*env.dt;if(q.y>r.y+r.h){d.splice(i,1);continue}c.fillStyle=rgba(p.color||[205,228,238],.9);c.beginPath();c.arc(cx,q.y,2.4,0,7);c.fill()}}}
vessel('pipette',{custom:pipette});
/* waga */
function balance(c,r,st,env){const T=env.th,m=smooth(env,'m',st.mass==null?0:st.mass,4),w=Math.min(r.w,170),x=r.x+(r.w-w)/2,by=r.y+r.h-44,cx=x+w/2;
c.fillStyle=T.dark?'#1e293b':'#e2e8f0';c.strokeStyle=T.glass;c.lineWidth=3;rr(c,x,by,w,40,8);c.fill();c.stroke();
c.fillStyle=T.dark?'#06130c':'#cfe8d4';rr(c,cx-34,by+7,68,22,4);c.fill();c.fillStyle=T.dark?'#7cffb2':'#10361f';c.font='800 14px ui-monospace,monospace';c.textAlign='center';c.fillText(fmt(m,2)+' g',cx,by+23);
c.fillStyle=T.mut;c.fillRect(cx-3,by-12,6,12);c.fillStyle=T.dark?'#475569':'#94a3b8';rr(c,cx-w*.36,by-18,w*.72,7,3);c.fill();
if(m>.005){const k=Math.min(1,m/40);c.fillStyle=rgba(st.massCol||[238,238,232],.95);c.beginPath();c.ellipse(cx,by-19,8+30*k,2+10*k,0,Math.PI,0);c.fill();c.strokeStyle='rgba(0,0,0,.25)';c.lineWidth=1;c.stroke()}}
vessel('balance',{custom:balance});
/* papierki wskaźnikowe: kolory z CHE.COLORS (ind-uniwersalny, ind-lakmus, ind-fenoloftaleina); zapas gdy brak modułu */
const sm=(x,a,b)=>Math.max(0,Math.min(1,(x-a)/(b-a))),mc=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
const PHF={'ind-uniwersalny':p=>{const U=[[229,38,46],[239,90,40],[246,162,30],[232,194,44],[215,217,58],[92,184,92],[33,168,154],[47,127,193],[74,75,181],[107,45,143]],k=Math.max(0,Math.min(8.999,p/14*9)),i=Math.floor(k);return mc(U[i],U[i+1],k-i)},'ind-lakmus':p=>mc([220,38,38],[37,99,235],sm(p,4.5,8.3)),'ind-fenoloftaleina':()=>[219,39,119]};
const phCol=(id,p)=>colors.at(id,p)||PHF[id](p);
const PAPERS={universal:{n:'Uniwersalny',dry:[238,228,172],f:p=>phCol('ind-uniwersalny',p),rd:p=>'pH ≈ '+Math.round(p)},litmusRed:{n:'Lakmus czerw.',dry:[226,96,104],f:p=>mc([226,96,104],phCol('ind-lakmus',p),sm(p,7,8.5)),rd:p=>p>8.3?'zasadowy':'bez zmiany'},litmusBlue:{n:'Lakmus niebiesk.',dry:[86,112,206],f:p=>mc([86,112,206],phCol('ind-lakmus',p),1-sm(p,4.8,6.8)),rd:p=>p<4.5?'kwaśny':'bez zmiany'},phenol:{n:'Fenoloftaleina',dry:[247,245,240],f:p=>mc([247,245,240],phCol('ind-fenoloftaleina',10),sm(p,8.2,10)),rd:p=>p>8.2?'zasadowy':'bez zmiany'}};
function paper(c,r,st,env){const T=env.th,list=st.papers||['universal','litmusRed','litmusBlue','phenol'],n=list.length,pH=st.pH==null?7:st.pH,pool=env.pool,dip=smooth(env,'dip',st.dip==null?1:st.dip,3),y0=r.y+r.h-70,top=r.y+8,len=r.h-102+34*dip,tipY=top+len,gap=r.w/n,sw=Math.min(gap*.52,34);
if(pool.fr!==st.fresh){pool.fr=st.fresh;pool.pw=0;pool.p0=null}
let wet=pool.pw||0;if(dip>.7){wet+=(46-wet)*Math.min(1,(env.dt||.016)*1.2);pool.p0=pH}pool.pw=wet;const pc=pool.p0==null?pH:pool.p0;
c.fillStyle=rgba(st.liquid||[205,228,238],.5);rr(c,r.x+8,y0,r.w-16,r.y+r.h-34-y0,6);c.fill();
list.forEach((id,i)=>{const P=PAPERS[id]||PAPERS.universal,x=r.x+gap*(i+.5)-sw/2;c.fillStyle=rgba(P.dry);rr(c,x,top,sw,len,2);c.fill();
if(wet>1){const wh=Math.min(len,wet);c.fillStyle=rgba(P.f(pc));rr(c,x,tipY-wh,sw,wh,2);c.fill()}
c.strokeStyle='rgba(0,0,0,.18)';c.lineWidth=1;rr(c,x,top,sw,len,2);c.stroke();c.fillStyle=T.dark?'#475569':'#94a3b8';c.fillRect(x-3,top-5,sw+6,8);
c.textAlign='center';c.fillStyle=T.mut;c.font='600 9px Inter,system-ui';c.fillText(P.n,x+sw/2,r.y+r.h-20);if(wet>30){c.fillStyle=T.text;c.font='700 9px Inter,system-ui';c.fillText(P.rd(pc),x+sw/2,r.y+r.h-8)}});
c.strokeStyle=T.glass;c.lineWidth=3;c.lineJoin='round';rr(c,r.x+8,y0-6,r.w-16,r.y+r.h-34-y0+6,10);c.stroke()}
vessel('paper',{custom:paper});
/* zbiornik cząsteczek: gaz / ciecz / ciało stałe; geometria z CHE.MOLECULE gdy dostępna, inaczej mała tabela */
const ELC={H:'#f1f5f9',C:'#334155',N:'#3b82f6',O:'#ef4444',F:'#22c55e',Cl:'#22c55e',S:'#eab308',P:'#f97316',Na:'#a855f7',K:'#c084fc',Ca:'#fb923c',Mg:'#10b981',Cu:'#f59e0b',Fe:'#78716c',Zn:'#94a3b8',Ag:'#cbd5e1'},ELR={H:.5,C:.78,N:.72,O:.68,F:.58,Cl:.99,S:1.05,P:1.08};
const MOLS={H2O:[['O',0,0],['H',-.8,.6],['H',.8,.6]],CO2:[['C',0,0],['O',-1.2,0],['O',1.2,0]],H2:[['H',-.37,0],['H',.37,0]],O2:[['O',-.6,0],['O',.6,0]],N2:[['N',-.55,0],['N',.55,0]],NH3:[['N',0,0],['H',-.85,.6],['H',.85,.6],['H',0,-.95]],CH4:[['C',0,0],['H',-.8,-.8],['H',.8,-.8],['H',-.8,.8],['H',.8,.8]],HCl:[['H',-.6,0],['Cl',.6,0]],Na:[['Na',0,0]],Cl:[['Cl',0,0]]};
function molAtoms(id){if(MOLS[id])return MOLS[id];try{const M=C.MOLECULE&&C.MOLECULE.get&&C.MOLECULE.get(id);if(M&&M.atoms&&M.atoms.length){let mx=0,my=0;M.atoms.forEach(a=>{mx+=+a.x||0;my+=+a.y||0});mx/=M.atoms.length;my/=M.atoms.length;return MOLS[id]=M.atoms.map(a=>[a.element||a.symbol||'C',(+a.x||0)-mx,(+a.y||0)-my])}}catch(_){}return MOLS.H2O}
function molTank(c,r,st,env){const T=env.th,pool=env.pool,mt=pool.mt=pool.mt||{list:[]},dt=Math.min(.05,env.dt||.016),ph=st.phase||'gas',sp=Math.sqrt(Math.max(.05,((st.T==null?25:st.T)+273)/298)),bx=r.x+6,bw=r.w-12,by=r.y+8,bh=r.h-14,spec=st.mol||[{id:'H2O',n:10}];
const want={};let N=0;spec.forEach(s=>{want[s.id]=(want[s.id]||0)+s.n;N+=s.n});const cnt={};
mt.list=mt.list.filter(p=>{if(!(p.id in want))return false;cnt[p.id]=(cnt[p.id]||0)+1;return cnt[p.id]<=want[p.id]});
Object.keys(want).forEach(id=>{for(let i=(cnt[id]||0);i<want[id];i++)mt.list.push({id,x:bx+Math.random()*bw,y:by+Math.random()*bh,vx:(Math.random()-.5)*60,vy:(Math.random()-.5)*60,a:Math.random()*6.28,w:(Math.random()-.5)*2})});
const s=Math.max(6,Math.min(15,Math.sqrt(bw*bh/Math.max(N,1))/3.3)),k=mt.list.length,cols=Math.max(1,Math.ceil(Math.sqrt(k*bw/Math.max(1,bh*.55)))),rows=Math.max(1,Math.ceil(k/cols));
if(ph==='liquid'){c.fillStyle=rgba(st.liquid||[205,228,238],.3);c.fillRect(bx,by+bh*.4,bw,bh*.6)}
mt.list.forEach((p,i)=>{if(ph==='solid'){const cw=bw/cols,ch=Math.min(cw,bh*.6/rows),t=env.t||0;p.x=bx+cw*(i%cols+.5)+Math.sin(t/90*sp+i*1.7)*1.4*sp;p.y=by+bh-ch*(Math.floor(i/cols)+.5)-2+Math.cos(t/110*sp+i*2.3)*1.4*sp;return}
const v0=(ph==='gas'?70:26)*sp,top=ph==='gas'?by:by+bh*.4;p.vx+=(Math.random()-.5)*v0*dt*8;p.vy+=(Math.random()-.5)*v0*dt*8+(ph==='liquid'?120*dt:0);const v=Math.hypot(p.vx,p.vy),mx=v0*(ph==='gas'?2.2:1.6);if(v>mx){p.vx*=mx/v;p.vy*=mx/v}
p.x+=p.vx*dt;p.y+=p.vy*dt;p.a+=p.w*dt*(ph==='gas'?3:1);const m=s*1.2;if(p.x<bx+m){p.x=bx+m;p.vx=Math.abs(p.vx)}if(p.x>bx+bw-m){p.x=bx+bw-m;p.vx=-Math.abs(p.vx)}if(p.y<top+m){p.y=top+m;p.vy=Math.abs(p.vy)}if(p.y>by+bh-m){p.y=by+bh-m;p.vy=-Math.abs(p.vy)}});
mt.list.forEach(p=>{const at=molAtoms(p.id),cs=Math.cos(p.a),sn=Math.sin(p.a),pts=at.map(a=>[p.x+(a[1]*cs-a[2]*sn)*s,p.y+(a[1]*sn+a[2]*cs)*s,a[0]]);
c.strokeStyle=T.dark?'#94a3b8':'#64748b';c.lineWidth=Math.max(1.5,s*.22);c.lineCap='round';
for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j];if(Math.hypot(a[0]-b[0],a[1]-b[1])<((ELR[a[2]]||.8)+(ELR[b[2]]||.8))*1.25*s){c.beginPath();c.moveTo(a[0],a[1]);c.lineTo(b[0],b[1]);c.stroke()}}
pts.forEach(q=>{c.fillStyle=ELC[q[2]]||'#a1a1aa';c.beginPath();c.arc(q[0],q[1],(ELR[q[2]]||.8)*s*.62,0,7);c.fill();c.strokeStyle='rgba(0,0,0,.35)';c.lineWidth=1;c.stroke()})});
c.strokeStyle=T.glass;c.lineWidth=4;c.lineJoin='round';rc(c,r.x+2,r.y+4,r.w-4,r.h-8,14);c.stroke();
c.fillStyle=T.mut;c.font='600 10px Inter,system-ui';c.textAlign='left';c.fillText(spec.map(q=>q.id+'×'+q.n).join('  ')+' · '+({gas:'gaz',liquid:'ciecz',solid:'ciało stałe'}[ph]||ph),r.x+10,r.y+r.h-12)}
vessel('molTank',{custom:molTank});


/* --- BARWY: jedno źródło (CHE.COLORS), z zapasem gdy go brak --- */
const colors={water:()=>{const K=C.COLORS;return K&&K.water?K.water.slice():WATER.slice()},at:(id,p)=>{const K=C.COLORS;try{return K&&K.at?K.at(id,p):null}catch(_){return null}},rgb:h=>{const K=C.COLORS;if(Array.isArray(h))return h.slice();if(K&&K.rgb)try{return K.rgb(h)}catch(_){}return WATER.slice()},mix:(a,b,t)=>a.map((v,i)=>Math.round(v+(b[i]-v)*Math.max(0,Math.min(1,t))))};
/* --- ADAPTER REAKCJI: spec widoku (out:[gaz|osad|barwa], colId, l0/l1, ppt, fumes, solid) + postęp p → stan GFX --- */
function fromReaction(sp,p,extra){sp=sp||{};p=Math.max(0,Math.min(1,p||0));const e=p*p*(3-2*p),out=sp.out||[],has=k=>out.indexOf(k)>=0,l0=sp.l0?colors.rgb(sp.l0):colors.water();let liq=sp.l1?colors.mix(l0,colors.rgb(sp.l1),e):l0;
if(has('barwa')){const c=colors.at(sp.colId||'ion-cu2');if(c)liq=colors.mix(liq,colors.rgb(c),.45*e)}
const ppts=[],pc=sp.pptCol||(has('osad')||sp.ppt?colors.at(sp.ppt||'ppt-agcl'):null);if(pc)ppts.push({col:colors.rgb(pc),eq:2.6*Math.max(0,(p-.25)/.75),metal:false});
const solids=sp.solid?[{col:colors.rgb(sp.solid.col),eq:(sp.solid.eq||4)*(1-e*(1-(sp.solid.end||0))),t:sp.solid.t||'metal'}]:[];
const env=Math.max(0,Math.min(1,Math.sin(p*Math.PI*.9)+.15))*(p>=1?0:1),plume=sp.solid&&sp.l1&&p>0&&p<1?{col:colors.rgb(sp.l1),k:Math.sin(p*Math.PI)}:null;
return Object.assign({liquid:liq,level:sp.level||.78,ppts,solids,plume,gas:has('gaz')&&p>0?env:0,foam:sp.foam&&p>0?env*.9:0,bubSize:sp.bubSize||1,bubN:sp.bubN||1,fumes:sp.fumes&&p>0&&p<1.01?Math.min(1,p*4):0,fumeColor:sp.fumeColor||null,heat:sp.heat&&p>0&&p<1?sp.heat:0,pop:pc?Math.min(1,p*3)*(1-.55*p):0,T:sp.T==null?25:sp.T},extra||{})}
/* --- RYSOWANIE W GOTOWYM PŁÓTNIE (widoki z M.add: ctx,w,h,czas[s]) --- */
const CP=new WeakMap();
function canvasDraw(ctx,w,h,time,st,o){o=o||{};const key=ctx.canvas||ctx,P=CP.get(key)||{pool:{},last:time};CP.set(key,P);const dt=Math.min(.05,Math.max(0,time-P.last));P.last=time;const r=o.rect||{x:w*.18,y:55,w:w*.64,h:h-88};draw(o.vessel||'beaker',ctx,r,st,{t:time*1000,dt,pool:P.pool,only:o.only,opt:{effects:o.effects}});return r}
return{version:'1.4',colors,fromReaction,canvasDraw,trigger,optionsPanel,presets:PRESETS,flameColors:FLAME_COLORS,flameNames:FLAME_NAMES,metals:METALS,effects:{register:effect,get:id=>E[id]||null,list:()=>Object.keys(E),options:id=>E[id]?{label:E[id].label||id,defaults:E[id].defaults||{},schema:E[id].schema||{},free:!!E[id].free,oneShot:!!E[id].oneShot}:null},vessels:{register:vessel,get:id=>V[id]||null,list:()=>Object.keys(V)},draw,mount,mountEffect,fromLab,theme:th,tempColor:tc,rgba}})();
C.LAB.GFX=GFX;
/* ===== CHE.LAB.LIBRARY v1.0 — katalog elementów: naczynia, przyrządy, aparatura, efekty (jedno źródło GFX) ===== */
(function(){
const GF=C.LAB.GFX;
const META={beaker:['Zlewka','naczynie','Uniwersalna; wszystkie efekty cieczy'],flask:['Kolba stożkowa','naczynie','Kolba Erlenmeyera'],testTube:['Probówka','naczynie','Pojedynczy test'],cylinder:['Cylinder miarowy','naczynie','Pomiar objętości'],roundFlask:['Kolba okrągłodenna','naczynie','Ogrzewanie, destylacja'],volFlask:['Kolba miarowa','naczynie','Kreska miarowa; roztwory o znanym stężeniu'],funnel:['Lejek','naczynie','Sączenie, przelewanie'],petri:['Szalka Petriego','naczynie','Płytka: krystalizacja, reakcje na szkle'],evapDish:['Parownica','naczynie','Odparowanie, krystalizacja'],molTank:['Zbiornik cząsteczek','naczynie','Cząsteczki: gaz / ciecz / ciało stałe; geometria z CHE.MOLECULE'],burette:['Biureta','przyrząd','st.titrant {V,Vmax,drip,color}'],pipette:['Pipeta','przyrząd','st.pip {lv,drip,color}'],pHmeter:['pH-metr cyfrowy','przyrząd','st.pH, st.T'],paper:['Papierki wskaźnikowe','przyrząd','Kolory z CHE.COLORS; st.pH, st.dip, st.fresh'],thermometer:['Termometr','przyrząd','st.T'],balance:['Waga','przyrząd','st.mass'],burner:['Palnik Bunsena','aparatura','Płomień: st.fx.flame'],cooler:['Chłodnica Liebiga','aparatura','st.coolant {Tin,Tout,flow,q}'],stage:['Podstawa / scena','aparatura','Kotwica dla efektów swobodnych']};
const CSS='.cl-nav{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 10px}.cl-nav button,.cl-btn{border:1px solid var(--border,#e2e8f0);background:var(--panel,#fff);color:inherit;padding:6px 11px;border-radius:999px;font:inherit;font-size:13px;cursor:pointer}.cl-nav button.on{background:#2563eb;color:#fff;border-color:#2563eb}.cl-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}.cl-card{border:1px solid var(--border,#e2e8f0);border-radius:12px;padding:10px;background:var(--panel,#fff)}.cl-card h3{margin:0;font-size:14px}.cl-card code{font-size:11px;opacity:.65}.cl-tag{font-size:10px;padding:1px 7px;border-radius:99px;background:rgba(100,116,139,.15);margin-right:4px}.cl-d{margin:4px 0 6px;font-size:12px;opacity:.75}.cl-ctl{display:grid;gap:3px;margin-top:6px;font-size:12px}.cl-ctl label{display:grid;grid-template-columns:70px 1fr auto;gap:6px;align-items:center}.cl-sel{margin-top:6px;margin-right:6px}';
const H={cooler:150,balance:170,paper:270,molTank:230,petri:140,evapDish:160,funnel:220,pipette:230};
const SETS={'H₂O':[{id:'H2O',n:14}],'CO₂ + H₂':[{id:'CO2',n:8},{id:'H2',n:8}],'NH₃':[{id:'NH3',n:12}],'CH₄ + O₂':[{id:'CH4',n:6},{id:'O2',n:10}],'HCl + H₂O':[{id:'HCl',n:6},{id:'H2O',n:12}]};
const ce=(t,cls,txt)=>{const e=document.createElement(t);if(cls)e.className=cls;if(txt!=null)e.textContent=txt;return e};
function demo(id){const s={liquid:[205,228,238],level:.6,T:25,heat:0,gas:0,pop:0,pH:4.2,mass:12.34,dip:0,fresh:0,titrant:{V:18,Vmax:50,drip:.6,color:[205,228,238]},pip:{lv:.6,drip:0,color:[205,228,238]},flame:{air:100},coolant:{Tin:15,Tout:28,flow:.0005,q:50},phase:'gas',mol:SETS['H₂O']};const m=META[id];if(m&&m[1]==='naczynie'&&id!=='molTank'){s.gas=.5;s.T=60}if(id==='burner')s.fx={flame:true};return s}
function range(c,l,min,max,step,v,fn){const w=ce('div','cl-ctl'),lb=ce('label'),i=ce('input'),o=ce('output',null,v);i.type='range';i.min=min;i.max=max;i.step=step;i.value=v;i.oninput=()=>{o.textContent=i.value;fn(+i.value)};lb.append(ce('span',null,l),i,o);w.appendChild(lb);c.appendChild(w)}
function btn(c,t,fn){const b=ce('button','cl-btn',t);b.type='button';b.style.marginTop='6px';b.style.marginRight='6px';b.onclick=fn;c.appendChild(b)}
function sel(c,opts,fn){const s=ce('select','cl-sel');opts.forEach(([v,t])=>{const o=ce('option',null,t);o.value=v;s.appendChild(o)});s.onchange=()=>fn(s.value);c.appendChild(s)}
function ctl(c,id,st){
if(id==='pHmeter'||id==='paper')range(c,'pH',0,14,.1,st.pH,v=>st.pH=v);
if(id==='paper'){btn(c,'Zanurz / wyjmij',()=>{st.dip=st.dip?0:1});btn(c,'Nowe papierki',()=>{st.fresh++;st.dip=0})}
if(id==='thermometer')range(c,'T °C',-20,120,1,st.T,v=>st.T=v);
if(id==='burette')range(c,'V cm³',0,50,.5,st.titrant.V,v=>st.titrant.V=v);
if(id==='pipette')range(c,'poziom',0,1,.01,st.pip.lv,v=>st.pip.lv=v);
if(id==='balance')range(c,'masa g',0,200,.01,st.mass,v=>st.mass=v);
if(id==='molTank'){sel(c,[['gas','gaz'],['liquid','ciecz'],['solid','ciało stałe']],v=>st.phase=v);sel(c,Object.keys(SETS).map(k=>[k,k]),v=>st.mol=SETS[v]);range(c,'T °C',-50,600,5,25,v=>st.T=v)}}
function mount(host,opt){opt=opt||{};if(!document.getElementById('che-lib-css')){const s=ce('style');s.id='che-lib-css';s.textContent=CSS;document.head.appendChild(s)}
const root=ce('div'),nav=ce('div','cl-nav'),main=ce('div');root.append(nav,main);host.appendChild(root);let cards=[];
const clear=()=>{cards.forEach(m=>m.destroy&&m.destroy());cards=[];main.innerHTML=''};
const card=(g,title,id,tags,desc)=>{const c=ce('div','cl-card');c.appendChild(ce('h3',null,title));c.appendChild(ce('code',null,id+' '));tags.forEach(t=>c.appendChild(ce('span','cl-tag',t)));c.appendChild(ce('div','cl-d',desc));g.appendChild(c);return c};
function tabV(g,kind){GF.vessels.list().forEach(id=>{const m=META[id]||[id,'aparatura',''];if(m[1]!==kind)return;const c=card(g,m[0],'GFX.vessels · '+id,[m[1]],m[2]),st=demo(id);cards.push(GF.mount(c,{vessel:id,height:H[id]||210,get:()=>st}));ctl(c,id,st)})}
function tabE(g,free){GF.effects.list().forEach(id=>{const f=GF.effects.get(id);if(!!f.free!==free)return;const c=card(g,f.label||id,'GFX.effects · '+id,[f.free?'swobodny':'w naczyniu','warstwa: '+f.layer],f.free?'Rysowany nad sceną; st.fx / GFX.trigger':'Rysowany w naczyniu; stan z st.*'),
st=Object.assign(demo('beaker'),{gas:1,heat:3,fumes:1,T:95,foam:.6}),only=f.free?[id]:['liquid','meniscus',id],vs=f.free?'stage':(f.vessels?f.vessels[0]:'beaker');if(f.free)st.fx={[id]:true};
const m=GF.mount(c,{vessel:vs,height:200,get:()=>st,only,fx:f.free?{[id]:true}:null});cards.push(m);
if(f.free&&f.oneShot)btn(c,'Uruchom',()=>m.trigger(id,{}));
if(f.schema&&Object.keys(f.schema).length){const o=ce('div','cl-ctl'),fxo={};c.appendChild(o);GF.optionsPanel(o,id,fxo,()=>{st.fx=Object.assign({},st.fx,{[id]:Object.assign({},fxo)})})}})}
const TABS={'Naczynia':g=>tabV(g,'naczynie'),'Przyrządy':g=>tabV(g,'przyrząd'),'Aparatura':g=>tabV(g,'aparatura'),'Efekty (ciecz)':g=>tabE(g,false),'Efekty (swobodne)':g=>tabE(g,true)};
function show(n){clear();const g=ce('div','cl-grid');main.appendChild(g);TABS[n](g);[].forEach.call(nav.children,b=>b.classList.toggle('on',b.textContent===n))}
Object.keys(TABS).forEach(n=>{const b=ce('button',null,n);b.type='button';b.onclick=()=>show(n);nav.appendChild(b)});
show(opt.tab||'Naczynia');return{show,destroy:clear}}
C.LAB.LIBRARY={version:'1.0',mount,meta:META,sets:SETS};
})();
/* ===== /CHE.LAB.LIBRARY ===== */
