/* ===== CHE.LAB.GFX v1.6 — wspólny zestaw wizualizacji: naczynia + przyrządy + aparatura + efekty + zestawy (sceny) =====
   Każdy element działa osobno (GFX.mount / GFX.draw) lub razem (GFX.mount z parts / GFX.scene).
   Rozszerzanie: GFX.effects.register(id,{layer:'back|in|front',vessels?,draw(e)}) · GFX.vessels.register(id,{path|custom,hmax,pad,rim,shadow,mat})
                 GFX.scenes.register(id,{label,parts,links,init,tick,ui,overlay}).
   v1.6: fizyka zjawisk z CHE.PHYS (płomień, wrzenie, pęcherzyki, osady, kierunek oparów) + GFX.rx (rejestr wyglądu reakcji).
   Zgodność: API v1.4 bez zmian (draw, mount, mountEffect, fromLab, fromReaction, canvasDraw, trigger, presets…).
   Zależności z zakresu nadrzędnego: g (window), C (CHE), clamp, pH(S), liquidColor(S), WATER. */
const GFX=(function(){
const E={},V={},SC={};
const rnd=i=>{const x=Math.sin(i*127.1)*43758.5453;return x-Math.floor(x)};
const rgba=(c,a)=>'rgba('+(c[0]|0)+','+(c[1]|0)+','+(c[2]|0)+','+(a==null?1:a)+')';
const cl01=v=>Math.max(0,Math.min(1,v));
const th=()=>{const a=document.documentElement.getAttribute('data-theme'),d=a?a==='dark':!!(g.matchMedia&&g.matchMedia('(prefers-color-scheme: dark)').matches);
 return{dark:d,glass:d?'#94a3b8':'#64748b',glassHi:d?'rgba(226,232,240,.28)':'rgba(255,255,255,.85)',tint:d?'rgba(148,163,184,.07)':'rgba(190,214,232,.18)',text:d?'#e2e8f0':'#1e293b',mut:d?'#94a3b8':'#64748b',hi:'rgba(255,255,255,.5)',metal:d?'#475569':'#94a3b8',metalD:d?'#334155':'#64748b',metalL:d?'#64748b':'#cbd5e1',shadow:d?'rgba(0,0,0,.35)':'rgba(15,23,42,.13)',bg:d?'#0b1220':'#f1f5f9',paper:d?'#1e293b':'#ffffff',wood:d?'#7c5a3a':'#b08154'}};
const tc=T=>{const k=Math.max(0,Math.min(1,(T-10)/80));return[60+k*195,150-k*40,235-k*195]};
function effect(id,def){E[id]=Object.assign({id,layer:'in',portable:true,independent:true},def);if(C.LAB.VISUALS&&C.LAB.VISUALS.effectRegistry)C.LAB.VISUALS.effectRegistry[id]={id,portable:true,independent:true,enabledByDefault:true};return E[id]}
function vessel(id,def){V[id]=Object.assign({id,hmax:1,pad:0,lw:4},def);return V[id]}
const rr=(c,x,y,w,h,r)=>{c.beginPath();if(c.roundRect)c.roundRect(x,y,w,h,r);else c.rect(x,y,w,h)};
const fmt=(x,n)=>(+x).toFixed(n).replace('.',',');
const font=(c,w,s,m)=>{c.font=w+' '+s+'px '+(m?'ui-monospace,monospace':'Inter,system-ui,sans-serif')};
const txt=(c,s,x,y,col,al,sz,w)=>{c.fillStyle=col;c.textAlign=al||'left';font(c,w||600,sz||11);c.fillText(s,x,y)};

/* ===================== NACZYNIA (path → działają wszystkie efekty cieczy) ===================== */
const rc=(c,x,y,w,h,r)=>{c.beginPath();c.moveTo(x,y);c.lineTo(x,y+h-r);c.quadraticCurveTo(x,y+h,x+r,y+h);c.lineTo(x+w-r,y+h);c.quadraticCurveTo(x+w,y+h,x+w,y+h-r);c.lineTo(x+w,y)};
vessel('beaker',{path:(c,r)=>{c.beginPath();c.moveTo(r.x-7,r.y-3);c.quadraticCurveTo(r.x,r.y-1,r.x,r.y+9);c.lineTo(r.x,r.y+r.h-16);c.quadraticCurveTo(r.x,r.y+r.h,r.x+16,r.y+r.h);c.lineTo(r.x+r.w-16,r.y+r.h);c.quadraticCurveTo(r.x+r.w,r.y+r.h,r.x+r.w,r.y+r.h-16);c.lineTo(r.x+r.w,r.y)},hmax:1,rim:r=>[r.x,r.x+r.w,r.y,1],shadow:1,scale:{max:250,step:50,minor:25,x:.68}});
vessel('testTube',{path:(c,r)=>{const w=Math.min(r.w,70),x=r.x+(r.w-w)/2;c.beginPath();c.moveTo(x,r.y);c.lineTo(x,r.y+r.h-w/2);c.arc(x+w/2,r.y+r.h-w/2,w/2,Math.PI,0,true);c.lineTo(x+w,r.y)},hmax:.8,pad:2,rim:r=>{const w=Math.min(r.w,70),x=r.x+(r.w-w)/2;return[x,x+w,r.y]},lw:3});
vessel('cylinder',{path:(c,r)=>{const w=Math.min(r.w,90),x=r.x+(r.w-w)/2;rc(c,x,r.y,w,r.h-9,5)},hmax:.86,pad:11,rim:r=>{const w=Math.min(r.w,90),x=r.x+(r.w-w)/2;return[x,x+w,r.y]},shadow:1,scale:{max:100,step:20,minor:5,x:.5},
 deco:(c,r,T)=>{const w=Math.min(r.w,90),x=r.x+(r.w-w)/2,b=r.y+r.h;c.fillStyle=T.tint;c.strokeStyle=T.glass;c.lineWidth=2.5;c.beginPath();c.moveTo(x-14,b);c.lineTo(x-6,b-9);c.lineTo(x+w+6,b-9);c.lineTo(x+w+14,b);c.closePath();c.fill();c.stroke()}});
vessel('flask',{path:(c,r)=>{const cx=r.x+r.w/2,n=Math.min(r.w*.16,30),sh=r.y+r.h*.34;c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,sh);c.lineTo(r.x+r.w*.06,r.y+r.h-14);c.quadraticCurveTo(r.x+r.w*.06,r.y+r.h,r.x+r.w*.06+14,r.y+r.h);c.lineTo(r.x+r.w*.94-14,r.y+r.h);c.quadraticCurveTo(r.x+r.w*.94,r.y+r.h,r.x+r.w*.94,r.y+r.h-14);c.lineTo(cx+n,sh);c.lineTo(cx+n,r.y)},hmax:.6,pad:2,rim:r=>{const cx=r.x+r.w/2,n=Math.min(r.w*.16,30);return[cx-n,cx+n,r.y]},shadow:1,labelY:.78});
vessel('roundFlask',{path:(c,r)=>{const cx=r.x+r.w/2,n=Math.min(r.w*.12,22),R=Math.max(n*2,Math.min(r.w*.46,r.h*.36)),cy=r.y+r.h-R-2,h=Math.sqrt(R*R-n*n),d=Math.atan2(h,n);c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,cy-h);c.arc(cx,cy,R,Math.PI+d,-d,true);c.lineTo(cx+n,r.y)},hmax:.62,pad:2,rim:r=>{const cx=r.x+r.w/2,n=Math.min(r.w*.12,22);return[cx-n,cx+n,r.y]},labelY:.72});
vessel('volFlask',{path:(c,r)=>{const cx=r.x+r.w/2,n=r.w*.07,sh=r.y+r.h*.42,L=r.x+r.w*.04,R=r.x+r.w*.96,b=r.y+r.h;c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,sh);c.bezierCurveTo(cx-n,sh+r.h*.12,L,sh+r.h*.08,L,b-26);c.quadraticCurveTo(L,b,L+22,b);c.lineTo(R-22,b);c.quadraticCurveTo(R,b,R,b-26);c.bezierCurveTo(R,sh+r.h*.08,cx+n,sh+r.h*.12,cx+n,sh);c.lineTo(cx+n,r.y)},hmax:.84,pad:2,rim:r=>{const cx=r.x+r.w/2,n=r.w*.07;return[cx-n,cx+n,r.y]},shadow:1,labelY:.8});
vessel('funnel',{path:(c,r)=>{const cx=r.x+r.w/2;c.beginPath();c.moveTo(r.x+r.w*.08,r.y);c.lineTo(cx-4,r.y+r.h*.55);c.lineTo(cx-4,r.y+r.h);c.lineTo(cx+4,r.y+r.h);c.lineTo(cx+4,r.y+r.h*.55);c.lineTo(r.x+r.w*.92,r.y)},hmax:.9,pad:2,rim:r=>[r.x+r.w*.08,r.x+r.w*.92,r.y],lw:3});
vessel('petri',{path:(c,r)=>{const y0=r.y+r.h*.7;rc(c,r.x+r.w*.04,y0,r.w*.92,r.y+r.h-y0-2,8)},hmax:.26,pad:2,shadow:1,lw:3});
vessel('evapDish',{path:(c,r)=>{const x0=r.x+r.w*.08,x1=r.x+r.w*.92,y0=r.y+r.h*.5,yb=r.y+r.h;c.beginPath();c.moveTo(x0,y0);c.bezierCurveTo(x0,yb,x1,yb,x1,y0)},hmax:.45,pad:2,mat:'porcelain',rim:r=>[r.x+r.w*.08,r.x+r.w*.92,r.y+r.h*.5],shadow:1});
vessel('crucible',{path:(c,r)=>{const w=Math.min(r.w,r.h*1.1),x=r.x+(r.w-w)/2,y=r.y+r.h*.18,b=r.y+r.h;c.beginPath();c.moveTo(x,y);c.lineTo(x+w*.17,b-10);c.quadraticCurveTo(x+w*.2,b,x+w*.3,b);c.lineTo(x+w*.7,b);c.quadraticCurveTo(x+w*.8,b,x+w*.83,b-10);c.lineTo(x+w,y)},hmax:.75,pad:1,mat:'porcelain',shadow:1,
 rim:r=>{const w=Math.min(r.w,r.h*1.1),x=r.x+(r.w-w)/2;return[x,x+w,r.y+r.h*.18]},
 deco:(c,r,T,st)=>{if(!st.lid)return;const w=Math.min(r.w,r.h*1.1),x=r.x+(r.w-w)/2,y=r.y+r.h*.18;c.fillStyle=T.dark?'#cbd5e1':'#f8fafc';c.strokeStyle=T.glass;c.lineWidth=2.5;c.beginPath();c.moveTo(x-6,y-1);c.quadraticCurveTo(x+w/2,y-r.h*.16,x+w+6,y-1);c.closePath();c.fill();c.stroke();rr(c,x+w/2-6,y-r.h*.16,12,7,3);c.fill();c.stroke()}});
vessel('watchGlass',{path:(c,r)=>{const x0=r.x+r.w*.04,x1=r.x+r.w*.96,y0=r.y+r.h*.55;c.beginPath();c.moveTo(x0,y0);c.quadraticCurveTo(r.x+r.w/2,r.y+r.h*1.02,x1,y0)},hmax:.2,pad:r=>r.h*.22,lw:3,shadow:1});
/* wkraplacz (rozdzielacz): gruszka + kranik + nóżka; ciecz tylko w gruszce (pad = nóżka) */
const dfG=r=>{const cx=r.x+r.w/2,n=Math.min(r.w*.08,8),R=Math.min(r.w*.42,r.h*.22),yb=r.y+r.h*.62,yt=r.y+r.h*.1,cy=yb-R*1.15;return{cx,n,R,yb,yt,cy}};
vessel('dropFunnel',{path:(c,r)=>{const{cx,n,R,yb,yt,cy}=dfG(r);c.beginPath();c.moveTo(cx-n,r.y);c.lineTo(cx-n,yt);c.bezierCurveTo(cx-n,yt+R*.5,cx-R,cy-R*.7,cx-R,cy);c.bezierCurveTo(cx-R,cy+R*.85,cx-5,yb-8,cx-3,yb);c.lineTo(cx-3,r.y+r.h);c.lineTo(cx+3,r.y+r.h);c.lineTo(cx+3,yb);c.bezierCurveTo(cx+5,yb-8,cx+R,cy+R*.85,cx+R,cy);c.bezierCurveTo(cx+R,cy-R*.7,cx+n,yt+R*.5,cx+n,yt);c.lineTo(cx+n,r.y)},
 hmax:.5,pad:r=>r.h*.38,lw:3,rim:r=>{const{cx,n}=dfG(r);return[cx-n,cx+n,r.y]},hl:.3});

/* ===================== EFEKTY W NACZYNIU (kolejność rejestracji = kolejność rysowania w warstwie) ===================== */
effect('heatGlow',{layer:'back',label:'Poświata cieplna',defaults:{color:null},schema:{color:{t:'color',l:'Barwa poświaty'}},draw:e=>{const s=e.st;const gc=e.o.color||[255,140,40];if(!(s.heat>0))return;const c=e.c;c.save();c.shadowColor=rgba(gc,Math.min(1,s.heat/2));c.shadowBlur=26;e.path();c.strokeStyle=rgba(gc,.8);c.lineWidth=6;c.stroke();c.restore()}});
/* ciecz: menisk wklęsły, falowanie, wir od mieszadła, cieniowanie walca */
effect('liquid',{label:'Ciecz',draw:e=>{const c=e.c,r=e.r,col=e.st.liquid||[205,228,238];if(e.top>=e.bot-.5)return;const g1=c.createLinearGradient(0,e.top,0,e.bot);g1.addColorStop(0,rgba(col,.6));g1.addColorStop(1,rgba(col.map(v=>v*.84),.84));
 const poly=()=>{c.beginPath();c.moveTo(r.x-8,e.bot+2);c.lineTo(r.x-8,e.surf(r.x));for(let x=0;x<=r.w;x+=4)c.lineTo(r.x+x,e.surf(r.x+x));c.lineTo(r.x+r.w+8,e.surf(r.x+r.w));c.lineTo(r.x+r.w+8,e.bot+2);c.closePath()};
 poly();c.fillStyle=g1;c.fill();const g2=c.createLinearGradient(r.x,0,r.x+r.w,0);g2.addColorStop(0,'rgba(0,0,0,.10)');g2.addColorStop(.22,'rgba(0,0,0,0)');g2.addColorStop(.62,'rgba(255,255,255,.07)');g2.addColorStop(1,'rgba(0,0,0,.12)');c.fillStyle=g2;poly();c.fill()}});
effect('meniscus',{label:'Menisk',draw:e=>{if(e.top>=e.bot-1)return;const c=e.c,r=e.r;c.beginPath();for(let x=0;x<=r.w;x+=4){const y=e.surf(r.x+x);x?c.lineTo(r.x+x,y):c.moveTo(r.x,y)}c.strokeStyle='rgba(255,255,255,.6)';c.lineWidth=1.6;c.stroke();c.globalAlpha=.35;c.translate(0,3);c.stroke();c.translate(0,-3);c.globalAlpha=1}});
/* osad: warstwa z fakturą + opadające płatki po wytrąceniu */
/* v1.6: pokrój osadu z CHE.PHYS.ppt(id): serowaty (AgCl) · kłaczkowaty (wodorotlenki) · krystaliczny · drobny (mleczny, długo opada) */
const PPT_LOOK={serowaty:{per:1800,n:22,a:2.6,b:2.2,haze:.28,al:.85},'kłaczkowaty':{per:4200,n:18,a:4.5,b:3.2,haze:.36,al:.5},krystaliczny:{per:1300,n:30,a:1.4,b:1.4,haze:.14,al:.95,cr:1},drobny:{per:6500,n:60,a:1,b:1,haze:.46,al:.7}};
effect('precipitate',{label:'Osad',draw:e=>{const c=e.c,r=e.r,pop=e.st.pop||0;let p=0;(e.st.ppts||[]).forEach((q,qi)=>{const hb=q.habit||(q.id&&C.PHYS?C.PHYS.ppt(q.id).habit:null),L=PPT_LOOK[hb]||{per:2600,n:28,a:2,b:1.2,haze:.32,al:.75};if(!q.metal&&pop>0){c.fillStyle=rgba(q.col,L.haze*Math.min(1,pop));c.fillRect(r.x,e.top,r.w,e.bot-e.top);
  for(let i=0;i<L.n;i++){const u=((e.t/L.per)+rnd(i+qi*40))%1,y=e.top+(e.bot-e.top)*u,x=r.x+6+rnd(i+7)*(r.w-12)+Math.sin(e.t/500+i)*3;c.fillStyle=rgba(q.col.map(v=>v*.88),L.al*pop);c.beginPath();if(L.cr){c.save();c.translate(x,y);c.rotate(rnd(i+9)*3+e.t/900);c.rect(-L.a,-L.a,L.a*2,L.a*2);c.restore()}else c.ellipse(x,y,L.a+rnd(i)*L.a*.8,L.b+rnd(i+3)*L.b*.5,rnd(i+9)*3,0,7);c.fill();if(L.cr&&rnd(i+e.t/400|0)>.85){c.fillStyle='rgba(255,255,255,.8)';c.fillRect(x-.5,y-.5,1.2,1.2)}}}
 if(q.eq<=.02)return;const hh=Math.max(4,Math.min(34,q.eq*7)),yb=e.bot-p,yt=yb-hh;c.fillStyle=rgba(q.col,q.metal?.95:.92);c.beginPath();c.moveTo(r.x,yb+2);c.lineTo(r.x,yt);for(let x=0;x<=r.w;x+=6)c.lineTo(r.x+x,yt+Math.sin(x*.21+qi)*1.6+rnd(x+qi)*1.4);c.lineTo(r.x+r.w,yb+2);c.closePath();c.fill();
 c.fillStyle=rgba(q.col.map(v=>v*.78),.55);for(let i=0;i<Math.min(40,r.w/4);i++){c.fillRect(r.x+rnd(i+qi*9)*r.w,yt+3+rnd(i+30)*(hh-4),1.6,1.6)}p+=hh});e.ph=p}});
effect('plume',{draw:e=>{const p=e.st.plume;if(!p||p.k<=.02)return;const c=e.c,r=e.r,cx=r.x+r.w/2,cy=e.bot-(e.ph||0)-22,rad=Math.max(24,r.w*.22)*(1+p.k*.8),g=c.createRadialGradient(cx,cy-rad*.2,2,cx,cy-rad*.2,rad);g.addColorStop(0,rgba(p.col,.55*p.k));g.addColorStop(1,rgba(p.col,0));c.fillStyle=g;c.fillRect(cx-rad,cy-rad*1.3,rad*2,rad*2.1)}});
/* mętnienie (np. woda wapienna + CO2, S z tiosiarczanu) */
effect('turbidity',{label:'Zmętnienie',defaults:{color:null},schema:{color:{t:'color',l:'Barwa zawiesiny'}},draw:e=>{const k=cl01(e.st.turb||0);if(k<=.01||e.top>=e.bot)return;const c=e.c,r=e.r,col=e.o.color||e.st.turbCol||[244,244,238];c.fillStyle=rgba(col,.62*k);c.fillRect(r.x-8,e.top,r.w+16,e.bot-e.top+2);
 c.fillStyle=rgba(col.map(v=>v*.9),.8*k);for(let i=0;i<60;i++){const y=e.top+((rnd(i+3)+e.t/9000*(1+rnd(i)))%1)*(e.bot-e.top);c.fillRect(r.x+rnd(i)*r.w+Math.sin(e.t/700+i)*2,y,1.5,1.5)}}});
/* ciała stałe: pasek metalu / granulki / kawałki (marmur) / proszek; pozycje → źródła bąbelków */
const shapeOf=s=>s.shape||(s.t==='metal'?'strip':'chips');
effect('solids',{label:'Ciała stałe',draw:e=>{const c=e.c,r=e.r,pos=e.pool.solPos=[];let sx=r.x+r.w*.18;(e.st.solids||[]).forEach((s,si)=>{if(s.eq<=.02)return;const k=Math.max(.15,Math.min(1,s.eq/4)),sh=shapeOf(s),col=s.col,base=e.bot-(e.ph||0)-2,lt=col.map(v=>Math.min(255,v+50)),dk=col.map(v=>v*.6);
 if(sh==='strip'){const w=Math.max(6,r.w*.07),h=(26+30*k),x=r.x+r.w*.5-w/2+(si*14),y=base-h;const g1=c.createLinearGradient(x,0,x+w,0);g1.addColorStop(0,rgba(lt));g1.addColorStop(.5,rgba(col));g1.addColorStop(1,rgba(dk));c.fillStyle=g1;rr(c,x,y,w,h,2);c.fill();c.strokeStyle='rgba(0,0,0,.3)';c.lineWidth=1;c.stroke();pos.push({x,y,w,h})}
 else if(sh==='powder'){const w=r.w*(.3+.4*k),h=6+10*k,x=r.x+(r.w-w)/2;c.fillStyle=rgba(col);c.beginPath();c.moveTo(x,base);c.quadraticCurveTo(x+w/2,base-h*2,x+w,base);c.closePath();c.fill();pos.push({x,y:base-h,w,h})}
 else{const n=sh==='granule'?Math.round(3+5*k):Math.round(2+4*k),sz=sh==='granule'?5+4*k:7+7*k;for(let i=0;i<n;i++){const x=r.x+r.w*(.2+.6*rnd(i+si*13)),y=base-sz*.7-(i%3)*sz*.5;c.beginPath();for(let a=0;a<7;a++){const an=a/7*6.283,rad=sz*(.65+.35*rnd(i*7+a+si));c.lineTo(x+Math.cos(an)*rad,y+Math.sin(an)*rad*.8)}c.closePath();const g2=c.createLinearGradient(x-sz,y-sz,x+sz,y+sz);g2.addColorStop(0,rgba(lt));g2.addColorStop(1,rgba(dk));c.fillStyle=g2;c.fill();c.strokeStyle='rgba(0,0,0,.25)';c.lineWidth=1;c.stroke();pos.push({x:x-sz*.6,y:y-sz*.6,w:sz*1.2,h:sz*1.2})}}
 sx+=10})}});
/* bąbelki: miejsca nukleacji na dnie lub powierzchnia ciała stałego (metal + kwas) */
effect('bubbles',{label:'Bąbelki',defaults:{size:1,rate:1},schema:{size:{t:'range',min:.4,max:3,step:.1,l:'Wielkość'},rate:{t:'range',min:.2,max:4,step:.1,l:'Natężenie'}},draw:e=>{const c=e.c,r=e.r,b=e.pool.bub=e.pool.bub||[],pp=e.pool.pops=e.pool.pops||[],g=e.st.gas||0,sz=(e.st.bubSize||1)*e.o.size,nn=(e.st.bubN||1)*e.o.rate,sol=e.pool.solPos||[],fromSol=e.st.bubFrom!=='bottom'&&sol.length>0;
 if(g>0&&e.top<e.bot-6){const n=Math.floor(g*nn*e.dt*22+Math.random());for(let i=0;i<n&&b.length<180;i++){let x,y;if(fromSol&&Math.random()<.8){const s=sol[(Math.random()*sol.length)|0];x=s.x+Math.random()*s.w;y=s.y+Math.random()*s.h}else{const k=(Math.random()*7)|0;x=r.x+14+rnd(k+50)*(r.w-28)+(Math.random()-.5)*6;y=e.bot-6-(e.ph||0)}
  if(y>e.top+4)b.push({x,y,r:(1.3+Math.random()*2.6)*sz,v:10,p:Math.random()*6})}}
 /* v1.6 wrzenie (CHE.PHYS.boil): pęcherzyki pary z ośrodków nukleacji na dnie; poniżej Tb zapadają się w chłodniejszej cieczy */
 const PHb=C.PHYS,bo=PHb&&e.st.T!=null?PHb.boil(e.st.T,{sub:e.st.solvent,p:e.st.p}):null;e.pool.boil=bo;
 if(bo&&bo.bubbles>.01&&e.top<e.bot-6){const n=Math.floor(bo.bubbles*e.o.rate*e.dt*34+Math.random());for(let i=0;i<n&&b.length<220;i++){const k=(Math.random()*6)|0,x=r.x+12+rnd(k+90)*(r.w-24)+(Math.random()-.5)*4,y=e.bot-4-(e.ph||0);if(y>e.top+4){const rr0=(1.6+Math.random()*(1.5+3*bo.bubbles))*sz;b.push({x,y,r:rr0,r0:rr0,v:6,p:Math.random()*6,vap:bo.collapse})}}}
 /* wznoszenie: prędkość graniczna z CHE.PHYS.bubbleRise(d) — małe wolniej, duże szybciej (st.timeScale: zwolnienie, domyślnie 0,25) */
 const pxcm=Math.max(6,(e.r.h||200)/9),slow=e.st.timeScale==null?.25:e.st.timeScale,dpx=Math.max(.05,10/pxcm);
 for(let i=b.length-1;i>=0;i--){const q=b[i],vt=PHb?PHb.bubbleRise(q.r*2*dpx)*pxcm*slow:60;q.v+=(vt-q.v)*Math.min(1,e.dt*6);q.y-=q.v*e.dt;q.x+=Math.sin(e.t/200+q.p)*.4*(q.r>3?1.6:1);
  if(q.vap){q.r-=e.dt*q.r0*q.vap*1.4;if(q.r<.5){b.splice(i,1);continue}}
  if(q.y<e.surf(q.x)+1){pp.push({x:q.x,r:q.r,a:1});b.splice(i,1);continue}const k=1+.4*(e.bot-q.y)/Math.max(1,e.bot-e.top),rb=q.r*k;c.beginPath();c.arc(q.x,q.y,rb,0,7);c.fillStyle='rgba(255,255,255,.42)';c.fill();c.strokeStyle='rgba(80,100,120,.5)';c.lineWidth=1;c.stroke();c.beginPath();c.arc(q.x-rb*.3,q.y-rb*.3,Math.max(.6,rb*.25),0,7);c.fillStyle='rgba(255,255,255,.9)';c.fill()}
 for(let i=pp.length-1;i>=0;i--){const q=pp[i];q.a-=e.dt*4;if(q.a<=0){pp.splice(i,1);continue}c.strokeStyle='rgba(255,255,255,'+q.a*.7+')';c.lineWidth=1;c.beginPath();c.ellipse(q.x,e.surf(q.x)+1,q.r*(2.2-q.a),q.r*.6*(2.2-q.a),0,0,7);c.stroke()}}});
effect('foam',{label:'Piana',draw:e=>{const f=e.st.foam||0;if(f<=.02)return;const c=e.c,r=e.r;for(let i=0;i<34;i++){const x=r.x+6+rnd(i+31)*(r.w-12),y=e.surf(x)+1-rnd(i+8)*12*f+Math.sin(e.t/500+i)*1.2,rad=2+rnd(i+2)*4.5*f;c.beginPath();c.arc(x,y,rad,0,7);c.fillStyle='rgba(255,255,255,'+(.6*f)+')';c.fill();c.strokeStyle='rgba(120,140,160,'+(.35*f)+')';c.lineWidth=.8;c.stroke()}}});
effect('ripples',{label:'Kręgi na powierzchni',draw:e=>{const p=e.st.pop||0;if(p<=0)return;const c=e.c,f=1-p;for(let i=0;i<3;i++){const k=Math.min(1,f+i*.12);c.strokeStyle='rgba(255,255,255,'+(.5*(1-k)*p)+')';c.lineWidth=1.5;c.beginPath();c.ellipse(e.r.x+e.r.w/2,e.top+2,10+k*e.r.w*.35,2+k*7,0,0,7);c.stroke()}}});
/* kropla odczynnika (wskaźnika): spada, rozlewa się smugą, zanika — jednorazowa: GFX.trigger(pool,'dropMix',{color}) */
effect('dropMix',{evented:true,label:'Kropla odczynnika',defaults:{color:[219,39,119],dur:2.8,xf:.5},schema:{color:{t:'color',l:'Barwa kropli'},dur:{t:'range',min:.8,max:6,step:.1,l:'Czas rozmycia'}},draw:e=>{const c=e.c,r=e.r;(e.evs||[]).forEach(v=>{const o=v.o,x0=r.x+r.w*(o.xf==null?.5:o.xf),a=v.age,fall=.28;v.dur=o.dur;
 if(a<fall){const y=r.y+(e.top-r.y)*(a/fall);c.fillStyle=rgba(o.color,.9);c.beginPath();c.arc(x0,y,3,0,7);c.fill();return}
 const u=(a-fall)/(o.dur-fall),al=Math.pow(1-u,1.3),H=(e.bot-e.top);for(let i=0;i<7;i++){const d=Math.min(1,u*1.6)*(.25+.12*i),x=x0+Math.sin(i*1.9+a*1.6)*r.w*.12*u*(1+i*.15),y=e.top+6+H*d*.85,R=6+u*(18+i*5)*(r.w/160);const gr=c.createRadialGradient(x,y,1,x,y,R);gr.addColorStop(0,rgba(o.color,.55*al));gr.addColorStop(1,rgba(o.color,0));c.fillStyle=gr;c.beginPath();c.arc(x,y,R,0,7);c.fill()}
 if(u<.25){c.strokeStyle='rgba(255,255,255,'+(.6*(1-u*4))+')';c.lineWidth=1.2;c.beginPath();c.ellipse(x0,e.surf(x0)+1,6+u*80,1.5+u*10,0,0,7);c.stroke()}})}});
/* smugi (rozcieńczanie stężonego kwasu, mieszanie cieczy o różnej gęstości) */
effect('schlieren',{label:'Smugi mieszania',defaults:{color:null},schema:{color:{t:'color',l:'Barwa smug'}},draw:e=>{const k=cl01(e.st.schl||0);if(k<=.01)return;const c=e.c,r=e.r,col=e.o.color||e.st.schlCol||[255,255,255],H=e.bot-e.top;c.lineWidth=2.2;for(let i=0;i<7;i++){const x0=r.x+r.w*(.35+.3*rnd(i+5)),ph=e.t/900+i*1.3;c.strokeStyle=rgba(col,.32*k*(.5+.5*rnd(i)));c.beginPath();for(let s=0;s<=20;s++){const y=e.top+H*s/20*(.4+.6*k),x=x0+Math.sin(ph+s*.55)*r.w*.06*(1+s/10);s?c.lineTo(x,y):c.moveTo(x,y)}c.stroke()}}});
/* mieszadełko magnetyczne (st.stir 0..1) — wir liczony w e.surf */
effect('stirBar',{label:'Mieszadełko magnetyczne',draw:e=>{if(e.st.stir==null||e.st.stirBar===false)return;const c=e.c,r=e.r,p=e.pool,L=Math.min(r.w*.3,44),y=e.bot-5;p.sa=(p.sa||0)+(e.st.stir||0)*e.dt*26;const k=Math.cos(p.sa),cx=r.x+r.w/2,hw=Math.max(5,Math.abs(k)*L/2);c.fillStyle=k>0?'#f8fafc':'#e2e8f0';c.strokeStyle='rgba(0,0,0,.35)';c.lineWidth=1;rr(c,cx-hw,y-4,hw*2,8,4);c.fill();c.stroke()}});
effect('condensation',{label:'Skraplanie na ściankach',vessels:['beaker','flask','testTube','cylinder','roundFlask','volFlask'],draw:e=>{const bo=C.PHYS?C.PHYS.boil(e.st.T||25,{sub:e.st.solvent,p:e.st.p}):null,a=bo?.55*bo.cond:Math.min(.55,((e.st.T||25)-55)/60);if(a<=.01)return;const c=e.c;c.fillStyle='rgba(235,245,255,'+a+')';for(let i=0;i<16;i++){const side=i%2?e.r.x+e.r.w-5-rnd(i)*7:e.r.x+5+rnd(i)*7,y=e.r.y+8+rnd(i+9)*Math.max(10,e.top-e.r.y-6)+((e.t/1800+rnd(i))%1)*6;c.beginPath();c.arc(side,y,1.4+rnd(i+4)*1.8,0,7);c.fill()}}});
effect('fumes',{layer:'front',label:'Opary',defaults:{color:null,density:1},schema:{color:{t:'color',l:'Barwa oparów'},density:{t:'range',min:0,max:3,step:.1,l:'Gęstość'}},draw:e=>{const s=(e.st.fumes||0)*e.o.density;if(s<=0)return;const c=e.c,r=e.r,m=e.v.rim?e.v.rim(r):[r.x,r.x+r.w,r.y],mw=m[1]-m[0];const gq=e.st.fumeGas&&C.PHYS?C.PHYS.gas(e.st.fumeGas):null,by=gq?gq.buoy:1,dn=by<-.05;for(let i=0;i<12;i++){const f=((e.t/(dn?3400:2600))+rnd(i))%1,side=rnd(i+7)<.5?-1:1;c.beginPath();if(dn){/* cięższy od powietrza: wylewa się przez brzeg i opada po ściance */const ex=f<.35?m[0]+mw*(.3+rnd(i+3)*.4)+side*f/.35*mw*.45:(side<0?m[0]-6-(f-.35)*14:m[1]+6+(f-.35)*14);c.arc(ex+Math.sin(e.t/700+i)*4,f<.35?m[2]-6+f*8:m[2]+(f-.35)*e.r.h*.9,7+f*12,0,7)}else c.arc(m[0]+mw*.2+rnd(i+3)*mw*.6+Math.sin(e.t/700+i)*12*(.3+f),m[2]-f*48*(.4+.6*Math.max(.2,by)),8+f*18,0,7);c.fillStyle=rgba(e.o.color||e.st.fumeColor||[170,90,30],.3*(1-f)*Math.min(1,s));c.fill()}}});
effect('steam',{layer:'front',label:'Para wodna',defaults:{color:null},schema:{color:{t:'color',l:'Barwa pary'}},draw:e=>{const T=e.st.T||25,bo=C.PHYS?C.PHYS.boil(T,{sub:e.st.solvent,p:e.st.p}):null,k=bo?bo.steam:Math.max(0,Math.min(1,(T-70)/30));if(k<=.01)return;const c=e.c,r=e.r,m=e.v.rim?e.v.rim(r):[r.x,r.x+r.w,r.y],mw=m[1]-m[0];for(let i=0;i<9;i++){const f=((e.t/2200)+rnd(i+40))%1;/* v1.6: miękkie kłęby (gradient radialny) — w trybie ciemnym para nie wygląda jak szary dym */const x=m[0]+mw*.25+rnd(i+7)*mw*.5+Math.sin(e.t/600+i)*9*(.3+f),y=m[2]-4-f*58,R=9+f*16,col=e.o.color||[240,246,252],a=(e.T.dark?.3:.42)*k*(1-f),gr=c.createRadialGradient(x,y,1,x,y,R);gr.addColorStop(0,rgba(col,a));gr.addColorStop(.6,rgba(col,a*.45));gr.addColorStop(1,rgba(col,0));c.fillStyle=gr;c.beginPath();c.ellipse(x,y,R,R*.72,0,0,7);c.fill()}}});
effect('heatConvection',{layer:'front',label:'Konwekcja ciepła',draw:e=>{if(!(e.st.heat>2.2))return;const c=e.c,r=e.r;for(let i=0;i<5;i++){const f=((e.t/1500)+rnd(i+20))%1;c.beginPath();c.arc(r.x+r.w*(.2+.15*i)+Math.sin(e.t/500+i)*8,r.y-f*50,8+f*14,0,7);c.fillStyle='rgba(235,240,245,'+.45*(1-f)+')';c.fill()}}});
effect('splash',{layer:'front',label:'Pryskanie',draw:e=>{const c=e.c,d=e.pool.drops2=e.pool.drops2||[],s=e.st;if(s.splash>0){const n=Math.ceil(s.splash*e.dt*40),m=e.v.rim?e.v.rim(e.r):[e.r.x,e.r.x+e.r.w,e.r.y];for(let i=0;i<n&&d.length<220;i++)d.push({x:(m[0]+m[1])/2+(Math.random()-.5)*(m[1]-m[0])*.8,y:Math.max(m[2],e.top-4),vx:(Math.random()-.5)*260,vy:-180-Math.random()*220,r:2+Math.random()*3});s.splash=Math.max(0,s.splash-e.dt)}for(let i=d.length-1;i>=0;i--){const q=d[i];q.vy+=620*e.dt;q.x+=q.vx*e.dt;q.y+=q.vy*e.dt;if(q.y>e.r.y+e.r.h+60){d.splice(i,1);continue}c.beginPath();c.arc(q.x,q.y,q.r,0,7);c.fillStyle=rgba(s.liquid||[205,228,238],.9);c.fill();c.strokeStyle='rgba(180,40,40,.7)';c.lineWidth=1;c.stroke()}}});
/* podziałka: zlewka / cylinder (opcje z definicji naczynia) */
effect('scale',{layer:'front',label:'Podziałka',vessels:['beaker','cylinder'],defaults:{},schema:{},draw:e=>{const v=e.v,sc=Object.assign({},v.scale,e.st.scale||{}),c=e.c,r=e.r;if(!sc.max)return;const yb=e.bot,yt=e.bot-v.hmax*r.h,x=r.x+r.w*sc.x;c.strokeStyle=e.T.mut;c.fillStyle=e.T.mut;c.lineWidth=1;font(c,600,8);c.textAlign='left';
 for(let m=sc.minor;m<=sc.max;m+=sc.minor){const y=yb-(yb-yt)*m/sc.max,maj=Math.abs(m%sc.step)<1e-6;c.globalAlpha=maj?.9:.6;c.beginPath();c.moveTo(x-(maj?7:4),y);c.lineTo(x+(maj?7:4),y);c.stroke();if(maj)c.fillText(m,x+9,y+3)}c.globalAlpha=1;if(sc.unit!==false){font(c,700,8);c.fillText(sc.unit||'mL',x+9,yt-6)}}});
/* etykieta naczynia (wzór substancji) */
effect('label',{layer:'front',label:'Etykieta',draw:e=>{const s=e.st.label;if(!s)return;const c=e.c,r=e.r;font(c,800,12);const w=c.measureText(s).width+14,x=r.x+r.w/2-w/2,y=r.y+r.h*(e.v.labelY||.58);c.fillStyle=e.T.dark?'rgba(30,41,59,.92)':'rgba(255,255,255,.93)';c.strokeStyle=e.T.glass;c.lineWidth=1;rr(c,x,y,w,19,4);c.fill();c.stroke();c.fillStyle=e.T.text;c.textAlign='center';c.fillText(s,x+w/2,y+14)}});
/* korek (st.stopper: true | 'tube' — z otworem na rurkę) */
effect('stopper',{layer:'front',label:'Korek',draw:e=>{const s=e.st.stopper;if(!s||!e.v.rim)return;const c=e.c,m=e.v.rim(e.r),w=m[1]-m[0],cx=(m[0]+m[1])/2,y=m[2];c.fillStyle=e.T.dark?'#57534e':'#78716c';c.strokeStyle='rgba(0,0,0,.4)';c.lineWidth=1;c.beginPath();c.moveTo(cx-w/2-4,y-12);c.lineTo(cx+w/2+4,y-12);c.lineTo(cx+w/2-2,y+10);c.lineTo(cx-w/2+2,y+10);c.closePath();c.fill();c.stroke();
 if(s==='tube'){c.strokeStyle=e.T.glass;c.lineWidth=7;c.beginPath();c.moveTo(cx,y-26);c.lineTo(cx,y+22);c.stroke();c.strokeStyle=e.T.dark?'#1e293b':'#eef4f8';c.lineWidth=4;c.stroke()}}});
/* kranik wkraplacza + krople (st.tap 0..1) */
effect('tap',{layer:'front',label:'Kranik',vessels:['dropFunnel'],draw:e=>{const c=e.c,r=e.r,{cx}=dfG(r),y=r.y+r.h*.74,op=cl01(e.st.tap||0);c.fillStyle=e.T.dark?'#cbd5e1':'#e2e8f0';c.strokeStyle=e.T.glass;c.lineWidth=2;rr(c,cx-9,y-6,18,12,5);c.fill();c.stroke();c.save();c.translate(cx,y);c.rotate(op>0?Math.PI/2:0);c.fillStyle=e.T.dark?'#1d4ed8':'#2563eb';rr(c,-16,-3,32,6,3);c.fill();c.restore();
 if(op>0&&e.top<e.bot-1)drips(c,e.env,e.st,cx,r.y+r.h,e.st.liquid||[205,228,238],op*1.4,r,2.4)}});

/* ===================== WSPÓLNE: krople spadające z końcówki (biureta, pipeta, kroplomierz, wkraplacz) =====================
   rate (0..): losowe kroplenie; st.dropReq (licznik): pojedyncze krople na żądanie; st.landY (ułamek wys. płótna) i st.onDrop(kolor) dla scen */
function drips(c,env,st,x,y,col,rate,r,sz){const p=env.pool,d=p.drops=p.drops||[],dt=env.dt||.016;if(rate>0&&Math.random()<Math.min(1.5,rate)*dt*6)d.push({x,y,v:0});
 const req=st.dropReq||0;if(p.dq==null)p.dq=req;while(p.dq<req){d.push({x,y,v:0});p.dq++}
 const land=st.landY!=null&&env.H?st.landY*env.H:r.y+r.h+(st.landY!=null?st.landY:0);
 for(let i=d.length-1;i>=0;i--){const q=d[i];q.v+=900*dt;q.y+=q.v*dt;if(q.y>=land){d.splice(i,1);if(typeof st.onDrop==='function')st.onDrop(col);continue}c.fillStyle=rgba(col,.92);c.beginPath();c.moveTo(q.x,q.y-sz*2.4);c.quadraticCurveTo(q.x+sz,q.y-sz*.5,q.x+sz,q.y);c.arc(q.x,q.y,sz,0,Math.PI);c.quadraticCurveTo(q.x-sz,q.y-sz*.5,q.x,q.y-sz*2.4);c.fill();c.strokeStyle='rgba(60,80,100,.35)';c.lineWidth=.8;c.stroke()}}
