/* --- v1.5: łuczywko (tlące / płonące / zgaszone) + „pyk!" (wykrywanie H₂) --- */
effect('splint',{free:true,layer:'front',label:'Łuczywko',defaults:{mode:'flame',len:120,angle:-35},schema:{mode:{t:'select',opts:['flame','glow','off'],l:'Stan (płonie / tli się / zgaszone)'},len:{t:'range',min:60,max:200,step:5,l:'Długość'},angle:{t:'range',min:-80,max:10,step:1,l:'Kąt'}},
draw:e=>{const c=e.c,o=e.o,a=e.anchor,t=e.t,an=o.angle*Math.PI/180,ex=a.x+Math.cos(an)*o.len,ey=a.y+Math.sin(an)*o.len;c.lineCap='round';c.strokeStyle=e.T.wood;c.lineWidth=6;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(ex,ey);c.stroke();c.strokeStyle='rgba(0,0,0,.18)';c.lineWidth=2;c.stroke();
 c.fillStyle='#1c1917';c.beginPath();c.arc(a.x,a.y,4,0,7);c.fill();
 if(o.mode==='glow'){const k=.7+.3*Math.sin(t/120);const g1=c.createRadialGradient(a.x,a.y,1,a.x,a.y,14);g1.addColorStop(0,'rgba(255,190,80,'+k+')');g1.addColorStop(1,'rgba(255,90,20,0)');c.fillStyle=g1;c.beginPath();c.arc(a.x,a.y,14,0,7);c.fill();c.fillStyle='rgba(255,120,40,'+k+')';c.beginPath();c.arc(a.x,a.y,3.2,0,7);c.fill();
  for(let i=0;i<4;i++){const f=((t/2000)+rnd(i))%1;c.fillStyle='rgba(120,120,120,'+.3*(1-f)+')';c.beginPath();c.arc(a.x+Math.sin(t/400+i)*5,a.y-6-f*40,3+f*6,0,7);c.fill()}}
 else if(o.mode==='flame'){const H=34,W=8,fl=Math.sin(t/70)*1.5;c.save();c.shadowColor='rgba(255,170,40,.8)';c.shadowBlur=14;c.beginPath();c.moveTo(a.x-W,a.y);c.bezierCurveTo(a.x-W*1.2,a.y-H*.45,a.x-W*.3+fl,a.y-H*.8,a.x+fl*1.5,a.y-H);c.bezierCurveTo(a.x+W*.3+fl,a.y-H*.8,a.x+W*1.2,a.y-H*.45,a.x+W,a.y);c.closePath();const g2=c.createLinearGradient(0,a.y,0,a.y-H);g2.addColorStop(0,'rgba(255,170,40,.95)');g2.addColorStop(1,'rgba(255,230,120,.25)');c.fillStyle=g2;c.fill();c.restore()}}});
effect('pop',{free:true,oneShot:true,layer:'front',label:'„Pyk!" — zapłon H₂',defaults:{dur:.9,color:[170,200,255],text:'pyk!'},schema:{color:{t:'color',l:'Barwa błysku'}},draw:e=>{const c=e.c,a=e.anchor;e.evs.forEach(v=>{const o=v.o,k=Math.min(1,v.age/o.dur),x=o.x==null?a.x:o.x,y=o.y==null?a.y:o.y,R=8+50*Math.sqrt(k),al=1-k;const g1=c.createRadialGradient(x,y,1,x,y,R);g1.addColorStop(0,'rgba(255,255,255,'+al+')');g1.addColorStop(.4,rgba(o.color,.7*al));g1.addColorStop(1,rgba(o.color,0));c.fillStyle=g1;c.beginPath();c.arc(x,y,R,0,7);c.fill();c.strokeStyle='rgba(255,255,255,'+.7*al+')';c.lineWidth=2;c.beginPath();c.arc(x,y,R*1.4,0,7);c.stroke();
 c.fillStyle=rgba(e.T.dark?[255,255,255]:[30,41,59],al);font(c,900,20);c.textAlign='center';c.fillText(o.text,x+30,y-20-30*k)})}});
PRESETS.push({label:'Łuczywko płonące',id:'splint',o:{mode:'flame'}},{label:'Łuczywko tlące się (test na O₂)',id:'splint',o:{mode:'glow'}},{label:'„Pyk!" — wodór',id:'pop',o:{}});
/* kotwica: niewidoczny punkt sceny (zaczepienie efektów swobodnych) */
vessel('anchor',{custom:(c,r)=>({x:r.x+r.w/2,y:r.y+r.h/2})});
