/* ===== CHE.LAB.LIBRARY v1.3 — katalog: fizyka (CHE.PHYS), reakcje (GFX.rx), naczynia, przyrządy, aparatura, efekty, cząsteczki/jony, zestawy (jedno źródło GFX) ===== */
(function(){
const GF=C.LAB.GFX;
const META={electroscope:['Elektroskop','elektrostatyka','st {ball, leaves, theta?, ground, rod:{q,d}} · model: CHE.PHYS.electro.electroscope'],chargedRod:['Pręt naelektryzowany','elektrostatyka','st {q, col} · pary ± i nadmiar ładunku'],pendulum:['Wahadełko elektrostatyczne','elektrostatyka','st {phi, q}; polaryzacja: GFX.electro.pendulum(…,{polar})'],fieldMap:['Linie pola elektrycznego','elektrostatyka','st.charges [{x,y,q}] (0–1) · CHE.PHYS.electro.fieldAt'],chargeBar:['Rozpływ ładunku w pręcie','elektrostatyka','st.cells [kula, …, elektroskop] · przewodnik / izolator'],beaker:['Zlewka','naczynie','Uniwersalna; dzióbek, podziałka, wszystkie efekty cieczy'],flask:['Kolba stożkowa','naczynie','Kolba Erlenmeyera; miareczkowanie, reakcje z gazem'],testTube:['Probówka','naczynie','Pojedynczy test'],cylinder:['Cylinder miarowy','naczynie','Pomiar objętości; podziałka i stopka'],roundFlask:['Kolba okrągłodenna','naczynie','Ogrzewanie, destylacja'],volFlask:['Kolba miarowa','naczynie','Kreska miarowa; roztwory o znanym stężeniu'],funnel:['Lejek','naczynie','Sączenie, przelewanie'],petri:['Szalka Petriego','naczynie','Płytka: krystalizacja, reakcje na szkle'],evapDish:['Parownica','naczynie','Porcelana; odparowanie, krystalizacja'],crucible:['Tygiel','naczynie','Porcelana; prażenie ciał stałych; st.lid — pokrywka'],watchGlass:['Szkiełko zegarkowe','naczynie','Mała ilość substancji, odparowanie kropli'],dropFunnel:['Wkraplacz (rozdzielacz)','naczynie','Kranik st.tap; krople do naczynia poniżej (landY, onDrop)'],molTank:['Zbiornik cząsteczek','naczynie','Cząsteczki i jony: gaz / ciecz / ciało stałe; ładunki jonów'],
 burette:['Biureta','przyrząd','st.titrant {V,Vmax,drip,color}; krople na żądanie st.dropReq'],pipette:['Pipeta','przyrząd','st.pip {lv,drip,color}'],dropper:['Kroplomierz','przyrząd','st.dropper {lv,color,drip}; st.dropReq → jedna kropla; gruszka się ściska'],pHmeter:['pH-metr cyfrowy','przyrząd','st.pH, st.T'],paper:['Papierki wskaźnikowe','przyrząd','Kolory z CHE.COLORS; st.pH, st.dip, st.fresh'],thermometer:['Termometr','przyrząd','st.T'],balance:['Waga','przyrząd','st.mass'],conductivity:['Tester przewodnictwa','przyrząd','Elektrody, bateria, żarówka; st.cond 0–1'],pHscale:['Skala pH','przyrząd','Barwy wskaźnika z CHE.COLORS; st.pH, st.ind, st.marks'],
 burner:['Palnik Bunsena','aparatura','Płomień: st.flame {on,power,air,phi}'],spiritLamp:['Lampa spirytusowa','aparatura','st.lamp {on,lv}; zgaszona → kołpak'],tripod:['Trójnóg z siatką','aparatura','Siatka żarzy się: st.heat'],hotplate:['Mieszadło magnetyczne z grzaniem','aparatura','st.heat 0–3, st.stir 0–1 (mieszadełko + wir w naczyniu)'],stand:['Statyw z łapą','aparatura','st.clamps [{x,y,w,ring}] (ułamki płótna); layer:"front" = szczęki nad naczyniem'],tubeRack:['Statyw z probówkami','aparatura','st.tubes [{label,liquid,level,…}] — każda probówka to pełne naczynie'],gasCollect:['Zbieranie gazu nad wodą','aparatura','st.gasV 0–1, st.gas, st.gasColor; wlot z lewej (40% wys.)'],cooler:['Chłodnica Liebiga','aparatura','st.coolant {Tin,Tout,flow,q}'],stage:['Podstawa / scena','aparatura','Kotwica dla efektów swobodnych'],anchor:['Kotwica','ukryty','']};
const NEW=['flame','boil','glow','gas','bubbles','precipitate','molTank','crucible','watchGlass','dropFunnel','dropper','conductivity','pHscale','spiritLamp','tripod','hotplate','stand','tubeRack','gasCollect','turbidity','dropMix','schlieren','stirBar','scale','label','stopper','tap','splint','pop'];
const CSS='.cl-top{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:0 0 10px}.cl-top input{flex:1 1 180px;min-height:34px;padding:5px 11px;border:1px solid var(--border,#e2e8f0);border-radius:999px;background:var(--panel,#fff);color:inherit;font:inherit}.cl-stat{font-size:12px;opacity:.7}.cl-nav{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 10px}.cl-nav button,.cl-btn{border:1px solid var(--border,#e2e8f0);background:var(--panel,#fff);color:inherit;padding:6px 11px;border-radius:999px;font:inherit;font-size:13px;cursor:pointer}.cl-nav button.on{background:#2563eb;color:#fff;border-color:#2563eb}.cl-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,240px),1fr));gap:10px}.cl-card{border:1px solid var(--border,#e2e8f0);border-radius:12px;padding:10px;background:var(--panel,#fff);min-width:0}.cl-card.wide{grid-column:1/-1}.cl-card h3{margin:0;font-size:14px}.cl-card code{font-size:11px;opacity:.65}.cl-tag{white-space:nowrap;font-size:10px;padding:1px 7px;border-radius:99px;background:rgba(100,116,139,.15);margin-right:4px}.cl-tag.new{background:#16a34a;color:#fff}.cl-d{margin:4px 0 6px;font-size:12px;opacity:.75}.cl-ctl{display:grid;gap:3px;margin-top:6px;font-size:12px}.cl-ctl label{display:grid;grid-template-columns:72px 1fr auto;gap:6px;align-items:center}.cl-sel{margin-top:6px;margin-right:6px}';
const H={cooler:150,balance:170,paper:270,molTank:230,petri:140,evapDish:160,funnel:220,pipette:230,dropper:230,crucible:170,watchGlass:130,dropFunnel:280,stand:260,tripod:180,spiritLamp:240,hotplate:150,tubeRack:230,gasCollect:260,conductivity:280,pHscale:150,burner:260,burette:280};
const SETS={'H₂O':[{id:'H2O',n:14}],'HCl(aq): H₃O⁺ + Cl⁻':[{id:'H3O+',n:6},{id:'Cl-',n:6},{id:'H2O',n:8}],'CH₃COOH(aq) — słaby':[{id:'CH3COOH',n:5},{id:'H3O+',n:1},{id:'CH3COO-',n:1},{id:'H2O',n:9}],'H₂SO₄(aq)':[{id:'H3O+',n:6},{id:'SO42-',n:3},{id:'H2O',n:8}],'NaOH(aq): Na⁺ + OH⁻':[{id:'Na+',n:6},{id:'OH-',n:6},{id:'H2O',n:8}],'NaCl(aq)':[{id:'Na+',n:6},{id:'Cl-',n:6},{id:'H2O',n:8}],'CO₂ + H₂':[{id:'CO2',n:8},{id:'H2',n:8}],'NH₃':[{id:'NH3',n:12}],'CH₄ + O₂':[{id:'CH4',n:6},{id:'O2',n:10}],'HCl + H₂O (gaz)':[{id:'HCl',n:6},{id:'H2O',n:12}],'cukier (aq)':[{id:'C6H12O6',n:3},{id:'H2O',n:12}]};
const ce=(t,cls,txt)=>{const e=document.createElement(t);if(cls)e.className=cls;if(txt!=null)e.textContent=txt;return e};
function demo(id){const s={liquid:[205,228,238],level:.6,T:25,heat:0,gas:0,pop:0,pH:4.2,mass:12.34,dip:0,fresh:0,titrant:{V:18,Vmax:50,drip:.6,color:[205,228,238]},pip:{lv:.6,drip:0,color:[205,228,238]},flame:{air:100},coolant:{Tin:15,Tout:28,flow:.0005,q:50},phase:'gas',mol:SETS['H₂O'],dropper:{lv:.6,color:[219,39,119],drip:.25},dropReq:0,lamp:{on:1,lv:.6},stir:null,cond:.8,gasV:.35,ind:'ind-uniwersalny',marks:[{pH:1,label:'HCl'},{pH:2.9,label:'ocet'},{pH:7,label:'woda'},{pH:13,label:'NaOH'}]};const m=META[id];
 if(m&&m[1]==='naczynie'&&id!=='molTank'){s.gas=.5;s.T=60}if(id==='burner')s.fx={flame:true};if(id==='crucible'){s.level=0;s.gas=0;s.T=25;s.solids=[{col:[28,28,28],eq:2.5,shape:'powder'}]}if(id==='dropFunnel'){s.level=.75;s.tap=.5;s.gas=0;s.T=25}if(id==='watchGlass'){s.liquid=[59,130,196];s.gas=0;s.T=25}if(id==='hotplate'){s.heat=1.5;s.stir=.6}if(id==='tripod')s.heat=2;if(id==='gasCollect')s.gas=.6;if(id==='conductivity'){s.label='HCl(aq)'}if(id==='stand')s.layer='both';return s}
function range(c,l,min,max,step,v,fn){const w=ce('div','cl-ctl'),lb=ce('label'),i=ce('input'),o=ce('output',null,v);i.type='range';i.min=min;i.max=max;i.step=step;i.value=v;i.oninput=()=>{o.textContent=i.value;fn(+i.value)};lb.append(ce('span',null,l),i,o);w.appendChild(lb);c.appendChild(w)}
function btn(c,t,fn){const b=ce('button','cl-btn',t);b.type='button';b.style.marginTop='6px';b.style.marginRight='6px';b.onclick=fn;c.appendChild(b);return b}
function sel(c,opts,fn,v){const s=ce('select','cl-sel');opts.forEach(([k,t])=>{const o=ce('option',null,t);o.value=k;s.appendChild(o)});if(v!=null)s.value=v;s.onchange=()=>fn(s.value);c.appendChild(s)}
function ctl(c,id,st){const kind=(META[id]||[])[1];
 if(kind==='naczynie'&&id!=='molTank'){range(c,'poziom',0,1,.01,st.level,v=>st.level=v);range(c,'gaz',0,1,.05,st.gas,v=>st.gas=v);range(c,'T °C',0,110,1,st.T,v=>st.T=v);range(c,'mieszanie',0,1,.05,0,v=>st.stir=v||null)}
 if(id==='pHmeter'||id==='paper'||id==='pHscale')range(c,'pH',0,14,.1,st.pH,v=>st.pH=v);
 if(id==='pHscale')sel(c,GF.indicators,v=>st.ind=v);
 if(id==='paper'){btn(c,'Zanurz / wyjmij',()=>{st.dip=st.dip?0:1});btn(c,'Nowe papierki',()=>{st.fresh++;st.dip=0})}
 if(id==='thermometer')range(c,'T °C',-20,120,1,st.T,v=>st.T=v);
 if(id==='burette')range(c,'V cm³',0,50,.5,st.titrant.V,v=>st.titrant.V=v);
 if(id==='pipette')range(c,'poziom',0,1,.01,st.pip.lv,v=>st.pip.lv=v);
 if(id==='dropper'){btn(c,'Kropla',()=>st.dropReq++);range(c,'kroplenie',0,1.5,.05,st.dropper.drip,v=>st.dropper.drip=v)}
 if(id==='dropFunnel')range(c,'kranik',0,1,.05,st.tap,v=>st.tap=v);
 if(id==='crucible')btn(c,'Pokrywka',()=>st.lid=!st.lid);
 if(id==='balance')range(c,'masa g',0,200,.01,st.mass,v=>st.mass=v);
 if(id==='hotplate'||id==='tripod')range(c,'grzanie',0,3,.1,st.heat,v=>st.heat=v);
 if(id==='hotplate')range(c,'obroty',0,1,.05,st.stir,v=>st.stir=v);
 if(id==='spiritLamp')btn(c,'Zapal / zgaś',()=>st.lamp.on=st.lamp.on?0:1);
 if(id==='burner'){range(c,'moc',0,1,.05,1,v=>{st.flame.on=v>0?1:0;st.flame.power=v});range(c,'powietrze',0,100,5,100,v=>st.flame.air=v)}
 if(id==='gasCollect'){range(c,'V gazu',0,1,.01,st.gasV,v=>st.gasV=v);range(c,'przepływ',0,1,.05,st.gas,v=>st.gas=v)}
 if(id==='conductivity')range(c,'jony',0,1,.01,st.cond,v=>st.cond=v);
 if(id==='molTank')molCtl(c,st)}
function molCtl(c,st){sel(c,[['gas','gaz'],['liquid','ciecz'],['solid','ciało stałe']],v=>st.phase=v,st.phase);sel(c,Object.keys(SETS).map(k=>[k,k]),v=>st.mol=SETS[v]);range(c,'T °C',-50,600,5,25,v=>st.T=v)}
/*@@LIB_EXT@@*/
function mount(host,opt){opt=opt||{};if(!document.getElementById('che-lib-css')){const s=ce('style');s.id='che-lib-css';s.textContent=CSS+PLOT_CSS;document.head.appendChild(s)}GF.ui.ensure();
 const root=ce('div'),top=ce('div','cl-top'),q=ce('input'),stat=ce('span','cl-stat'),nav=ce('div','cl-nav'),main=ce('div');q.placeholder='Szukaj: np. kolba, płomień, jony, kwas…';q.type='search';top.append(q,stat);root.append(top,nav,main);host.appendChild(root);let cards=[],cur=null;
 const nV=GF.vessels.list().filter(id=>(META[id]||[])[1]!=='ukryty').length,nE=GF.effects.list().length,nS=GF.scenes.list().length;stat.textContent='GFX v'+GF.version+' · '+nV+' elementów · '+nE+' efektów · '+nS+' zestawów · '+(GF.rx?GF.rx.list().length:0)+' reakcji · CHE.PHYS '+(C.PHYS?C.PHYS.version:'—');
 const clear=()=>{cards.forEach(m=>m.destroy&&m.destroy());cards=[];main.innerHTML=''};
 const card=(g,title,id,tags,desc,key,wide)=>{const c=ce('div','cl-card'+(wide?' wide':''));c.dataset.q=(title+' '+id+' '+tags.join(' ')+' '+desc).toLowerCase();c.appendChild(ce('h3',null,title));c.appendChild(ce('code',null,id+' '));if(NEW.indexOf(key)>=0)c.appendChild(ce('span','cl-tag new','nowe'));tags.forEach(t=>c.appendChild(ce('span','cl-tag',t)));c.appendChild(ce('div','cl-d',desc));g.appendChild(c);return c};
 function tabV(g,kind){GF.vessels.list().forEach(id=>{const m=META[id]||[id,'aparatura',''];if(m[1]!==kind)return;const c=card(g,m[0],'GFX.vessels · '+id,[m[1]],m[2],id),st=demo(id);cards.push(GF.mount(c,{vessel:id,height:H[id]||210,get:()=>st}));ctl(c,id,st)})}
 function tabE(g,free){GF.effects.list().forEach(id=>{const f=GF.effects.get(id);if(!!f.free!==free)return;const c=card(g,f.label||id,'GFX.effects · '+id,[f.free?'swobodny':'w naczyniu','warstwa: '+f.layer].concat(f.vessels?['tylko: '+f.vessels.slice(0,2).join(', ')]:[]),f.free?'Rysowany nad sceną; st.fx / GFX.trigger':f.evented?'Jednorazowy w naczyniu: GFX.trigger(pool,"'+id+'",{color})':'Rysowany w naczyniu; stan z st.*',id),
  st=Object.assign(demo('beaker'),{gas:1,heat:3,fumes:1,T:95,foam:.6,turb:.6,schl:1,stir:id==='stirBar'?.8:null,label:'HCl',stopper:true,plume:{col:[59,130,196],k:.8},ppts:[{col:[248,250,252],eq:1.2}],solids:[{col:[154,167,179],eq:3,t:'metal',shape:'granule'}],pop:0,splash:0,level:id==='tap'?.75:.6,tap:.6}),only=f.free?[id]:['glass','liquid','meniscus',id].concat(id==='bubbles'?['solids']:[]),vs=f.free?'stage':(f.vessels?f.vessels[0]:'beaker');if(f.free)st.fx={[id]:true};
  let n=0;const m=GF.mount(c,{vessel:vs,height:200,parts:!f.free&&f.layer==='front'&&['fumes','steam','heatConvection','splash','stopper'].indexOf(id)>=0?[{id:vs,x:.2,y:.36,w:.6,h:.6}]:null,get:()=>{n++;if(id==='splash'&&n%160===1)st.splash=.6;if((id==='ripples'||id==='precipitate')){st.pop=1-((n%150)/150)}return st},only,fx:f.free?{[id]:true}:null});cards.push(m);
  if((f.free&&f.oneShot)||f.evented){btn(c,'Uruchom',()=>m.trigger(id,f.evented?{color:[[219,39,119],[37,99,235],[250,204,21]][(Math.random()*3)|0]}:{}));if(f.evented)setTimeout(()=>m.trigger(id,{}),400)}
  if(f.schema&&Object.keys(f.schema).length){const o=ce('div','cl-ctl'),fxo={};c.appendChild(o);GF.optionsPanel(o,id,fxo,()=>{st.fx=Object.assign({},st.fx,{[id]:Object.assign({},fxo)})})}})}
 function tabM(g){Object.keys(SETS).forEach(k=>{const c=card(g,k,'GFX.vessels · molTank',['cząsteczki'],SETS[k].map(x=>GF.molecules.name(x.id)+' ×'+x.n).join(', '),'molTank'),st={phase:/aq|cukier/.test(k)?'liquid':'gas',mol:SETS[k],T:25};cards.push(GF.mount(c,{vessel:'molTank',height:220,get:()=>st}));molCtl(c,st)})}
 function tabS(g){GF.scenes.list().forEach(id=>{const D=GF.scenes.get(id),c=card(g,D.label,'GFX.scene(host,"'+id+'")',['zestaw',D.lesson||''],D.desc||'',id,true);cards.push(GF.scene(c,id))})}
 const push=m=>cards.push(m);const TABS={'Zestawy':tabS,'Fizyka (CHE.PHYS)':g=>tabF(g,card,push),'Reakcje (GFX.rx)':g=>tabR(g,card,push),'Naczynia':g=>tabV(g,'naczynie'),'Przyrządy':g=>tabV(g,'przyrząd'),'Aparatura':g=>tabV(g,'aparatura'),'Elektrostatyka':g=>tabV(g,'elektrostatyka'),'Efekty (ciecz)':g=>tabE(g,false),'Efekty (swobodne)':g=>tabE(g,true),'Cząsteczki i jony':tabM};
 function filt(){const s=q.value.trim().toLowerCase();[].forEach.call(main.querySelectorAll('.cl-card'),c=>{c.style.display=!s||c.dataset.q.indexOf(s)>=0?'':'none'})}q.oninput=filt;
 function show(n){cur=n;clear();const g=ce('div','cl-grid');main.appendChild(g);TABS[n](g);filt();[].forEach.call(nav.children,b=>b.classList.toggle('on',b.textContent===n))}
 Object.keys(TABS).forEach(n=>{const b=ce('button',null,n);b.type='button';b.onclick=()=>show(n);nav.appendChild(b)});
 show(opt.tab||'Zestawy');return{show,destroy:clear}}
C.LAB.LIBRARY={version:'1.3',mount,meta:META,sets:SETS};
})();
/* ===== /CHE.LAB.LIBRARY ===== */
