;/* ===== v0.37: widoki CHE.IONIC — równania jonowe (zastępuje 'neutralization') i tabela rozpuszczalności ===== */
(function(){
var C=window.CHE,V=C&&C.VIEW;if(!V||!V.define||!C.IONIC)return;
var el=function(t,c,h){var e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e};
var TYPES=[['neutralization','Zobojętnianie'],['precipitation','Strącanie osadu'],['carbonate+acid','Węglan + kwas'],['salt+acid','Sól + kwas'],['acid+basic-oxide','Tlenek + kwas'],['metal+acid','Metal + kwas']];
function eqCard(host,k){var I=C.IONIC.equations(k),d=(C.DATA.REACTION_DATA||{})[k]||{},TN=C.DATA.REACTION_TYPE_NAMES||{};if(!I){host.innerHTML='<div class="note">Brak reakcji '+k+'.</div>';return}
 var row=function(lab,txt,bg){return '<div style="border:1px solid var(--border,#d5dee6);border-left:4px solid '+bg+';border-radius:10px;padding:8px 12px;margin:6px 0"><div style="font-size:11px;font-weight:800;letter-spacing:.04em;opacity:.7;text-transform:uppercase">'+lab+'</div><div style="font:600 16px Inter,system-ui;margin-top:2px">'+txt+'</div></div>'};
 host.innerHTML=row('Cząsteczkowe',I.molecular,'#2b5e9c')+row('Jonowe pełne',I.full,'#6b3fa0')+row('Jonowe skrócone',I.net,'#2e7d4f')+
  '<div class="note"><b>Jony obserwatory</b> (nie zmieniają się): '+(I.spectators.join(', ')||'brak')+'<br>'+(I.notes.length?'<b>Zapis cząsteczkowy zostaje dla:</b> '+I.notes.join(' · ')+'<br>':'')+'<b>Typ:</b> '+(TN[d.type]||d.type||'—')+' · <b>Obserwacja:</b> '+(d.observation||'—')+'</div>'}
function eqView(host,first){host.innerHTML='';var R=C.DATA.REACTIONS||{},RD=C.DATA.REACTION_DATA||{},bar=el('div'),area=el('div'),gfx=el('div');gfx.style.cssText='max-width:420px';host.append(bar,area,gfx);var cur=first||'hclNaOH',m=null;
 TYPES.forEach(function(t){var ks=Object.keys(R).filter(function(k){var J=RD[k]&&RD[k].type===t[0]&&!R[k].aliasOf?C.IONIC.equations(k):null;return J&&J.ionic});if(!ks.length)return;var r=el('div','r','<b style="min-width:120px">'+t[1]+':</b> ');ks.forEach(function(k){var b=el('button',null,C.IONIC.equations(k).molecular.split('→')[0].trim());b.type='button';b.dataset.k=k;b.onclick=function(){cur=k;show()};r.appendChild(b)});bar.appendChild(r)});
 function show(){[].forEach.call(bar.querySelectorAll('button'),function(b){b.classList.toggle('on',b.dataset.k===cur)});eqCard(area,cur);gfx.innerHTML='';var G=C.LAB&&C.LAB.GFX;if(G&&G.rx){var key=G.rx.list(function(s){return (s.rxKey||s.key)===cur})[0]||(G.rx.get(cur)?cur:null);if(key){m=G.rx.mount(gfx,key,{height:220,dur:5,auto:true})}}}
 show()}
V.define('neutralization',{title:'Równania jonowe — cząsteczkowe, jonowe pełne, jonowe skrócone',tag:'E8',hint:'Wybierz reakcję z silnika. Zapis jonowy jest generowany automatycznie: mocne elektrolity i rozpuszczalne sole → jony; woda, słabe kwasy, gazy i osady → zapis cząsteczkowy.',foot:'CHE.IONIC.equations(id) · rozpuszczalność: CHE.DATA.SOLUBILITY_TABLE · reakcje: CHE.REACTION (te same co w lekcji i Atlasie)',build:function(host){eqView(host,'hclNaOH')}});
V.define('rownania-jonowe-v01',{title:'Równania jonowe — wszystkie reakcje z silnika',tag:'E8',hint:'Zobojętnianie, strącanie, węglany, sole, tlenki i metale z kwasami — trzy poziomy zapisu.',foot:'CHE.IONIC',build:function(host){eqView(host,'agno3Hcl')}});
V.define('tabela-rozpuszczalnosci-v01',{title:'Tabela rozpuszczalności (20 °C)',tag:'E8',hint:'Kliknij komórkę: wzór, nazwa i rozpuszczalność związku. Kolory osadów z CHE.COLORS, gdy są w bazie.',foot:'CHE.DATA.SOLUBILITY_TABLE — R > 1 g, T 0,1–1 g, N < 0,1 g na 100 g wody; „—” nie istnieje w roztworze wodnym / rozkłada się',
 build:function(host){host.innerHTML='';var T=C.DATA.SOLUBILITY_TABLE,I=C.IONIC,COL={R:'rgba(46,125,79,.16)',T:'rgba(176,111,28,.2)',N:'rgba(184,58,69,.18)','—':'rgba(100,116,139,.12)'};
  var w=el('div');w.style.cssText='overflow-x:auto';var t='<table style="border-collapse:collapse;font-size:12.5px;min-width:720px"><tr><th></th>'+T.cations.map(function(c){return '<th style="padding:4px 5px">'+c.ion+'</th>'}).join('')+'</tr>';
  T.anions.forEach(function(a){t+='<tr><th style="padding:4px 6px;text-align:left;white-space:nowrap">'+a.ion+'</th>'+T.cations.map(function(c){var s=T.table[a.id][c.id]||'',k=I.compound(c.id,a.id);return '<td data-c="'+c.id+'" data-a="'+a.id+'" title="'+(k?k.pretty+' — '+k.name:'')+'" style="cursor:pointer;text-align:center;font-weight:800;padding:5px 4px;border:1px solid var(--border,#e2e8f0);background:'+(COL[s]||'')+'">'+s+'</td>'}).join('')+'</tr>'});
  w.innerHTML=t+'</table>';host.appendChild(w);var info=el('div','note','Kliknij komórkę tabeli.');host.appendChild(info);
  host.appendChild(el('div','note','<b>R</b> — rozpuszczalny · <b>T</b> — trudno rozpuszczalny · <b>N</b> — praktycznie nierozpuszczalny (wytrąca się jako osad) · <b>—</b> — nie istnieje w wodzie lub rozkłada się (hydroliza, redoks). Wiersze F⁻ i SiO₃²⁻ — orientacyjnie.'));
  w.addEventListener('click',function(e){var td=e.target.closest('td[data-c]');if(!td)return;var k=I.compound(td.dataset.c,td.dataset.a);if(!k)return;var s=k.sol,leg=T.legend[s]||'';
   var col=null;try{var ppt=(C.COLORS.list('precipitate')||[]).find(function(r){return r.name&&r.name.replace(/[₀-₉]/g,function(ch){return '₀₁₂₃₄₅₆₇₈₉'.indexOf(ch)})===k.formula});col=ppt&&ppt.hex}catch(_){}
   info.innerHTML='<b style="font-size:16px">'+k.pretty+'</b> — '+k.name+'<br>'+s+': '+leg+(col?'<br>Barwa osadu: <span style="display:inline-block;width:14px;height:14px;border-radius:3px;vertical-align:-2px;border:1px solid #9aa;background:'+col+'"></span> '+((C.COLORS.list('precipitate').find(function(r){return r.hex===col})||{}).state||''):'')+(s==='N'||s==='T'?'<br><i>Powstaje jako osad w reakcji strąceniowej, gdy w roztworze spotkają się jony '+T.cations.find(function(c){return c.id===td.dataset.c}).ion+' i '+T.anions.find(function(a){return a.id===td.dataset.a}).ion+'.</i>':'')})}});
})();
