;/* ===== v0.45: 'stech-kalkulator-v01' — kalkulator stechiometryczny na reakcjach silnika (CHE.STECH). ===== */
(function(){
var C=window.CHE,V=C&&C.VIEW;if(!V||!V.define)return;
var el=function(t,c,h){var e=document.createElement(t);if(c)e.className=c;if(h!=null)e.innerHTML=h;return e};
var SUB='₀₁₂₃₄₅₆₇₈₉',pf=function(s){return String(s).replace(/\d/g,function(d){return SUB[d]})},fm=function(v,d){return isFinite(v)?(Math.round(v*Math.pow(10,d))/Math.pow(10,d)).toString().replace('.',','):'—'};
var GROUPS=[['tlenki (N01)',/O2$|O2Inc|H2o$|Decomp|O2Soot|cuoH2|cuoC|fe2o3|termit|Naoh|Hcl|H2so4|caoCo2|na2oCo2/],['wszystkie',/.*/]];
V.define('stech-kalkulator-v01',{title:'Kalkulator stechiometryczny — masa, mole, objętość gazu, odczynnik limitujący',tag:'CHE',
 hint:'Wybierz reakcję z bazy silnika i podaj masę (lub mole / objętość gazu) jednej substancji. Kalkulator pokazuje tok rozumowania: n = m/M → stosunek współczynników → m = n·M, a na końcu sprawdza prawo zachowania masy. Tryb „limitujący”: podaj masy dwóch substratów.',
 foot:'CHE.STECH (jedno źródło obliczeń) · równania: CHE.REACTION · masy molowe: CHE.CHEM.molarMass (ELEMENTS_118) · V gazu w warunkach normalnych: 22,4 dm³/mol.',
 build:function(host){host.innerHTML='';var S=C.STECH,D=C.DATA,st={k:'mgO2',mode:'calc'};
  var bar=el('div','r');host.appendChild(bar);var gs=el('select');GROUPS.forEach(function(g,i){var o=el('option',null,g[0]);o.value=i;gs.appendChild(o)});var lg=el('label',null,'grupa ');lg.appendChild(gs);bar.appendChild(lg);
  var rs=el('select');rs.style.maxWidth='360px';var lr=el('label',null,'reakcja ');lr.appendChild(rs);bar.appendChild(lr);
  var mb=el('button',null,'tryb: obliczenia');mb.type='button';bar.appendChild(mb);
  var inp=el('div','r');host.appendChild(inp);var out=el('div');host.appendChild(out);
  function fill(){var re=GROUPS[+gs.value][1];rs.innerHTML='';Object.keys(D.REACTIONS).filter(function(k){return re.test(k)}).forEach(function(k){var e='';try{e=C.REACTION.equation(k)}catch(_){}var o=el('option',null,pf(e).replace(/(^|\s)([₀-₉]+)\s/g,function(m,a,b){return a+b.replace(/[₀-₉]/g,function(c){return SUB.indexOf(c)})+' '}));o.value=k;rs.appendChild(o)});if(rs.querySelector('option[value="'+st.k+'"]'))rs.value=st.k;else st.k=rs.value;form()}
  function sp(){var r=D.REACTIONS[st.k];return r.reactants.map(function(x){return x.formula}).concat(r.products.map(function(x){return x.formula}))}
  function form(){inp.innerHTML='';var L=sp();if(st.mode==='calc'){var s1=el('select');L.forEach(function(f){var o=el('option',null,pf(f));o.value=f;s1.appendChild(o)});var q=el('input');q.type='number';q.value='10';q.step='any';q.style.width='90px';var u=el('select');[['m','g'],['n','mol'],['V','dm³ (gaz)']].forEach(function(x){var o=el('option',null,x[1]);o.value=x[0];u.appendChild(o)});
    var l1=el('label',null,'dane: ');l1.append(s1,q,u);inp.appendChild(l1);var go=el('button','on','Oblicz');go.type='button';inp.appendChild(go);go.onclick=function(){var o={f:s1.value};o[u.value]=+q.value;show(S.compute(st.k,o))};q.oninput=go.onclick;s1.onchange=go.onclick;u.onchange=go.onclick;go.onclick()}
   else{var r=D.REACTIONS[st.k],ins={};r.reactants.forEach(function(x){var q=el('input');q.type='number';q.step='any';q.value='10';q.style.width='80px';ins[x.formula]=q;var l=el('label',null,'m('+pf(x.formula)+') [g] ');l.appendChild(q);inp.appendChild(l);q.oninput=calc});function calc(){var a={};Object.keys(ins).forEach(function(f){a[f]=+ins[f].value});var res=S.limiting(st.k,a);if(!res){out.innerHTML='';return}show(res.result,res)}calc()}}
  function show(r,lim){if(!r){out.innerHTML='<div class="note">Brak danych.</div>';return}var e='';try{e=C.REACTION.equation(st.k)}catch(_){}
   out.innerHTML='<div style="font:700 16px ui-monospace,monospace;margin:8px 0">'+e.replace(/([A-Za-z\)\]])(\d+)/g,function(m,a,n){return a+pf(n)})+'</div>'+(lim?'<div class="note"><b>Odczynnik limitujący: '+pf(lim.limiting)+'</b> (najmniejszy stosunek n/współczynnik: '+lim.table.map(function(t){return pf(t.f)+' '+fm(t.n,4)+'/'+t.c+' = '+fm(t.ratio,4)}).join(' · ')+')'+(lim.excess.length?'<br>W nadmiarze zostaje: '+lim.excess.map(function(x){return pf(x.f)+' '+fm(x.m,2)+' g'}).join(', '):'')+'</div>':'')+
    '<div style="overflow-x:auto"><table style="border-collapse:collapse;font-size:14px;margin:6px 0"><tr>'+['substancja','współcz.','M [g/mol]','n [mol]','m [g]','V [dm³]'].map(function(h){return'<th style="padding:4px 10px;text-align:left;border-bottom:1px solid #cbd5e1">'+h+'</th>'}).join('')+'</tr>'+r.rows.map(function(x){return'<tr><td style="padding:4px 10px">'+pf(x.f)+(x.side==='s'?' <small>(substrat)</small>':' <small>(produkt)</small>')+'</td><td style="padding:4px 10px">'+x.coef+'</td><td style="padding:4px 10px">'+fm(x.M,2)+'</td><td style="padding:4px 10px">'+fm(x.n,4)+'</td><td style="padding:4px 10px"><b>'+fm(x.m,2)+'</b></td><td style="padding:4px 10px">'+(x.V!=null?fm(x.V,2):'')+'</td></tr>'}).join('')+'</table></div>'+
    '<div class="note"><b>Tok rozumowania:</b><br>'+r.steps.join('<br>')+'</div><div class="note" style="opacity:.8">W zadaniach szkolnych zwykle zaokrągla się masy atomowe (Mg = 24, O = 16) — wynik może różnić się w drugim miejscu po przecinku.</div>'}
  gs.onchange=fill;rs.onchange=function(){st.k=rs.value;form()};mb.onclick=function(){st.mode=st.mode==='calc'?'lim':'calc';mb.textContent='tryb: '+(st.mode==='calc'?'obliczenia':'odczynnik limitujący');form()};fill()}});
})();
