/* ===== SILNIK EFEKTÓW SWOBODNYCH (free): płomień, iskry, spalanie metalu, wybuch, błysk =====
   Opcje: defaults + schema (UI generowane automatycznie: GFX.optionsPanel). Włączanie: st.fx={id:opcje|true}; jednorazowe: GFX.trigger(pool,id,opcje). */
const lg=(c,k)=>c.map(v=>Math.round(v+(255-v)*k));
const FLAME_COLORS=(C.PHYS&&C.PHYS.flameColors())||{Li:[225,45,70],Na:[255,196,40],K:[190,125,235],Ca:[255,115,45],Sr:[245,40,45],Ba:[150,225,95],Cu:[50,225,165]};/* v1.6: jedno źródło CHE.COLORS przez CHE.PHYS */
const FLAME_NAMES=(C.PHYS&&C.PHYS.flameNames())||{};
const METALS={Mg:{flame:[255,255,255],glow:[255,252,240],ash:[240,240,235],smoke:[240,240,240],sparks:[255,250,225],dur:7,bright:1.5,sparkRate:45,ribbon:'#aab3bb'},Fe:{flame:[255,185,70],glow:[255,170,60],ash:[55,45,42],smoke:[100,95,92],sparks:[255,205,95],dur:10,bright:.65,sparkRate:75,ribbon:'#6b7280'},Na:{flame:[255,200,40],glow:[255,225,120],ash:[235,235,230],smoke:[235,235,230],sparks:[255,215,70],dur:6,bright:1,sparkRate:20,ribbon:'#cbd5e1'},Zn:{flame:[170,235,255],glow:[220,250,255],ash:[240,240,240],smoke:[235,240,245],sparks:[200,240,255],dur:8,bright:.9,sparkRate:25,ribbon:'#94a3b8'},Cu:{flame:[50,225,165],glow:[160,255,220],ash:[30,30,32],smoke:[60,90,80],sparks:[90,240,190],dur:9,bright:.7,sparkRate:15,ribbon:'#c2703a'}};
function emit(pool,n,o,x,y){const sp=pool.sp=pool.sp||[];for(let i=0;i<n&&sp.length<700;i++){const an=(o.angle||0)*Math.PI/180+(Math.random()-.5)*(o.spread==null?1:o.spread),v=o.speed*(.35+Math.random()*.85);sp.push({x,y,vx:Math.cos(an)*v,vy:Math.sin(an)*v,life:o.life*(.5+Math.random()*.7),age:0,col:o.color,g:o.gravity,s:o.size*(.6+Math.random()*.8)})}}
function trigger(pool,id,opts){const f=E[id];if(!f)return null;const o=Object.assign({},f.defaults,opts||{}),ev={id,o,age:0,dur:o.dur||f.dur||.5,fired:0};(pool.events=pool.events||[]).push(ev);return ev}
effect('flame',{free:true,layer:'front',label:'Płomień',defaults:{power:1,phi:1,soot:0,temp:1200,color:null,size:1,flicker:1,glow:1,fuel:'CH4',salt:'',diffusion:false},schema:{fuel:{t:'select',opts:['CH4','C3H8','C4H10','C2H5OH','H2','CO','C2H2','C25H52'],l:'Paliwo (CHE.PHYS)'},power:{t:'range',min:0,max:1,step:.05,l:'Moc'},phi:{t:'range',min:.4,max:2,step:.05,l:'φ mieszanki (1/λ)'},salt:{t:'select',opts:['','Li','Na','K','Ca','Sr','Ba','Cu','B'],l:'Sól w płomieniu (próba płomieniowa)'},soot:{t:'range',min:0,max:1,step:.05,l:'Kopcenie (min.)'},size:{t:'range',min:.4,max:2,step:.05,l:'Rozmiar'},flicker:{t:'range',min:0,max:3,step:.1,l:'Migotanie'},glow:{t:'range',min:0,max:3,step:.1,l:'Poświata'},color:{t:'color',l:'Barwa wymuszona'}},
/* v1.6: barwa, sadza, temperatura, widoczność i migotanie liczone w CHE.PHYS.flame (jedno źródło dla palnika, lampy, lekcji, Atlasu) */
draw:e=>{const c=e.c,o=e.o,t=e.t,cx=e.anchor.x,top=e.anchor.y,P=Math.max(0,Math.min(1,o.power));if(P<.03)return;
const PH=C.PHYS,F=PH?PH.flame({fuel:o.fuel||'CH4',phi:o.phi,power:P,soot:o.soot,salt:o.salt||null,diffusion:o.diffusion}):null;e.pool.flameInfo=F;
const phi=F?F.phi:o.phi,soot=F?F.soot:o.soot,hk=F?F.h:P*(.55+.45*Math.min(1,o.temp/1800)),H=(60+125*Math.min(1.6,hk))*o.size,W=(10+28*P*(phi>1.15?1.25:1))*o.size,hz=F?F.flickerHz:8,
 fl=(Math.sin(t/1000*6.283*hz*.5)*W*.08+Math.sin(t/1000*6.283*hz*1.3)*W*.04)*o.flicker,col=o.color,al=F?F.alpha:1;
const rich=soot>.3,outer=col?[col.map(Math.round).join(','),col.map(v=>v*.75|0).join(',')]:F?[F.outer.join(','),F.outer.map(v=>v*.8|0).join(',')]:rich?['255,200,70','255,150,35']:['190,225,255','95,160,255'],
 core=col?[lg(col,.7).join(','),lg(col,.35).join(',')]:F?[F.core.join(','),lg(F.core,.35).join(',')]:rich?['255,235,150','255,190,60']:['40,90,230','110,170,255'];
const gl=c.createRadialGradient(cx,top-H*.4,2,cx,top-H*.4,H*1.1);gl.addColorStop(0,'rgba('+outer[1]+','+Math.min(1,.22*P*o.glow*(rich?1.5:1)*al)+')');gl.addColorStop(1,'rgba('+outer[1]+',0)');c.fillStyle=gl;c.fillRect(cx-H*1.2,top-H*1.6,H*2.4,H*2.2);
const body=(k,cl,a,wk)=>{const w=W*(wk||k),h=H*k;c.beginPath();c.moveTo(cx-w,top);c.bezierCurveTo(cx-w*1.15,top-h*.4,cx-w*.45+fl,top-h*.8,cx+fl*1.6,top-h);c.bezierCurveTo(cx+w*.45+fl,top-h*.8,cx+w*1.15,top-h*.4,cx+w,top);c.closePath();const g=c.createLinearGradient(0,top,0,top-h);g.addColorStop(0,'rgba('+cl[0]+','+a+')');g.addColorStop(1,'rgba('+cl[1]+','+(a*.35)+')');c.fillStyle=g;c.fill()};
c.save();c.shadowColor='rgba('+outer[1]+','+(.85*al)+')';c.shadowBlur=18;body(1,outer,.78*al);c.restore();
/* stożek wewnętrzny (premiks): wysokość ~ przepływ / prędkość spalania SL */
const cone=F?(F.cone>0?.25+F.cone*.55:.45):.52;body(cone,core,.9*Math.max(.35,al),F&&F.cone>0?.62:cone);
if(soot>.45){c.fillStyle='rgba(40,40,40,'+(.12+.2*soot)+')';for(let i=0;i<7;i++){const u=((t/1600)+i*.14)%1;c.beginPath();c.arc(cx+(i-3)*9+Math.sin(t/300+i)*5,top-H*.9-u*60,3+i%2+u*3,0,7);c.fill()}}}});
effect('sparks',{free:true,layer:'front',label:'Iskry',defaults:{rate:40,color:[255,215,120],speed:260,gravity:700,spread:1.3,life:.9,size:2,angle:-90,count:60},schema:{rate:{t:'range',min:0,max:200,step:5,l:'Natężenie'},color:{t:'color',l:'Barwa'},speed:{t:'range',min:60,max:700,step:10,l:'Prędkość'},gravity:{t:'range',min:0,max:1600,step:50,l:'Grawitacja'},spread:{t:'range',min:.1,max:6.28,step:.1,l:'Rozrzut'},life:{t:'range',min:.2,max:2.5,step:.1,l:'Czas życia'},size:{t:'range',min:.5,max:5,step:.1,l:'Grubość'}},alive:p=>p.sp&&p.sp.length>0,
draw:e=>{const c=e.c,o=e.o,p=e.pool,a=e.anchor,sp=p.sp=p.sp||[],dt=e.dt;if(e.active)emit(p,Math.floor(o.rate*dt+Math.random()),o,a.x,a.y);e.evs.forEach(v=>{if(!v.fired){v.fired=1;emit(p,v.o.count||60,v.o,v.o.x==null?a.x:v.o.x,v.o.y==null?a.y:v.o.y)}});
c.globalCompositeOperation='lighter';c.lineCap='round';for(let i=sp.length-1;i>=0;i--){const q=sp[i];q.age+=dt;if(q.age>q.life){sp.splice(i,1);continue}q.vy+=q.g*dt;const px=q.x,py=q.y;q.x+=q.vx*dt;q.y+=q.vy*dt;const k=1-q.age/q.life;c.strokeStyle=rgba(q.col,k);c.lineWidth=q.s*k+.3;c.beginPath();c.moveTo(px-q.vx*.012,py-q.vy*.012);c.lineTo(q.x,q.y);c.stroke()}c.globalCompositeOperation='source-over'}});
effect('metalBurn',{free:true,layer:'front',label:'Spalanie metalu',defaults:{metal:'Mg',power:1,progress:null,sparks:1,smoke:1,glow:1},schema:{metal:{t:'select',opts:['Mg','Fe','Na','Zn','Cu'],l:'Metal'},power:{t:'range',min:.2,max:2,step:.1,l:'Intensywność'},glow:{t:'range',min:0,max:2,step:.1,l:'Blask'},sparks:{t:'range',min:0,max:3,step:.1,l:'Iskry'},smoke:{t:'range',min:0,max:3,step:.1,l:'Dym tlenku'}},alive:p=>p.mb&&p.mb.k>0,
draw:e=>{const c=e.c,o=e.o,a=e.anchor,t=e.t,dt=e.dt,pb=e.pool.mb=e.pool.mb||{k:0,sm:[]};if(e.active)pb.metal=o.metal;const M=METALS[pb.metal||o.metal]||METALS.Mg;if(o.progress!=null)pb.k=o.progress;else if(e.active)pb.k=Math.min(1,pb.k+dt*o.power/M.dur);
const burning=e.active&&pb.k<1,xs=a.x-70,len=64*(1-pb.k*.94),ex=xs+len;c.strokeStyle=e.T.glass;c.lineWidth=3;c.lineCap='round';c.beginPath();c.moveTo(xs-34,a.y-52);c.lineTo(xs,a.y);c.stroke();c.strokeStyle=M.ribbon;c.lineWidth=3.5;c.beginPath();c.moveTo(xs,a.y);c.lineTo(ex,a.y);c.stroke();
const fy=e.r.y+e.r.h-12;c.fillStyle=rgba(M.ash,.95);c.beginPath();c.ellipse(a.x,fy,10+42*pb.k,2+9*pb.k,0,0,7);c.fill();
if(burning){const fl=.75+.25*Math.sin(t/35)+.15*Math.sin(t/13),R=(40+90*o.power)*fl*o.glow*M.bright;c.globalCompositeOperation='lighter';const g=c.createRadialGradient(ex,a.y,1,ex,a.y,R);g.addColorStop(0,rgba(M.glow,1));g.addColorStop(.25,rgba(M.flame,.55));g.addColorStop(1,rgba(M.flame,0));c.fillStyle=g;c.beginPath();c.arc(ex,a.y,R,0,7);c.fill();c.globalCompositeOperation='source-over';c.fillStyle='#fff';c.beginPath();c.arc(ex,a.y,3+3*fl,0,7);c.fill();
if(o.sparks)emit(e.pool,Math.floor(M.sparkRate*o.sparks*dt+Math.random()),{angle:-90,spread:6.28,speed:200,gravity:500,life:.7,color:M.sparks,size:1.8},ex,a.y);if(o.smoke&&Math.random()<dt*14*o.smoke)pb.sm.push({x:ex,y:a.y,r:6,a:.5,vx:(Math.random()-.5)*14})}
for(let i=pb.sm.length-1;i>=0;i--){const q=pb.sm[i];q.y-=26*dt;q.x+=q.vx*dt;q.r+=10*dt;q.a-=.18*dt;if(q.a<=0){pb.sm.splice(i,1);continue}c.fillStyle=rgba(M.smoke,q.a);c.beginPath();c.arc(q.x,q.y,q.r,0,7);c.fill()}}});
effect('explosion',{free:true,oneShot:true,layer:'front',label:'Wybuch',defaults:{size:1,color:[255,170,60],dur:1.3,smoke:1,smokeColor:[70,70,75],shock:1,flash:1,debris:70,shake:1},schema:{size:{t:'range',min:.4,max:2.5,step:.1,l:'Rozmiar'},color:{t:'color',l:'Barwa ognia'},dur:{t:'range',min:.5,max:3,step:.1,l:'Czas [s]'},smoke:{t:'range',min:0,max:2,step:.1,l:'Dym'},smokeColor:{t:'color',l:'Barwa dymu'},shock:{t:'range',min:0,max:2,step:.1,l:'Fala uderzeniowa'},flash:{t:'range',min:0,max:1,step:.05,l:'Błysk'},debris:{t:'range',min:0,max:200,step:5,l:'Odłamki / iskry'},shake:{t:'range',min:0,max:3,step:.1,l:'Drżenie'}},
draw:e=>{const c=e.c,a=e.anchor;e.evs.forEach(v=>{const o=v.o,k=Math.min(1,v.age/o.dur),R=(30+150*Math.sqrt(k))*o.size,x=o.x==null?a.x:o.x,y=o.y==null?a.y:o.y;if(!v.fired){v.fired=1;emit(e.pool,o.debris,{angle:-90,spread:6.28,speed:380*o.size,gravity:900,life:1.1,color:lg(o.color,.35),size:2.6},x,y)}
if(o.flash&&v.age<.18){c.fillStyle='rgba(255,255,255,'+(.85*o.flash*(1-v.age/.18))+')';c.fillRect(x-2000,y-2000,4000,4000)}
const al=Math.pow(1-k,.8),g=c.createRadialGradient(x,y,0,x,y,R);g.addColorStop(0,'rgba(255,255,240,'+al+')');g.addColorStop(.35,rgba(o.color,.85*al));g.addColorStop(1,rgba(o.color.map(q=>q*.5),0));c.fillStyle=g;c.beginPath();c.arc(x,y,R,0,7);c.fill();
if(o.shock){c.strokeStyle='rgba(255,255,255,'+(.6*(1-k)*Math.min(1,o.shock))+')';c.lineWidth=3*(1-k)+1;c.beginPath();c.arc(x,y,R*1.7,0,7);c.stroke()}
if(o.smoke&&k>.2){const u=(k-.2)/.8;for(let i=0;i<10;i++){const an=rnd(i+3)*6.28,d=R*(.5+rnd(i)*.6);c.beginPath();c.arc(x+Math.cos(an)*d*.7,y-u*90*o.size+Math.sin(an)*d*.4,(14+rnd(i+9)*22)*o.size*(.6+u),0,7);c.fillStyle=rgba(o.smokeColor,.4*Math.min(1,o.smoke)*(1-u));c.fill()}}})}});
effect('flash',{free:true,oneShot:true,layer:'front',label:'Błysk',defaults:{color:[255,255,255],dur:.35,alpha:.8},schema:{color:{t:'color',l:'Barwa'},dur:{t:'range',min:.1,max:1.5,step:.05,l:'Czas [s]'},alpha:{t:'range',min:.1,max:1,step:.05,l:'Jasność'}},draw:e=>{const c=e.c,a=e.anchor;e.evs.forEach(v=>{c.fillStyle=rgba(v.o.color,v.o.alpha*(1-v.age/v.dur));c.fillRect(a.x-2000,a.y-2000,4000,4000)})}});
function hexOf(c){return '#'+c.map(v=>('0'+Math.round(v).toString(16)).slice(-2)).join('')}
function rgbOf(h){return[1,3,5].map(i=>parseInt(h.substr(i,2),16))}
function optionsPanel(host,id,o,cb){host.innerHTML='';const f=E[id];if(!f||!f.schema)return;const d=f.defaults||{};Object.keys(f.schema).forEach(k=>{const s=f.schema[k],row=document.createElement('label');row.style.cssText='display:grid;grid-template-columns:120px 1fr auto;gap:6px;align-items:center;font-size:12px';row.innerHTML='<span>'+s.l+'</span>';let inp;
if(s.t==='range'){inp=document.createElement('input');inp.type='range';inp.min=s.min;inp.max=s.max;inp.step=s.step||.05;inp.value=o[k]!=null?o[k]:d[k];const out=document.createElement('output');out.textContent=inp.value;inp.oninput=()=>{o[k]=+inp.value;out.textContent=inp.value;cb&&cb(k)};row.append(inp,out)}
else if(s.t==='color'){inp=document.createElement('input');inp.type='color';inp.value=hexOf(o[k]||d[k]||[255,200,60]);inp.oninput=()=>{o[k]=rgbOf(inp.value);cb&&cb(k)};const b=document.createElement('button');b.type='button';b.textContent='auto';b.onclick=()=>{delete o[k];if(d[k])inp.value=hexOf(d[k]);cb&&cb(k)};row.append(inp,b)}
else{inp=document.createElement('select');(s.opts||[]).forEach(x=>{const q=document.createElement('option');q.value=q.textContent=x;inp.appendChild(q)});inp.value=o[k]||d[k];inp.onchange=()=>{o[k]=inp.value;cb&&cb(k)};row.append(inp,document.createElement('span'))}
host.appendChild(row)})}
const PRESETS=[{label:'Spalanie magnezu',id:'metalBurn',o:{metal:'Mg'}},{label:'Wełna stalowa (iskry)',id:'metalBurn',o:{metal:'Fe'}},{label:'Spalanie sodu (żółty)',id:'metalBurn',o:{metal:'Na'}},{label:'Spalanie miedzi (zielone)',id:'metalBurn',o:{metal:'Cu'}},{label:'Płomień — metan',id:'flame',o:{phi:1,power:.8}},{label:'Płomień — kopcący',id:'flame',o:{phi:1.4,soot:.6,power:.9}},{label:'Płomień — lit (czerwony)',id:'flame',o:{color:FLAME_COLORS.Li,power:.8}},{label:'Płomień — sód (żółty)',id:'flame',o:{color:FLAME_COLORS.Na,power:.8}},{label:'Płomień — potas (fioletowy)',id:'flame',o:{color:FLAME_COLORS.K,power:.8}},{label:'Płomień — bar (zielony)',id:'flame',o:{color:FLAME_COLORS.Ba,power:.8}},{label:'Płomień — miedź (niebieskozielony)',id:'flame',o:{color:FLAME_COLORS.Cu,power:.8}},{label:'Wybuch H₂ + O₂ (niebieski)',id:'explosion',o:{color:[140,185,255],size:1.1,smoke:.5,smokeColor:[190,200,215]}},{label:'Wybuch — ognisty',id:'explosion',o:{}},{label:'Iskry',id:'sparks',o:{rate:90}},{label:'Błysk',id:'flash',o:{}}];
vessel('stage',{custom:(c,r,st,env)=>{const T=env.th,ax=r.x+r.w/2,ay=r.y+r.h*.72,fy=r.y+r.h-8;c.strokeStyle=T.glass;c.lineWidth=4;c.lineCap='round';c.beginPath();c.moveTo(r.x+r.w*.12,fy);c.lineTo(r.x+r.w*.88,fy);c.stroke();c.fillStyle=T.dark?'#475569':'#94a3b8';c.fillRect(ax-3,ay+4,6,fy-ay-4);return{x:ax,y:ay}}});
