# -*- coding: utf-8 -*-
"""N04 Sole v1.0 — lekcja zbudowana na danych silnika (CHE.IONIC, SOLUBILITY_TABLE, CHE.REACTION).
Każde równanie z silnika ma atrybut data-rx="klucz" — audyt CHE.CONSISTENCY porównuje tekst z CHE.REACTION.equation()."""
import os, re, json
D = os.path.dirname(os.path.abspath(__file__))
kw = open(os.path.join(D, 'kw_new.html'), encoding='utf-8').read()
VIZ_CSS = re.search(r'<style id="che-lesson-viz-ref-style">.*?</style>', kw, re.S).group(0)
V15_CSS = re.search(r'<style id="kw-v15-style">.*?</style>', kw, re.S).group(0)

def viz(vid, title, sub='Silnik CHE · otwiera się w oknie'):
    return ('<div class="che-lesson-viz-ref" data-che-lesson-viz="%s"><button type="button" data-che-open-viz="%s" '
            'onclick="parent.postMessage({type:\'CHE_LESSON_OPEN_VISUAL\',visualId:\'%s\',lessonId:\'N04\'},\'*\')"><b>%s</b><span>%s</span></button></div>\n') % (vid, vid, vid, title, sub)
def adv(title, body):
    return '<details class="adv"><summary>%s <span class="adv-tag">poziom akademicki · poza maturą rozszerzoną</span></summary><div class="adv-body">%s</div></details>\n' % (title, body)
def eq(key, text, note=''):
    return '<div class="formula-lg" data-rx="%s">%s</div>%s\n' % (key, text, ('<p class="mini-note">%s</p>' % note) if note else '')
def card(cls, label, body):
    return '<div class="card %s"><span class="card-label">%s</span>%s</div>\n' % (cls, label, body)
def sec(n, title, body):
    return '<section id="s%s">\n<div class="part-heading"><span class="part-num">%s</span> %s</div>\n%s</section>\n\n' % (n, n, title, body)
def exp(title, rows):
    return '<div class="exp-card"><h5>%s</h5><div class="exp-grid">%s</div></div>\n' % (title, ''.join('<b>%s</b><span%s>%s</span>' % (k, ' class="formula"' if k == 'Równanie' else '', v) for k, v in rows))
def table(head, rows):
    return '<div class="table-wrap"><table><thead><tr>%s</tr></thead><tbody>%s</tbody></table></div>' % (''.join('<th>%s</th>' % h for h in head), ''.join('<tr>%s</tr>' % ''.join('<td>%s</td>' % c for c in r) for r in rows))

S = []
# ---------------- 0. minimum ----------------
MIN = '''<section class="minimum-card" id="minimum"><h3>Muszę umieć na E8 — 10 faktów</h3><ol>
<li><strong>Sól</strong> to związek zbudowany z kationów metalu (lub NH₄⁺) i anionów reszty kwasowej; wzór ogólny M<sub>n</sub>R<sub>m</sub>. W stanie stałym — <strong>kryształ jonowy</strong>.</li>
<li><strong>Wzór</strong>: suma ładunków = 0 (Al³⁺ + SO₄²⁻ → Al₂(SO₄)₃). <strong>Nazwa</strong>: reszta kwasowa + metal (+ wartościowość, gdy zmienna): siarczan(VI) żelaza(III).</li>
<li><strong>Dysocjacja</strong> soli rozpuszczalnych: Al₂(SO₄)₃ → 2 Al³⁺ + 3 SO₄²⁻.</li>
<li><strong>Tabela rozpuszczalności</strong>: R — rozpuszczalna, T — trudno, N — nierozpuszczalna (wytrąca się jako osad).</li>
<li><strong>Otrzymywanie</strong>: metal + kwas · tlenek metalu + kwas · wodorotlenek + kwas · metal + niemetal · tlenek metalu + tlenek niemetalu · wodorotlenek + tlenek niemetalu · sól + kwas · sól + zasada · sól + sól · metal + sól.</li>
<li><strong>Reakcja strąceniowa</strong> zachodzi, gdy jeden z produktów jest nierozpuszczalny: Ag⁺ + Cl⁻ → AgCl↓.</li>
<li><strong>Wypieranie metali</strong>: metal aktywniejszy wypiera mniej aktywny z roztworu soli: Zn + CuSO₄ → ZnSO₄ + Cu.</li>
<li><strong>Zapis jonowy</strong>: cząsteczkowy → jonowy pełny → jonowy skrócony (bez jonów obserwatorów).</li>
<li><strong>Ważne sole</strong>: NaCl, CaCO₃ (wapień, marmur, kreda), CaSO₄·2H₂O (gips), Na₂CO₃, NaHCO₃, saletry (KNO₃, NaNO₃), fosforany (nawozy, kości).</li>
<li><strong>BHP</strong>: AgNO₃ plami i parzy skórę, sole baru i ołowiu są trujące, CaO i Ca(OH)₂ — żrące (okulary).</li>
</ol></section>'''

S.append(sec(1, 'Budowa i definicja soli', card('card-core', 'Definicja', '<p><strong>Sól</strong> — związek chemiczny zbudowany z <strong>kationów metalu</strong> (lub kationu amonu NH₄⁺) i <strong>anionów reszty kwasowej</strong>.</p><div class="formula-lg">M<sub>n</sub>R<sub>m</sub>  (n · ładunek kationu = m · |ładunek anionu|)</div><p>W stanie stałym sól tworzy <strong>kryształ jonowy</strong>: jony ułożone regularnie, przyciągane siłami elektrostatycznymi. Stąd wysokie temperatury topnienia (NaCl — 801 °C), kruchość i przewodzenie prądu w stopie i w roztworze.</p>')
 + card('card-understand', 'Skąd biorą się sole?', '<p>Sól powstaje, gdy H z kwasu zostaje „zastąpiony” metalem: HCl → NaCl, H₂SO₄ → Na₂SO₄ (sól obojętna) lub NaHSO₄ (sól <strong>wodorowa</strong> — zastąpiono tylko część H). Z drugiej strony grupy OH z wodorotlenku zastępuje reszta kwasowa.</p>')
 + viz('ion-map-v02', 'Mapa jonów — ładunki, pochodzenie, wykrywanie', 'Dane: tabela rozpuszczalności i kwasy z silnika')))

S.append(sec(2, 'Wzory i nazwy soli', card('card-basic', 'Reguła wzoru — krzyżowanie ładunków', '<ol><li>Zapisz jony z ładunkami: Fe³⁺ i SO₄²⁻.</li><li>„Skrzyżuj” wartości ładunków jako indeksy: Fe₂(SO₄)₃.</li><li>Skróć, jeśli się da (Ca²⁺ + CO₃²⁻ → CaCO₃, nie Ca₂(CO₃)₂).</li><li>Sprawdź: 2·(+3) + 3·(−2) = 0 ✓. Jon wieloatomowy w nawiasie, gdy jest go więcej niż jeden.</li></ol>')
 + table(['Reszta (kwas)', 'Anion', 'Nazwa soli', 'Przykład'], [['HCl', 'Cl⁻', 'chlorek', 'NaCl — chlorek sodu'], ['H₂S', 'S²⁻', 'siarczek', 'FeS — siarczek żelaza(II)'], ['HNO₃', 'NO₃⁻', 'azotan(V)', 'KNO₃ — azotan(V) potasu'], ['H₂SO₃', 'SO₃²⁻', 'siarczan(IV)', 'Na₂SO₃ — siarczan(IV) sodu'], ['H₂SO₄', 'SO₄²⁻', 'siarczan(VI)', 'CuSO₄ — siarczan(VI) miedzi(II)'], ['H₂CO₃', 'CO₃²⁻', 'węglan', 'CaCO₃ — węglan wapnia'], ['H₃PO₄', 'PO₄³⁻', 'fosforan(V)', 'Ca₃(PO₄)₂ — fosforan(V) wapnia'], ['H₂SiO₃', 'SiO₃²⁻', 'krzemian', 'Na₂SiO₃ — krzemian sodu'], ['CH₃COOH', 'CH₃COO⁻', 'octan', 'CH₃COONa — octan sodu']])
 + card('card-understand', 'Wartościowość metalu w nazwie', '<p>Dla metali o zmiennej wartościowości podajemy ją cyfrą rzymską: FeCl₂ — chlorek żelaza(II), FeCl₃ — chlorek żelaza(III), CuSO₄ — siarczan(VI) miedzi(II). Dla Na, K, Mg, Ca, Ba, Al, Zn, Ag — nie podajemy.</p>')
 + card('card-extra', 'LO — sole wodorowe, hydroksosole, hydraty', '<ul><li><strong>Wodorosole</strong>: NaHCO₃ — wodorowęglan sodu, NaHSO₄ — wodorosiarczan(VI) sodu, NaH₂PO₄ — diwodorofosforan(V) sodu.</li><li><strong>Hydroksosole</strong>: Mg(OH)Cl — chlorek wodorotlenek magnezu.</li><li><strong>Hydraty</strong>: CuSO₄·5H₂O — siarczan(VI) miedzi(II)—woda(1/5), CaSO₄·2H₂O — gips.</li></ul>')
 + viz('tabela-rozpuszczalnosci-v01', 'Tabela rozpuszczalności — każda komórka podaje wzór i nazwę soli')))

S.append(sec(3, 'Dysocjacja soli i tabela rozpuszczalności', card('card-basic', 'Dysocjacja (sole rozpuszczalne)', '<div class="formula-lg">NaCl → Na⁺ + Cl⁻</div><div class="formula-lg">K₂SO₄ → 2 K⁺ + SO₄²⁻</div><div class="formula-lg">Al₂(SO₄)₃ → 2 Al³⁺ + 3 SO₄²⁻</div><div class="formula-lg">Ca(NO₃)₂ → Ca²⁺ + 2 NO₃⁻</div><p class="mini-note">Sole są mocnymi elektrolitami: to, co się rozpuściło, jest całkowicie zdysocjowane. Sól nierozpuszczalna (np. CaCO₃) praktycznie nie daje jonów w roztworze.</p>')
 + card('card-core', 'Jak czytać tabelę rozpuszczalności', '<ul><li><strong>R</strong> — rozpuszczalny (&gt; 1 g w 100 g wody) · <strong>T</strong> — trudno rozpuszczalny (0,1–1 g) · <strong>N</strong> — nierozpuszczalny (&lt; 0,1 g) · <strong>—</strong> — nie istnieje w wodzie / rozkłada się.</li><li>Zawsze rozpuszczalne: sole sodu, potasu, amonu i <strong>wszystkie azotany(V)</strong>.</li><li>Chlorki — rozpuszczalne poza AgCl (N) i PbCl₂ (T). Siarczany(VI) — poza BaSO₄, PbSO₄ (N) oraz CaSO₄, Ag₂SO₄ (T).</li><li>Węglany, fosforany(V), siarczki — w większości nierozpuszczalne (poza Na, K, NH₄).</li></ul>')
 + viz('tabela-rozpuszczalnosci-v01', 'Interaktywna tabela rozpuszczalności (20 °C)', 'CHE.DATA.SOLUBILITY_TABLE · kliknij komórkę')))

M = [
 ('1. Metal + kwas → sól + wodór', [('znHcl', 'Zn + 2 HCl → ZnCl₂ + H₂↑'), ('mgH2so4', 'Mg + H₂SO₄ → MgSO₄ + H₂↑')], 'Tylko metale przed wodorem w szeregu aktywności.'),
 ('2. Tlenek metalu + kwas → sól + woda', [('cuoH2so4', 'CuO + H₂SO₄ → CuSO₄ + H₂O'), ('caoHcl', 'CaO + 2 HCl → CaCl₂ + H₂O')], ''),
 ('3. Wodorotlenek + kwas → sól + woda (zobojętnianie)', [('hclNaOH', 'HCl + NaOH → NaCl + H₂O'), ('h3po4Caoh2', '2 H₃PO₄ + 3 Ca(OH)₂ → Ca₃(PO₄)₂ + 6 H₂O')], ''),
 ('4. Metal + niemetal → sól kwasu beztlenowego', [('na2Cl2', '2 Na + Cl₂ → 2 NaCl'), ('feS', 'Fe + S → FeS')], ''),
 ('5. Tlenek metalu + tlenek niemetalu → sól kwasu tlenowego', [('caoCo2', 'CaO + CO₂ → CaCO₃')], ''),
 ('6. Wodorotlenek + tlenek niemetalu → sól + woda', [('naohCo2', '2 NaOH + CO₂ → Na₂CO₃ + H₂O'), ('caoh2Co2', 'Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O')], 'Druga reakcja to wykrywanie CO₂ wodą wapienną.'),
 ('7. Sól + kwas → nowa sól + nowy kwas', [('caco3Hcl', 'CaCO₃ + 2 HCl → CaCl₂ + H₂O + CO₂↑'), ('agno3Hcl', 'AgNO₃ + HCl → AgCl↓ + HNO₃')], 'Zachodzi, gdy powstaje gaz, osad lub słabszy kwas.'),
 ('8. Sól + zasada → nowa sól + nowy wodorotlenek', [('cuso4Naoh', 'CuSO₄ + 2 NaOH → Cu(OH)₂↓ + Na₂SO₄'), ('fecl3Naoh', 'FeCl₃ + 3 NaOH → Fe(OH)₃↓ + 3 NaCl')], 'Zachodzi, gdy powstaje osad wodorotlenku.'),
 ('9. Sól + sól → dwie nowe sole', [('agno3Nacl', 'AgNO₃ + NaCl → AgCl↓ + NaNO₃'), ('bacl2Na2so4', 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2 NaCl'), ('pbno32Ki', 'Pb(NO₃)₂ + 2 KI → PbI₂↓ + 2 KNO₃')], 'Obie sole muszą być rozpuszczalne, a jeden produkt — nie.'),
 ('10. Metal + sól → nowa sól + nowy metal (wypieranie)', [('znCuso4', 'Zn + CuSO₄ → ZnSO₄ + Cu'), ('feCuso4', 'Fe + CuSO₄ → FeSO₄ + Cu'), ('cuAgno3', 'Cu + 2 AgNO₃ → Cu(NO₃)₂ + 2 Ag')], 'Metal aktywniejszy (wcześniej w szeregu) wypiera mniej aktywny. Cu + ZnSO₄ — brak reakcji.'),
]
body = card('card-core', 'Mnemonik: 10 dróg do soli', '<p>Zapamiętaj pary substratów: <strong>M+K · TM+K · W+K · M+N · TM+TN · W+TN · S+K · S+Z · S+S · M+S</strong> (M — metal, K — kwas, TM / TN — tlenek metalu / niemetalu, W — wodorotlenek, N — niemetal, S — sól, Z — zasada).</p>')
for t, eqs, note in M:
    body += '<h3>%s</h3>\n<div class="card card-basic">' % t + ''.join(eq(k, x) for k, x in eqs) + ('<p class="mini-note">%s</p>' % note if note else '') + '</div>\n'
body += viz('rownania-jonowe-v01', 'Równania jonowe dla tych reakcji (generowane przez silnik)', 'cząsteczkowe → jonowe pełne → skrócone')
body += viz('sole-doswiadczenia-v01', 'Pracownia: otrzymywanie soli, strącanie, wypieranie metali', 'Zlewki i probówki w silniku GFX')
S.append(sec(4, 'Otrzymywanie soli — 10 metod', body))

S.append(sec(5, 'Reakcje strąceniowe i wykrywanie jonów', card('card-core', 'Reguła', '<p>Mieszamy dwa roztwory soli (lub sól i zasadę/kwas). Jeśli z jonów obecnych w roztworze może powstać związek oznaczony w tabeli jako <strong>N</strong> (lub T) — wytrąca się <strong>osad</strong>. Jony, które się nie zmieniają, to <strong>jony obserwatory</strong>.</p>')
 + card('card-basic', 'Trzy poziomy zapisu — AgNO₃ + NaCl', eq('agno3Nacl', 'AgNO₃ + NaCl → AgCl↓ + NaNO₃') + '<div class="formula-lg">Ag⁺ + NO₃⁻ + Na⁺ + Cl⁻ → AgCl↓ + Na⁺ + NO₃⁻</div><div class="formula-lg">Ag⁺ + Cl⁻ → AgCl↓</div><p class="mini-note">Na⁺ i NO₃⁻ — jony obserwatory.</p>')
 + table(['Wykrywany jon', 'Odczynnik', 'Obserwacja', 'Równanie skrócone'], [['Cl⁻', 'AgNO₃', 'biały, serowaty osad (ciemnieje na świetle)', 'Ag⁺ + Cl⁻ → AgCl↓'], ['SO₄²⁻', 'BaCl₂', 'biały osad, nie roztwarza się w kwasach', 'Ba²⁺ + SO₄²⁻ → BaSO₄↓'], ['CO₃²⁻', 'HCl', 'musowanie, gaz mętni wodę wapienną', 'CO₃²⁻ + 2 H⁺ → H₂O + CO₂↑'], ['Cu²⁺', 'NaOH', 'niebieski galaretowaty osad', 'Cu²⁺ + 2 OH⁻ → Cu(OH)₂↓'], ['Fe³⁺', 'NaOH', 'rdzawobrunatny osad', 'Fe³⁺ + 3 OH⁻ → Fe(OH)₃↓'], ['I⁻', 'Pb(NO₃)₂', 'jaskrawożółty osad', 'Pb²⁺ + 2 I⁻ → PbI₂↓'], ['Ca²⁺', 'Na₂CO₃', 'biały osad, musuje z kwasem', 'Ca²⁺ + CO₃²⁻ → CaCO₃↓']])
 + viz('ion-map-v02', 'Mapa jonów: z czym każdy jon tworzy osad') + viz('rownania-jonowe-v01', 'Równania jonowe — strącanie')))

S.append(sec(6, 'Wypieranie metali — szereg aktywności', card('card-basic', 'Reguła', '<p>Metal stojący w szeregu aktywności <strong>wcześniej</strong> (aktywniejszy) wypiera z roztworu soli metal stojący <strong>dalej</strong>:</p><p>K &gt; Ca &gt; Na &gt; Mg &gt; Al &gt; Zn &gt; Fe &gt; Sn &gt; Pb &gt; (H) &gt; Cu &gt; Ag &gt; Au</p>' + eq('feCuso4', 'Fe + CuSO₄ → FeSO₄ + Cu') + '<div class="formula-lg">jonowo: Fe + Cu²⁺ → Fe²⁺ + Cu</div><p>To reakcja <strong>redoks</strong>: Fe oddaje elektrony (utlenia się), Cu²⁺ je przyjmuje (redukuje się).</p><p class="mini-note">Cu + FeSO₄ — brak reakcji (Cu stoi za Fe). Metale K, Ca, Na reagują najpierw z wodą — do wypierania się nie nadają.</p>')
 + viz('kw-szereg-metali-v01', 'Szereg aktywności: metale w kwasie solnym')))

S.append(sec(7, 'Ważne sole — właściwości i zastosowania', table(['Sól', 'Nazwy zwyczajowe', 'Zastosowanie / występowanie'], [['NaCl', 'sól kamienna, halit', 'przyprawa, konserwowanie, sól drogowa, produkcja Cl₂ i NaOH, sól fizjologiczna 0,9%'], ['CaCO₃', 'wapień, marmur, kreda', 'budownictwo, produkcja wapna, nawozy, pasta do zębów'], ['CaSO₄·2H₂O', 'gips', 'budownictwo, opatrunki gipsowe, sztukateria'], ['Na₂CO₃', 'soda', 'szkło, mydło, zmiękczanie wody'], ['NaHCO₃', 'soda oczyszczona', 'proszek do pieczenia, leki zobojętniające'], ['KNO₃, NaNO₃', 'saletra indyjska, chilijska', 'nawozy azotowe, proch czarny, konserwant'], ['Ca₃(PO₄)₂', 'fosforyt (składnik kości)', 'nawozy fosforowe; kości i zęby (hydroksyapatyt)'], ['CuSO₄·5H₂O', 'siny kamień', 'środek grzybobójczy; bezwodny — wykrywa wodę'], ['AgNO₃', 'lapis', 'przyżeganie brodawek, analiza chlorków']])
 + card('card-understand', 'Cykl wapienny (budownictwo)', eq('caco3Decomp', 'CaCO₃ → CaO + CO₂', 'prażenie wapienia → wapno palone') + eq('caoH2o', 'CaO + H₂O → Ca(OH)₂', 'gaszenie wapna — silnie egzotermiczne') + eq('caoh2Co2Mortar', 'Ca(OH)₂ + CO₂ → CaCO₃ + H₂O', 'twardnienie zaprawy wapiennej na powietrzu'))
 + card('card-understand', 'Twardość wody i kras', eq('caco3Co2H2o', 'CaCO₃ + CO₂ + H₂O → Ca(HCO₃)₂', 'woda z CO₂ rozpuszcza wapień — jaskinie') + eq('cahco32Decomp', 'Ca(HCO₃)₂ → CaCO₃ + H₂O + CO₂', 'gotowanie wody twardej → kamień kotłowy; w jaskiniach stalaktyty i stalagmity') + '<p class="mini-note">Twardość <strong>przemijająca</strong> (Ca(HCO₃)₂, Mg(HCO₃)₂) — usuwa ją gotowanie. <strong>Trwała</strong> (CaSO₄, MgCl₂) — zmiękcza się sodą: Ca²⁺ + CO₃²⁻ → CaCO₃↓.</p>')))

S.append(sec(8, 'Odczyn roztworów soli — hydroliza <span class="level-badge level-extra">LO</span>', card('card-extra', 'Kiedy roztwór soli nie jest obojętny?', '<p>Jon pochodzący od <strong>słabego</strong> kwasu lub <strong>słabej</strong> zasady reaguje z wodą (<strong>hydroliza</strong>):</p>' + table(['Sól', 'Pochodzi od', 'Odczyn', 'Równanie hydrolizy'], [['NaCl, K₂SO₄', 'mocny kwas + mocna zasada', 'obojętny', 'brak hydrolizy'], ['Na₂CO₃', 'słaby kwas + mocna zasada', 'zasadowy', 'CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻'], ['CH₃COONa', 'słaby kwas + mocna zasada', 'zasadowy', 'CH₃COO⁻ + H₂O ⇌ CH₃COOH + OH⁻'], ['NH₄Cl', 'mocny kwas + słaba zasada', 'kwasowy', 'NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺'], ['CuSO₄', 'mocny kwas + słaba zasada', 'kwasowy', 'Cu²⁺ + 2 H₂O ⇌ CuOH⁺ + H₃O⁺']]) + '<p class="mini-note">Dlatego roztwór sody barwi fenoloftaleinę na malinowo, a roztwór CuSO₄ czerwieni papierek uniwersalny.</p>')
 + adv('Hydroliza ilościowo', '<p>Dla anionu słabego kwasu: K<sub>b</sub> = K<sub>w</sub>/K<sub>a</sub>. Np. CH₃COO⁻: K<sub>b</sub> = 10⁻¹⁴ / 1,75·10⁻⁵ ≈ 5,7·10⁻¹⁰; dla 0,1 mol/dm³ CH₃COONa [OH⁻] ≈ √(K<sub>b</sub>·c) ≈ 7,6·10⁻⁶ → pOH ≈ 5,1, pH ≈ 8,9. Dla CO₃²⁻ (K<sub>a2</sub> H₂CO₃ = 4,68·10⁻¹¹) K<sub>b</sub> ≈ 2,1·10⁻⁴ → 0,1 M Na₂CO₃ ma pH ≈ 11,7. Kationy metali hydrolizują jako akwakompleksy: [Fe(H₂O)₆]³⁺ ⇌ [Fe(OH)(H₂O)₅]²⁺ + H⁺ (pK<sub>a</sub> ≈ 2,2).</p>')))

S.append(sec(9, 'Sole w przyrodzie i w organizmie <span class="bio-tag">BIOL-CHEM</span>', card('card-extra', 'Biologia i medycyna', '<ul><li><strong>Na⁺ i K⁺</strong> — potencjał spoczynkowy błony komórkowej (pompa sodowo-potasowa); nadmiar NaCl w diecie podnosi ciśnienie krwi.</li><li><strong>Ca²⁺ i fosforany</strong> — kości i zęby (hydroksyapatyt Ca₁₀(PO₄)₆(OH)₂), krzepnięcie krwi, skurcz mięśni.</li><li><strong>Kamienie nerkowe</strong> — najczęściej szczawian wapnia CaC₂O₄ (N).</li><li><strong>Sól fizjologiczna</strong> — 0,9% NaCl, izotoniczna z osoczem.</li><li><strong>BaSO₄</strong> jest kontrastem RTG, bo jest nierozpuszczalny — rozpuszczalne sole baru są trujące.</li><li><strong>Fosforany</strong> w ATP i DNA; nadmiar fosforanów i azotanów z nawozów → eutrofizacja wód.</li></ul>')))

EXPS = [
 exp('Doświadczenie 1 — Otrzymywanie soli przez zobojętnianie i krystalizację', [('Problem', 'Jak otrzymać NaCl z kwasu i zasady?'), ('Hipoteza', 'Po zobojętnieniu i odparowaniu wody zostaną kryształy soli.'), ('Sprzęt', 'NaOH(aq), HCl(aq), fenoloftaleina, biureta lub kroplomierz, parownica, palnik.'), ('Przebieg', 'Do NaOH z fenoloftaleiną dodajemy kroplami HCl do odbarwienia; roztwór odparowujemy.'), ('Obserwacja', 'Malinowa barwa znika; po odparowaniu — białe, sześcienne kryształy.'), ('Wniosek', 'W reakcji zobojętniania powstała sól.'), ('Równanie', 'HCl + NaOH → NaCl + H₂O'), ('BHP', 'Okulary; nie dopuścić do pryskania przy odparowywaniu.')]),
 exp('Doświadczenie 2 — Strącanie wodorotlenku miedzi(II)', [('Problem', 'Czy CuSO₄ reaguje z NaOH?'), ('Hipoteza', 'Powstanie niebieski osad Cu(OH)₂ (N w tabeli).'), ('Sprzęt', 'Probówka, CuSO₄(aq), NaOH(aq).'), ('Przebieg', 'Do roztworu CuSO₄ dodajemy roztwór NaOH.'), ('Obserwacja', 'Niebieski, galaretowaty osad; roztwór nad osadem odbarwia się.'), ('Wniosek', 'Zaszła reakcja strąceniowa: Cu²⁺ + 2 OH⁻ → Cu(OH)₂↓.'), ('Równanie', 'CuSO₄ + 2 NaOH → Cu(OH)₂↓ + Na₂SO₄'), ('BHP', 'NaOH żrący — okulary, rękawice.')]),
 exp('Doświadczenie 3 — Wykrywanie jonów chlorkowych', [('Problem', 'Czy woda z kranu zawiera jony Cl⁻?'), ('Hipoteza', 'Po dodaniu AgNO₃ pojawi się białe zmętnienie.'), ('Sprzęt', 'Probówki, woda z kranu, woda destylowana, roztwór AgNO₃ (kilka kropel HNO₃).'), ('Przebieg', 'Do obu próbek dodajemy po kilka kropel AgNO₃.'), ('Obserwacja', 'Woda z kranu — białe zmętnienie; destylowana — brak zmian.'), ('Wniosek', 'Woda z kranu zawiera jony chlorkowe.'), ('Równanie', 'Ag⁺ + Cl⁻ → AgCl↓'), ('BHP', 'AgNO₃ plami skórę na czarno.')]),
 exp('Doświadczenie 4 — Gwóźdź w roztworze CuSO₄', [('Problem', 'Czy żelazo wypiera miedź z roztworu jej soli?'), ('Hipoteza', 'Tak — Fe stoi w szeregu aktywności przed Cu.'), ('Sprzęt', 'Zlewka, roztwór CuSO₄, oczyszczony gwóźdź.'), ('Przebieg', 'Zanurzamy gwóźdź na kilka minut.'), ('Obserwacja', 'Gwóźdź pokrywa się czerwonobrunatnym nalotem, roztwór blednie i zielenieje.'), ('Wniosek', 'Fe wypiera Cu z roztworu soli (redoks).'), ('Równanie', 'Fe + CuSO₄ → FeSO₄ + Cu'), ('BHP', 'Okulary.')]),
 exp('Doświadczenie 5 — Wapno palone i gaszone (pokaz)', [('Problem', 'Co powstaje z wapienia po prażeniu i dodaniu wody?'), ('Hipoteza', 'CaO, a z wodą — zasadowy Ca(OH)₂.'), ('Sprzęt', 'Kawałek wapienia, palnik, parownica, woda, fenoloftaleina.'), ('Przebieg', 'Prażymy wapień, ostudzony wrzucamy do wody z fenoloftaleiną.'), ('Obserwacja', 'Woda się ogrzewa, roztwór barwi się na malinowo.'), ('Wniosek', 'Powstał CaO, który z wodą daje zasadę Ca(OH)₂.'), ('Równanie', 'CaCO₃ → CaO + CO₂;  CaO + H₂O → Ca(OH)₂'), ('BHP', 'CaO żrący, wysoka temperatura — tylko pokaz.')]),
 exp('Doświadczenie 6 — Odczyn roztworów soli (LO)', [('Problem', 'Czy roztwory soli są zawsze obojętne?'), ('Hipoteza', 'Nie — zależy, od jakiego kwasu i zasady pochodzi sól.'), ('Sprzęt', 'Papierek uniwersalny, roztwory: NaCl, Na₂CO₃, NH₄Cl, CuSO₄.'), ('Przebieg', 'Badamy odczyn każdego roztworu.'), ('Obserwacja', 'NaCl — zielony (obojętny), Na₂CO₃ — niebieski, NH₄Cl i CuSO₄ — czerwonawy.'), ('Wniosek', 'Sole słabych kwasów — odczyn zasadowy, sole słabych zasad — kwasowy (hydroliza).'), ('Równanie', 'CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻;  NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺'), ('BHP', 'Okulary.')]),
]
S.append(sec(10, 'Doświadczenia', viz('sole-doswiadczenia-v01', 'Pracownia: doświadczenia z solami (GFX)', 'Strącanie, wypieranie, cykl wapienny') + ''.join(EXPS)))

KLIN = [('CaCl', 'CaCl₂', 'Ca²⁺ i dwa Cl⁻ — suma ładunków musi wynosić 0.'), ('Al₃(SO₄)₂', 'Al₂(SO₄)₃', 'Krzyżujemy ładunki: Al³⁺ → indeks 3 przy SO₄, SO₄²⁻ → indeks 2 przy Al.'), ('„siarczan sodu” dla Na₂SO₃', 'siarczan(IV) sodu', 'Na₂SO₄ to siarczan(VI); trzeba podać wartościowość siarki.'), ('chlorek żelaza dla FeCl₃', 'chlorek żelaza(III)', 'Żelazo ma zmienną wartościowość — podajemy ją.'), ('Cu + ZnSO₄ → CuSO₄ + Zn', 'brak reakcji', 'Cu stoi w szeregu aktywności za Zn — nie wypiera go.'), ('NaCl + KNO₃ → NaNO₃ + KCl (zachodzi)', 'nie zachodzi — wszystkie produkty rozpuszczalne', 'Bez osadu, gazu lub słabego elektrolitu jony tylko się mieszają.'), ('AgCl → Ag⁺ + Cl⁻ (dysocjacja w wodzie)', 'AgCl praktycznie nie dysocjuje', 'AgCl jest nierozpuszczalny (N) — zostaje osadem.'), ('jonowo: Ag⁺ + NO₃⁻ → AgNO₃', 'Ag⁺ + Cl⁻ → AgCl↓', 'Azotany są rozpuszczalne — NO₃⁻ to jon obserwator.'), ('„roztwory soli zawsze mają pH 7”', 'zależy od soli (hydroliza)', 'Na₂CO₃ — zasadowy, NH₄Cl — kwasowy.'), ('wapno palone = Ca(OH)₂', 'wapno palone = CaO, gaszone = Ca(OH)₂', 'CaO + H₂O → Ca(OH)₂ (gaszenie).')]
kl = '<div class="table-wrap"><table class="klinika-table"><thead><tr><th>Błąd</th><th>Poprawnie</th><th>Dlaczego?</th></tr></thead><tbody>' + ''.join('<tr class="error-row"><td class="col-blad" data-label="Błąd">%s</td><td class="col-ok" data-label="Poprawa">%s</td><td data-label="Dlaczego">%s</td></tr>' % k for k in KLIN) + '</tbody></table></div>'
S.append(sec(11, 'Klinika błędów', kl))

def lvl(t, qs, ans, start):
    return '<h3>%s</h3><div class="card"><ol start="%d">%s</ol><details class="answer"><summary>Pokaż odpowiedzi</summary><ol start="%d">%s</ol></details></div>\n' % (t, start, ''.join('<li>%s</li>' % q for q in qs), start, ''.join('<li>%s</li>' % a for a in ans))
EX = lvl('Poziom A — podstawa', ['Napisz wzory: chlorek magnezu, siarczan(VI) glinu, azotan(V) wapnia, fosforan(V) sodu.', 'Nazwij: K₂CO₃, FeCl₂, Fe₂(SO₄)₃, CuS.', 'Zapisz dysocjację: Na₂SO₄, Al(NO₃)₃, K₃PO₄.', 'Odczytaj z tabeli: czy rozpuszczalne są AgCl, Na₂CO₃, BaSO₄, CaCO₃?'],
         ['MgCl₂, Al₂(SO₄)₃, Ca(NO₃)₂, Na₃PO₄.', 'węglan potasu, chlorek żelaza(II), siarczan(VI) żelaza(III), siarczek miedzi(II).', 'Na₂SO₄ → 2 Na⁺ + SO₄²⁻; Al(NO₃)₃ → Al³⁺ + 3 NO₃⁻; K₃PO₄ → 3 K⁺ + PO₄³⁻.', 'AgCl — N, Na₂CO₃ — R, BaSO₄ — N, CaCO₃ — N.'], 1)
EX += lvl('Poziom B — trening', ['Zaproponuj 3 sposoby otrzymania MgCl₂ — zapisz równania.', 'Uzupełnij: Zn + CuSO₄ → ? ; Cu + AgNO₃ → ? ; Cu + FeSO₄ → ?', 'Zapisz cząsteczkowo i jonowo (skrócono): BaCl₂ + K₂SO₄.', 'Które pary roztworów dadzą osad: (a) NaCl + AgNO₃, (b) KNO₃ + NaCl, (c) CuCl₂ + NaOH?'],
         ['Mg + 2 HCl → MgCl₂ + H₂↑; MgO + 2 HCl → MgCl₂ + H₂O; Mg(OH)₂ + 2 HCl → MgCl₂ + 2 H₂O (lub Mg + Cl₂ → MgCl₂).', 'ZnSO₄ + Cu; Cu(NO₃)₂ + 2 Ag; brak reakcji.', 'BaCl₂ + K₂SO₄ → BaSO₄↓ + 2 KCl; Ba²⁺ + SO₄²⁻ → BaSO₄↓.', '(a) tak — AgCl; (b) nie; (c) tak — Cu(OH)₂.'], 5)
EX += lvl('Poziom C — ambitny', ['Jak rozróżnić roztwory NaCl, Na₂SO₄ i Na₂CO₃, mając HCl, BaCl₂ i AgNO₃? Zaplanuj kolejność.', 'Oblicz masę osadu AgCl, który powstanie z 5,85 g NaCl (nadmiar AgNO₃).', 'Wyjaśnij, dlaczego woda twarda daje kamień kotłowy. Zapisz równanie.'],
         ['HCl: musuje tylko Na₂CO₃. Do pozostałych BaCl₂: biały osad — Na₂SO₄. Ostatni z AgNO₃ — biały osad AgCl — NaCl.', 'n(NaCl) = 5,85 / 58,44 ≈ 0,1 mol → n(AgCl) = 0,1 mol → m = 0,1 · 143,32 ≈ 14,3 g.', 'Ca(HCO₃)₂ → CaCO₃ + H₂O + CO₂ — przy ogrzewaniu wytrąca się nierozpuszczalny CaCO₃.'], 8)
EX += lvl('Poziom D — LO rozszerzone', ['Przewidź odczyn: K₂CO₃, NH₄NO₃, KCl, CH₃COOK. Zapisz równania hydrolizy.', 'Dlaczego w zapisie jonowym CaCO₃ + 2 HCl CaCO₃ zostaje w postaci cząsteczkowej?'],
         ['K₂CO₃ — zasadowy (CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻); NH₄NO₃ — kwasowy (NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺); KCl — obojętny; CH₃COOK — zasadowy.', 'CaCO₃ jest nierozpuszczalny (N) — w roztworze nie występuje jako jony: CaCO₃ + 2 H⁺ → Ca²⁺ + H₂O + CO₂↑.'], 11)
S.append(sec(12, 'Ćwiczenia', EX + adv('Iloczyn rozpuszczalności i efekt wspólnego jonu', '<p>Dla osadu MₐXᵦ: K<sub>sp</sub> = [M]ᵃ[X]ᵇ (np. AgCl: K<sub>sp</sub> = 1,77·10⁻¹⁰ → rozpuszczalność s = √K<sub>sp</sub> ≈ 1,33·10⁻⁵ mol/dm³). Osad wytrąca się, gdy iloczyn stężeń jonów przekroczy K<sub>sp</sub>. Dodatek wspólnego jonu (np. NaCl do roztworu nad AgCl) zmniejsza rozpuszczalność; z kolei tworzenie kompleksów zwiększa ją (AgCl rozpuszcza się w NH₃: AgCl + 2 NH₃ → [Ag(NH₃)₂]⁺ + Cl⁻).</p>')))

S.append(sec(13, 'Fiszki', '<div class="flashcard-grid" id="flashcards"></div>'))
S.append(sec(14, 'Test', '<div id="quizWrap"></div><div class="quiz-score" id="quizScore"></div>'))
S.append(sec(15, 'Słownik i mosty', '<div class="card"><dl>' + ''.join('<div class="def-item"><dt>%s</dt><dd>%s</dd></div>' % x for x in [('Sól', 'związek z kationów metalu (lub NH₄⁺) i anionów reszty kwasowej'), ('Reakcja strąceniowa', 'reakcja, w której powstaje nierozpuszczalny osad'), ('Jon obserwator', 'jon, który nie zmienia się w reakcji — pomijamy go w zapisie skróconym'), ('Hydroliza soli', 'reakcja jonów słabego kwasu lub słabej zasady z wodą, zmieniająca odczyn'), ('Hydrat', 'sól zawierająca cząsteczki wody w krysztale, np. CuSO₄·5H₂O'), ('Twardość wody', 'zawartość jonów Ca²⁺ i Mg²⁺ w wodzie')]) + '</dl></div>'
 + card('card-new', 'Mosty', '<ul><li><strong>N03 Kwasy</strong> — reakcje kwasów prowadzą do soli; szereg aktywności; zapis jonowy.</li><li><strong>N02 Wodorotlenki</strong> — zobojętnianie, osady wodorotlenków.</li><li><strong>Atlas</strong> — każdy metal pokazuje rozpuszczalność swoich związków i reakcje z silnika.</li></ul>')))

CARDS = [['Sól — budowa', 'kationy metalu (lub NH₄⁺) + aniony reszty kwasowej'], ['Wzór siarczanu(VI) glinu', 'Al₂(SO₄)₃'], ['Fe₂(SO₄)₃ — nazwa', 'siarczan(VI) żelaza(III)'], ['Zawsze rozpuszczalne', 'sole Na⁺, K⁺, NH₄⁺ i wszystkie azotany(V)'], ['Wykrywanie Cl⁻', 'AgNO₃ → biały osad AgCl'], ['Wykrywanie SO₄²⁻', 'BaCl₂ → biały osad BaSO₄'], ['Wykrywanie CO₃²⁻', 'kwas → CO₂ mętni wodę wapienną'], ['Cu²⁺ + OH⁻', 'niebieski osad Cu(OH)₂'], ['Fe + CuSO₄', 'FeSO₄ + Cu (wypieranie)'], ['Cu + ZnSO₄', 'brak reakcji'], ['Wapno palone / gaszone', 'CaO / Ca(OH)₂'], ['Gips', 'CaSO₄·2H₂O'], ['Kamień kotłowy', 'CaCO₃ z rozkładu Ca(HCO₃)₂'], ['Odczyn Na₂CO₃', 'zasadowy (hydroliza CO₃²⁻)'], ['Odczyn NH₄Cl', 'kwasowy (hydroliza NH₄⁺)'], ['Jon obserwator', 'nie zmienia się w reakcji']]
QS = [['Który wzór jest poprawny?', ['Al₃(SO₄)₂', 'Al₂(SO₄)₃', 'AlSO₄'], 1], ['Który związek jest nierozpuszczalny?', ['NaNO₃', 'BaSO₄', 'K₂CO₃'], 1], ['Co zajdzie po zmieszaniu NaCl i KNO₃?', ['wytrąci się osad', 'nic — wszystkie sole rozpuszczalne', 'wydzieli się gaz'], 1], ['Który metal wyprze miedź z CuSO₄?', ['Ag', 'Fe', 'Au'], 1], ['Skrócony zapis AgNO₃ + NaCl:', ['Ag⁺ + Cl⁻ → AgCl↓', 'Na⁺ + NO₃⁻ → NaNO₃', 'AgNO₃ → Ag⁺ + NO₃⁻'], 0], ['Wapno gaszone to…', ['CaO', 'Ca(OH)₂', 'CaCO₃'], 1], ['Barwa osadu Fe(OH)₃:', ['niebieska', 'rdzawobrunatna', 'biała'], 1], ['Odczyn roztworu Na₂CO₃:', ['kwasowy', 'obojętny', 'zasadowy'], 2], ['Jak usunąć twardość przemijającą?', ['gotowaniem', 'dodając NaCl', 'filtrując'], 0], ['Nazwa NaHCO₃:', ['węglan sodu', 'wodorowęglan sodu', 'wodorotlenek sodu'], 1]]
JS = '<script>(function(){var cards=' + json.dumps(CARDS, ensure_ascii=False) + ';var g=document.getElementById("flashcards");if(g){g.innerHTML=cards.map(function(c){return \'<button class="flashcard" type="button"><span class="front">\'+c[0]+\'</span><span class="back">\'+c[1]+\'</span></button>\'}).join("");g.querySelectorAll(".flashcard").forEach(function(b){b.addEventListener("click",function(){b.classList.toggle("flipped")})})}' \
     + 'var qs=' + json.dumps(QS, ensure_ascii=False) + ';var w=document.getElementById("quizWrap"),sc=document.getElementById("quizScore"),ok=0,n=0;if(w){qs.forEach(function(q,i){var d=document.createElement("div");d.className="quiz-q";d.innerHTML="<h5>"+(i+1)+". "+q[0]+"</h5><div class=\\"quiz-opts\\">"+q[1].map(function(o,j){return \'<button type="button" class="quiz-opt" data-a="\'+j+\'">\'+o+"</button>"}).join("")+"</div>";w.appendChild(d);d.querySelectorAll(".quiz-opt").forEach(function(b){b.onclick=function(){if(d.dataset.done)return;d.dataset.done=1;n++;var a=+b.dataset.a;if(a===q[2])ok++;d.querySelectorAll(".quiz-opt").forEach(function(x){x.disabled=true;if(+x.dataset.a===q[2])x.classList.add("correct");else if(x===b)x.classList.add("wrong")});sc.textContent="Wynik: "+ok+" / "+n}})})}' \
     + 'var b=document.getElementById("advToggle");if(b){var all=function(){return document.querySelectorAll("details.adv")};var k=all().length;b.textContent="Pokaż treści akademickie ("+k+")";b.onclick=function(){var on=b.getAttribute("aria-pressed")!=="true";all().forEach(function(d){d.open=on});b.setAttribute("aria-pressed",on?"true":"false");b.textContent=(on?"Ukryj":"Pokaż")+" treści akademickie ("+k+")"}}})();</script>'

TOC = '<details class="toc-item" open><summary class="toc-summary">Spis treści</summary><nav class="toc-links">' + ''.join('<a class="toc-link" href="#s%d">%d. %s</a>' % (i, i, t) for i, t in [(1, 'Budowa'), (2, 'Wzory i nazwy'), (3, 'Dysocjacja, tabela'), (4, 'Otrzymywanie — 10 metod'), (5, 'Strącanie, wykrywanie'), (6, 'Wypieranie metali'), (7, 'Ważne sole'), (8, 'Hydroliza (LO)'), (9, 'Sole w organizmie'), (10, 'Doświadczenia'), (11, 'Klinika błędów'), (12, 'Ćwiczenia'), (13, 'Fiszki'), (14, 'Test'), (15, 'Słownik, mosty')]) + '</nav></details>'
HTML = ('<!DOCTYPE html>\n<html lang="pl">\n<head>\n<meta charset="utf-8"/>\n<meta content="width=device-width,initial-scale=1.0" name="viewport"/>\n<title>Chemia N04 — Sole (v1.0 MASTER LAB)</title>\n' + VIZ_CSS + V15_CSS + '</head>\n<body>\n<main class="page" id="main">\n'
        '<section class="hero card"><div class="hero-kicker">N04 · MASTER LAB v1.0</div><h1>Sole</h1><p class="lead">Budowa, wzory i nazwy, dysocjacja, tabela rozpuszczalności, 10 metod otrzymywania, strącanie i wykrywanie jonów, wypieranie metali, ważne sole, hydroliza (LO), sole w organizmie, doświadczenia, klinika błędów i ćwiczenia. Równania i dane — z silnika CHE (te same co w Atlasie i lekcji o kwasach).</p>'
        '<div class="tag-row"><span class="level-badge level-basic">E8</span><span class="level-badge level-understand">ROZUMIENIE</span><span class="level-badge level-extra">LO ROZSZERZONE</span></div>'
        '<button type="button" class="adv-toggle" id="advToggle" aria-pressed="false">Pokaż treści akademickie</button></section>\n'
        + MIN + TOC + ''.join(S) + '</main>\n' + JS + '\n</body>\n</html>\n')
open(os.path.join(D, 'sole_new.html'), 'w', encoding='utf-8').write(HTML)
print('OK sole', len(HTML), 'data-rx:', HTML.count('data-rx='), 'viz:', HTML.count('che-lesson-viz-ref"'), 'adv:', HTML.count('class="adv"'))
