

try {

(function(g){'use strict';const C=g.CHE=g.CHE||{},D=C.DATA=C.DATA||{},E=C.ENGINE=C.ENGINE||{};const old=C.SCIENCE_INTEGRITY;
function audit(){const base=old?.audit?.()||{};const cov=C.DATA_COVERAGE?.audit?.()||{total:0,complete:0,referenceReady:0};const aw=C.ATOMIC_WEIGHT_REFERENCE?.audit?.()||{total:0,value:0,range:0,nonStandard:0,provenanceComplete:0};const issues=[...(base.issues||[])],warnings=[...(base.warnings||[])];if(aw.total!==118)issues.push({code:'CIAAW_ATOMIC_WEIGHT_COVERAGE_NOT_118',actual:aw.total,expected:118});if(aw.provenanceComplete!==118)issues.push({code:'CIAAW_ATOMIC_WEIGHT_PROVENANCE_INCOMPLETE',actual:aw.provenanceComplete,total:118});warnings.push({code:'ATOMIC_WEIGHT_POLICY',message:'CIAAW 2024 rozróżnia wartości punktowe, przedziały oraz elementy bez standardowej masy atomowej; tryb none nie jest zastępowany liczbą.'});return {...base,issues,warnings,coverage:{...(base.coverage||{}),atomicProps:{present:cov.complete,total:118,partial:cov.partial,referenceReady:cov.referenceReady},atomicWeightReference:aw},scientificGate:false};}
function regression(){const a=audit(),aw=C.ATOMIC_WEIGHT_REFERENCE?.audit?.()||{};return [{id:'SCI59-001',name:'CIAAW records 118/118',ok:aw.total===118,detail:String(aw.total)+'/118'},{id:'SCI59-002',name:'CIAAW provenance 118/118',ok:aw.provenanceComplete===118,detail:String(aw.provenanceComplete)+'/118'},{id:'SCI59-003',name:'ranges preserved',ok:aw.range>=5,detail:String(aw.range)+' range records'},{id:'SCI59-004',name:'non-standard elements explicit',ok:aw.nonStandard>=20,detail:String(aw.nonStandard)+' explicit none records'},{id:'SCI59-005',name:'scientific gate remains blocked',ok:a.scientificGate===false,detail:'atomic physical data still incomplete'}];}
C.SCIENCE_INTEGRITY={version:'2.59',audit,regression,coverage:()=>C.DATA_COVERAGE?.audit?.()||null};E.modules=E.modules||{};E.modules.SCIENCE_INTEGRITY='2.59';E.registry=E.registry||{};E.registry.SCIENCE_INTEGRITY={layer:'AUDIT',owner:'CHE.SCIENCE_INTEGRITY',depends:['DATA_COVERAGE','ATOMIC_WEIGHT_REFERENCE','PROVENANCE','THERMO','ELECTRO','ISOTOPE']};E.version='2.59';E.dataVersion='2.59';E.contractVersion='2.59';E.schemaVersion='2.59';if(E.PUBLIC)E.PUBLIC.version='2.59';if(E.API_CONTRACT)E.API_CONTRACT.version='2.59';if(E.RUNTIME)E.RUNTIME.version='2.59';
if(E.AUDIT?.run&&!E.AUDIT.__v259Wrapped){E.AUDIT.__v259Wrapped=true;const base=E.AUDIT.run.bind(E.AUDIT);E.AUDIT.run=function(){const r=base();const x=C.SCIENCE_INTEGRITY.regression();r.groups=r.groups||{};r.groups.v259=x;r.summary=r.summary||{};r.summary.v259={total:x.length,failed:x.filter(t=>!t.ok).length};r.v259=x;r.ok=!!r.ok&&x.every(t=>t.ok);E.lifecycle={state:r.ok?'ready':'blocked',auditedAt:new Date().toISOString()};return r;};}
})(window);

} catch (err) {
  try { console.warn('[CHE module 84]', err && err.message ? err.message : err); } catch(_){}
}